.travis.yml, pennylane/__init__.py
Now that Ubuntu Xenial (16.04) is supported natively on Travis (see https://github.com/travis-ci/travis-ci/issues/9815), we can now run the test suite on Python 3.7 as well.
=> Adds a Python 3.7 build to the Travis configuration

doc/code/expval.rst, doc/code/expval/cv.rst, doc/code/expval/qubit.rst, pennylane/expval/__init__.py, pennylane/expval/cv.py, pennylane/expval/qubit.py, pennylane/plugins/default_gaussian.py, pennylane/plugins/default_qubit.py, pennylane/qnode.py, tests/test_default_gaussian.py, tests/test_default_qubit.py, tests/test_device.py, tests/test_expval.py
Adds an Identity Expectation for both the CV and qubit case. The implementation was complicated by the fact that it is not possible to have a CV and and a qubit Expectation under the same name. I have basically followed the rout recommended in https://discuss.pennylane.ai/t/pennylane-version-0-2-discussion/27/9. 
In the end I actually managed not having to touch `QNode` at all and no braking changes in the plugins are required.
This is achieved by implementing a "placeholder" class in `expval.__init__` that has an overloaded `__new__()` method, which inspects the list of Expectations a device supports to determine whether it is a CV or qubit device and then returns an instance of the appropriate Identity classes for the CV or qubit device.
The PR comes …
=> Add Identity expectation

pennylane/expval/__init__.py, pennylane/expval/cv.py, pennylane/expval/qubit.py
Somehow we overlooked this when merging the identity branch. Sorry, this was my mistake...
=> fixes the par_domain of the newly introduced Identity Expectation

.travis.yml, pennylane/ops/cv.py, pennylane/plugins/default_gaussian.py, pennylane/qnode.py, pennylane/utils.py, tests/test_classical_gradients.py, tests/test_default_gaussian.py, tests/test_optimize.py
Makes `DisplacedSqueezedState()` and `CatState()` take real (abs and phase) parameters instead of complex ones. This fixes #146 .
=> Makes DisplacedSqueezedState() and CatState() take real (abs and phase) parameters instead of complex ones.

.travis.yml, pennylane/operation.py, pennylane/qnode.py, pennylane/variable.py, tests/test_qnode.py
This PR supports wires being `Variable` objects.
**Benefits:**
This allows us to support the use case where the wire number may be passed as a keyword argument.
None, as far as I can tell.
#150
=> Support wires as variable objects

pennylane/plugins/default_gaussian.py, pennylane/plugins/default_qubit.py
A mini fix to ignore the parameters of `identity()` instead of suppressing the pylint error. See if you like that.
=> ignore the unused parameters to identity() in the default plugins

.github/CHANGELOG.md, pennylane/_version.py, pennylane/plugins/default_gaussian.py, pennylane/plugins/default_qubit.py, setup.py
**Description of the Change:** Adds the new `interfaces` submodule to `setup.py`
**Benefits:** will now properly package the `interfaces` module
=> Interfaces setup bug fix

pennylane/template.py
The docstring was missing two parameter lists.
CVNeuralNet is however not usable with Pytorch, which is why we have to rewrite it in the long run.
=> Fixed error in CVQNN docstring and added some more explanation

pennylane/ops/cv.py
This resolves #180. I could not find any other place which was using scipy packages implicitly.
=> Explicit import for scipy.linalg.block_diag

tests/test_ops.py
- Rewrote `test_ops.py` using pytest.
- Removed loops and used `pytest.mark.parameterize`
**Benefits:**
#99 
I noticed that the tests for `cv.CrossKerr`raises a ValueError error and the other two (cv.CrossKerr and cv.CubicPhase) raise RuntimeError for the same test. I did not understand what is the proper exception to check so I split the tests. @josh146
=> PyTest styled refactoring of tests.

tests/test_expval.py
Used PyTest function to perform the regex matching test for expval. Simple change and move to pytest style testing. I am still not very happy with the function inside a function (defining the ´circuit´with the @qnode decorator) but I think there cannot be any other way to do this directly without constructing another circuit function inside.
Also, the code is blacked.
#99
=> PyTest refactoring of test_expval

pennylane/expval/qubit.py, pennylane/plugins/default_qubit.py, tests/test_default_qubit.py
This PR adds support for expectation values of two-qubit Hermitian operators and implements it for `default_qubit` plugin. This is the implementation suggested by @josh146 in the [discussion](https://discuss.pennylane.ai/t/optimizing-state-overlap-multi-qubit-qml-expval-hermitian/84/2) and answering @bencbartlett
**Benefits:**
We can slowly think of supporting this for CV and then extending to an arbitrary gate, e.g., Toffoli.
Plugins should support multi-qubit operators too. In some cases there might be a neat trick with a change of basis which allows this as @josh146 explains for the Rigetti systems.
#175
=> Two qubit observable

tests/conftest.py, tests/test_qnode.py
Changes:
* Ports half of `test_qnode.py` to pytest. Specifically, the `TestQNodeGradients` class is ported.
* Adds a session `conftest.py` file, for suite-wide pytest fixtures.
Todo:
* Port the remainder of `test_qnode.py` to pytest.
=> Port QNode gradient tests to pytest

pennylane/_device.py, tests/test_device.py
The `Device.supported` method is a union between the sets of supported operation names and expectation names. However, some of the expectations and operations have the same name, i.e., `PauliX`, `PauliZ`, `PauliY`, `Hadamard`. Thus, if the `PauliX` operation is supported, this will also accidentally mark the `PauliX` expectation as supported.
To fix this, the `check_validity` method now explicitly checks the operation/expectation against the `Device.operations` and `Device.expectations` methods.
**Benefits:**
Correctly raises error for plugins such as the Qiskit plugin, where only `PauliZ` expectations are allowed, but all `Pauli` operations are allowed.
We should fix the `Device.supported` method, adding a keyword argument to switch …
=> Fixes a bug in operation and expectation validation on devices

doc/tutorials/qubit_rotation.rst, pennylane/_device.py, pennylane/operation.py
This PR fixes two bugs noted in https://discuss.pennylane.ai/t/passing-non-differentiable-arguments-to-qnode/135/5:
1. When QNode keyword arguments are used to specify wires of operations/expvals, complicated casting rules can cause them to be of type `np.int64` rather than the standard Python type `int`. This can cause issues with external plugin devices, for example, if the targeted framework performs validation to ensure that `isinstance(qubit, int)`. 
To fix this, we explicitly cast the operation wires directly to integers in `Operation.wires`.
2. There is a typo in the qubit rotation tutorial; the line
> PennyLane does differentiate QNodes with respect to keyword arguments,
so they are useful for passing external data to your QNode.
should instead say
> …
=> Keyword argument bug fixes

pennylane/__init__.py, pennylane/_device.py, pennylane/configuration.py, pennylane/decorator.py, pennylane/operation.py, pennylane/plugins/default_gaussian.py, pennylane/plugins/default_qubit.py, pennylane/qnode.py, pennylane/variable.py, tests/test_configuration.py, tests/test_default_qubit.py
* Removes logging configuration from `__init__.py`
* Removes logging calls from modules that don't currently do any logging
* Converts some logging calls to warnings, where it makes sense
**Benefits:**
Imported Python libraries should *not* be configuring the logger, as this will override the users logging. See https://sweetness.hmmz.org/2013-11-18-use-of-logging-package-from-within-a-library.html.
> Except in very rare cases, the majority of logging configuration should be deferred to the consuming application's top level, where tools like `logging.config.fileConfig()` can be used to configure the entire system's logging using a standard convention, rather than package-specific or app-specific hard-wired values or environment variables or whatever else. …
=> Cleans up logging in PennyLane module files

pennylane/plugins/default_qubit.py
**Description of the Change:** When using `qml.QubitStateVector` to prepare an arbitrary state, the `default.qubit` device was accidentally casting the state to `np.float64`. This PR fixes this, instead casting the result to a `np.complex128` array.
**Benefits:** fixes a bug that led to unphysical simulation.
**Related GitHub Issues:** #210
=> Fixes QubitStateVector bug in Default Qubit plugin

tests/test_classical_gradients.py
This refactors and gets rids of the loops for the classical gradient tests. 
**Benefits:**
Tests are self-contained, easier to read
Repetition of some code but they could be parameterized with pytest fixtures.
#99
=> Refactored classical_gradients test to pytest

pennylane/expval/qubit.py, pennylane/plugins/default_gaussian.py, pennylane/plugins/default_qubit.py, tests/test_default_gaussian.py, tests/test_default_qubit.py
* Removes limit on `default.qubit` which previously only allowed 1 and 2 qubit operations/expvals. Now, you can apply arbitrary N-qubit operations, and measure arbitrary N-qubit observables. This is done by replacing the `DefaultQubit.expand_one` and `DefaultQubit.expand_two` with a single, more general `expand` method, that works for any unitary/Hermitian matrix.
* Removes limit on `default.gaussian` which previously only allowed 1 and 2 mode gates. It now supports N-mode operations. This is done by replacing the `DefaultGaussian.expand_one` and `DefaultGaussian.expand_two` with a single, more general `expand` method, that works for any sized symplectic matrix.
**Benefits:**
* Allows `qml.Interferometer()` to work on the `default.gaussian` plugin for >2 …
=> Allow reference plugins to use > 2 wire operations and expvals

doc/index.rst, doc/installing.rst
1. Adding detailed commands for installation from source code like we discussed in an earlier PR. 
2. Adding the discussion forum  as a direct link. 
**Benefits:**
Having a direct visible help tab called `Get Help` in the side gallery is easier to spot. It does not depend on the user scrolling down the front page or going through all the side tabs to find the page on `Support`. I personally always look for the `Help` tab on a website when I have issues. We can also rename it to `Discussion Forum `. What do you guys think ?
=> Documentation: change installation instruction about source code

pennylane/plugins/default_qubit.py
**Description of the Change:** Modified `default.qubit` plugin to use tensordot for gate applications instead of creating large dense arrays 
**Benefits:** speed improvement of 5-10x
**Possible Drawbacks:** This PR was the biggest bang-for-your-buck change, but code could still be optimized more for speed by using a multi-index representation of states/gates internally. 
**Related GitHub Issues:** none
=> Switch default.qubit to use tensordot

pennylane/plugins/default_qubit.py, tests/test_default_qubit.py
**Description of the Change:** Removed `expand` method from `default.qubit`. Both gate applications and expectations now use `tensordot` under the hood
**Benefits:** apparent 25x speed-up over current code
**Possible Drawbacks:** 
=> Refactored default.qubit for more speed

.gitignore, doc/tutorials/qubit_rotation.rst
**Description of the Change:** This PR fixes a broken link in the tutorial documentation. 
**Benefits:** Fixes a broken link in the documentation and links to the correct location. This change is a result of `expval` being merged into `measure`
**Possible Drawbacks:** None, in the foreseeable future.
**Related GitHub Issues:** Issue #245
=> Fix for Issue #245

tests/test_classical_gradients.py
There were missing assert statements. Also, the file now uses the tol
fixture and not numpys builtin tolerance.
Furthermore two bugs in the tests were removed.
Issues: #99
=> Fix test_classical_gradients.py

.github/CHANGELOG.md, doc/API/overview.rst, pennylane/_device.py, tests/test_default_gaussian.py, tests/test_default_qubit.py, tests/test_device.py
Replaced the method `Device.supported` with two separate methods `Device.supports_operation` and `Device.supports_observable`. The new methods can be called either with a string or a class information object:
```python
dev.supports_observable('PauliX')
dev.supports_observable(qml.PauliX)
```
**Benefits:**
No more errors due to operations that can be confused for observables that are not supported.
The method `Device.supported` was removed.
Do you think we should instead keep it and raise a depreceation warning?
#205
=> Replace device supported with separate methods for operations and observables

tests/test_device.py
Refactor the test of the abstract `Device` class from unittest to pytest. On the way, all dependencies on `default.qubit` and `default.gaussian` where replaced with appropriate Mock instances of `Device`.
Also some tests that were basically tests of `default.qubit` and `default.gaussian` were removed, as well as the extensive loop tests.
**Benefits:**
* Uses the better pytest framework
* No more dependence on `default.qubit` and `default.gaussian`
* No more loop tests
* Extensive use of `unittest.mock`
#99, #199
=> Refactor test_device.py to pytest

pennylane/_device.py, pennylane/about.py, pennylane/qnode.py, tests/test_about.py, tests/test_configuration.py, tests/test_device.py
* Adds a `Device.parameters` property, so that devices can view the `QNode.variable_ops` dictionary mapping free parameters to operation parameters. This property acts similarly to `Device.op_queue` and `Device.obs_queue`.
* Bug fixes to `pennylane.about()`, and updates the test correspondingly
**Benefits:**
* Should be backwards compatible with existing plugins
* Plugins for frameworks which support parametric compilation will only need to re-compile the program when the parameter mapping changes, potentially leading to a significant speedup for users during optimization.
**Related GitHub Issues:** #221
=> Adds `Device.parameters` so that devices can access free parameter mappings

.github/CHANGELOG.md, pennylane/operation.py, pennylane/ops/__init__.py, pennylane/ops/cv.py, pennylane/ops/qubit.py, pennylane/plugins/default_gaussian.py, pennylane/plugins/default_qubit.py, tests/test_default_gaussian.py, tests/test_default_qubit.py, tests/test_quantum_gradients.py
**Context:**
All PennyLane operations must specify the required class attribute `num_wires` so that PennyLane knows how many wires it should apply to, and perform automatic validation.  This works fine for operations with a specific fixed number of wires (i.e., PauliX, CNOT, TwoModeSqueezing). However, it has led to confusion for operations that can correspond to _any_ number of wires in the system, or that must be restricted to _all_ wires in the system.
As a stop gap, we have been using `num_wires = 0` to represent both 'all' wires *and* 'any' wires, which has led to even more confusion.
This PR makes several improvements to address the past confusion.
* Introduces two enumerations: `Any` and `All`, representing any number of wires and all wires in the …
=> Added enumerations to represent All and Any wires

.github/CHANGELOG.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .travis.yml, pennylane/about.py, setup.py, tests/conftest.py
* Updates the changelog
* Updates the PyPI project web address to point to the GitHub repository, so that GitHub dependency tracking works properly.
* ~Updates the CI to use the latest version of TF in the tests (1.13.1 -> 1.14.0)~ See https://github.com/XanaduAI/pennylane/pull/284#issuecomment-517597208.
* Simplifies the issue and PR template, making them clearer and more concise.
* Adds a line to the PR template, reminding users to add an entry to the changelog.
**Benefits:** all the above
=> Update changelog, and simplify PR and issue template

.travis.yml
**Context:** PyTorch 1.2 was released a couple of days ago
**Description of the Change:** Updates the Travis configuration to test PennyLane against PyTorch 1.2
**Benefits:** Bugs arising from new PyTorch breaking changes/bugs will be found
=> Update Travis to test against PyTorch 1.2

pennylane/plugins/default_gaussian.py
Fixes the docstring of the returned value in gaussian_state
**Context:**
Wrong docstring in gaussian_state
Fixes a broken docstring
**Benefits:**
Correct docstring
=> Wrong description in gaussian_state

.github/CHANGELOG.md, .travis.yml, pennylane/plugins/default_qubit.py
**Context:**
`RotX`,  `RotY`  and `RotZ` in `pennylane.plugins.default_qubit` use Scipy's `expm` function to calculate matrix exponentials. This can be implemented more efficiently using Euler's identity formula. See the PennyLane [discussion forum](https://discuss.pennylane.ai/t/using-expm-vs-euler-formula-in-default-qubit-rotations/192) for more info.
The unitary operations in `default.qubit` are are no longer calculated with `expm` but with Euler's identity instead.
**Benefits:**
A significant speed up for calls to `RotX`,  `RotY`  and `RotZ`.
None
None
=> Implemented Pauli matrix exponentiation without expm

tests/test_default_qubit.py
Refactor test_default_qubit.py from unittest to pytest, removing the loop tests on the way.
**Benefits:**
No more loop tests. No more unittest.
N/A
#99, #199
=> Refactor test_default_qubit.py

doc/code/measure.rst, requirements.txt, setup.py
This PR addresses Issue #304.
It adds the "sample" function to the explicit list of functions generated by the automodule directive for pennylane.measure.
=>  Fix#304 - Add sample to explicit members in automodule 

pennylane/ops/qubit.py
**Context:**
Operations have the class property `generator`, which provides PennyLane with information of the Hamiltonian used to generate the operation. To use parametrized operations with the `QNGOptimizer`, this generator must be defined. It is currently only defined for the `RX`, `RY`, `RZ`, and `PhaseShift` gates.
Adds `generator` definitions to the `CRX`, `CRY`, and `CRZ` operations, allowing them to be used in circuits optimized by `QNGOptimizer`.
**Benefits:**
Increases the number of parametrized gates that can be optimized by the `QNGOptimizer`.
**Possible Drawbacks:** 
Currently, the 'generator' property only makes sense for parametrized gates with at most one parameter. To enable `qml.Rot(theta, phi, varphi)` to be used with the `QNGOptimizer`, …
=> Add generators to the controlled rotation gates

.github/CHANGELOG.md, examples/pennylane_run_state_preparation.py
**Description of the Change:** Change purity to be less than or equal to one (not greater than) and fix spelling in word "parameters"
=> Fix 2 typos in state preparation tutorial

pennylane/ops/cv.py
Fixes 2 typos in CV operations page
The stated number of parameters for these two functions have a typo:
=> Documentation: Fix 2 typos in CV operations

.github/CHANGELOG.md, pennylane/qnode.py
**Context:** Returning an Observable without specifying a Measurement currently raises an error with a message that has not been properly formatted.  
**Description of the Change:** Fix formatting on the error message to include the name of the Observable being referred to instead of parentheses {}.
**Benefits:** Fixes error message formatting.
=> Fix formatting in measurement type error message

examples/pennylane_run_barren_plateaus.py
The barren plateau tutorial (just merged) is dependent on how many samples one considers for a random circuit. I was using a very low number for simulations which got decent results but its not reliable as we saw in the rendered tutorial:
https://pennylane.readthedocs.io/en/latest/tutorials/pennylane_run_barren_plateaus.html#barren-plateaus
This PR reduces the number of qubits and increases the number of samples to 200 which sort of reproduces the straight line plot in the original paper. 
Please have a look @josh146 since the plot looks quite ugly right now and statisticians would scoff at sample size 25 :p 
@co9olguy
=> Updated samples in Barren Plateau tutorial for better figure

.github/CHANGELOG.md, pennylane/_version.py
* Bumps the version number to v0.6.0 to ready for release.
=> Version bump to v0.6.0

doc/xanadu_theme/layout.html
**Context:**
Sphinx does not 'know' about the new top navigation bar, and does not take it into account when scrolling to page sections. In addition, code domains automatically link to the signature, as opposed to the top of the page, which would make more sense now that we have individual pages per code object.
This PR introduces two changes:
1. Javascript function that scans all internal links on a page. If they are API links, and the reference matches the page name, the reference is stripped from the link. This will cause the page to load at the top, rather than scrolling to the signature.
2. If the URL loaded _does_ contain a reference hash, the JQuery `scrollTop` function is used to ensure the navbar height offset is taken into account.
**Benefits:** …
=> Fix scrolling behaviour on API links

.github/CHANGELOG.md, pennylane/_device.py
**Context:**
In the ``_device.py`` file there are currently deprecated ways of referring to abstract properties.
Using the current ``@abstractmethod decorator`` as [described here](https://docs.python.org/3/library/abc.html#abc.abstractmethod).
**Benefits:**
Removing the deprecated function calls to abstract properties in the ``_device.py`` file.
N/A
N/A
=> Changing deprecated abstract property definitions in _device.py

doc/introduction/measurements.rst
Updates the Using PennyLane/Measurement page with some features and common patterns that aren't mentioned anywhere else in the documentation:
1. Adds a short example of multiple measurements
2. Shows how to specify tensor observables
3. Shows how to execute a QNode with differing number of shots (I put this here because it generally is used with the `sample()` function, maybe there is a better place for it?)
**Benefits:** Briefly introduces tensor observables, multiple measurements, changing shots.
=> Updates measurements page

pennylane/decorator.py, pennylane/interfaces/tf.py, pennylane/interfaces/torch.py, pennylane/qnode.py, tests/test_qnode.py
**Context:** Currently, it is hard to debug QNodes to ensure that they are executing the correct quantum circuit, for instance, if they include classical branching/logic within the QNode.
**Description of the Change:** Adds a `print_applied` method to QNodes, that prints the operation and observable queue as last constructed.
Example:
```python
from pennylane.templates.embeddings import AngleEmbedding
from pennylane.templates.layers import StronglyEntanglingLayers
from pennylane.init import strong_ent_layer_uniform
dev = qml.device('default.qubit', wires=2)
@qml.qnode(dev, interface="torch")
def circuit(weights, x=None):
AngleEmbedding(x, [0,1])
StronglyEntanglingLayers(weights=weights, wires=[0,1])
init_weights = …
```
=> Adds a print_applied method to QNodes

doc/development/plugins.rst
Updates the building a plugin guide to:
* Fix broken links
* Change the structure slightly (separate the 'Applying operations' section into 'Applying Operations', 'Measuring observables', and 'Advanced execution').
* Add info on tensor observable API
**Benefits:** links are fixed, now back up to date.
**Related GitHub Issues:** #362
=> Updates the building a plugin guide

pennylane/plugins/__init__.py, requirements.txt, setup.py
**Context:**
The Tensornetwork is missing as a requirement in `setup.py` and this causes tests of plugins (e.g. PennyLane-Qiskit) to fail when using a device from PennyLane core.
Adding the Tensornetwork library as a requirement in `setup.py`
**Benefits:**
Fixing Travis tests for plugins.
N/A
N/A
=> Adding tensornetwork to setup.py

pennylane/_device.py, pennylane/circuit_graph.py, pennylane/measure.py, pennylane/operation.py, pennylane/plugins/default_qubit.py, pennylane/qnode.py, pennylane/qnode_new/qnode.py, pennylane/templates/embeddings.py, pennylane/templates/layers.py, pennylane/utils.py, pennylane/variable.py
**Context:**
The ``Raises`` section is often missing from docstrings in PennyLane. Docstrings modifiend in the upcoming PR  #377 were left intact.
Adds the ``Raises`` section with a related message.
**Benefits:**
Information about exceptions appears in the documentation online.
N/A
N/A
=> Adding 'Raises' sections to docstrings throughout PL

pennylane/plugins/default_qubit.py
**Context:**
Currently, the ``expval``, ``var`` and ``sample`` methods of ``default_qubit`` all include a minor check for getting the operator matrix of an observable. This is done so that not just a single, but multiple observables are accepted.
Organizes the check into the new separate method ``get_operator_matrix_for_measurement`` in ``default_qubit``.
**Benefits:**
Removes code duplication and makes the code cleaner.
N/A
N/A
=> Refactor getting the operator matrix into separate method

pennylane/optimize/qng.py, tests/test_optimize_qng.py
**Context:** The explicit pseudo-inverse, as used by the QNG optimizer, can be numerically unstable.
**Description of the Change:** Replaces the use of `sp.linalg.pinvh(metric_tensor) @ grad` with `np.linalg.solve(metric_tensor, grad)`.
**Benefits:** Should be much more stable and have better accuracy.
=> Replace pinv with np.linalg.solve in the QNG optimizer

doc/introduction/configuration.rst
Fix the typo in the example for the configuration file
=> Correct typo in configuration file

.github/CONTRIBUTING.md
**Context:**
Certain links are currently broken in the ``.github/CONTRIBUTING.md`` file.
Fixes the link urls and places the correct links.
**Benefits:**
The page once again contains the correct urls.
As a follow-up, the [issue template](https://github.com/XanaduAI/thewalrus/blob/master/.github/ISSUE_TEMPLATE.md) could be updated as per the warning from github.
N/A
=> Correcting link urls, placing the correct links

doc/conf.py, doc/requirements.txt
**Context:**
There are many copy snippets on the PL documentation websites and it would be nice to make them copiable.
Adds the ``sphinx-copybutton`` extension and the requirement for the extension.
**Benefits:**
Every code snippet becomes copiable.
This copy button does not hide prompts such as ``>>>`` in the beginning of the line or result lines. This is currently an open issue: https://github.com/choldgraf/sphinx-copybutton/issues/30
Another approach could be using a [solution that hides prompts](http://z4r.github.io/python/2011/12/02/hides-the-prompts-and-output/). This would then, not have the copying functionality.
N/A
=> Adding the copy button in sphinx

setup.py
**Context:**
When installing PennyLane through
``pip install git+https://github.com/XanaduAI/pennylane.git#egg=pennylane``, the following traceback follows upon ``import pennylane``:
```python
File "<stdin>", line 1, in <module>
File "/lib/python3.7/site-packages/pennylane/__init__.py", line 35, in <module>
from ._device import Device, DeviceError
File "/lib/python3.7/site-packages/pennylane/_device.py", line 23, in <module>
from pennylane.qnodes import QuantumFunctionError
ModuleNotFoundError: No module named 'pennylane.qnodes'
```
Adding ``pennylane.qnodes`` to the ``packages`` list in ``setup.py`` and ordering the other packages in alphabetical order.
**Benefits:**
The packaging is corrected and ``pip install …
=> Reordering and adding pennylane.qnodes to setup.py's packages

.travis.yml, doc/requirements.txt, requirements.txt, setup.py
**Context:** The latest release of SciPy, v1.4.0, uses a version of pybind11 that clashes with the version used for PyTorch. Attempting to import pytorch _after_ SciPy will lead to a segmentation fault.
**Description of the Change:** Pins scipy to v1.3.2 for now, to temporarily fix the issue.
**Benefits:** CI and docs will build again
**Possible Drawbacks:** Will need to remember to unpin once 1.4.1 is released.
**Related GitHub Issues:** https://github.com/scipy/scipy/issues/11237
=> Pin scipy to version 1.3.2

doc/requirements.txt, requirements.txt, setup.py
Reverts XanaduAI/pennylane#447
Now that Scipy 1.4.1 is out, this PR can be reverted
=> Revert "Pin scipy to version 1.3.2"

doc/introduction/chemistry.rst, qchem/pennylane_qchem/qchem.py, qchem/tests/test_active_space.py, qchem/tests/test_convert_hamiltonian.py, qchem/tests/test_decompose_hamiltonian.py, qchem/tests/test_generate_hamiltonian.py, qchem/tests/test_meanfield_data.py
Function names in PL-Qchem were previously long and repetitive. This PR changes function names to shorten then and make them more intuitive. Note that file names for tests have also been changed
=> Refactor function names

pennylane/plugins/default_qubit.py
**Context:**
The definition of the ``ev`` method was duplicated in the recent version of ``DefaultQubit``.
Remove the duplicated method.
**Benefits:**
No duplicate function definitions.
N/A
N/A
=> Remove duplicate definition

pennylane/plugins/default_qubit.py
**Context:**
There are some outputs when using ``default.qubit``.
Remove the unnecessary print statement from ``default.qubit``.
**Benefits:**
No outputs.
N/A
N/A
=> Remove unnecessary print statement

doc/introduction/chemistry.rst, pennylane/_device.py, tests/test_device.py
**Context:**
There is currently no check for instantiating the ``Device`` class with ``shots<1``.
Use the setter of the ``shots`` property instead of setting the ``_shots`` attribute in the ``__init__`` method of ``Device``. This setter includes checks.
**Benefits:**
Subclasses of ``Device`` cannot be instantiated with ``shots<1`` and an error is raised (e.g. devices from the Qiskit plugin).
N/A
Related integration test fails in the Qiskit plugin.
=> Setting shots when instantiating Device

pennylane/beta/plugins/__init__.py, pennylane/beta/plugins/default_tensor.py, pennylane/beta/plugins/default_tensor_tf.py, setup.py, tests/beta/test_default_tensor.py, tests/beta/test_default_tensor_tf.py, tests/conftest.py
**Context:** The experimental TensorNetwork simulator had a short name that did not fit the PennyLane convention for device shortnames.
* `expt.tensornet` has become `default.tensor`
* `expt.tensornet.tf` has become `default.tensor.tf`
**Benefits:**
* The `expt` prefix has been replaced by `default`, to bring it inline with existing PennyLane simulators.
* `tensornet` has been shortened to `tensor`
=> Rename expt.tensornet device to default.tensor

pennylane/circuit_graph.py, pennylane/operation.py, pennylane/qnodes/base.py, tests/qnodes/test_qnode_base.py, tests/test_operation.py
**Context:**
A `Tensor` instance might contain `Identity` instances in its `obs` attribute. It is oftentimes preferable to:
* not have such identities there
* in case there is only a single observable in `obs`, obtain the single observable instead of a `Tensor`
Adds the `non_identity_obs` attribute and the `prune` method to the `Tensor` class, where
* The `non_identity_obs` returns the non-identity observables contained in the tensor product.
* The `prune` method returns a pruned tensor product of observables by removing the `Identity` instances from the observables building up the `Tensor`. If the tensor product only contains one observable, then this observable instance is returned.
**Benefits:**
There are functionalities included to remove unnecessary …
=> Create Tensor prune method for removing Identity instances

.github/CHANGELOG.md, .travis.yml, setup.py
**Context:** Python 3.8 has been out for a couple of months now, and a lot of dependencies are adding support for it.
**Description of the Change:** Adds continuous integration against Python 3.8
**Possible Drawbacks:** Currently, wheels are not available for TensorFlow on Python 3.8.
=> Check Python 3.8 compatibility

pennylane/qnodes/base.py, pennylane/qnodes/passthru.py
**Context:**
Quantum functions need a QNode as a context to capture their contents when they are executed. The context is currently set using a global variable that the nodes set in their `_construct` method, and then released immediately afterwards.
* `BaseQNode` is given `__enter__` and `__exit__` methods, turning it into a context manager for qfuncs.
**Benefits:**
* The context is set using a `with` statement in the `_construct` methods of `BaseQNode` subclasses. All the code that involves the global variable is now in one place, and releasing the context happens automatically even if there's an exception in the qfunc.
=> Make QNodes context managers for qfuncs.

.github/CHANGELOG.md, pennylane/operation.py, tests/qnodes/test_qnode_qubit.py
**Context:**
If a `VariableRef` has a zero internal multiplier, `Operation.get_parameter_shift` raises a divide-by-zero error.
* Adds a check for a zero multiplier.
* Adds a test for `VariableRef` multipliers.
**Benefits:**
* The bug is fixed.
=> Fixes the divide-by-zero bug in Operation.get_parameter_shift.

pennylane/templates/embeddings/amplitude.py
**Context:**
Fixes a bug a user found: ``AmplitudeEmbedding`` had a lower normalization tolerance than the qnode, leading to edge cases where almost normalized states were used in a simulation.
Update tolerance to qnode value of 1e-10.
**Related GitHub Issues:** 
Discussion Forum thread https://discuss.pennylane.ai/t/help-with-custom-circuit-design-in-pennylane/343
=> change tolerance

doc/code/qml_operation.rst, doc/code/qml_utils.rst, doc/code/qml_variable.rst, pennylane/beta/plugins/default_tensor_tf.py, pennylane/circuit_drawer/representation_resolver.py, pennylane/circuit_graph.py, pennylane/operation.py, pennylane/qnodes/base.py, pennylane/qnodes/passthru.py, pennylane/templates/embeddings/amplitude.py, pennylane/templates/state_preparations/mottonen.py, pennylane/templates/utils.py, pennylane/utils.py, pennylane/variable.py, tests/circuit_drawer/test_representation_resolver.py, tests/circuit_graph/test_circuit_graph_hash.py, tests/qnodes/test_qnode_base.py, tests/test_operation.py, tests/test_qubit_device.py, tests/test_templates_utils.py, tests/test_variable.py
**Context:**
Recently in #488, the `Variable` class was renamed to `VariableRef`, in order to avoid confusion with the TensorFlow `Variable` class, and to better represent what the class represented (a reference to a free parameter).
However, we noticed after the fact that several of the plugins import `qml.Variable` as part of their program conversion logic. Due to time and resource constraints, and the fact that a bugfix release of PennyLane core is imminent, it has been decided to temporarily revert the renaming in PennyLane core, to avoid breaking API changes in a bugfix release/ the need to release new versions of the plugins.
* Reverts all instances of `VariableRef` to `Variable` across the code base, docs, and test suite.
**Benefits:**
* Avoids …
=> Temporarily rename `VariableRef` back to `Variable`

pennylane/templates/layers/strongly_entangling.py, tests/test_templates_layers.py
Currently, the user receives a `ZeroDivisionError` when using a `StronglyEntanglingLayer` on just one qubit. This is due to the `l % (len(wires) - 1)` term in line 102 which is for checking the ranges of the two qubit gates.
This PR fixes this bug by only initiating and checking `ranges` if the number or wires is above 1. Otherwise, `ranges` is set to be a list of all zeros.
MWE:
```python
from pennylane.templates import StronglyEntanglingLayers
n_qubits = 1
dev = qml.device("default.qubit", wires=n_qubits)
@qml.qnode(dev, interface='tf')
def circuit(weights):
StronglyEntanglingLayers(weights, wires=list(range(n_qubits)))
weights = np.random.random((3, n_qubits, 3))
circuit(weights)
```
EDIT: At one point I …
=> Fix bug in single qubit strongly entangling layers

pennylane/circuit_graph.py, tests/qnodes/test_qnode_base.py
**Context:**
The `print_applied` function was added to the `QNode` to allow easy inspection of the applied circuit. Later, the possibility of returning probabilities was added to PennyLane via `return qml.probs`. But it was forgotten to add it to the return type dictionary in `print_applied` so that the method crashed when probabilities were returned.
A fallback was added to the return type dictionary to prevent such errors in the future and an appropriate display of probs was added.
**Benefits:**
One more bug fixed!
None.
=> Fix print_applied for Probabilities

pennylane/templates/broadcast.py, pennylane/templates/embeddings/amplitude.py, pennylane/templates/embeddings/angle.py, pennylane/templates/embeddings/basis.py, pennylane/templates/embeddings/displacement.py, pennylane/templates/embeddings/qaoa.py, pennylane/templates/embeddings/squeezing.py, pennylane/templates/layers/basic_entangler.py, pennylane/templates/layers/cv_neural_net.py, pennylane/templates/layers/random.py, pennylane/templates/layers/simplified_two_design.py, pennylane/templates/layers/strongly_entangling.py, pennylane/templates/state_preparations/basis.py, pennylane/templates/state_preparations/mottonen.py, pennylane/templates/subroutines/interferometer.py, pennylane/templates/utils.py, tests/test_templates_utils.py
**Context:**
In PR #564  the issue of having the functions in ``pennylane.templates.utils`` being private came up. Since we want to expose them in the docs for developers to use, it is more consistent to make them public.
Refactor the names to delete leading underscore.
Minor polish of docstrings.
**Benefits:**
Will make the ``automodapi`` command included in PR #564 show the functions.
=> Refactor template utils function to be public

.github/CHANGELOG.md
**Context:**
In PR #566 the changelog was not updated to account for the template utils functions now being public. This PR rectifies the omission.
Add entry to CHANGELOG.
=> add PR 566 in changelog

tests/qnn/test_keras.py
This PR speeds up the KerasLayer tests.
Currently:
`192 passed, 2 warnings in 138.41s`
This PR:
`49 passed, 2 warnings in 6.27s`
Generally, this is done by lightening the load due to lots of parameterizations, rather than removing tests. Specifically:
- Removing loops over batch size, which didn't really add much to the tests anyway
- Lowering the batch size to 2 in all cases
- Changing `indices_up_to(4)` to `indices_up_to(2)` in `test_call`
- Removing the loop over `qml.qnodes.decorator.ALLOWED_INTERFACES` in tests such as `test_call`
- Adding a `test_interface_conversion` to test for conversion between QNode interfaces
=> Speed up KerasLayer tests

tests/qnn/test_keras.py, tests/qnodes/test_qnode_decorator.py
**Context:**
We had a very hard-to-track bug in the tests: When moving a specific test into a subfolder, it would suddenly fail. What happens is that moving the test changes the execution order of tests. As a consequence, a certain troublesome qnode test gets executed first. In it, a device class attribute gets assigned and screws up the later test.
Unset value of attribute in test that causes trouble.
**Benefits:** Prevents future issues where this test interferes with others.
=> Unset attribute in test

pennylane/_qubit_device.py, tests/test_qubit_device.py
**Context:**
As of https://github.com/XanaduAI/pennylane/pull/573 the `analytic_probability` method has been added to the `QubitDevice` and it was made an __abstract method__. What this implies, is that every device inheriting from `QubitDevice` will have to define this method.
This, however, logically should not be required for hardware-like devices.
If `analytic_probability` is not defined, the following ``TypeError`` is raised:
```python
TypeError: Can't instantiate abstract class QPUDevice with abstract methods analytic_probability
../pennylane/pennylane/__init__.py:164: TypeError
```
- Modifies `QubitDevice.analytic_probability` from being an abstract method to raising `NotImplementedError` upon being called
**Benefits:**
The implication for devices …
=> Modify analytic_probability from being abstract to raising NotImplementedError

pennylane/templates/layers/random.py, tests/templates/test_layers.py
**Context:**
Fixes #580 with an extensive improvement of the docstring and tests.
Explains random behaviour in docstring
We decided for complex reasons to make the template use a default seed, which means that whenever it is called without a seed it produces one and the same circuit. This is not intuitive, but I hope it is now explained in the docs.
**Related GitHub Issues:** #580
=> Improve RandomLayers docstring

pennylane/collections/map.py, pennylane/vqe/vqe.py, tests/collections/test_collections.py, tests/test_vqe.py
**Context:**
Recently the ability to pass the step size for the finite differences grad method was added #530. Reflecting this change in `qml.map` and `VQECost` was, however, left out.
Adds `**kwargs` to the signature of `VQECost.__init__` and `qml.map`.
**Benefits:**
The step size (`h`) can now be passed  as a keyword argument to these funcitons.
N/A
N/A
=> Kwargs in qml.map and VQECost (example of passing step size)

.github/CHANGELOG.md, pennylane/qnodes/decorator.py, pennylane/qnodes/jacobian.py, tests/collections/test_collections.py, tests/qnodes/test_qnode_decorator.py, tests/qnodes/test_qnode_jacobian.py, tests/test_vqe.py
**Context:**
This PR allows users to create QNodes with a set order for the finite difference method. Without this PR, the `jacobian` and `_pd_finite_diff` of `JacobianQNode` do allow an `order` option, but this is not  settable upon instantiation.
Add an `order` attribute that is set when the `JacobianQNode` is instantiated, and passed on to `_pd_finite_diff`. Update tests accordingly.
**Benefits:**
The order can now set when `JacobianQNode` is initialized.
We were already using the default order of 1, which seems to be the best. Allowing users to more easily change this opens the possibility of it being misused. However, the default is still 1 and it is likely only advanced users will know to change the order.
**Related GitHub …
=> Expose the finite difference order when creating a QNode

pennylane/measure.py
The CNOT in the example does not make a difference. We are not creating a Bell state here, as qubit 0 is the control for `CNOT` which was left in the 0 state after the `Hadamard` on the 1. qubit. Therefore adding it might just complicate this example.
=> Minor update to probs example circuit

.github/CHANGELOG.md, doc/development/plugins.rst, pennylane/_qubit_device.py, tests/test_prob.py
**Context:**
Estimating probabilities for the `analytic=False` option was added in #573. However, the current solution results in errors for certain edge cases.
```python
dev = qml.device('default.qubit', wires=1, analytic=False)
def circuit(): 
qml.PauliX(0) 
return qml.probs(wires=[0])
circuit()
```
Yields:
```python
~/pennylane/pennylane/_qubit_device.py in probability(self, wires)
417             return self.analytic_probability(wires=wires)
418 
--> 419         return self.estimate_probability(wires=wires)
420 
421     def marginal_prob(self, prob, wires=None):
~/pennylane/pennylane/_qubit_device.py in estimate_probability(self, wires)
394         prob = np.zeros([len(wires) ** 2], dtype=np.float64)
395         print('estimate prob: ', prob, …
```
=> Fix estimate prob

.github/CHANGELOG.md, .travis.yml, pennylane/templates/layers/random.py
**Context:**
Fix for Issue #532: The RandomLayers template used numpy's ``random.choice`` function to select wires. This function however returns ``numpy`` objects, which some devices - like qiskit - can't deal with.
Note that with our planned improved wire management this bug would not appear.
Convert wires back to ``int``.
Fixes #532
=> Fix Issue 532 - Bug in RandomLayers

.github/CHANGELOG.md, pennylane/operation.py, pennylane/ops/__init__.py, pennylane/ops/cv.py, pennylane/ops/qubit.py, pennylane/qnodes/base.py, tests/beta/test_default_tensor.py, tests/qnodes/test_qnode_base.py, tests/test_operation.py
**Context:**
To introduce a ``Wires`` class we need to rename a small existing ``Wires`` class. This PR does the refactor.
It also makes the constants defined in the class more specific
* Refactor ``qml.operations.Wires`` -> ``qml.operations.ActsOn``
* Refactor ``qml.operations.Wires.All`` -> ``qml.operations.ActsOn.AllWires``
* Refactor ``qml.operations.Wires.Any`` -> ``qml.operations.ActsOn.AnyWires``
**Benefits:**  Name is freed and class is more specific.
=> Refactor old Wires class

.github/CHANGELOG.md
I had placed my name under Contributors in the changelog for the wrong Release version.
=> Fixed contributor list

.github/CHANGELOG.md, pennylane/interfaces/tf.py, tests/interfaces/test_tf.py
This PR fixes https://github.com/XanaduAI/pennylane/issues/613, where it was reported that `tape.jacobian` doesn't work using the TF interface.
Currently, the following code does not work:
```python
import tensorflow as tf
dev = qml.device("default.qubit", wires=1)
@qml.qnode(dev, interface="tf")
def circuit(params, params2):
qml.RX(params[0], wires=0)
qml.RY(params[1], wires=0)
qml.Rot(*params2, wires=0)
return qml.probs(0)
params = tf.Variable([0.1, 1.0])
params2 = tf.Variable([0.1, 1.0, 2.0])
with tf.GradientTape() as tape:
res = circuit(params, params2)
print(res)
jacobian = tape.jacobian(res, [params, params2])
print("Jacobian (TF):", jacobian)
```
(note, slightly edited from the issue to make the QNode arguments be multiple tensors)
With this PR, the above …
=> Fix TensorFlow's jacobian when applied to a QNode

pennylane/qnodes/passthru.py, tests/qnodes/test_qnode_passthru.py
**Context:**
The decompositions of operations raise an error within `PassthruQNode` (see #620).
Turned off domain checking for `PassthruQNode._check_circuit`, but outside of the context such that no queuing takes place (e.g. from decompositions)
**Benefits:**
* Solves #620
* The `"classical"` option can now be passed in the following `default_tensor_tf` test:
https://github.com/XanaduAI/pennylane/blob/f17ce4749416345c2ec172fb46f9b6c9cb839a85/tests/beta/test_default_tensor_tf.py#L682
As per this TODO:
https://github.com/XanaduAI/pennylane/blob/f17ce4749416345c2ec172fb46f9b6c9cb839a85/tests/beta/test_default_tensor_tf.py#L726
N/A
#620, For code quality: #630
=> Fix passthru decomposition

pennylane/_device.py
**Context:** The existing `__str__()` and `__repr__()` methods of the abstract `Device` class were missing format parameters.
**Description of the Change:** Adds in string parameters.
Example:
```pycon
>>> import pennylane as qml
>>> dev1 = qml.device("qiskit.basicaer", wires=4)
>>> dev1
<BasicAerDevice (qiskit.basicaer, wires=4, shots=1024) at 0x7f05108a37f0>
>>> print(dev1)
Qiskit PennyLane plugin
Short name: qiskit.basicaer
Package: pennylane_qiskit
Plugin version: 0.9.0-dev
Author: Xanadu
Wires: 4
Shots: 1024
```
If a plugin developer wants to display additional plugin-specific information, they will need to manually define `__str__`. E.g., if the Qiskit device wants to display the provider information.
**Benefits:** Printing devices works as expected. …
=> Fix string representation of devices

pennylane/beta/plugins/default_tensor_tf.py, pennylane/qnodes/decorator.py, tests/beta/test_default_tensor_tf.py, tests/qnodes/test_qnode_decorator.py
**Description of the Change:** Renames `diff_method="classical"` to `"backprop"` 
**Benefits:** Better describes the differentiation method than "classical". Note that I have not updated the changelog, as this will cause a non-trivial clash with #634; I will update it there once merged in.
=> Rename the classical diff_method to backprop

pennylane/optimize/rotoselect.py, pennylane/optimize/rotosolve.py, tests/test_optimize.py
**Context:**
The Rotosolve and Rotoselect optimisers do not work properly with nested weights; throwing an `IndexError: too many indices for array`, in, e.g., this case:
```python
weights = np.random.random(size=(2, 1))
dev_qubit = qml.device('default.qubit', wires=1)
@qml.qnode(dev_qubit)
def circuit(weights):
qml.RX(weights[0, 0], wires=0)
qml.RX(weights[1, 0], wires=0)
return qml.expval(qml.PauliZ(wires=0))
opt = qml.RotosolveOptimizer()
weights = opt.step(lambda w: circuit(w), weights)
```
The Rotosolve and Rotoselect optimisers are updated to support nested arrays/lists for input weights. Furthermore, the corresponding tests are updated to test this. They are also fixed so that they work properly (I found some …
=> Rotosolve unflatten fix

.github/CHANGELOG.md, pennylane/circuit_graph.py, tests/circuit_graph/test_qasm.py, tests/conftest.py
* Adds `CircuitGraph.to_openqasm()` method, which serializes the circuit graph as an OpenQASM string. A dummy 'QASM Serialization' device is also created, allowing the serialization method to take advantage of built-in decomposition logic. For example:
```pycon
>>> dev = qml.device("default.qubit", wires=2)
>>> @qml.qnode(dev)
>>> def qnode(x, y, z):
...    qml.Rot(x, y, z, wires=1)
...    return qml.expval(qml.PauliX(0))
>>> qnode(0.3, 0.1, 0.2) # construct the qnode
>>> print(qnode.circuit.to_qasm())
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c[2];
rz(0.3) q[1];
ry(0.1) q[1];
rz(0.2) q[1];
h q[0];
measure q[0] -> c[0];
measure q[1] -> c[1];
```
* Adds `circuit_graph/test_qasm.py` test file, containing three test classes:
- Unit tests, directly …
=> Serialize CircuitGraph to QASM

qchem/CHANGELOG.md, qchem/pennylane_qchem/_version.py, qchem/pennylane_qchem/qchem.py, qchem/tests/test_hf_state.py
**Context:**
Initialization of the qubit states for QChem applications 
Add the function ``hf_state`` to ``qchem`` module to generate an array encoding the occupation-number representation of the Hartree-Fock (HF) state. 
**Benefits:**
This function allows to initialize the qubit register to encode the HF state, the typical starting point for quantum chemistry simulations. 
e.g.,
```
n_electrons = 2
m_orbitals = 4
init_state = hf_state(n_electrons, m_orbitals)
qml.BasisState(init_state, wires=wires)
```
None
None
=> Add function 'hf_state' to 'qchem' module

doc/introduction/interfaces/tf.rst
**Description of the Change:** Corrects `circuit()` call to `circuit4()` in the final example.
**Benefits:** Corrects typo.
=> Fixes a typo in the TF interface documentation

.github/CHANGELOG.md, .travis.yml, README.rst, doc/development/guide/installation.rst, pennylane/interfaces/tf.py, qchem/CHANGELOG.md, qchem/setup.py, setup.py, tests/collections/conftest.py, tests/interfaces/test_tf.py, tests/interfaces/test_torch.py, tests/templates/test_integration.py, tests/test_configuration.py, tests/test_vqe.py
**Context:** Python 3.5 reaches end of life [2020-09-13](https://devguide.python.org/#status-of-python-branches), and several other big Python frameworks (including [NumPy](https://numpy.org/neps/nep-0029-deprecation_policy.html)) have deprecated Python 3.5 support.
In addition, by dropping Python 3.5 support, we can now increase our TF1 support from 1.13 (the highest version support on Python 3.5) to TF 1.15, which is significantly more compatible with TF2 and will ease maintenance.
* Deprecates official Python 3.5 support, and removes Python 3.5 from the Travis build matrix.
* Increases minimum TensorFlow version from 1.13 to 1.15.
**Benefits:**
We can now use features introduced in Python 3.6, including:
* f-strings:
```pycon
>>> name = "Fred"
>>> f"He …
```
=> Officially remove Python 3.5 support, update TF1.X support to >=1.15

pennylane/templates/state_preparations/arbitrary_state_preparation.py
**Context:**
There seems to be a bug in the docstring of the ``ArbitraryStatePreparation`` template, which says that 2^n-2 weights are expected, while the template needs (and checks for) 2^(n+1)-2.
**Description of the Change:** Adapt docstring.
=> change require wires in docstrin

.github/CHANGELOG.md, tests/templates/test_subroutines.py
**Context:**
This PR fixes a bug in the unit tests ``test_single_ex_unitary_operations`` and ``'test_double_ex_unitary_operations``. This is very simple fix but a very important one as it allows to test correctness of the entire set of quantum gates applied for building the UCCSD ansatz. 
Add a loop in functions ``test_single_ex_unitary_operations`` and ``test_double_ex_unitary_operations`` in the module ``test_subroutines.py``.
**Benefits:**
Improves significantly the robustness of the unit tests.
None
None
=> Fix bug in the functions "test_single_ex_unitary_operations" and "test_double_ex_unitary_operations"

doc/requirements.txt, pennylane/beta/plugins/default_tensor.py, requirements.txt
The tensor network plugin was causing tests to fail for Python3.6. Upon closer inspection, I determined that this is because Travis is pulling in tensornetwork v0.4.0, which has breaking changes to the UI (the plugin is coded against v0.3.0). 
However, the other Python versions pass all tests, despite also using tensornetwork v0.4.0 :thinking:. Could there be some issue with the provided wheels??
=> Pin version of tensornetwork and update docstring

pennylane/wires.py, tests/test_wires.py
**Context:**
Part of wires refactor. 
Adds ``at_index`` function to wires class, which returns the wire representation at a given index.
Adapts the class to deal correctly with strings as inputs. Formerly we would have
>>> Wires('h')
<Wires=['h', 'i']>
but now we have
>>> Wires('h')
<Wires=['hi']>
Added test for both.
=> [WIRES] small tweaks to wires class

pennylane/_device.py, pennylane/_qubit_device.py, pennylane/beta/plugins/default_tensor_tf.py, pennylane/circuit_drawer/circuit_drawer.py, pennylane/circuit_drawer/representation_resolver.py, pennylane/circuit_graph.py, pennylane/operation.py, pennylane/plugins/default_qubit.py, pennylane/qnodes/base.py, pennylane/qnodes/qubit.py, pennylane/qnodes/rev.py, pennylane/templates/broadcast.py, pennylane/vqe/vqe.py, qchem/pennylane_qchem/qchem.py, tests/circuit_drawer/test_circuit_drawer.py, tests/circuit_graph/test_circuit_graph.py, tests/circuit_graph/test_qasm.py, tests/ops/test_qubit_ops.py, tests/plugins/test_default_qubit.py, tests/qnodes/test_qnode_base.py, tests/templates/test_embeddings.py, tests/templates/test_layers.py, tests/templates/test_state_preparations.py, tests/templates/test_subroutines.py, tests/test_operation.py, tests/test_qubit_device.py
**Context:**
We are planning a PennyLane release for 22 June at relatively short notice. The current master - which is halfway into the wire refactor - breaks the ``QubitDevice`` based plugins. 
We considered the best way to solve this (releasing small changes to the plugins to make them compatible, try different hotfixes as temporary solutions,...) and decided that the quickest and safest way is to roll back the changes that made the operator attribute ``wires`` be a wires object. 
With this, everything is back to as it were for the plugins. The changes are relatively easy to pick up in the next PR #666 of the wires refactor, which rolled back some of the changes anyways. 
Convert ``Operation.wires`` to list and temporarily fix all the tests that have …
=> [WIRES] Undo PR#653 which made operation.wires a Wires class object

doc/development/guide.rst, doc/development/guide/adr.rst
Adds a section to the PennyLane developers guide regarding ADRs. This includes:
* When to write an ADR.
* The style and contents of the ADR.
Note that this page does _not_ discuss the process of submission and acceptance of an ADR; it merely discusses ADR contents and style.
=> Adds details on ADR structure to the documentation.

.github/CHANGELOG.md, pennylane/interfaces/autograd.py, pennylane/interfaces/tf.py, pennylane/interfaces/torch.py, tests/interfaces/test_autograd.py, tests/interfaces/test_tf.py, tests/interfaces/test_torch.py
**Context:**
The PennyLane interface functions `to_torch(qnode)`, `to_tf(qnode)`, and `to_autograd(qnode)` currently all make the assumption that the input QNode either has no attached interface (i.e., it is a 'bare' `JacobianQNode`) or that it has an autograd interface.
This causes issues if the QNode to be converted has the same interface as the one to be applied (see PL-451, whereby `to_tf(to_tf(qnode))` causes the gradient to be zeroed), or already has a pre-existing interface.
* All interfaces now keep a reference to the original bare QNode under the `_qnode` attribute.
* The interface functions return the input QNode, without modification, if the input QNode interface matches the function.
* If the input QNode has a pre-existing interface, then the …
=> Allow interface functions to convert QNodes with pre-existing interfaces

pennylane/_qubit_device.py
Currently, the ``estimate_probability`` method of ``QubitDevice`` normalises probabilities by using the number of shots. There may be future pathological cases where the shots are changed, but the collected samples (in ``self._samples``) are not. For example, when we use the method directly:
```python
dev = qml.device('default.qubit', wires=2, analytic=False)
def circuit():
qml.RX(0.5, wires=0)
qml.RX(0.5, wires=1)
return qml.probs(wires=[0, 1])
circuit()
print(sum(dev.estimate_probability())) # 1.0
dev.shots = 10
print(sum(dev.estimate_probability())) # 100.0
```
This PR changes the method to use the length of the sample array instead.
=> Make QubitDevice's estimate_probability independent of the number of shots

qchem/CHANGELOG.md, qchem/pennylane_qchem/qchem/obs.py, qchem/tests/test_s2_obs.py
**Context:**
This is part of the refactoring of the obs module used to build many-body observables.
The total spin operator S^2 is constructed by calling the function `spin2` as implemented in the obs module.
**Benefits:**
The function to construct the observable is simpler and does not depend on any external-to-pennylane data structure. It returns the observable.
None
None
=> Refactor implementation of the total spin observable S2

qchem/CHANGELOG.md, qchem/pennylane_qchem/qchem/obs.py, qchem/tests/test_sz_obs.py
**Context:**
This is part of the refactoring of the ``obs`` module containing the functionalities to build many-body observables.
The total-spin projection operator ``Sz`` is constructed by calling the function ``spin_z`` as implemented in the ``obs`` module. 
**Benefits:**
The function to construct the observable is simpler. It does not depend on any external-to-pennylane data structure and returns directly the observable. 
None.
None.
=> Refactor implementation of the Sz observable

pennylane/beta/plugins/default_tensor_tf.py, pennylane/circuit_drawer/representation_resolver.py, pennylane/circuit_graph.py, pennylane/operation.py, pennylane/qnodes/base.py, pennylane/qnodes/cv.py, pennylane/qnodes/qubit.py, pennylane/qnodes/rev.py, tests/ops/test_qubit_ops.py, tests/qnodes/test_qnode_metric_tensor.py, tests/templates/test_decorator.py, tests/templates/test_state_preparations.py, tests/templates/test_subroutines.py, tests/test_operation.py, tests/test_utils.py
**Context:**
In the `Operator` class (including the inheriting classes `Operation`, `Observable` and `Tensor`), `.params` is used for the unevaluated parameters (so could contain Variable instances), while `.parameters` are evaluated.
The QNode always queries `Operator.params`, while the device always queries `Operator.parameters`.
The three main changes in `operation.py` are:
* `Operator.params` is changed to `Operator.data`
* Classes inheriting `Operator` are updated to call `self.data` instead of `self.params`
* `Tensor.params` is changed to `Tensor.data`
Furthermore, all calls to `op.params` are changed to `op.data`, including in a lot of tests.
**Benefits:**
It'll be less confusing having `op.data` and `op.parameters` rather than, as before, having …
=> Renaming Operator.params to Operator.data

doc/introduction/operations.rst
Quick PR that adds the Toffoli gate to the ops page in the docs.
=> Add Toffoli gate to operations page

pennylane/collections/map.py, pennylane/operation.py, pennylane/utils.py
**Context:**
Tiny PR into Maria's Wires PR for potential bug fixes. There are two places in the code that still assumes consecutive int wires which could affect qchem's adaptation of custom Wires. Making this separate from qchem since it touches the core codes.
1. The QNode `map` function still has a ` wires = list(range(dev.num_wires))` line. Replaced with `wires = dev.register`.
2. The `Tensor.prune()` function ignores custom Wires and uses int wire `0` if there are no non-identity. Replaced with `self.wires[0]`.
However, a few tests are failing after the change, all with `maximum recursion depth exceded` error. They all seem to stem from the function `utils._flatten()` where it tries to recursively flatten the new `Wires` class whose elements are still …
=> Leftover consecutive wires assumption in map and Tensor.prune

pennylane/operation.py, pennylane/wires.py
This PR temporarily solves the issue of how to order observables with the new wires management with a minimal solution.
Since the Tensor class will be redesigned soon, we limit ourselves here to implement a unique order by list comparison, which sorts lists lexicographically.
=> [WIRES] Sort observables in Tensor class

pennylane/devices/tests/test_wires.py, pennylane/plugins/tests/pytest.ini
One of the new wires tests was giving us trouble on stochastic devices, because it required a very high shot number to pass. Deleting it. 
Along with that some accidentally committed folders are deleted too.
=> [WIRES] Delete a wires test 

pennylane/devices/tests/pytest.ini
Re-add the pytest.ini file that was accidentally deleted.
=> Add pytest.ini file to device test suite in new folder

pennylane/devices/tests/test_gates.py
The finite precision of a unitary in the shared device tests causes some plugins to fail the tests. 
This PR constructs the unitary from two angles to allow for very high precision.
=> Increase precision of unitary in device tests

pennylane/circuit_graph.py, tests/circuit_graph/test_qasm.py
**Context:** The OpenQASM specification requires that all register indices are consecutive integers.
* Modifies the `to_openqasm()` method to serialize the index of each operation wires, rather than the label
* Fixes the corresponding tests
=> Fixes the OpenQASM serializer to work with the wires refactor

pennylane/devices/tests/test_wires.py
The device test suite currently fails when in non-analytic mode using `default.qubit`:
` pytest pennylane/devices/tests/ --analytic False --device default.qubit`
This is because an `np.allclose()` assert needs the tolerance updated to `atol`.
=> Fix test suite which fails for default.qubit when in non-analytic mode

pennylane/vqe/vqe.py
**Context:** In the last cell on qml.VQECost documentation page, code is wrong. In place of hamiltonian it should be H which is already declared above the last cell code block
**Description of the Change:** Changed `hamiltonian` to `H`
**Benefits:** Fixes the code bug
**Possible Drawbacks:** NA
**Related GitHub Issues:** #751
=> Fixed Error in code on qml.VQECost page #751

qchem/CHANGELOG.md, qchem/pennylane_qchem/qchem/obs.py, qchem/tests/test_particle_number_obs.py, qchem/tests/test_s2_obs.py, qchem/tests/test_sz_obs.py
**Context:**
This is a very minor refactor of the functions in the `obs` module for the sake of consistency in the used naming convention throughout QChem.
Merging into (#750).
The naming convention used in the `structure` module has been propagated to the `obs` module.
The changes include:
- `n_electrons` renamed to `electrons`.
- `n_orbitals` renamed to `orbitals`.
In addition, the argument `orbitals` is used now to pass the number of *spin*  orbitals.
**Benefits:**
Unified naming convention.
None
None
=> Minor refactor of the 'obs' module

doc/conf.py, doc/development/guide/adr.rst, doc/development/guide/installation.rst, doc/development/guide/pullrequests.rst, doc/development/plugins.rst, doc/index.rst, doc/xanadu_theme/footer.html, doc/xanadu_theme/header.html, doc/xanadu_theme/layout.html, pennylane/__init__.py
**Context:** Due to the change of GitHub organization, various links needed to be updated.
* Changes `XanaduAI/pennylane` to `PennyLaneAI/pennylane` across the board
* Updates the `plugins.rst` page to remove reference to the outdated plugin template repo, and to add in a link to the shared device tests.
**Possible Drawbacks:** Similar changes will need to be made in ~PennyLaneAI/pennylane.ai~, PennyLaneAI/qml, and all plugins.
**Related GitHub Issues:** Fixes #767
=> Update broken PennyLane links

benchmark/bm_jacobian_end_weighted.py, benchmark/bm_jacobian_front_weighted.py, pennylane/qnodes/base.py, tests/qnodes/test_qnode_base.py
**Context:**
Addresses the #541 issue where a solution to use `lists` internally was suggested. One thing that remained to be explored was whether the change would cause performance loss. Based on benchmarking results, this would not be the case (see **Benchmarking**).
Applies the change.
**Benefits:**
QubitUnitary can take complex matrices without any performance loss.
N/A
https://github.com/PennyLaneAI/pennylane/issues/541
**Benchmarking**
Applied the following benchmarks on `default.qubit` and `default.tensor`:
1. Jacobian evaluation uniform
2. Jacobian evaluation front weighted
3. Jacobian evaluation end weighted
*Results:*
1.
* `master` (`14bda6ac`)
```
default.qubit
Timing per loop: [0.19840829 …
```
=> Use lists to store variable values inside BaseQNode

.github/CHANGELOG.md, pennylane/_qubit_device.py, pennylane/devices/default_qubit.py, pennylane/devices/default_qubit_autograd.py, pennylane/devices/default_qubit_tf.py, tests/devices/test_default_qubit.py, tests/devices/test_default_qubit_autograd.py, tests/devices/test_default_qubit_tf.py
**Context:**
This PR uses some array/tensor manipulation tricks such as [roll](https://numpy.org/doc/stable/reference/generated/numpy.roll.html), [transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) and [slicing](https://stackoverflow.com/questions/42656930/numpy-assignment-like-numpy-take) to speed up the application of some gates:
- PauliX
- PauliY
- PauliZ
- Hadamard
- SWAP
- S
- T
- CNOT
- CZ
For example, `PauliX` can be achieved simply using `np.roll(state, 1, wire_axis)`. Currently in PL, these gates are applied using the `_apply_diagonal_unitary()` and `_apply_unitary_einsum()` methods, which both internally perform a contraction using `einsum`.
Additional methods have been added to `DefaultQubit` for each of the above …
=> Speed up default.qubit by using permutations to apply some gates

pennylane/beta/tapes/circuit_graph.py, pennylane/beta/tapes/tape.py
This PR changes the `QuantumTape._grad_method()` to make it more efficient. This method loops over the circuit graph observables and checks if a path exists between a given operator and observable. Presently, this is done by checking the size of the `CircuitGraph.nodes_between()` set, which is size zero if no path exists. However, a more direct approach is to use the new `CircuitGraph.has_path()` method, which internally uses `networkx.algorithms.shortest_paths.generic.has_path()`.
We can benchmark performance between different approaches for both calling the QNode and evaluating its gradient. Using a 6 qubit, 6 layer circuit we compare: (A) approach in this PR, (B) approach in `quantum-tape` branch, (C) approach in `quantum-tape` branch with the `if` statement in line 875 commented out, …
=> Use has_path instead of nodes_between

.github/CHANGELOG.md, doc/introduction/operations.rst, pennylane/devices/default_qubit.py, pennylane/devices/tests/test_gates.py, pennylane/ops/qubit.py, tests/ops/test_qubit_ops.py
**Context:** PennyLane currently has the CX (CNOT) and CZ gates, but does not provide the CY operation.
* Adds the CY operation to PennyLane, as `qml.CY`.
* Adds the decomposition `CY = S(0) @ CRY(pi/2, [0, 1])` for devices that don't support the CY gate natively. If a device does not support CRY, this will also be decomposed automatically.
* Adds tests.
=> Add qml.CY operation

pennylane/beta/queuing/measure.py, pennylane/beta/tapes/circuit_graph.py, pennylane/beta/tapes/tape.py, tests/beta/tapes/test_tape.py
**Context:** Extends the beta quantum tape to support Jacobian computation.
This PR adds the features and methods found in the `JacobianQNode` to the quantum tape. In particular, this includes:
* Gradient bookkeeping: validating and calculating the allowed parameter gradients, by inspecting the `grad_method` attribute of operations, and ensuring that the requested Jacobian method is supported by all parameters.
* Adds a new `NewCircuitGraph.has_path` method to the circuit graph, to help us determine whether there is a path between a parametrized operation and a measurement. This is a replacement for the `node_between` method, which has additional overhead; we only care that a path exists, we do not care to know the operations inbetween. This method was added …
=> [TAPE] Add support for tape gradient bookkeeping and Jacobian computation

.github/CHANGELOG.md, pennylane/wires.py, tests/test_wires.py
@cgogolin had the great request to add ``_add__`` and ``__radd__`` to the wires class as a shortcut to ``all_wires()``:
``` python
wires1 = Wires([2, 1, 3])
wires2 = Wires([1, 4, 5, 2])
wires3 = Wires([6, 5])
print(wires1 + wires2 + wires3) # <Wires = [2, 1, 3, 4, 5, 6]>
```
This PR adds the two functions and two tests. 
**Drawbacks:**
Unfortunately, this does not allow native use of ``sum([wires1, wires2, wires3])``, which would be quite elegant in our code base. ``sum`` requires a start object which is ``0`` by default, so the ``0`` wire would always be added. 
One could pass the start object explicitly and use ``sum([wires1 + wires2 + wires3], Wires([]))`` which produces the same result, but is arguably more confusing than ``all_wires([wires1 + wires2 + wires3])``.
=> Add ``__add__`` to Wires class.

doc/development/guide/architecture.rst, doc/development/guide/documentation.rst, doc/development/guide/installation.rst, doc/development/guide/tests.rst, doc/development/plugins.rst
**Context:** Was orienting myself by reading the documentation and caught some typos along the way.
**Description of the Change:** Various spelling/grammatical updates throughout the development guide.
**Benefits:** Typos are removed.
**Related GitHub Issues:** None
=> Fix typos in documentation

qchem/CHANGELOG.md, qchem/pennylane_qchem/qchem/obs.py, qchem/tests/test_two_particle.py
**Context:**
Generalization of PL-QChem to build arbitrary electronic Hamiltonians
Fix error in the calculation of the contribution of core orbitals to two-particle operators in the function ``two_particle``.
**Benefits:**
The contribution of core orbitals is computed correctly.
None
None
=> Fix error in the calculation of  'v_core' in the 'two_particle' function

pennylane/devices/tests/test_gates.py, pennylane/devices/tests/test_measurements.py
For devices like 'lighting.qubit', which does not support `Hermitian` observables and `QubitUnitary` gates, the shared device tests using such operations fail. This PR is a hotfix which queries the device and skips tests if necessary.
In the long run we would want a more general strategy of flagging tests based on device capabilities.
=> Skip device tests that use Hermitian and QubitUnitary if not supported by device

.github/CHANGELOG.md, pennylane/numpy/tensor.py, tests/test_numpy_wrapper.py
**Context:**
The PennyLane NumPy wrapper was recently modified so that indexed elements are returned as NumPy tensors:
```pycon
>>> fd = np.array([1, 2], requires_grad=False)
>>> fd[0]
np.array(1, requires_grad=False)
```
This is to ensure that the differentiability information (the `requires_grad` attribute) is not lost upon indexing. This matches the behaviour of other autodifferentiation frameworks:
```pycon
>>> fd = torch.tensor([1., 2.], requires_grad=True)
>>> fd[0]
tensor(1., grad_fn=<SelectBackward>)
```
A side effect, however, is that NumPy arrays aren't hashable; so functions (such as `set()`) which would previously iterate fine over 1D arrays, no longer work:
```pycon
>>> import numpy as onp
>>> set(onp.array([1, 2, 3]))
>>> {1, 2, 3}
>>> set(np.array([1, 2, 3]))
TypeError: …
```
=> Fixing compatibility related to scalar NumPy tensors and hashing

pennylane/devices/default_qubit_tf.py, tests/devices/test_default_qubit_tf.py
This PR resolves https://github.com/PennyLaneAI/pennylane/issues/835.
Currently, TensorFlow does not fully support slicing into tensors of rank 9 or above (see discussion in https://github.com/PennyLaneAI/pennylane/issues/835). This impacts `default.qubit.tf`, which uses slicing when applying certain gates such as CNOT through special tensor manipulation tricks. These gates are applied through special methods such as `DefaultQubit._apply_cnot()`.
The following special methods are available, with those having a red circle impacted by the above limitation:
- `_apply_x()` :green_circle: 
- `_apply_y()` :red_circle: 
- `_apply_z()` :red_circle: 
- `_apply_hadamard()` :red_circle: 
- `_apply_s()`, `_apply_t()` :red_circle: 
- `_apply_cnot()` :red_circle: 
- `_apply_swap()` :green_circle: 
- …
=> Fix applying operations in default.qubit.tf when using 9 or more wires

.github/CHANGELOG.md, pennylane/devices/default_qubit.py, pennylane/devices/default_qubit_tf.py, tests/devices/test_default_qubit.py, tests/devices/test_default_qubit_autograd.py, tests/devices/test_default_qubit_tf.py
During development of the `default.mixed` device, code coverage tests revealed that an `if` statement in the `_apply_state_vector()` was never evaluating to `True`. This PR fixes the same issue for `default.qubit` and therefore also for other devices that inherit from it. This should increase code coverage.
The issue is simply that `device_wires.labels` is an n-tuple, e.g., `(0, 1, 2)`, while `sorted(device_wires.labels)` is a list, e.g., `[0, 1, 2]`
=> Fixes if statement in default.qubit

doc/code/qml_grouping.rst, doc/xanadu_theme/static/xanadu.css_t, pennylane/grouping/graph_colouring.py, pennylane/grouping/group_observables.py, pennylane/grouping/optimize_measurements.py, pennylane/grouping/transformations.py, pennylane/grouping/utils.py, tests/grouping/test_graph_colouring.py, tests/grouping/test_group_observables.py, tests/grouping/test_grouping_utils.py, tests/grouping/test_optimize_measurements.py
This PR contains minor adjustments to standardize the docstrings of the `grouping` subpackage. It mostly addresses formatting and standardization, without substantial content being added (hence separated from #850).
The changes include:
* Placed the `Example` section at the end of each docstring
* Renamed section headers `**Usage example:**`and `**Example usage:**` to `**Example**`
* Shortened variable names in some examples
* Updated the indentation for `Returns` section, removed names of returned objects, updated `tuple` return type docs
* Removed line break at the end of the docstrings
* Adjusted `Raises` in one case
The following is the way a `tuple` return type was documented:
```rst
tuple:
* some_type1: some description or returned obj1
* some_type2: some description or returned …
```
=> Grouping subpackage docstring updates

.github/CHANGELOG.md, pennylane/_device.py, pennylane/_qubit_device.py, pennylane/qnodes/base.py, tests/qnodes/test_qnode_base.py, tests/test_device.py, tests/test_qubit_device.py
In response to Issue [847](https://github.com/PennyLaneAI/pennylane/issues/847), during optimization the number of device executions per iteration step can vary based upon factors such as the choice of optimizer and the choice of differentiation method.
An execution property has been added to the `Device` class. This allows executions of all default devices to be tracked.  
This enables easy access to the number of times a device has been executed and facilitates visualisation of this quantity.
May need updating dependent on updates to `shots`. 
(Closes https://github.com/PennyLaneAI/pennylane/issues/847)
=> add execution property to Device class for tracking the number of device executions over a QNodes lifetime

.github/CHANGELOG.md, codecov.yml, pennylane/ops/qubit.py, tests/ops/test_qubit_ops.py
**Context:** Applying `PauliRot` with the Pauli `II...I` previously threw an error as assumptions in `_matrix` and `decomposition` methods assumed at least one non-identity Pauli. Furthermore, in debugging this, it was found that input verification in the constructor did not account for the case where `wires` was a single `int`.
**Description of the Change:** Both issues have been addressed through checks to handle the special cases.
**Benefits:** Programs no longer terminate when encountering the above issues.
**Related GitHub Issues:** #856
=> Adds handling of single-qubit Paulis and all-identity Pauli to PauliRot operation. 

.github/CHANGELOG.md, pennylane/qnn/keras.py, pennylane/tape/qnode.py, tests/qnn/conftest.py, tests/qnn/test_keras.py, tests/qnn/test_qnn_torch.py
**Context:** The `qnn.KerasLayer` class needs modification to work in tape mode, due to the removal of QNode signature introspection.
**Description of changes:**
* The `KerasLayer` class requires different logic for signature validation and qnode evaluation in tape mode, so the new methods `_signature_validation_tape_mode` and `_evaluate_qnode_tape_mode`, to be called instead if in tape mode. This resulted in some 'rearrangement' of the class, but the underlying changes are minimal.
* The `get_circuit()` fixture is copied into `test_keras_layer.py`, since it needs to be modified for tape mode, _and_ the Torch class hasn't been ported yet (at least in `master`).
* Some of the tests would previously use the `get_circuit` fixture, but monkeypatch the created valid circuit to be non-valid, to …
=> Updating qnn.KerasLayer to work in tape mode

pennylane/templates/embeddings/displacement.py
A slight change in the docstring. Helps with rendering the [first line of the docs](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.embeddings.DisplacementEmbedding.html).
=> Small update in DisplacementEmbedding docstring

doc/introduction/templates.rst
While reviewing #879, I noticed that the templates quickstart required a lot of scrolling to get to the gallery of templates, kind of defeating its purpose as a quickstart. This PR emphasizes the gallery (the most useful and visually appealing part of the page imo), by:
* Removing the 'how to use a template' codeblock. Every template docstring now has a usage details section, so is perhaps not needed anymore here.
* Moving the 'custom templates' section to the end, after the gallery.
=> Update the templates quickstart to emphasize the templates gallery

pennylane/operation.py, pennylane/tape/measure.py, tests/tape/test_tape_measure.py, tests/test_observable.py, tests/test_operation.py
Adds a `__repr__` method to a tape's measurement process.
For example:
``` python
with qml.tape.QuantumTape() as tape:
qml.tape.measure.expval(qml.PauliZ(wires='a')@qml.PauliZ(wires='b'))
qml.tape.measure.var(qml.PauliZ(wires='b'))
```
In master:
``` python
print(tape.measurements)
>>>[<pennylane.tape.measure.MeasurementProcess object at 0x7f773edf1820>, <pennylane.tape.measure.MeasurementProcess object at 0x7f773edf19d0>]
```
On this branch:
``` python
print(tape.measurements)
>>>[expval(PauliZ(wires=['a'] @ PauliZ(wires=['b'])), var(PauliZ(wires=['b'])]
```
The observable `__str__` methods have been removed to have `__repr__` as the single source of truth, and since they rendered things funnily. Tests have been added.
=> Add representation to MeasurementProcess

.github/CHANGELOG.md, pennylane/qnodes/base.py, pennylane/templates/layers/random.py, tests/templates/test_layers.py, tests/templates/test_subroutines.py, tests/test_numpy_wrapper.py
**Context:**
* #900
* #893
Adds tensor unwrapping in BaseQNode for keyword arguments.
**Benefits:**
A more general solution compared to #893 for handling `pennylane.numpy.tensor` objects as gate parameters.
Related PennyLane-Qiskit tests:
* https://github.com/PennyLaneAI/pennylane-qiskit/pull/115
N/A
Closes #900
=> Add tensor unwrapping in BaseQNode for keyword arguments 

pennylane/tape/tapes/jacobian_tape.py, tests/tape/tapes/test_jacobian_tape.py
This PR fixes a bug in tape mode that occurs when some parameters are independent of a measurement. Consider the following snippet:
```python
qml.enable_tape()
dev = qml.device("default.qubit", wires=2)
def circ(params):
qml.RX(params[0], wires=0)
qml.RX(params[1], wires=1)
params = np.ones(2)
qml.grad(circ)(params)
```
This takes the gradient of a PauliZ expectation value on the first qubit. We expect to get `(array([-0.52167534, 0]),)` since the second parameter has no effect on the first qubit. Instead, we incorrectly get `(array([-0.52167534, -0.52167534]),)`.
Now suppose we have `return qml.expval(qml.PauliZ(1))`. Instead of getting an incorrect result, we get a …
=> Fix gradient in tape mode when measurements are independent of a parameter

tests/qnn/test_qnn_torch.py
**Context:**
In #899, a test of `TorchLayer` to run backward with `CUDA` tensor is implemented. I found that converting operation of the tensor to CUDA device was accidentally removed. This PR fixes that issue.
Changed the tensor to be fed into the QNode to be on GPU device.
**Benefits:**
The test has actual meaning.
None.
#899, #709
=> Followup #899

.github/CHANGELOG.md, pennylane/qaoa/layers.py, tests/test_qaoa.py
**Context:**
As part of the recent queuing refactor, _all_ operation objects now get queued within a `QueuingContext`. If a container object (such as `Tensor`) is queued, it annotates the queue to claim ownership of the (previously) queued constituent operations. Previously, this was not the case; the `Tensor` class did not queue itself, and the existence of tensor products was assumed implicitly.
The queuing refactor has been completed within [tape mode](https://pennylane.readthedocs.io/en/latest/code/qml_tape.html). 
However, the queuing refactor was not considered when the QAOA module was written, and some functions within the module (e.g., `_diagonal_terms`) create `Tensor` objects _within_ the QNode queuing context for the sole purpose of validation --- the created Tensor objects are …
=> Fixes bug in the QAOA _diagonal_terms function to take into account the queuing refactor

.github/CHANGELOG.md, doc/code/qml.rst, pennylane/__init__.py, tests/test_device.py
**Context:**
PennyLane uses Python [entrypoints](https://packaging.python.org/specifications/entry-points/) to load available plugin devices. To do so, we must import and query the `pkg_resources` built-in library.
However, `pkg_resources` loads all data _on import_, not when extracting entrypoints, which means that any existing Python sessions need to be restarted for newly installed plugins to be made available. This particular impacts users that are installing PennyLane and plugins on [Google Colab](https://colab.research.google.com/), as the error message returned ("Device does not exist!") does not indicate the required action, namely, restarting the runtime.
* A new function, `qml.refresh_devices()`, has been added, allowing PennyLane to rescan …
=> Allow PennyLane to rescan and refresh available plugin devices within the same Python runtime

.github/CHANGELOG.md, doc/code/qml.rst, doc/code/qml_qaoa.rst, doc/introduction/chemistry.rst, pennylane/__init__.py, pennylane/optimize/qng.py, pennylane/templates/layers/particle_conserving_u1.py, pennylane/templates/layers/particle_conserving_u2.py, pennylane/templates/subroutines/uccsd.py, pennylane/utils.py, pennylane/vqe/__init__.py, pennylane/vqe/vqe.py, qchem/tests/test_convert_observable.py, tests/test_optimize_qng.py, tests/test_qaoa.py, tests/test_vqe.py
This PR renames `VQECost` to `ExpvalCost` to reflect its more general usage. `VQECost` is available but deprecated.
=> Rename VQECost to ExpvalCost

.github/CHANGELOG.md, pennylane/qnodes/base.py, pennylane/vqe/vqe.py, tests/qnodes/test_qnode_base.py, tests/test_vqe.py
This PR provides support for returning the metric tensor in ExpvalCost.
Calculating metric tensors are not supported in general in tape mode, so as a short term fix, this PR creates a non-tape mode QNode. That QNode is then used for evaluation of the metric tensor. This adds back the restrictions we had in the old QNode (e.g., no in-QNode processing, restrictions on qnode signature), but allows the QNG optimizer to have some compatibility with tape mode.
A long term fix is to provide metric tensor evaluation in tape mode QNodes.
=> Support returning the metric tensor of ExpvalCost in tape mode

.github/CHANGELOG.md, doc/code/qml.rst, pennylane/__init__.py, tests/test_classical_gradients.py
**Context:**
If we would like to track the cost function during optimization, the ability to access the value of the cost function computed during the optimization step is ideal, rather than requiring the cost function to be recomputed manually and externally.
However, none of the optimizers explicitly compute the forward pass/cost function internally. So there is no explicit cost value that can be provided.
This is a quirk of Autograd - unlike PyTorch and TensorFlow, which enforce (via their UI) the need to manually perform a forward pass before you can access the backward pass, Autograd has no such restriction. Instead, calling ``autograd.grad()`` causes Autograd to perform both the forward pass and the backward pass at once.
* Modifies `grad_fn = …
=> Modify qml.grad so that it stores and makes accessible the value of the intermediate forward pass

.github/CONTRIBUTING.md
CI checks are now done using GitHub actions. This PR removes a final mention.
One question:
what is the purpose of `qchem/install_dependencies.sh`, which also accesses `$TRAVIS_PYTHON_VERSION`.
=> Remove mention of Travis

.github/CHANGELOG.md, pennylane/ops/qubit.py, tests/ops/test_qubit_ops.py
**Context:**
* For the metric tensor computation, all parametrized gates must provide their generator. If a gate does not provide its generator, the metric tensor computation will raise an error.
* The `qml.MultiRZ` gate allows us to very efficiently implement `exp(-i θ Z ⊗ Z ⊗ ... ⊗  Z/2)` on simulator devices, since it is a diagonal in the computational basis. However, if a device does not support `qml.MultiRZ`, the operation on `N` wires simply gets decomposed into `2N-2` CNOTs and a single RZ.
* `qml.MultiRZ` does not provide a generator. Therefore, when using the `QNGOptimizer`, one of two things could happen:
1. The device supports `MultiRZ` natively: QNG optimization will fail since the generator is unknown
2. The device does not support `MultiRZ` natively: QNG optimization will …
=> Define the generator for the MultiRZ operation

.github/CHANGELOG.md, pennylane/devices/default_qubit_tf.py, pennylane/devices/tf_ops.py, tests/devices/test_default_qubit_tf.py, tests/gate_data.py
**Context:**
Passing a TensorFlow `Variable` to the  `MultiRZ` operation with the `default.qubit.tf` device results in an error:
```python
import tensorflow as tf
x = tf.Variable(np.array([1.7]))
dev = qml.device('default.qubit.tf', wires=3)
@qml.qnode(dev, interface='tf')
def circuit(params):
qml.MultiRZ(params[0], wires=[0])
circuit(x)
```
```
~/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
96       dtype = dtypes.as_dtype(dtype).as_datatype_enum
97   ctx.ensure_initialized()
---> 98   return ops.EagerTensor(value, ctx.device_name, dtype)
99 
100 
TypeError: Cannot convert (-0-1j) to EagerTensor of dtype double
```
propagated from: …
=> Support for MultiRZ and CRot in default.qubit.tf

.github/CHANGELOG.md, pennylane/tape/tapes/tape.py, tests/tape/tapes/test_tape.py
**Context:**
Fixes a bug in `QuantumTape.set_parameters()`. The previous implementation assumed that the `self.trainable_parms` set would always be iterated over in increasing integer order. However, this is not guaranteed behaviour, and can lead to the incorrect tape parameters being set if this is not the case.
For example, consider the following edge case:
```python
N = 5
dev = qml.device("default.qubit", wires=N)
qml.enable_tape()
def circuit(weight):
qml.templates.DoubleExcitationUnitary(weight, wires1=[0, 1], wires2=[3, 4])
return [qml.expval(qml.PauliZ(w)) for w in range(N)]
```
The expected result of this circuit is always an all-ones array, however this is not the case:
```pycon
>>> print(circuit( 1.34817))
[0.78127841 …
```
=> Fixes bug in tape.set_parameters()

.github/CHANGELOG.md, pennylane/tape/qnode.py, tests/tape/tapes/test_qnode.py
**Context:** During code review of another PR, I noticed that the exception message for interfaces was not displaying correctly.
**Description of the Change:** Fixes the exception message 
**Benefits:** Bug fixed
=> Fix incorrect exception message for unknown interfaces

.github/CHANGELOG.md
Corrects #897 PR number to point to PR instead of the issue in changelog.
=> Correct PR number in changelog

qchem/CHANGELOG.md, qchem/pennylane_qchem/_version.py, qchem/pennylane_qchem/qchem/structure.py, qchem/requirements.txt, qchem/setup.py, qchem/tests/test_active_space.py, qchem/tests/test_convert_observable.py, qchem/tests/test_meanfield.py, qchem/tests/test_observable.py, qchem/tests/test_one_particle.py, qchem/tests/test_particle_number_obs.py, qchem/tests/test_s2_obs.py, qchem/tests/test_sz_obs.py, qchem/tests/test_two_particle.py
**Context:** OpenFermion v1.0 was recently released, which features a reorganization of the library. As a result, `qml.qchem` will fail on import if the latest version of OpenFermion is installed.
* Updates the import paths.
**Benefits:**
* The new import paths are backwards compatible with OpenFermion v0.11; qchem was previously importing based on the file location rather than the documented import location.
* A bugfix release of QChem will need to be made ASAP to allow QChem to continue working for current users.
=> Update OpenFermion import paths

.github/CHANGELOG.md, pennylane/operation.py, pennylane/ops/channel.py, tests/ops/test_channel_ops.py, tests/test_operation.py
This PR adds analytical gradient recipes for channels that support them, namely `BitFlip`, `PhaseFlip`, and `DepolarizingChannel`. It also removes:
1. A warning stating that analytical gradients are not supported for channels (now they are!) 
2. A check that was made to ensure that channel parameters were valid probabilities. This latter led to problems when parameters were circuit variables and in any case was not preventing parameters to have negative values during optimization
=> Adds analytical channel gradients + (removes unnecessary warnings)

.github/ISSUE_TEMPLATE.md, .github/workflows/assign_bugs.yml
**Context**
Adds an action that checks if an issue contains the `[BUG]` or `bug` keywords once being opened and:
* Assigns the `bug` label;
* Assigns people listed in advance to the issue.
Updates the issue template to encourage using the `[BUG]` keyword in the title of bug issues.
**Benefits**
Automated bug labelling and assignment to the team.
**Things to note**
* Checking the issue is done based on the text in the title and the body of the issue. That is, an issue labelled as `bug` will not be assigned automatically unless the correct keyword was used in the corresponding texts.
* Users to be assigned & listed are done statically for now. This will likely be subject to change and superceded. The approach taken is a beneficial starting point.
**Examples**
See …
=> Automatic bug assignment

doc/requirements.txt, pennylane/circuit_graph.py
This pull request fixes a small function that names a variable `list`, thus overriding python's inbuilt type.
=> avoid redefining a build-in type

.github/CHANGELOG.md, pennylane/tape/tapes/qubit_param_shift.py, tests/tape/interfaces/test_qnode_autograd.py
**Context:**
QNodes with a single probability output, of the form
```python
def circuit(x, y):
qml.RX(x, wires=[0])
qml.RY(y, wires=[1])
return qml.probs(wires=[1])
```
would result in the following error when differentiated in tape-mode using the parameter-shift rule:
```
File "/home/pennylane/tape/tapes/qubit_param_shift.py", line 172, in processing_fn
return np.dot(coeffs, results)
File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (2,) and (2,1,2) not aligned: 2 (dim 0) != 1 (dim 1)
```
This is due to the fact that we are using `np.dot(coeffs, results)` as a shorthand for `[c*r for c, r in zip(coeffs, results)]`. However, in the case of returning a single probability array, NumPy attempts to broadcast the dot product …
=> Fix bug where a QNode with a single probability output was not correctly differentiated

pennylane/wires.py
**Context:**
Make wire combining faster with sets.
Many of the wire combination methods (`shared_wires`, `all_wires` and `unique_wires`) previously used `if wire in list` a lot, which takes linear time when searching. These linear time searches were then looped over, causing the final run times to be O(n^2) where n is the number of labels. We replace many of these methods with faster methods that instead use `set`s, reducing their runtimes to just O(n).
Speedups:
```
all_wires small -10%
shared_wires small +25%
unique_wires small +67%
all_wires large +21%
shared_wires large +72%
unique_wires large +86%
```
See full benchmarks in comment below.
These improvements are orthogonal to David's improvements: #983
**Benefits:**
Wires should be faster
**Possible …
=> Faster wire combining.

.github/CHANGELOG.md, pennylane/devices/default_qubit.py
This is an update to the internals of `default.qubit` so that the `_apply_operation` method accepts an input state and returns an output state. This allows for external functions to interact with the device and request an evolved state - something we need in https://github.com/PennyLaneAI/pennylane/pull/1017.
It appears that we do not need to update the tests, since we have not written fully comprehensive unit tests for each method in `default.qubit`. The current tests use the `apply()` method, which is one step above `_apply_operation`, so at least the new changes are still being tested implicitly.
=> Update default qubit so that _apply_operation is more functional

pennylane/tape/tapes/qubit_param_shift.py, tests/tape/interfaces/test_qnode_autograd.py, tests/tape/interfaces/test_qnode_tf.py, tests/tape/interfaces/test_qnode_torch.py
**Context:**
* The QNode integration tests were hardcoded to only test finite differences and backprop
* Makes the QNode integration tests more robust, by adding in support for testing parameter-shift as well.
* A bug was uncovered while making the tests more robust; namely, that differentiating multiple probability outputs was returning the incorrect results. This bug was due to the usage of `np.dot(coeffs, results)` when performing the parameter-shift rule; `np.dot` does not simply perform the dot product along `axis=0` (as intended) when `results` is N-dimensional; in fact, its broadcasting rules [are quite complicated](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).
To fix this, `np.dot()` was replaced with either:
- an explicit list …
=> Makes QNode integration tests more robust and fixes uncovered bugs

.github/CHANGELOG.md, pennylane/tape/operation.py, tests/tape/test_tape_measure.py
**Context:**
The [Noisy Optimization with Cirq](https://pennylane.ai/qml/demos/tutorial_noisy_circuit_optimization.html) tutorial currently uses the following pattern:
```python
obs = [qml.PauliX(0) @ qml.PauliZ(1), qml.PauliZ(0) @ qml.PauliY(1)]
def circuit():
ansatz()
return qml.expval(obs[0])
```
However, with the completion of the queuing refactor last year, this pattern no longer works. Under the queuing refactor, the following is expected to take place:
* The individual observables queue themselves.
* The tensor product 'annotates' the queue, marking itself as the owner of its constituent observables.
* Finally, the `expval` function annotates the tensor product as an expectation value.
However, because the tensor products and observables are defined _outside_ the …
=> Fixes bug in queuing observables of tensors

pennylane/grouping/utils.py, tests/grouping/test_grouping_utils.py
**Context:**
* The function `qchem._qubit_operator_to_terms` when converting from OpenFermion hamiltonians to PennyLane Hamiltonians, *single term observables are always converted to Tensors*. E.g., `0.6543 [Z0]` will be `Tensor(PauliZ(0))`, and _not_ a plain `PauliZ(0)` observable.
* The `are_identical_pauli_words` function in the grouping module determines equality by first comparing object type, and _then_ object value. As a result, `are_identical_pauli_words(qml.PauliZ(0), Tensor(qml.PauliZ(0))` returns False.
* The `are_identical_pauli_words` function will now attempt to 'prune' all tensors before comparison, ensuring that `are_identical_pauli_words(qml.PauliZ(0), Tensor(qml.PauliZ(0))` returns True.
**Benefits:**
* The function `group_observables` now …
=> Bug fix in are_identical_pauli_words function to ensure observables are always pruned

pennylane/tape/qnode.py, tests/tape/test_tape_measure.py
**Context:**
With https://github.com/PennyLaneAI/pennylane/pull/1008 devices can be swapped under the hood to get the best differentiation method. This means that certain internal device data may be lost during the QNode call.
Updates the `_pre_rotated_state` and `_state` private attributes of the original device with the device that was actually used during execution.
*Note*: the way of how the state prior to rotations in being stored might not be completely unified between devices and is not a part of the shared device methods (not a member of `QubitDevice`). Therefore we are attempting to set the affected attributes, but if they do not exist then no change is done.
**Benefits:**
States are updated even if a different device is used under the hood. …
=> Update the state original tape device

pennylane/tape/interfaces/autograd.py
**Context:**
The vjp function does not return the expected values.
Without tape mode:
```pycon
>>> vjp = make_vjp(fun, x)
>>> vjp(np.array([1, 0, 0, 0]))
array([-0.654, 0.54])
```
The output of the VJP function should be of size 2, matching the input parameter size.
However, in tape mode, this is happening:
```pycon
>>> vjp = make_vjp(fun, x)
>>> vjp(np.array([1, 0, 0, 0]))
-0.654
```
**Benefits:**
=> Fix vjp to work with nested params

.github/CHANGELOG.md, pennylane/vqe/vqe.py
**Context:**
As mentioned in the related issue, a deprecation warning was being displayed while running the test suite. A minor change to the import statement fixed the issue.
Modified the `collections` import statement in the `vqe/vqe.py` file to import `Sequence` from `collections.abc` instead.
**Benefits:**
No more deprecation warning for importing `Sequence` from `collections` instead of `collections.abc` in `vqe/vqe.py`.
Issue #1043
=> Importing collections in vqe/vqe.py fixed

pennylane/optimize/gradient_descent.py, pennylane/optimize/momentum.py, pennylane/optimize/nesterov_momentum.py, pennylane/optimize/qng.py, pennylane/optimize/rotoselect.py, pennylane/optimize/rotosolve.py
**Context:**
* Several of the optimizer docstrings had rendering bugs and outdated terminology
**Description of the Change:** 
* Removes rendering bugs in the `Returns:` statement by removing indentation in continuation lines. While the `Args:` section requires continuation lines be indented since there might be multiple arguments, there is only ever a _single_ return, and so the return is never indented.
* In #959, most of the optimizers were updated to remove restrictions on cost function signatures. As a result, the `x` argument was changed to `*args` to be more general. Some stray `x` mentions in the docstrings were removed.
**Benefits:** Docstrings render correctly.
I noticed while working on this that the `QNGOptimizer` is the one optimizer that continues to …
=> Fixes bugs in optimizer docstrings

pennylane/tape/qnode.py, tests/tape/tapes/test_qnode.py
**Context:**
The original QNode could be passed a `mutable` argument, to avoid re-constructing the CircuitGraph with every call. By default this was True, but advanced users could set this to False if (a) they knew that the QNode quantum structure was independent of the QNode input, and (b) they needed to reduce overhead when calling the QNode a large number of times.
However, this keyword argument was not ported to the new QNode. Since the new QNode signature has `**kwargs`, the QNode would accept the `mutable` argument, but would not act on it, which is likely confusing to users.
This PR returns the `mutable` keyword to the new QNode, for full backcompatibility.
It is a very easy change (a single if statement), and the majority of this PR is just two new …
=> Add mutable argument support

pennylane/templates/layers/cv_neural_net.py
**Context:**
An update to a new numpy version has uncovered that we need to update a line in the `CVNeuralNet` template to use the new math library. 
Previously we called the broadcast function as
```python
broadcast(unitary=Squeezing, pattern="single", wires=wires, parameters=list(zip(r, phi_r)))
```
while we should have concatenated the tensors via
```python
r_and_phi_r = [qml.math.expand_dims(r[l], axis=1), qml.math.expand_dims(phi_r[l], axis=1)]
r_and_phi_r = qml.math.concatenate(r_and_phi_r, axis=1)
broadcast(unitary=Squeezing, pattern="single", wires=wires, parameters=r_and_phi_r)
```
I also moved the code to the highest-level template function to avoid one unnecessary function call.
**Benefits:** Tests should pass now.
In the process I realised we are …
=> Fix for #1056

pennylane/tape/tapes/cv_param_shift.py
**Context:** The second order CV parameter shift rule was giving incorrect gradients. We did not notice this until we were updating the [hybrid demo](https://pennylane.ai/qml/demos/tutorial_plugins_hybrid.html), since PennyLane does not provide a non-Gaussian simulator.
**Description of the Change:** Changes the index used to query the gradient method
**Benefits:** Second order parameter-shift now works
=> Fix bug in CV second order parameter-shift formula, where the incorrect parameter is being differentiated

tests/conftest.py, tests/qnn/test_cost.py
I noticed some tests were failing locally for me (without `jax` installed). I should install `jax`, but in case anyone else hasn't got it installed, this PR will make sure their tests don't fail.
=> Add fixture to skip test if jax is not present

.github/CHANGELOG.md, .github/workflows/tests.yml, pennylane/tape/qnode.py
**Context:** The maximum number of expansions allowed by a QNode is currently set to 2.
* The QNode has a new keyword argument, `max_expansion`, that determines the maximum number of times the internal circuit should be expanded when executed on a device. This allows it to be easily user accessible.
* The default number of max expansions has been increased to 10
**Benefits:** Devices that require multiple operation decompositions are now supported
=> Make QNode max expansion accessible as a keyword argument

.github/CHANGELOG.md, pennylane/_grad.py, pennylane/optimize/gradient_descent.py, pennylane/optimize/nesterov_momentum.py, tests/devices/test_default_qubit_autograd.py, tests/interfaces/test_autograd.py, tests/math/test_autograd_box.py, tests/math/test_functions.py, tests/tape/interfaces/test_qnode_autograd.py, tests/test_classical_gradients.py
**Context:**
I realised yesterday that `autograd.grad` behaves differently depending if the `argnum` argument is a sequence or an integer:
```python
>>> import autograd
>>> from autograd import numpy as np
>>> autograd.grad(np.sin, argnum=0)(0.6)
0.8253356149096783
>>> autograd.grad(np.sin, argnum=[0])(0.6)
(array(0.82533561),)
```
We never take this into account in PennyLane, which can lead to gradients often being returned as tuple of size 1.
* If the inferred `argnum` argument is a sequence of length 1, only the contained integer is passed to `autograd.grad`.
**Benefits:**
* The return of `qml.grad` should now _always_ match the return type of the function being differentiated.
* A lot of superfluous `[0]` could be removed from the tests (e.g., …
=> Fix qml.grad so that the returned gradient always matches the cost function return type if only a single argument is differentiated

.github/CHANGELOG.md, pennylane/devices/default_qubit_autograd.py, pennylane/devices/default_qubit_jax.py, pennylane/devices/default_qubit_tf.py, tests/devices/test_default_qubit_autograd.py, tests/devices/test_default_qubit_jax.py, tests/devices/test_default_qubit_tf.py
**Context:**
* A hangover from the old device API, where operations would be serialized to strings before sending them to the device, is that  inverting a gate mutates the operation name; the operation name becomes `OriginalName.inv`.
* `default.qubit.autograd`, `default.qubit.tf`, and `default.qubit.jax`, when using backpropagation as the differentiation method, need to ensure that all mathematical operations use autograd/TF respectively.
These two devices were not taking into account operation names that might have been appended with `'.inv'`, and thus inverted parametric operations could not be differentiated in backprop mode.
This was missed in previous releases for a couple of reasons:
* The shared integration tests were testing *evaluation* of inverse operations, but not gradients. …
=>  Fixes a bug where inverse operations could not be differentiated using backprop

.github/CHANGELOG.md, pennylane/_grad.py, pennylane/optimize/gradient_descent.py, pennylane/optimize/nesterov_momentum.py, tests/devices/test_default_qubit_autograd.py, tests/interfaces/test_autograd.py, tests/math/test_autograd_box.py, tests/math/test_functions.py, tests/tape/interfaces/test_qnode_autograd.py, tests/test_classical_gradients.py
**Context:** PR #1067 introduced an improvement to `qml.grad`, which removed the need to index into scalar gradients. However, it was determined that we did not want the behaviour of 0.15.0-dev to diverge from 0.14.0 until further in the release cycle.
**Description of the Change:** Reverts the change of #1067
**Benefits:** The same code for extracting the gradient of scalar functions will work on both 0.15.0-dev and 0.14.0
=> Revert recent improvement to qml.grad until closer to the next release

.github/CHANGELOG.md, pennylane/vqe/vqe.py, tests/test_vqe.py
**Context:**
1. The methods for the `Hamiltonian` class responsible for performing arithmetic operations added in https://github.com/PennyLaneAI/pennylane/pull/765 implicitly assume that the input arguments `coeffs` and `ops` are `list` typed. This is so because some `list` specific methods such as `extend`, `copy` are being called, producing errors when `coeffs` or `ops` are other iterables than lists.
2. The `Hamiltonian.simplify` method may result in an empty `coeffs` and `ops` list when subtracting a `Hamiltonian` from itself.
1. Converts the `coeffs` and `ops` arguments of `Hamiltonian` to `list` internally
2. Changes `ExpvalCost` to always return `np.array(0)` in `__call__` when specifying a zero Hamiltonian (either all entries of `coeffs` are 0 or …
=> Update Hamiltonian data storing and result of ExpvalCost for trivial Hamiltonians

.github/CHANGELOG.md, pennylane/_version.py, pennylane/devices/default_qubit_autograd.py, pennylane/devices/default_qubit_jax.py, pennylane/devices/default_qubit_tf.py, pennylane/tape/qnode.py, pennylane/vqe/vqe.py, tests/conftest.py, tests/devices/test_default_qubit_autograd.py, tests/devices/test_default_qubit_jax.py, tests/devices/test_default_qubit_tf.py, tests/qnn/test_cost.py, tests/test_vqe.py
* Merges the bugfix PRs in the [v0.14.1 milestone](https://github.com/PennyLaneAI/pennylane/milestone/7?closed=1) into a holding branch for the v0.14.1 release.
* Bumps the version number
* Updates the changelog
=> V0.14.1 bump

.github/CHANGELOG.md, doc/introduction/operations.rst, pennylane/devices/default_mixed.py, pennylane/devices/default_qubit.py, pennylane/devices/tests/test_gates.py, pennylane/ops/qubit.py, tests/ops/test_qubit_ops.py, tests/test_operation.py
**Context:**
Adds a new gate, `ControlledQubitUnitary`, which allows users to specify the matrix of a unitary, the control wire(s) and the target wire(s).
This gate has been added as an operation in `pennylane/ops/qubit.py`. It inherits from `QubitUnitary` and just performs some tweaks in the `__init__`.
The underlying matrix could get quite large if the user specifies a lot of control wires. However this seems anyway expected if we are working in the matrix representation.
=> Add controlled unitary gate

.github/CHANGELOG.md, pennylane/_qubit_device.py
**Context:**
* In https://github.com/aws/amazon-braket-sdk-python/pull/203, it was noted that the current implementation for converting between binary samples and the equivalent base-10 representation does not work for devices with more than 32 qubits.
* Modifies `QubitDevice`, replacing the current conversion logic with one that works for > 32 qubits.
**Benefits:**
* Samples can now be processed if the devices has more than 32 qubits
* The new logic is easier to read and understand than `np.ravel_multi_index`
* The new logic is ever so slightly faster:
There are two other places where `np.ravel_multi_index` is used:
- `default.qubit`, when applying a statevector to a subset of wires
- `default.mixed`, same as above.
It might be worth …
=> Micro-optimize basis state conversion

.github/CHANGELOG.md, doc/code/qml_templates.rst
**Context:** Typo in documentation
**Description of the Change:** Fixed the offending misspelling of Preparation
**Benefits:** Correctness
=> Correct Typo in qml_templates.rst

.github/CHANGELOG.md, pennylane/vqe/vqe.py, tests/test_vqe.py
**Context:** The `ExpvalCost` function assumes a cost function consisting of a sum of expectation values. However, since it accepts arbitrary keyword arguments, it is easy to pass `measure="var"` and assume it will now return variances of the Hamiltonian.
**Description of the Change:** Adds keyword validation, raising an error if a non-expectation statistic is requested.
**Benefits:** Clearer behaviour.
**Related GitHub Issues:** #1105
=> ExpvalCost raises an error if instantiated with variance measurements

.github/CHANGELOG.md, pennylane/qnn/keras.py, pennylane/templates/embeddings/amplitude.py, tests/qnn/conftest.py, tests/qnn/test_keras.py
**Context:**
Until now, only `int` and flat tuples like `(5,)` were acceptable values by the `output_dim` parameter in `qnn.KerasLayer`. After the addition of the `density_matrix()` return type by a QNode in PR #878 the output from a QNode may not necessarily be flat. This PR adds the support for tuples to be passed as an acceptable value to the `output_dim` parameter.
Now values like `(5, 5)` as well as integers like `2` or flat tuples like `(5,)` can be passed to the `output_dim` parameter. It is also to be noted that if an `Iterable` is passed (e.g, a list like `[5, 5]`) instead, it will be converted to a tuple. Internally the value of `output_dim` will either be a tuple or an integer.
**Example:**
Here, `c` is a circuit that outputs a `density_matrix()` …
=> Added support for output_dim to be a tuple

.github/CHANGELOG.md, pennylane/tape/qnode.py, tests/tape/tapes/test_qnode.py
**Context:** During tape construction, the differentiation options of the tape are set _prior_ to any potential tape expansion. Since tape expansion is a tape-to-tape transformation that outputs a new tape, if a decomposition is required, the tape differentiation options are lost.
**Description of the Change:** Moves the setting of the differentiation options to _after_ potential tape expansion.
**Benefits:** Preserves differentiation options, even if a decomposition is performed.
**Possible Drawbacks:** We plan to move tape expansion to the device, as a result, the logic that causes this bug within the QNode will be removed. This is not a drawback, just something to keep in mind --- an expected future change would have also eliminated this bug!
**Related GitHub Issues:** Closes #1115
=> Fixes a bug where decompositions would reset the differentiation method of a QNode

pennylane/tape/interfaces/tf.py, pennylane/tape/tapes/jacobian_tape.py
```python
import tensorflow as tf
dev = qml.device('default.qubit', wires=1)
@qml.qnode(dev, interface='tf', diff_method="parameter-shift")
def circuit(p):
qml.RX(p[0], wires=0)
qml.RY(p[1], wires=0)
return qml.probs(wires=0)
p = tf.Variable([0.1, 0.2, 0.3], dtype=tf.float64)
with tf.GradientTape() as tape1:
with tf.GradientTape() as tape2:
res = circuit(p)
g = tape2.gradient(res, p)
hessian = tape1.jacobian(g, p)
print(hessian)
```
gives
```
tf.Tensor(
[[-0.47766824  0.47766824  0.        ]
[-0.47766824  0.47766824  0.        ]
[ 0.          0.          0.        ]], shape=(3, 3), dtype=float64)
```
=> Add support for computing the Hessian for vector-valued QNodes

.github/CHANGELOG.md, pennylane/tape/tapes/tape.py, tests/tape/tapes/test_tape.py
**Context:**
The `is_sampled` attribute of a quantum tape is required for generating samples on the device level. The behaviour for this attribute was modified in #1027 and #1040.
Due to a bug, this attribute is not being set currently, although its test case is passing. The reason is that the underlying device gets swapped inside the test case, ultimately leading to unexpected behaviour.
* Adds the required line for updating the `is_sampled` attribute
* Fixes the test case
**Benefits:**
Sampling works correctly.
N/A
N/A
=> Fix is_sampled and its test

.github/CHANGELOG.md, pennylane/ops/cv.py, tests/ops/test_cv_ops.py
**Context:**
Added adjoint definitions for some CV ops.
**Benefits:**
Users can now use `qml.adjoint` when using CVOperations.
None
None.
=> Added adjoints for some CV gates

.github/workflows/assign_bugs.yml
**Changes**
Change to only checking the title of issues when automatically tagging bugs. This will necessitate the title to include either `[BUG]` or `bug` to be automatically labelled with the `"bug"` label and assigned. On the other hand, it will more so trigger labelling in cases where explicitly intended.
**Checking this functionality**
Keyword only in body: https://github.com/antalszava/bugs-scan/issues/11
Keyword in title: https://github.com/antalszava/bugs-scan/issues/12
=> Modify rule for auto-labelling issues describing malfunctions

pennylane/qnn/keras.py, tests/qnn/test_keras.py
**Context:**
A minor bug was introduced in https://github.com/PennyLaneAI/pennylane/pull/1070. Currently, the following gives a shape of `<unknown>`:
```python
layer = KerasLayer(...)
inputs = tf.keras.Input(shape=(2,))
inputs_shape = inputs.shape
output_shape = layer.compute_output_shape(inputs_shape)
print(output_shape)
```
(Note that `inputs_shape = (None, 2)`).
The output shape should be `(None, 1)`.
This PR ensures that the output shape is as expected, i.e., `(None, 1)`. A supporting test is added.
=> Fix output shape of KerasLayer

pennylane/ops/qubit.py
Extends the docstring of ``ControlledQubitUnitary`` to document new instance attributes.
=> Extend `ControlledQubitUnitary` docstring

pennylane/devices/default_qubit.py
Currently, `self.wire_map` in `default.qubit` is an `OrderedDict` instead of just a `dict`, but the ordering of this object is not necessary.
As using an `OrderedDict` adds overhead and involves importing it from a special package, I have changed the object back to `dict`.
=> OrderedDict in `default.qubit` removal

.github/CHANGELOG.md, pennylane/ops/qubit.py
**Description of the Change:** Updates the four-term parameter-shift rule to use coefficients that minimize the variance as per https://arxiv.org/abs/2104.05695
**Benefits:** More optimal choice of coefficients
=> Update 4-term parameter shift coefficients

doc/requirements.txt, doc/xanadu_theme/header.html, doc/xanadu_theme/layout.html, doc/xanadu_theme/static/xanadu.css_t
* Adds the blog to the navbar
* [Docutils version 0.17](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-17-2021-04-03), released on April 3rd, contains a new HTML5 writer that uses HTML5 semantic tags (`<main>`, `<section>`, `<header>`, `<footer>`, `<aside>`, `<figure>`, and `<figcaption>`) rather than `<div>`. This breaks the CSS on the website.
This PR pins docutils to version 0.16.
=> Add blog to navbar

.github/CHANGELOG.md, pennylane/tape/tape.py, tests/interfaces/test_tape_torch.py
**Context:** Applying the Torch interface, twice, to an expanded tape, resulted in an error. This is because the `expand()` function was not retaining the `__bare__` attribute of the tape, which stores the original (pre-interface) class of the tape.
**Description of the Change:** The `expand()` method now retains the `__bare__` attribute. A test has also been added.
**Benefits:** Fixes the aforementioned bug.
**Possible Drawbacks:** Not a drawback per se, just a note: once we remove tape subclasses (alongside gradient methods becoming transforms), we can remove the `__bare__` attribute.
**Related GitHub Issues:** Closes #1210
=> Fixes bug where applying the Torch interface repeatedly after expansion caused an error

.github/CHANGELOG.md, pennylane/qnn/cost.py, pennylane/qnn/keras.py, pennylane/qnn/torch.py, tests/qnn/test_cost.py, tests/qnn/test_keras.py, tests/qnn/test_qnn_torch.py
This reverts commit 816885aaf5e0e723861142348b3b8479536c0d4b.
Deprecation is no longer needed because of the use of lazy importing in https://github.com/PennyLaneAI/pennylane/pull/1228
=> Revert "Add deprecation warning to qnn module (#1170)"

qchem/requirements.txt, qchem/setup.py
Addresses #1145 as the `pyscf==1.7.2` strict pinning is no longer required.
The [original issue was solved in PySCF](https://github.com/pyscf/pyscf/commit/88aa846aff5ed6696dce2028b1855360c810412f) (see change to the SciPy requirement) after we've done the [strict pinning](https://github.com/PennyLaneAI/pennylane/pull/926).
=> Allow pyscf>=1.7.2 for QChem

.github/CHANGELOG.md, doc/development/plugins.rst, tests/test_configuration.py
Some more places where `analytic` appeared:
1. In the building a plugin guide: `DeviceError: The analytic argument has been replaced by shots=None. Please use shots=None instead of analytic=True.`
2. One test file
There was another which made me wonder: `./pennylane/optimize/shot_adaptive.py:        if dev.analytic:` (`check_device` method). @josh146 would this be intended because `Device.analytic` is still valid?
=> Remove more `analytic` occurrences

.github/CHANGELOG.md, pennylane/qnode.py
**Context:** The QNode docs for `diff_method` did not match current functionality.
**Description of the Change:** Removed `None` from the allowed argument types for the `QNode` since this option is not supported. Also updated the docstring for `interface` so it matched the formatting of the `diff_method`.  
**Benefits:** Docs are up to date!
**Related GitHub Issues:** None
=> Update QNode docstring

.github/CHANGELOG.md, doc/code/qml_qaoa.rst
=> Finalize max-weight-cycle qaoa addition

.github/workflows/assign_bugs.yml
Two examples:
https://github.com/antalszava/bugs-scan/issues/20
https://github.com/antalszava/bugs-scan/issues/19
```python
parameters: '[ {"keywords": ["[BUG]", "bug"], "labels": ["bug :bug:"], "assignees": ["antalszava"]}, {"keywords": ["unitaryHACK", "unitaryhack"], "labels": ["unitaryhack"], "assignees": ["antalszava"]}]'
github-token: "${{ secrets.GITHUB_TOKEN }}"
```
=> Update the bug assignment action to label unitary hack issue

.github/CHANGELOG.md, pennylane/ops/qubit.py, tests/ops/test_qubit_ops.py
**Context:**
Added SWAP decomposition and wrote tests to it
added the the function 
``` 
@staticmethod
def decomposition(wires): 
```
to ` pennylane/ops/qubit.py `  and tests for it at ` tests/ops/test_qubit_ops.py `
similar to #1313 
resolves #1304
=> [unitaryHACK] Added SWAP gate decomposition and related tests

.github/CHANGELOG.md, pennylane/utils.py, tests/test_utils.py
**Context:**
Deprecated qml.inv(). 
Added warnings in the documentation and code
**Benefits:**
Want to shift users to qml.adjoint() as it is a more general function
Fixes #1195
=> [unitaryHACK] Deprecated qml.inv()

.github/CHANGELOG.md, pennylane/ops/qubit.py, tests/ops/test_qubit_ops.py, tests/transforms/test_control.py
**Context:**
Added Toffoli decomposition along with tests
The Toffoli decomposition is done by using Hadamard, CNOT, T and T.inv() gates according to the following circuit
Made changes in `pennylane/ops/qubit.py` and `tests/ops/test_qubit_ops.py`
*Note*: the tape expansion in some test files (`tests/ops/test_qubit_ops.py` and `tests/transforms/test_control.py`) were adjusted. This was required because the test cases assumed that Toffoli had no decomposition, yielded incorrect results and failed the tests.
**Benefits:**
The user can now see the decomposition of the Toffoli gate into simpler gates
Fixes #1305
=> [unitaryHACK] Toffoli Decomposition

pennylane/operation.py
The docstring for `Operation.get_parameter_shift` was incorrect, as it implied that the function would only return two floats.
This corrects it to specify what is actually getting returned.
=> Minor docstring fix

.github/CHANGELOG.md, pennylane/circuit_drawer/grid.py, tests/circuit_drawer/test_circuit_drawer.py
**Context**
QNodes with no operations raises an error when drawn.
This error boils down to the grid that the `CircuitDrawer` creates. There is a copying operation that is called on a `None` type object (due to having no operations).
**Changes**
Catches the case where the grid is `None` and no copying of the internal grid happens, instead, an empty grid is used.
**Ralated Issues**
#1326
=> Fix drawing a QNode with no operations

doc/conf.py
At the moment, `pyscf` is not listed in the `docs/requirements.txt` (nor in the `pennylane/requirements.txt`), but it is imported in the `docs/conf.py` file. This PR removes the import.
=> Remove pyscf requirement from docs

.github/CHANGELOG.md, pennylane/templates/layers/strongly_entangling.py
**Context:**
Fixing a bug in the documentation of StronglyEntanglingLayers, which causes some text to disappear
Added a space to exit math mode
=> Fixing a bug in the documentation of StronglyEntanglingLayers

.github/CHANGELOG.md, pennylane/_qubit_device.py
**Context:**
Currently, the ```QubitDevice.var``` compute the variance using ```dot(eigvals, prob)```.
Since the variance of a Projector observable simply depends on a single element of the probability vector, it would lead to much more efficient memory usage if the element is indexed directly without allocating memory for the ```eigvals``` array when a large number of wires is involved. 
Implement special handling on QubitDevice.var for Projector observable.
**Benefits:**
More efficient memory usage when a large number of wires is used. 
**Related GitHub PR:**
[PR#1356](https://github.com/PennyLaneAI/pennylane/pull/1356)
=> Implement special handling on QubitDevice.var for Projector observable to improve memory usage

.github/CHANGELOG.md, pennylane/qnode.py, tests/tape/test_qnode.py
**Context:**
In PR #1075 we introduced a way to temporarily change the shots per call of a qnode. Due to a simple bug, the resetting to original shots value did not work if it was `None`.
Fix bug, add test.
The test checks for analytic vs non-analytic behaviour by comparing the variance of a Hadamard circuit's expectation run 100 times, and has a vanishingly small probability of failing (I assume it is 2^100 or so :) - the probability of observing 100 ones or zeros in a coin toss)
=> Fix bug where shots does not reset to None when temporarily changed

pennylane/_grad.py
**Context**
The `qml.grad` function documentation mentions that the information carried in the `requires_grad` attribute might be overridden when specifying the `argnum` argument, i.e., differentiation can be performed even for parameters that have `requires_grad=False` if they are specified in `argnum`.
This seems to not be the case:
```python
import pennylane.tape
dev = qml.device('default.qubit', wires=2)
def circuit(par, y):
qml.QubitStateVector(par, wires=[0,1])
qml.RY(y, wires=0)
p = np.array([1,0,0,0])
b =  np.array([0.3], requires_grad=False)
qml.grad(circuit, argnum=1)(p,b)
```
```
~/xanadu/pennylane/pennylane/numpy/tensor.py in tensor_to_arraybox(x, *args)
285 …
```
=> Update `qml.grad` docs: `requires_grad=False` raises when in `argnum`

.github/CHANGELOG.md, pennylane/grouping/group_observables.py, tests/grouping/test_optimize_measurements.py, tests/test_vqe.py
**Context**
The `ExpvalCost` class uses the grouping module when the `optimize=True` argument is set. Using this option, the terms in the Hamiltonian (that are Pauli words) are grouped based on a relation selected (e.g., qubit-wise commutativity) and then their corresponding coefficients are also grouped accordingly.
That is, grouping involves first the actual grouping of Hamiltonian terms and then grouping the coefficients of the terms.
When there are multiple equivalent terms in the Hamiltonian, with the current logic, the coefficient of the first term that matches a Pauli word will be used when grouping the coefficients. This is so because the grouping module assumes that the terms in the Hamiltonian are unique.
Therefore, equal terms of the Hamiltonian might get the same coefficient …
=> Pop observables and coeffs that have been grouped already

.github/CHANGELOG.md, pennylane/_version.py, pennylane/beta/devices/default_tensor.py, pennylane/devices/default_gaussian.py, pennylane/devices/default_mixed.py, pennylane/devices/default_qubit.py, qchem/CHANGELOG.md, qchem/pennylane_qchem/_version.py
Increments the version number to `0.17.0-dev`, similar to how it was done in https://github.com/PennyLaneAI/pennylane/pull/1241/.
Note: authors of new features should add changelog entries to the `0.17.0-dev` section and any improvements or bug fixes for `v0.16.0` should be merged into the [release candidate branch](https://github.com/PennyLaneAI/pennylane/tree/v0.16.0-rc0).
Organizing the changelog for the `v0.16.0` release will be a separate addition that will also be merged into `master`.
=> Incrementing the version number to `0.17.0-dev`

.github/CHANGELOG.md, pennylane/_qubit_device.py, pennylane/qnode.py, pennylane/tape/reversible.py, tests/tape/test_qnode.py, tests/tape/test_reversible.py, tests/test_qubit_device_adjoint_jacobian.py
Fixes Issue #1092 
When a QNode is created with a device with finite shots and adjoint differentiation, the User receives a warning reminding that adjoint differentiation is always exact.
When the adjoint jacobian method is called on a device with finite shots, the User also receives a warning to the same effect.
I only warn instead of interrupting with an error, as finite shots doesn't actually break the code.
=> Warnings for adjoint diff with finite shots

pennylane/devices/tests/test_measurements.py
**Context:**
With the addition of the projector observables in https://github.com/PennyLaneAI/pennylane/pull/1356, tests for sampling were added to the device test suite. [This](https://github.com/PennyLaneAI/pennylane/blob/a458d9baf2cee166fce98a7fe02b216d4c5e1b32/pennylane/devices/tests/test_measurements.py#L806) test checks on line [853](https://github.com/PennyLaneAI/pennylane/blob/a458d9baf2cee166fce98a7fe02b216d4c5e1b32/pennylane/devices/tests/test_measurements.py#L853) that the output samples span the full set of expected results, i.e., `{-1, 0, 1}`.
However, the test is not likely to pass on all devices, even for devices that are working as expected:
- The probability of sampling `-1` is `0.0001583`. With the `20000` shots used by the device, we only expect a few counts of `-1`.
- …
=> Fix sampling test for projector observable

.github/CHANGELOG.md, pennylane/transforms/qfunc_transforms.py, tests/transforms/test_qfunc_transform.py
**Context:** After applying a quantum function transform and constructing a QNode, the resultant QNode would return a 1-d array of measurement results even when there was only a single measurement.
**Description of the Change:** The qfunc transform decorator now checks the length of the list of measurements, and returns a list of results only when there are multiple measurements.
**Benefits:** Transformed QNodes that return a 0-d tensor now still return a 0-d tensor.
**Related GitHub Issues:** None
=> Fix return of single measurement in qfunc transform.

.github/CHANGELOG.md, pennylane/interfaces/torch.py
**Context:** A user has [reported an error](https://discuss.pennylane.ai/t/transfer-learning-error/1134/3) through the quantum transfer learning demo; when running on the GPU, the line
```
vjp = dy.view(1, -1) @ ctx.jacobian.apply(ctx, *ctx.saved_tensors)
```
in `torch.py` yields:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument mat2 in method wrapper_mm)
```
The reason for the error was discovered to be that the result of `ctx.jacobian.apply()`was on the CPU, even when the tensors it acted on were on the GPU.
**Description of the Change:** Updated the `backward` method in the torch interface to split the above operation into two parts, and check the device of the results. If at least one …
=> Fix backward pass on GPU in PyTorch interface

.github/CHANGELOG.md, pennylane/__init__.py, pennylane/measure.py, pennylane/operation.py, pennylane/queuing.py, pennylane/vqe/vqe.py, tests/collections/test_collections.py, tests/test_queuing.py, tests/test_vqe.py
**Context:**
Currently, there is no consistent, user-facing approach for applying (already instantiated) operators to a queuing context. Instead, there is a combination of different approaches:
- `op.queue()`: the most common approach. Almost all operators provide their own queuing logic currently, bar `Tensor`, which inherits a basic implementation from the base class and leads to inconsistent behaviour.
- `qml.QueuingContext.append()`: appends the object _directly_ to the currently active queuing context.
- `context._append()` appends the object to a specific queuing context.
This situation is not ideal, since `op.queue()` is not consistent, not documented, and not user-facing.
- Adds `Tensor.queue()` to make the `Tensor` class consistent with other …
=> Add function to apply instantiated operations to queuing contexts

.github/CHANGELOG.md, pennylane/interfaces/autograd.py, pennylane/interfaces/tf.py, pennylane/interfaces/torch.py, tests/interfaces/test_qnode_autograd.py, tests/interfaces/test_qnode_tf.py, tests/interfaces/test_qnode_torch.py
**Context:** The existing parameter-shift Hessian implementation returns incorrect Hessians for cost functions that perform post-processing on a vector-valued QNode.
- The bug was fixed in all three main interfaces (autograd, PyTorch, TF), by making sure that the vector-Hessian product is divided by the norm squared of `dy`.
- Tests were added for all three interfaces to ensure that this bug is fixed.
**Benefits:** Fixes the aforementioned bug.
**Related GitHub Issues:** Fixes #1424
=> Fixes vector-Hessian product bug

.github/CHANGELOG.md, pennylane/devices/tests/test_gates.py, pennylane/tape/jacobian_tape.py
Changes the uses of `np.complex` and `np.object` as per the NumPy deprecations from version 1.20: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations.
=> Numpy deprecations

.github/CHANGELOG.md, pennylane/ops/cv.py
**Context:** As described in [this issue](https://github.com/PennyLaneAI/pennylane-sf/issues/73), the docstring for the `FockStateVector` operation suggests that multi-mode states can be constructed with one dimension per wire, but does not clarify this must be constructed as a tensor product of single-mode states.
**Description of the Change:** Adds single-mode and multi-mode usage examples that specify dimensions required to construct `FockStateVector`.
**Benefits:** Improved clarity of docs.
**Related GitHub Issues:** Issue #[73](https://github.com/PennyLaneAI/pennylane-sf/issues/73) over in PennyLane-SF.
=> Add example to FockStateVector docs.

.github/CHANGELOG.md, pennylane/devices/default_qubit_jax.py, tests/devices/test_default_qubit_jax.py
The default qubit jax device currently always uses `float32` precision.
This change makes the device check the status of `jax.config.config.read('jax_enable_x64')`, which is the variable set to `True` by jax users to enable `float64` precision (also see [the jax gotcha](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision)).
**Benefit**
When users consciously change the default of jax' precision, the PennyLane device should play along and now does.
**Possible drawbacks**
The behaviour changes when `jax.config.config.read('jax_enable_x64')=True` but into the direction of what users would presumably expect.
An alternative method would be to use this update as new default but provide an override `precision` kwarg to allow for explicitly setting the …
=> make default precision equal to jax.config's jax_enable_x64

.github/CHANGELOG.md, pennylane/math/__init__.py, pennylane/math/multi_dispatch.py, pennylane/math/single_dispatch.py, pennylane/math/utils.py, tests/math/test_functions.py
**Context:** Cleans up the behaviour of `qml.math`, and adds better support for (a) unwrapping lists of tensors to NumPy arrays, and (b) determining trainability.
- `qml.math.requires_grad` is updated to work properly for both Autograd and JAX parameters, on both the forward and backward passes.
- `qml.math.get_trainable_indices` is added, which allows a sequence of tensor-like objects to be passed, and the indices corresponding to trainable tensors being returned.
- `qml.math.unwrap` unwraps a sequence of tensor-like objects to NumPy arrays.
**Benefits:** Clean and well-tested, interface agnostic methods for determining tensor trainability and conversions to NumPy arrays.
**Possible Drawbacks:** For the Autograd interface, assuming that `requires_grad=True` …
=> Add support for unwrapping of parameters, and determining trainability

.github/CHANGELOG.md, doc/introduction/interfaces/numpy.rst
**Context:**
Updates a failing code example.
Use keyword argument to mark a non-differentiable wires argument.
Add a random seed to make example reproducable.
Updated example reads:
#1498
=> [BugFix] Error in documentation's numpy differentiation code example

.github/CHANGELOG.md, pennylane/tape/tape.py, tests/tape/test_tape.py, tests/test_operation.py, tests/test_vqe.py
**Context:**
Some observables that are composed of other observables may define methods that change the constituent parts. This leaves observables without measurements in the queue. The tape's `process_queue` method, called upon exiting the queueing context, then throws an error.
The only example (as far as I know) in the current code base is the `Tensor.prune()` function:
``` python
with qml.tape.QuantumTape() as tape:
a = qml.PauliX(wires=0)
b = qml.Identity(wires=2)
T = qml.operation.Tensor(a, b).prune()
qml.expval(T)
```
However, once the Hamiltonian class becomes an Observable, the same is caused by the `Hamiltonain.simplify()` method. 
Note: one could in principle not allow such methods to be called in a tape context, but checking this everywhere is error-prone for development, and …
=> Remove tape check for observable without owners in the queue

.github/CHANGELOG.md, pennylane/_version.py, qchem/CHANGELOG.md, qchem/pennylane_qchem/_version.py
**Summary**
* Increments the version number similarly to https://github.com/PennyLaneAI/pennylane/pull/1410.
* Note: the remaining core devices (e.g., `default.tensor`, `default.gaussian`) now also depend on the `_version.py` file, hence change is made only there.
* Incorporates the changelog entry from https://github.com/PennyLaneAI/pennylane/pull/1505 in the new section of the changelog.
=> Incrementing the version number to `0.18.0-dev`

qchem/CHANGELOG.md, qchem/pennylane_qchem/qchem/structure.py, qchem/tests/test_convert_observable.py
**Context:** Fix github issue #1265.  This PR ensures the type consistency of the qubit Hamiltonian terms constructed by the 'convert_observable' function from an OpenFermion QubitOperator with respect to the same observable built directly using PennyLane operations.
The fix was implemented in the ``_qubit_operator_to_terms`` function of the ``qchem/structure`` module. An extra unit test was added to ``test_convert_observable.py``
**Benefits:**
Properties of Hamiltonian consistently return same type.
None
https://github.com/PennyLaneAI/pennylane/issues/1265
=> Fix GitHub issue #1265

.github/CHANGELOG.md, doc/code/qml_transforms.rst, pennylane/gradients/__init__.py, pennylane/gradients/vjp.py, pennylane/math/utils.py, tests/gradients/test_vjp.py
**Context:** Currently, PennyLane provides a `tape.jacobian()` method, which returns the Jacobian of a quantum circuit. It is then up to the interfaces to take this result, cast it to the correct tensor dtype, and construct the VJP. At the moment, this process is not ideal:
- The Jacobian is always computed prior to the vjp. This sometimes results in redundant quantum evals, especially if `dy = 0`.
- The VJP logic is duplicated across each interface, increasing maintenance burden, and leading to bugs not always being fixed in all places.
- There are no unit-tests for the VJP logic; instead, it is only tested via larger integration tests.
- Finally, the VJP logic is not differentiable, blocking higher order derivatives from being computed.
- Adds …
=> Adds a differentiable VJP transform

.github/CHANGELOG.md, pennylane/transforms/adjoint.py, pennylane/transforms/control.py, tests/transforms/test_adjoint.py, tests/transforms/test_control.py
**Context:**
The logic for the `qml.adjoint` top-level function was created by assuming that a queuing context (e.g., a QNode, tape, etc.) is active. The logic includes stopping the recoding of that queuing context such that the operations passed to `qml.adjoint` can be recorded by a temporary tape. This temporary tape is then used for creating the adjoint of the operation/list of operations.
When we have no active queuing context recording, the stopping logic raises an error (see #1457).
* Changes the logic of `qml.adjoint` to work when we're not within a queuing context. Further changes the `adjoint` method of the `ControlledOperation` class used for `qml.ctrl`.
* The change includes returning the list of operations adjointed by `qml.adjoint` just as …
=> Fix `qml.adjoint` with no queuing context

.github/CHANGELOG.md, pennylane/_qubit_device.py, pennylane/tape/tape.py, tests/tape/test_tape.py, tests/templates/test_state_preparations/test_mottonen_state_prep.py, tests/test_measure.py, tests/test_qubit_device.py
Identical to https://github.com/PennyLaneAI/pennylane/pull/1522, just targetting the release candidate branch.
One difference is the small update in the `Makefile` that was already in rc. Also, https://github.com/PennyLaneAI/pennylane/pull/1505 updated the tape tests, hence the line numbers are different in `master` and in the rc branch for that file.
=> V0.17.0 deprecations (targetting rc branch)

.github/CHANGELOG.md
**Context:** The changelog entry for PR #1388 needed to be updated post-merge, due to the merge crossing a release.
**Description of the Change:** Moves the changelog entry.
**Benefits:** New changelog entry accurately reflects placement of the new feature.
=> Update changelog entry for #1388

.coveragerc
Apparently, `.coveragerc` is an old file in PennyLane that excludes statements from codecoverage reports. However the CI ignores this file, and it is possible that some issues with claims that `NotImplementedErrors` or `__str__()` and `__repr__()` code pieces being untested stem from this file.
=> Reduce cases ignored by coveragerc 

.coveragerc
Note: the changelog has not been updated since this is CI related.
=> Remove `pass` from .coveragerc

.github/CHANGELOG.md, pennylane/tape/tape.py, tests/circuit_graph/test_qasm.py
The `tape.to_openqasm()` method now has a `measure_all` argument that specifies whether the serialized OpenQASM script includes computational basis measurements on all of the qubits or just those specified by the tape.
```python
from scipy.stats import ortho_group
with qml.tape.QuantumTape() as tape:
qml.RX(0.2, wires=0)
qml.RY(0.6, wires=1)
qml.expval(qml.PauliZ(0))
```
With `measure_all=True` (current, and default in this PR):
```pycon
>>> print(tape.to_openqasm(measure_all=True))
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c[2];
rx(0.2) q[0];
ry(0.6) q[1];
cx q[0],q[1];
measure q[0] -> c[0];
measure q[1] -> c[1];
```
New option:
```pycon
>>> print(tape.to_openqasm(measure_all=False))
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2]; …
```
=> Update tape's to_openqasm method

.github/CHANGELOG.md, doc/introduction/operations.rst
Removed the Shared operations section at the bottom and placed the identity observable under the sections Qubit observables and CV observables. Please check the [rendered page](https://pennylane--1576.org.readthedocs.build/en/1576/introduction/operations.html#qubit-observables).
#1567
=> Changed the location of the identity observable in the documentation

.github/CHANGELOG.md, doc/introduction/operations.rst
**Description of the Change:** The documentation in [pennylane/doc/introduction/operations.rst](https://github.com/PennyLaneAI/pennylane/blob/master/doc/introduction/operations.rst) has been updated to mirror the code in [pennylane/ops/qubit](https://github.com/PennyLaneAI/pennylane/tree/master/pennylane/ops/qubit). Specifically, `Qubit Gates` has been divided into categories that already exist and other new categories.
**Benefits:** The documentation is now more in line with the code and hence operations will be easier to find.
**Related GitHub Issues:** #1566
=> [Code Together] Categorizing the qubit gates in the documentation #1566

.github/CHANGELOG.md, tests/circuit_graph/test_circuit_graph_hash.py, tests/collections/test_qnode_collection.py, tests/conftest.py, tests/kernels/test_kernels.py, tests/tape/test_qnode.py
Fixes #1593 
Currently, the `tests` folder does not pass cleanly if only pennylane and required dependencies are installed, as dask and cvxpy are not required dependencies.  This PR skips tests that require one of these modules, but the module is not installed. 
I am still investigating the device suite tests, but those will be a separate PR.
=> relevant tests skip if cvxpy or dask is not installed

.github/CHANGELOG.md, tests/circuit_drawer/test_circuit_drawer.py, tests/circuit_graph/test_qasm.py, tests/gradients/test_finite_difference.py, tests/gradients/test_parameter_shift.py, tests/gradients/test_vjp.py, tests/interfaces/test_batch_tensorflow.py, tests/interfaces/test_tape_tf.py, tests/math/test_functions.py, tests/optimize/test_shot_adaptive.py, tests/pytest.ini, tests/qnn/test_keras.py, tests/templates/test_subroutines/test_double_excitation.py, tests/templates/test_subroutines/test_ucssd.py, tests/test_about.py, tests/test_vqe.py, tests/transforms/test_qmc_transform.py
This PR marks the 35 or so slowest tests that took longer than 1.5 seconds on my computer as "slow".
You can locally run all not slow tests via the command:
```
pytest -m "not slow" files_to_check
```
This will hopefully make the local execution of the test suite easier.
I also added the `pytest.ini` file to register the `"slow"` mark.
In the future, slow tests that get added should be marked via `@pytest.mark.slow`.
=> Mark tests slower than 1.5 seconds

.github/CHANGELOG.md, pennylane/devices/default_qubit_jax.py, tests/devices/test_default_qubit_jax.py
Fully deprecate `qml.sample` when `shots=None`: raise an error for `default.qubit.jax` instead of a warning. This is a change that was more generally adapted for `QubitDevice` in https://github.com/PennyLaneAI/pennylane/pull/1522.
=> Raise an error for `qml.sample` and `shots=None` in `default.qubit.jax`

pennylane/qnode.py
**Context:**
I managed to accidentally add newlines via my code review suggestions in #1591.
Removes all the mistakenly added newlines in the docstring.
**Benefits:**
Things look like they should, and the docstring will render correctly.
None
None
=> Remove (mistakenly added) newlines in docstring

.github/CHANGELOG.md, pennylane/devices/default_qubit.py
**Context:**
At the moment the `tutorial_general_parshift.py` is failing due to using jax.jit with `QubitStateVector`. It is due to an internal check using `qml.math.norm`. Therefore we replace it by `numpy`. This should solved the mentioned [issue](https://app.clubhouse.io/xanaduai/story/8933/build-dev-qml-repo-fails-because-of-tutorial-general-parshift-py).
=> Fix bug when using Jax jit and `QubitStateVector`

.github/CHANGELOG.md, pennylane/_device.py, tests/devices/test_default_gaussian.py
Adds a `UserWarning` to inform users that specifinyg the list of shots is only supported for `QubitDevice` based devices. See [related comment here](https://github.com/PennyLaneAI/pennylane/pull/1103#issuecomment-784287830) and the original PR: https://github.com/PennyLaneAI/pennylane/pull/1103
=> Raise a `UserWarning` for a list of shots in `Device.execute`

pennylane/circuit_drawer/mpldrawer.py
Currently, import pennylane in an environment without matplotlib raises an import error, as the `MPLDrawer` class requires it.  This change only raises an import error if someone tries to initialize the class.
=> bugfix: raise mpl import error inside class initialization

.github/CHANGELOG.md, pennylane/_device.py, tests/test_device.py
Found when inspecting [PR 1659](https://github.com/PennyLaneAI/pennylane/pull/1659/files).
Previously, this code:
```
dev = qml.device('default.gaussian', wires=1, shots=[2,2])
def circuit():
return qml.sample(qml.X(0))
circuit(shots=2)
```
Raised the warning:
```
DeviceError: Shots must be a single non-negative integer or a sequence of non-negative integers.
```
This is because the original devices shots (2+2 = 4) was of type `np.int64` instead of type `int`.  
This makes it so device shots will be an int even when derived from a shot list.
=> bugfix for device shot list processing

pennylane/ops/qubit/hamiltonian.py
It fixes a small mistake in the documentation example for hamiltonian.
=> Fix example hamiltonian _ob_data

pennylane/qnode.py, tests/beta/test_default_tensor_tf.py, tests/devices/test_default_qubit_jax.py
**Context**
In the QNode, for cases when `diff_method!='backprop'`, we apply the interface that was specified by the user.
With the changes in https://github.com/PennyLaneAI/pennylane/pull/1568, at the point where this is being done, we might have `diff_method='best'` represent backpropagation when we have a backpropagation device at hand. Therefore, we might be applying the interface even when we'll be using backpropagation. This is unwanted behaviour as the interface should not be applied when using backpropagation, as we're leaning on the machine learning framework to perform the gradient computation (instead of providing a gradient with the interface).
**Changes**
Extends the criterion used for checking when to apply the interface to a QNode.
=> Diff option backprop check rc

tests/devices/test_default_qubit_jax.py
Due to a [breaking change in JAX v0.2.21](https://github.com/google/jax/releases/tag/jax-v0.2.21), some JAX NumPy functions expect array arguments. Such a function is `jnp.allclose`.
> Many more jax.numpy functions now require array-like inputs, and will error
if passed a list (#7747 #7802 #7907 ).
See #7737 for a discussion of the rationale behind this change.
This PR updates failing tests such that the arguments passed to `jnp.allclose` are JAX NumPy arrays.
=> Turn to passing JAX arrays to `jnp.allclose`

doc/releases/changelog-dev.md, pennylane/gradients/gradient_transform.py, pennylane/transforms/classical_jacobian.py, pennylane/transforms/metric_tensor.py, tests/gradients/test_gradient_transform.py, tests/transforms/test_metric_tensor.py
**Context:** I discovered while hacking that batch transforms would not correctly apply to QNodes containing templates. This is because templates may perform classical computation, which the transform needs to take into account. However, the classical Jacobian computation was not using the same decomposition as the quantum component, resulting in a failure to perform the matrix multiplication due to a shape mismatch.
**Description of the Change:** Modifies the `classical_jacobian` function to use the same circuit decomposition as the quantum component.
**Benefits:** Batch transforms now work with templates.
=> Fixes a bug where batch transforms wouldn't work with templates

doc/development/guide/installation.rst, qchem/README.rst, qchem/requirements.txt, qchem/setup.py
**Context:** PySCF 2.0 was [released on PyPI today](https://pypi.org/project/pyscf/#history), however it seemingly fails to install.
**Description of the Change:** Pins PySCF in QChem to version `>=1.7.2, <2.0` to ensure tests and documentation continue to work.
**Benefits:** PennyLane CI continues to pass.
**Possible Drawbacks:** Will need to investigate and see if it is possible to support PySCF 2.0. The [GitHub release notes](https://github.com/pyscf/pyscf/releases) do not provide many details regarding breaking changes.
=> Pin PySCF to version < 2.0

doc/releases/changelog-dev.md
Adds a note on the non-default arguments used by functions that are being deprecated in the `init` module. This should help users pick their arguments such that they can reproduce previous results obtained by using the `init` module.
* [`np.random.normal` docs](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html#numpy-random-normal)
* [`np.random.uniform` docs](https://numpy.org/doc/stable/reference/random/generated/numpy.random.uniform.html?highlight=uniform)
=> Add non-default args for the `init` module deprecation (changelog)

doc/releases/changelog-dev.md, pennylane/optimize/qng.py, tests/optimize/test_qng.py
**Context**
The `QNGOptimizer` raises deprecation warnings because (see [related demo](http://pennylane.ai-dev.s3-website-us-east-1.amazonaws.com/qml/demos/tutorial_quantum_natural_gradient.html#quantum-natural-gradient-optimization)):
* inputs have to explicitly specify requires_grad=True;
* the keyword argument diag_approx is deprecated.
**Changes**
* Switches to using PennyLane NumPy for the optimizer
* Switches how the optimizer uses `qml.metric_tensor`
* Adds a deprecation warning when `diag_approx` is specified with `QNGOptimizer`
=> Update `QNGOptimizer` to handle deprecations

doc/releases/changelog-dev.md, pennylane/tape/tape.py, tests/transforms/test_metric_tensor.py
**Context:**
The `tape` method `get_parameters` relies on `tape.trainable_params` (if `trainable_only=True`), which is a `set`.
This means that if for some reason the internal ordering of `trainable_params` is not preserved (which is not guaranteed in python, in contrast to Python 3.7+ `dict`s), `get_parameters` will return the parameters in an incorrect order. In particular, the `classical_jacobian` outputs a permutation if this happens.
Adding `sorted` to the indices retrieved from `tape.trainable_params` within `tape.get_parameters`
**Benefits:**
The order of the parameters is stable.
For large tapes this incurs an overhead, but as `trainable_params` typically is "sorted" already, this overhead is _very_ small:
```python
a, b, c = …
```
=> Sorted `tape.get_parameters`

doc/releases/changelog-dev.md, pennylane/math/multi_dispatch.py, tests/math/test_functions.py
**Context:** In Autograph mode (e.g., using `@tf.function`), cost functions are initially traced with 'placeholder' tensors that have no shape, value, or dimension. This was causing `qml.math.dot()` to fail, as this function contains `tensor.ndim` calls.
**Description of the Change:** Modifies the TensorFlow section of `qml.math.dot`, to instead use `len(shape(x))` rather than `x.ndim`. This will work in both eager and autograph mode.
**Benefits:** Cost functions that use `@tf.function`, and involve `qml.math.dot()`, will now work without error.
=> Fix bug to ensure qml.math.dot works in autograph mode

.github/workflows/tests.yml
**Context:** Keras 2.7 was just released, however it appears to be incompatible with TF 2.6. 
**Description of the Change:** Ensures that the CI installs TF 2.6 and Keras 2.6
**Benefits:** CI runs.
**Possible Drawbacks:** Users pip installing TensorFlow will also get the incompatible Keras version. This is something that will need to be fixed by TensorFlow.
**Related GitHub Issues:** https://github.com/tensorflow/tensorflow/issues/52922
=> Ensure that the correct version of keras is installed for TensorFlow CI

doc/releases/changelog-dev.md, pennylane/beta/devices/default_tensor.py, tests/beta/test_default_tensor.py
**Context:**
The `default.tensor` device has never been moved out of the beta folder, and uses a very old device API (that would have to be reassessed in the upcoming device class refactor) as well as old tests (that would have to be rewritten for the current operator class refactor). 
We therefore decided to deprecate the device rather than maintaining it.
Raises a deprecation warning if the device is loaded.
**Benefits:**
We have plans to use more powerful tensor simulators to build devices in future.
At the moment there is no alternative device we can guide users towards.
=> Add deprecation warning for default.tensor

pennylane/hf/hamiltonian.py, pennylane/hf/hartree_fock.py, pennylane/hf/integrals.py, pennylane/hf/matrices.py, pennylane/hf/molecule.py
A couple of docstrings in the new hf module have typos or outdated names.  This PR fixes them.
=> fix docstrings in hf module

qchem/CHANGELOG.md, qchem/pennylane_qchem/qchem/structure.py, qchem/tests/test_meanfield.py
**Context:**
The function ``qchem.meanfield`` runs the HF calculation, using either PySCF or Psi4, and outputs the path to the file containing the HF data. Currently, this functions creates a directory tree based on the used  QChem package and the chosen basis set. For example:
```python
>>> qml.qchem.meanfield(symbols, coords, name="h2")
./pyscf/sto-3g/h2
```
Creating this directory structure causes problems when PennyLane is run in a  multiprocessing environment as pointed out by @mlxd.
Modify ``menafield`` function to encode the package and the basis set information in the name of the file instead of creating the dir tree.
```python
>>> qml.qchem.meanfield(symbols, coords, name="h2")
./h2_pyscf_sto-3g
```
**Benefits:**
Suppress creation of the dir tree, …
=> Modify 'qchem.meanfield' function to avoid creating a directory tree

pennylane/_grad.py, pennylane/math/is_independent.py, tests/math/test_is_independent.py
Adjusts the deprecation from https://github.com/PennyLaneAI/pennylane/pull/1773 to consider `ArrayBox` objects and updates `math/is_independent.py` such that `qml.math.is_independent` doesn't emit any deprecation warnings when using `qml.grad`/`qml.jacobian`.
=> `qml.math.is_independent` no deprecation warnings with `qml.grad`/`qml.jacobian`

doc/xanadu_theme/layout.html
**Context:** After the changes introduced in #1650, the `:orphan:` directive was needed in the changelog files in order to stop Sphinx from raising warnings. Unfortunately, Sphinx will render these.
**Description of the Change:** Adds javascript to the Sphinx theme to hide the `:orphan:` directives in the rendered docs.
**Benefits:** As above.
=> Hide :orphan: from displaying in the release notes

doc/introduction/chemistry.rst, doc/introduction/circuits.rst, doc/introduction/interfaces/numpy.rst, doc/introduction/templates.rst
This PR updates a few things in the introduction section of the documentation like:
* explicitly marking numpy arrays as trainable
* using `qml.expval` instead of `ExpvalCost`
* substituting `"auxiliary"` for  `"ancilla"`
* Removal of section on QNode Collections (outdated way of doing things)
=> Documentation Updates

pennylane/_grad.py, pennylane/devices/default_qubit_autograd.py, pennylane/math/is_independent.py, pennylane/math/quantum.py, pennylane/tracker.py, pennylane/transforms/batch_params.py, pennylane/transforms/batch_transform.py, tests/interfaces/test_batch_autograd.py, tests/math/test_is_independent.py, tests/transforms/test_batch_params.py
Updates docstrings that use `qml.grad`/`qml.jacobian` in light of #1773.
The following files were already okay (or are being updated separately):
1. Containing  `qml.grad`:
* `interfaces/batch/__init__.py`
* `transforms/unitary_to_rot.py` (addressed in #1859)
* `transforms/qfunc_transforms.py`
* `transforms/metric_tensor.py`
* `transforms/get_unitary_matrix.py`
* `transforms/batch_transform.py`
* `gradients/__init__.py`
2. Containing  `qml.jacobian`:
* `math/is_independent.py`: https://github.com/PennyLaneAI/pennylane/pull/1862
* `interfaces/autograd.py`
* `interfaces/batch/__init__.py`
* `gradients` (multiple files)
Features explicitly using `qml.grad`/`qml.jacobian`:
* `transforms/classical_jacobian.py`: uses the argnum syntax internally and offers this option too
* …
=> Update deprecated use of `qml.grad`/`qml.jacobian` in docstrings

doc/releases/changelog-dev.md, pennylane/circuit_drawer/mpldrawer.py
The CI tests were failing when matplotlib updated to version 3.5.  
Now, the `arrow` in the measurement box was added twice to the axes.  I therefore use a different call signature.  `ax.arrow` creates the arrow *and* adds them to the axes.  Before, I created them and then manually added it to the axes.
=> Update matplotlib circuit drawing to work with matplotlib v3.5

doc/releases/changelog-dev.md, pennylane/vqe/vqe.py, tests/test_vqe.py
**Context:**
`ExpvalCost` returns wrong values when `optimize=True` because of the shape of results due to shots (e.g (8000,5)).
Change the function to take into account the shape of the results.
**Benefits:**
It now returns the correct values.
Closes https://github.com/PennyLaneAI/pennylane/issues/1480
=> `ExpvalCost` when `optimize=True` with shots batch

pennylane/ops/qubit/parametric_ops.py
**Context:**
In the docs the call to PauliRot required 3 arguments `qml.PauliRot(theta, pauli_word, wires)`, but when calling these arguments through keywords we run into an error. 
This works 
```
def circuit(theta):
qml.PauliRot(theta, 'Z', wires=0)
return qml.state()
```
But this didn't
```
def circuit(theta):
qml.PauliRot(theta=theta, pauli_word='Z', wires=0)
return qml.state()
```
Updated the `__init__` method to contain the same call signature as the documentation. 
Link to issue: [1901](https://github.com/PennyLaneAI/pennylane/issues/1901)
=> Fixed bug in PauliRot where keyword args (theta and Pauli_word) were not being registered

doc/releases/changelog-dev.md, pennylane/tape/tape.py, tests/interfaces/test_batch_autograd.py, tests/interfaces/test_batch_autograd_qnode.py, tests/interfaces/test_batch_jax.py, tests/interfaces/test_batch_jax_qnode.py, tests/interfaces/test_batch_tensorflow.py, tests/interfaces/test_batch_tensorflow_qnode.py, tests/interfaces/test_batch_torch.py, tests/interfaces/test_batch_torch_qnode.py, tests/interfaces/test_qnode_autograd.py, tests/interfaces/test_qnode_tf.py, tests/interfaces/test_qnode_torch.py, tests/interfaces/test_tape_autograd.py, tests/interfaces/test_tape_tf.py, tests/interfaces/test_tape_torch.py, tests/tape/test_jacobian_tape.py, tests/tape/test_tape.py, tests/tape/test_unwrap.py, tests/transforms/test_tape_expand.py
**Context:**
Recently, the `trainable_params` property of `QuantumTape`s, which is a `set`, caused bugs based on the fact that it is not guaranteed to maintain its ordering.
In particular for larger tapes these rare instances seem to occur, which likely is the reason why it was not caught before.
As an example, consider the "unordered" set `{3, 1}`. As integer hashes are the integers themselves, a "canonical" ordering for python is according to the hash table, so that
```pycon
>>> {3, 1}
{1, 3}
```
This makes constructing small tests that fail based on `trainable_params` being a set quite hard.
`QuantumTape.trainable_params` is made a `list` instead, with an intermediate conversion to `set` and subsequent sorting within the attribute setter function to …
=> Make `tape.trainable_params` a list

doc/development/guide/tests.rst, doc/releases/changelog-dev.md, tests/pytest.ini
This PR adds more information to the [Developer Guide's Testing docs](https://pennylane.readthedocs.io/en/latest/development/guide/tests.html).
It also modifies `pytest.ini` so the `tests/beta` folder will not be included when running `pytest tests`. The beta tests can still be explicitly selected and executed.
[sc-11309]
=> Testing documentation

doc/releases/changelog-dev.md, pennylane/templates/embeddings/angle.py
=> Add example to AngleEmbedding

doc/releases/changelog-dev.md, pennylane/circuit_drawer/representation_resolver.py, tests/transforms/test_draw.py
Bugfix for Issue #1916 
Due to the new QNode expansion settings, the qnode tape has unexpanded templates, which the current text circuit drawer was unable to handle.  This bugfix generalizes the treatment of matrix parameters.
This code was previously raising an error:
```python
dev = qml.device('default.qubit', wires = 1)
def circuit():
qml.AmplitudeEmbedding(np.array([0,1]), wires=0)
return qml.state()
print(qml.draw(circuit)())
```
But now gives:
```
0: ──AmplitudeEmbedding(M0)──┤ State 
M0 =
[0.+0.j 1.+0.j]
```
=> Bugfix: draw template with matrix parameter

doc/releases/changelog-dev.md, pennylane/templates/embeddings/displacement.py, pennylane/templates/embeddings/squeezing.py
add examples to Squeezing and Displacement Embeddings
**Benefits:**
better documentation
none
#1727 #1735
=> Add examples to Squeezing and Displacement Embeddings

doc/development/release_notes.md, doc/releases/changelog-0.19.0.md, doc/releases/changelog-0.19.1.md, pennylane/_version.py, pennylane/devices/default_qubit.py
**Context:**
There is a check in `default.qubit` to ensure that the input statevector is normalized for the `QubitStateVector` operation.
For certain tensors, in particular those that are abstract (have no numeric value at the time), this check would result in an error. For this reason, there is first a condition checking whether that the input tensor is abstract or not.
The issue seems to arise still, however, because it seems that the output of extracting the norm for an input tensor could still be abstract.
This issue arises with:
* JAX Jitting when using `jax==0.2.10` and  `jaxlib==0.1.64`
* Input tensors with a complex dtype
* Specifying the input statevector outside of the QNode (without making it an input parameter of the QNode). If the input statevector was an input parameter, …
=> Update the norm check for `QubitStateVector` in `default.qubit` (v0.19.1)

doc/introduction/operations.rst
**Context:**
The `ThermalRelaxationError` was not added to the documentation introduction for operations.
=> Add intro doc for thermal relaxation error

doc/releases/changelog-dev.md, pennylane/transforms/batch_transform.py, tests/transforms/test_batch_transform.py
**Context:** Currently, when executing a batch transform, the line
https://github.com/PennyLaneAI/pennylane/blob/7e69c099bfa19de40b5f74157e9ff7895ef97cb6/pennylane/transforms/batch_transform.py#L292
results in the `qnode.execute_kwargs["max_diff"]` key being unintentionally deleted. This can cause issues if attempting to extract higher derivatives after performing a batch transformation.
**Description of the Change:** Copies the execution dictionary, to avoid accidental mutation.
**Benefits:** The QNode execution keyword options are now unaffected by batch transforms.
=> Fixes a bug where batch transforms would mutate a QNodes execution options

doc/releases/changelog-0.19.1.md, pennylane/devices/default_qubit.py, pennylane/devices/default_qubit_torch.py, pennylane/interfaces/torch.py, pennylane/math/single_dispatch.py, pennylane/ops/qubit/observables.py, pennylane/ops/qubit/parametric_ops.py, pennylane/ops/qubit/qchem_ops.py, pennylane/tape/jacobian_tape.py, tests/devices/test_default_qubit_torch.py, tests/gpu/test_torch.py, tests/interfaces/test_batch_torch.py, tests/kernels/test_kernels.py, tests/math/test_functions.py, tests/pytest.ini
**Context:**
With recent changes in `default.qubit` (https://github.com/PennyLaneAI/pennylane/pull/1749), the backpropagation variants of the device no longer define their own ML framework-specific implementation of parametric operations.
This means, that the pipeline defined in `pennylane/ops/qubit/parametric_ops.py` is being used by all backpropagation devices.
Some matrix definitions include scalars/constants (e.g., 0 or 1) that don't have an explicit type definition. When using Torch with GPU, such objects will be put on the CPU resulting in an error.
Such an operation is `qml.RX`:
```python
import torch
dev = qml.device("default.qubit.torch", wires=1)
@qml.qnode(dev, interface='torch')
def circuit(x, y):
qml.RX(x, wires=0)
qml.RZ(y, wires=0)
return …
```
=>  Fix parametric ops GPU compatibility (`v0.19.1`)

doc/releases/changelog-dev.md, pennylane/templates/layers/basic_entangler.py, tests/templates/test_layers/test_basic_entangler.py, tests/transforms/test_batch_params.py
=> Added Batching to BasicEntangerLayers

doc/releases/changelog-dev.md, pennylane/transforms/__init__.py, pennylane/transforms/optimization/__init__.py, pennylane/transforms/optimization/merge_amplitude_embedding.py, tests/transforms/test_optimization/test_merge_amplitude_embedding.py
**Context:** In certain situations it may be convenient to be able to use more than one `AmplitudeEmbedding` in the same circuit. A first approximation has been made but it has been decided to use circuit transformations to merge these gates. [(#1890)](https://github.com/PennyLaneAI/pennylane/pull/1890)
**Description of the Change:** A `merge_amplitude_embedding` transformation has been created, which takes a quantum function and returns it transformed by joining all gates of this type together.
**Example:**
```python
from pennylane.transforms import merge_amplitude_embedding
@merge_amplitude_embedding
def qfunc():
qml.AmplitudeEmbedding([0,1,0,0], wires = [0,1])
qml.AmplitudeEmbedding([0,1], wires = 2)
return qml.expval(qml.PauliZ(wires = 0))
dev = …
```
=> Multi amplitude embedding with transform

requirements.txt
Importing PennyLane seems to result in an error with `autoray <v0.2.5`. This PR bumps the version number in the `requirements.txt` iterates on the version of `autoray` required.
Closes #1941.
=> Bump autoray requirement

tests/optimize/test_adagrad.py, tests/optimize/test_adam.py, tests/optimize/test_gradient_descent.py, tests/optimize/test_momentum.py, tests/optimize/test_nesterov_momentum.py, tests/optimize/test_optimize.py, tests/optimize/test_qng.py, tests/optimize/test_rmsprop.py, tests/optimize/test_rotoselect.py
_Reoping PR #1919 due to issues with codefactor identifying problems on unrelated files._
**Context:** Tests for many of the optimizers are mostly located in a single file, with many fixtures and global variables making it difficult to reproduce individual tests in a different environment. Additionally, in anticipation of Pennylane v0.20.0 new warnings were introduced to ensure that variational parameters are explicitly marked since the `requires_grad` will be set to `False` by default. These warnings need to be removed from the tests.
- Optimizer tests are split up by optimizer
- Tests are more self-contained to simplify copy-pasting test code
- Removal of unnecessary tests
- New unit tests to cover internal functions
- Remove warnings for …
=> Refactor optimizer tests

doc/releases/changelog-dev.md, pennylane/ops/qubit/matrix_ops.py, pennylane/transforms/metric_tensor.py, tests/transforms/test_metric_tensor.py
**Context:**
The generator  and coefficient stored in `op.generator` are not modified when an operation is inverted. Therefore,
using this information in the metric tensor led to the wrong result for inverted gates. This is now fixed and three tests were modified to include this szenario.
Note that this bug affects both, the new Hadamard test-based metric tensor introduced in #1725 and the block-diagonal original version.
The coefficient is inverted with a minus sign if the operation in question has the `inverse` flag set to `True`. The documentation clearly states now that this assumes the generator of the operations for which the metric tensor is computed to be Hermitian.
**Benefits:**
bug fix and better documentation as well as test coverage.
**Possible …
=> Fix metric tensor for circuits with inverted gates

doc/releases/changelog-0.20.0.md, doc/releases/changelog-dev.md, pennylane/_version.py, qchem/CHANGELOG.md, qchem/pennylane_qchem/_version.py
Updates PennyLane and PennyLane-QChem as we're entering a new development version (v0.20.0 coming up):
* Moves the v0.20.0 changelog into a separate file
* Updates the dev changelog file to have empty sections
* Increments the version number to v0.21.0-dev
*Note*: QChem is not being released with v0.20.0.
See the same PR for the [v0.20.0 bump](https://github.com/PennyLaneAI/pennylane/pull/1832).
=> Incrementing the version number to `0.21.0-dev`

doc/releases/changelog-dev.md, pennylane/templates/embeddings/amplitude.py
**Context:**
When the `features` argument to the amplitude embedding template is batched in the form of a 2d numpy array, each feature set is processed and cast to a complex array, after which it is assigned back to the input array. This causes the warning `ComplexWarning: Casting complex values to real discards the imaginary part` when the input array is not already complex, due to the (implicit) assignment cast. 
**Description of the Change:** Pre-allocate a complex array to store the processed features in.
**Benefits:** No warning is raised and complex values are used as well when the template argument is batched.
**Related GitHub Issues:** Closes #1986
=> AmplitudeEmbedding: Fix warning from implicit cast of complex to real

doc/releases/changelog-dev.md, pennylane/math/multi_dispatch.py, tests/math/test_functions.py
**Context:**
When dispatching to an interface for a sequence of tensors, the function `_multi_dispatch` in [multi_dispatch.py](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/math/multi_dispatch.py) mistakenly lumps the SciPy interface together with "other" interfaces (such as TensorFlow and Torch, i.e. non-NumPy and non-Autograd). This leads to a warning being raised when a SciPy sparse matrix is used together with NumPy/Autograd about prioritizing TensorFlow and Torch:
```
UserWarning: Contains tensors of types {'autograd', 'scipy'}; dispatch will prioritize TensorFlow and PyTorch over autograd. Consider replacing Autograd with vanilla NumPy.
```
`_multi_dispatch` treats arguments with a 'SciPy' interface (e.g. sparse matrix) the same as for …
=> Make multi_dispatch treat scipy same as numpy

pennylane/transforms/metric_tensor.py
This section in the upcoming [documentation](https://pennylane--2001.org.readthedocs.build/en/2001/code/api/pennylane.metric_tensor.html?highlight=metric_tensor#pennylane.metric_tensor) for the metric tensor has a small error in the example code:
> The returned metric tensor is also fully differentiable in all interfaces. For example, we can compute the gradient of the Frobenius norm of the metric tensor with respect to the QNode weights :
> ```py
> >>> norm_fn = lambda x: qml.math.linalg(mt_fn(x), ord="fro")
> >>> grad_fn = qml.grad(norm_fn)
> >>> grad_fn(weights)
> array([-0.0282246 ,  0.01340413,  0.        ,  0.        ])
> ```
> 
Running the example results in:
```py
TypeError: 'NumpyMimic' object is not callable
```
because the code attempts to call `qml.math.linalg` instead of …
=> Fix missing function call in metric tensor docs example

doc/releases/changelog-dev.md, pennylane/interfaces/batch/jax.py, tests/interfaces/test_batch_jax_qnode.py
Adds a validation step to using the JAX interface akin to the [previous version of the interface](https://github.com/PennyLaneAI/pennylane/blob/488312df98b796556dcbddae63c63ff88c81c998/pennylane/interfaces/jax.py#L84) before batch execution.
=> Tape validation for the JAX interface (batch execute)

doc/releases/changelog-dev.md, pennylane/transforms/decompositions/two_qubit_unitary.py, tests/transforms/test_unitary_to_rot.py
**Context:** Circuits with >3 two-qubit unitaries were yielding a `RecursionError` when put through the `unitary_to_rot` transform.
**Description of the Change:** Fixes the queuing in the `two_qubit_decomposition` method and adds a relevant unit test.
**Benefits:** Arbitrary number of two-qubit unitaries can now be decomposed.
**Possible Drawbacks:** None; although, I'm admittedly not sure why this fixed the problem.
**Related GitHub Issues:** #2014
=> Fix two-qubit decomp to consider arbitrary number of unitaries

doc/releases/changelog-dev.md, pennylane/_device.py, pennylane/operation.py
The `string_for_inverse` attribute was used in only place, and that place could easily just use `".inv"` directly instead.  Therefore the attribute is removed.
=> [OpRefractor] remove `string_for_inverse`

doc/releases/changelog-dev.md, pennylane/transforms/classical_jacobian.py, tests/transforms/test_classical_jacobian.py
**Context:**
This implements the fix proposed in [this comment](https://github.com/PennyLaneAI/pennylane/issues/2018#issuecomment-992598533) on issue 2018.
For `argnum=None` and `interface="torch"`, `argnum` is now determined based on the `requires_grad` property of the arguments passed to `classical_jacobian`. This is implemented via `qml.math.get_trainable_indices`. When `argnum` is passed by the user, it of course takes precedence over this default behaviour (like before).
**Benefits:**
Fixes #2018
n/a
#2018
=> Fix `classical_jacobian` with untrainable arguments when used with Torch

doc/releases/changelog-dev.md, pennylane/operation.py, tests/test_operation.py
**Context:**
We decided to move towards a system where an operators trainable parameters are stored as `op.parameters` and the non-trainable ones (like `control_wires`, `basis_state`, `features`) as a dictionary `op.hyperparameters`.
This PR introduces a dummy version to enable PRs to be build on this attribute, even though the details will be worked out moving forward.
Add a simple test and attribute.
=> [OpRefactor] add temporary hyperparameter attribute

requirements.txt
Updates the Dask version being used for security purposes.
=> Upgrade Dask to `2021.10`

doc/introduction/interfaces.rst, doc/releases/changelog-dev.md
The [page for interfaces](https://pennylane.readthedocs.io/en/stable/introduction/interfaces.html) doesn't seem to explicitly mention that support for every interface applies to using any device.
This PR adds a bit more context.
=> Extend the interfaces description page

doc/releases/changelog-dev.md, pennylane/fourier/utils.py, pennylane/operation.py, pennylane/ops/qubit/hamiltonian.py, pennylane/ops/qubit/observables.py, pennylane/ops/qubit/parametric_ops.py, pennylane/ops/qubit/qchem_ops.py, pennylane/tape/reversible.py, pennylane/transforms/metric_tensor.py, pennylane/utils.py, tests/fourier/test_fourier_utils.py, tests/ops/qubit/test_parametric_ops.py, tests/ops/qubit/test_qchem_ops.py, tests/test_operation.py, tests/transforms/test_metric_tensor.py, tests/transforms/test_tape_expand.py
**Context:**
The `Operation.generator` property has long been badly designed, and a blocker for extending PennyLane. In its current form, it returns a 2-tuple `(generator, coeff)`, where
- `generator` is an operation _class_ or NumPy array
- `coeff` is a scaling factor
An unfortunate side effect of `generator` being a class is that it does not allow us to scale beyond simple observables, and further, does not allow us to encode wires.
- The generator property has been updated to an instance method, `Operation.generator()`.
- It now returns an instantiated operation, representing the generator of the instantiated operator.
- Various operators have been updated to specify the generator as either an `Observable`, `Tensor`, `Hamiltonian`, `SparseHamiltonian`, or …
=> Update the `Operation.generator` property

doc/releases/changelog-dev.md, setup.py
Increases the version of PennyLane-Lightning required such that no errors would arise from using earlier versions that do not support the new batch execution pipeline in PennyLane.
=> v0.20.0 Lightning required

pennylane/templates/layers/cv_neural_net.py, pennylane/templates/subroutines/qpe.py, pennylane/transforms/control.py
**Context:**
This PR fixes the following codefactor issues that seem to be appearing for the first time [here](https://github.com/PennyLaneAI/pennylane/pull/1973/files).
1. Line 205 in pennylane/templates/layers/cv_neural_net.py is missing `do_queue` argument which leads to an `arguments-differ` issue.
2. Line 149 in pennylane/templates/subroutines/qpe.py is missing `do_queue` argument which leads to an `arguments-differ` issue.
3. Line 130 in pennylane/transforms/control.py introduces `ops` which is not used anywhere and leads to an `unused-variable` issue. 
To fix issues 1 and 2, `pylint:disable=arguments-differ` is added to both files similar to what we have [here](https://github.com/PennyLaneAI/pennylane/blob/23b82a4d6b7c5a42d2a4a9e660ac7f61f2919e29/penny …
=> Fix codefactor issues

doc/releases/changelog-dev.md, pennylane/operation.py
This is a small change that should not affect users, but which makes the representation methods consistent with the `matrix` methods.
=> [OpRefactor] Rename wires as wire_order in heisenberg ops

pennylane/_qubit_device.py, pennylane/devices/default_mixed.py, pennylane/devices/default_qubit.py, pennylane/devices/default_qubit_torch.py, pennylane/math/quantum.py, pennylane/measure.py, pennylane/operation.py, pennylane/ops/identity.py, pennylane/ops/qubit/matrix_ops.py, pennylane/ops/qubit/non_parametric_ops.py, pennylane/ops/qubit/observables.py, pennylane/ops/qubit/parametric_ops.py, pennylane/transforms/metric_tensor.py, tests/devices/test_default_mixed.py, tests/devices/test_default_qubit.py, tests/devices/test_default_qubit_tf.py, tests/ops/qubit/test_non_parametric_ops.py, tests/ops/qubit/test_observables.py, tests/ops/qubit/test_parametric_ops.py, tests/ops/test_identity.py, tests/tape/test_tape.py, tests/test_measure.py, tests/test_operation.py, tests/test_qubit_device.py
**Context:**
Applies the new design to eigenvalues.
Renaming, make `eigvals` a proper method, add some docstrings and examples.
Didn't add tests. We should probably do this, but in interest of time I just rely on the old tests.
=> [OpRefactor] Update eigenvalue representations

doc/releases/changelog-dev.md, pennylane/devices/default_qubit.py, pennylane/devices/default_qubit_autograd.py, pennylane/devices/default_qubit_jax.py, pennylane/devices/default_qubit_tf.py, pennylane/devices/default_qubit_torch.py, tests/devices/test_default_qubit_autograd.py, tests/devices/test_default_qubit_jax.py, tests/devices/test_default_qubit_tf.py, tests/devices/test_default_qubit_torch.py
**Context:**
This PR implements the fix to #1125 proposed in [this comment](https://github.com/PennyLaneAI/pennylane/issues/1125#issuecomment-999206195)
The line 792
```python
prob = self.marginal_prob(self._abs(self._flatten(self._state)) ** 2, wires)
```
in `qml/devices/default_qubit.py` is replaced by
```python
flat_state = self._flatten(self._state)
real_state = self._real(flat_state)
imag_state = self._imag(flat_state)
prob = self.marginal_prob(real_state ** 2 + imag_state ** 2), wires)
```
avoiding the usage of `abs`, which does not have a well-defined derivative at 0.
**Benefits:**
Fixes #1125 in all interfaces.
Performance, see short discussion [here](https://github.com/PennyLaneAI/pennylane/issues/1125#issuecomment-999206195) …
=> Remove `abs` from `DefaultQubit`

doc/releases/changelog-dev.md, pennylane/tape/tape.py, tests/circuit_graph/test_qasm.py
Presumably due to a change in precision handling of a dependency, a qasm test started failing because of a different string representation of a 15th digit.
This PR adds a precision argument to the `to_openqasm` method, and uses it in the test. A test for the argument is also added.
=> Fix openqasm test

doc/introduction/interfaces.rst, doc/releases/changelog-dev.md, pennylane/_qubit_device.py, pennylane/qnode.py, tests/devices/test_default_qubit_torch.py, tests/ops/qubit/test_hamiltonian.py
Fixes #2077 and removes the comparison of the adjoint method to the reversible method in the doc string of `adjoint_jacobian` as it is not visible to users unless they use the old QNode.
Unrelated: Made the capability check for the adjoint diff method a tiny bit more readable.
Related issues:
#2077
=> Remove mentions of `"reversible"` method

doc/releases/changelog-dev.md, pennylane/ops/qubit/qchem_ops.py
**Context:** There is an error in the signs of the basis state transforms in the `DoubleExcitation` documentation; it does not match the actual transformation that is being performed.
**Description of the Change:** Fixes the signs in relevant places in the docs.
The existing example given is:
```python
dev = qml.device('default.qubit', wires=4)
def circuit(phi):
qml.PauliX(wires=0)
qml.PauliX(wires=1)
qml.DoubleExcitation(phi, wires=[0, 1, 2, 3])
return qml.state()
>>> circuit(0.1)
tensor([ 0.        +0.j,  0.        +0.j,  0.        +0.j,
-0.04997917+0.j,  0.        +0.j,  0.        +0.j,
0.        +0.j,  0.        +0.j,  0.        +0.j,
0.        +0.j,  0.        +0.j,  0.        +0.j,
0.99875026+0.j,  0.        +0.j,  0.        +0.j,
0.        +0.j], requires_grad=True) …
```
=> Fix sign errors in `qml.DoubleExcitation` documentation.

.github/ISSUE_TEMPLATE/bug_report.yml
The bug report template raises an error (see [here]()):
As the error message is saying, the eights (zero-based indexing) entry of the `body`, which is the very last entry in the `body`, requires the mandatory `key` called `label`. While the `options` of this entry do have a `label`, the entry itself does not.
This PR includes a dummy value for this `key`. (According to the documentation, an empty or whitespace-only string is not accepted for values of mandatory fields.)
=> Fix issue template for bug reports

pennylane/optimize/rotosolve.py
Fixes a no `self` use issue that Codefactor is raising.
=> Make `Rotosolve._validate inputs` static

pennylane/gradients/hessian_transform.py
Removes an unused `warnings` import that makes Codefactor fail.
=> Remove unused `warnings` import

doc/releases/changelog-dev.md, pennylane/optimize/rotosolve.py, tests/optimize/test_rotosolve.py
**Context:**
As discussed in #2100 , the warning that `RotosolveOptimizer` will only update arguments marked as trainable is made more visible in this PR. Additionally, a warning is raised if no trainable arguments are found.
Doc string improvement (enhance visibility of existing warning regarding training).
Introduce a warning for use cases in which the optimizer would not do anything.
**Benefits:**
UI improvement
N/A
#2100
=> Rotosolve warning no trainables

doc/releases/changelog-dev.md, pennylane/qnode.py, tests/devices/test_default_qubit_jax.py, tests/test_qnode.py
Fixes Issue #1481 on the new QNode, as previous fix #1588 only solved the problem on the old QNode.
Contrary to the last bugfix on this problem, this fix raises an error instead of a warning.
```
dev = qml.device('default.qubit.autograd', shots=10, wires=1)
@qml.qnode(dev, interface='autograd', diff_method='backprop')
def circ(x):
qml.RX(x, wires=0)
```
Now raises a `QuantumFunctionError`.
[sc-8003]
=> Raise error upon request of backpropagation on device with finite shots

doc/releases/changelog-dev.md, pennylane/gradients/param_shift_hessian.py, pennylane/gradients/vjp.py, pennylane/math/utils.py, tests/gradients/test_vjp.py
**Context:**
`qml.math.cast_like` attempts to copy the dtype of a tensor whereas `qml.math.convert_like` only uses the type of the tensors during conversion
The `qml.gradients` module uses `qml.math.convert_like`. There may, however, be cases where the dtype would need to be copied, otherwise unexpected behaviour arises.
**Benefits:**
#2105
=> Use `qml.math.cast` after `qml.math.convert_like` in `qml.gradients` to copy `dtype`

doc/introduction/interfaces.rst, doc/introduction/interfaces/numpy.rst, doc/releases/changelog-dev.md, pennylane/_grad.py, pennylane/qnn/keras.py, pennylane/qnn/torch.py, pennylane/qnode.py
**Context:** This PR updates various points in the documentation regarding which data types can be differentiated in autograd, and what the defaults for parameter trainability are.
**Benefits:**
=> Update the documentation with the latest changes in parameter differentiability

pennylane/interfaces/batch/__init__.py, tests/interfaces/test_batch_jax.py, tests/interfaces/test_batch_jax_qnode.py
Same https://github.com/PennyLaneAI/pennylane/pull/2136/, just targetting `master`.
=> Dont convert variables to numpy if on interface-specific device

doc/releases/changelog-dev.md, pennylane/qnode.py, tests/test_qnode.py
**Context:**
See linked issue https://github.com/PennyLaneAI/pennylane/issues/2170. The issue arises when swapping the underlying device in the QNode (e.g., when having `diff_method="backprop"`).
Instead of incrementing the number of executions, we set the number of executions using the number of executions from the device used.
**Benefits:**
`dev.num_executions` is recorded correctly.
N/A
Closes https://github.com/PennyLaneAI/pennylane/issues/2170
=> Fix `dev.num_executions` bug with QNode caching

doc/releases/changelog-dev.md, pennylane/gradients/finite_difference.py, pennylane/gradients/gradient_transform.py, pennylane/gradients/hessian_transform.py, pennylane/gradients/param_shift_hessian.py, pennylane/gradients/parameter_shift.py, pennylane/gradients/parameter_shift_cv.py, pennylane/transforms/metric_tensor.py, tests/gradients/test_finite_difference.py, tests/gradients/test_gradient_transform.py, tests/gradients/test_param_shift_hessian.py, tests/gradients/test_parameter_shift.py, tests/gradients/test_parameter_shift_cv.py, tests/transforms/test_metric_tensor.py
Similar to the previous changes in #2148 and #2139, we'd like to provide a warning or useful error message when a user attempts to compute metric tensor even though there are no trainable parameters, such as in the following example:
```py
dev = qml.device("default.qubit", wires=3)
def circuit(weights):
qml.RX(weights[0], wires=0)
qml.RY(weights[1], wires=0)
return qml.expval(qml.PauliZ(0) @ qml.PauliZ(1))
weights = [0.1, 0.2]
qml.metric_tensor(circuit)(weights)
```
Most or all gradient transforms actually throw an error at the moment when this is attempted, unless the `hybrid` parameter is set to False:
```
ValueError: need at least one array to stack
```
so this change will also resolve this bug.
With the proposed changes, a warning is raised and a default value returned …
=> Add warnings for the gradient transforms when there are no trainable parameters

doc/releases/changelog-dev.md, pennylane/grouping/__init__.py, pennylane/grouping/pauli.py, tests/grouping/test_pauli_group.py
**Context:**
As part of the QCut module, we need to efficiently measure over the full N-qubit Pauli group. Although there are `4^N` terms, we can measure only `3^N` groups.
Added the `partition_pauli_group` function to the `grouping` module.
The function returns Pauli words expressed as simple strings. This is sufficient for the QCut module's needs but some users may prefer the Pauli words as PL observables/tensors. Since the current implementation is sufficient for now, I propose to leave returning PL observables/tensors as a follow up addition.
Example:
```pycon
>>> qml.grouping.partition_pauli_group(3)
[['III', 'IIZ', 'IZI', 'IZZ', 'ZII', 'ZIZ', 'ZZI', 'ZZZ'],
['IIX', 'IZX', 'ZIX', 'ZZX'],
['IIY', 'IZY', 'ZIY', 'ZZY'],
['IXI', …
```
=> Partition the Pauli group into qubit-wise commuting terms

pennylane/__init__.py, pennylane/devices/default_qubit.py, pennylane/ops/mid_circuit_measure.py, pennylane/transforms/__init__.py, pennylane/transforms/defer_measurements.py, tests/ops/test_mid_circuit_measurements.py, tests/transforms/test_defer_measurements.py
Targets the branch used in https://github.com/PennyLaneAI/pennylane/pull/2134/ to showcase the diff.
Example
```python
@qml.defer_measurements
def teleportation_circuit(rads):
qml.RY(rads, wires=0)
qml.Hadamard(wires=1)
qml.CNOT(wires=[1, 2])
qml.Hadamard(wires=0)
m_0 = qml.mid_measure(0)
m_1 = qml.mid_measure(1)
qml.if_then(m_1, qml.RX)(math.pi, wires=2)
qml.if_then(m_0, qml.RZ)(math.pi, wires=2)
return qml.probs(wires=2)
```
=> [Prototype] Deferred measurement principle transform

doc/releases/changelog-dev.md, pennylane/_grad.py, tests/test_finite_diff.py
**Context:**
Adding a deprecation warning for `qml.finite_diff` which will be removed in the next release. Users will be directed to use `qml.gradients.finite_diff`. 
Running the following code yields the following warning: 
```
>>> def f(x, y):
...     return np.sin(y[0])*np.sin(y[1]) - x**-3
...
>>>
>>> (x, y) = (0.376, np.array([1.975, 0.33, -0.4]))
>>>
>>> gradient = qml.finite_diff(f, argnum=1)
UserWarning: The black-box finite_diff function will be deprecated, 
users can instead use qml.gradients.finite_diff to compute the gradient 
of tapes or qnodes. Otherwise a manually implementation is required.
>>>
>>> print(gradient(x, y))
[-0.12744129189670161 0.8698027233702277]
>>>
```
=> Deprecate `qml.finite_diff`

tests/math/test_is_abstract.py
**Context:** As of JAX 0.3.1, JAX will trace non-differentiated arguments. As a result, it is no longer possible to assume that non-differentiated arguments will not be abstract.
**Description of the Change:** Modify the test to add a note, and comment out an assertion that will no longer work with JAX 0.3.1
**Benefits:** Tests will pass with the latest JAX. No functionality in PL is dependent on this, so there is no 'breaking change' to report.
**Possible Drawbacks:** While this is not a 'breaking change', it is unfortunate. It means that the ability to inspect tensor values (e.g., during transforms or compilation) will not work with JAX even if it is a non-differentiated argument.
=> Modify JAX test to pass with JAX version 0.3.1

pennylane/gradients/gradient_transform.py, pennylane/operation.py, tests/test_operation.py
**Context:** As part of the recent operator refactor, the static method `Operator.decomposition` was renamed to `Operator.compute_decomposition`. The new `Operator.decomposition` is now an instance method.
**Description of the Change:** Adds a deprecation warning to alert developers to this change.
**Benefits:** As above.
**Related GitHub Issues:** Closes #2210
=> Raise a deprecation warning if `Operator.decomposition` is a staticmethod

pennylane/transforms/qcut.py, tests/transforms/test_qcut.py
**Context:**
Fragment tapes of cut circuit need to be expanded to multiple configurations in order to execute and recombine results. However, the observables of fragments tapes containing no `MeasureNode` were being lost. 
This PR fixes the logic so that measurements of such fragments persist across the following configurations 
**Benefits:**
Fixes broken pipeline for this specific case
Blocker for #2216
=> Fix expansion of fragments tapes containing no `MeasureNode`

pennylane/transforms/qcut.py, tests/transforms/test_qcut.py
**Context:**
In the circuit cutting workflow we have `MeasureNode` and `PrepareNode` operations to indicate where physical measurements and state preparations should occur.  These nodes are copied in the cutting workflow so as not to mutate the original circuit. This can later lead to problems with comparing node instances.
The operation classes of each have been update to provide an `id` attribute which an be used to compare 
**Benefits:**
Allows for comparison of node operations that isn't reliant on memory locations.
=> Update  `MeasureNode` and `PrepareNode`operation identifiers 

doc/releases/changelog-dev.md, pennylane/operation.py
**possible drawbacks**: I could not find any logic that relies on the expand function identifying Operations (as opposed to Observables) and hope this is safe. In any case, this _should_ not be logic that is used!
=> Move expand function from Operation to Operator

doc/releases/changelog-dev.md, pennylane/transforms/control.py, tests/transforms/test_control.py
**Context:** As per #2237, the `qml.ctrl` transform was not working with gradient transforms such as the parameter-shift rule. It does however work with backprop.
- Ensures that the tape parameters are up to date prior to expansion
- Sets `grad_method=None` to enforce decomposition if using the parameter-shift rule
- Adds tests
**Benefits:** Gradient transforms now work with `qml.ctrl`.
**Related GitHub Issues:** Fixes #2237
=> Fix bug to allow `qml.ctrl` to work with gradient transforms

doc/introduction/operations.rst, doc/releases/changelog-dev.md
**Context:**
The PennyLane documentation currently does not contain or link to information about the CV model of quantum computing, making it difficult for users unfamiliar with the model to use PennyLane's CV capabilities.
Link to the Strawberry Fields documentation which explains the difference between the CV and qubit model.
**Benefits:**
=> Add link to CV model page in StrawberryFields docs

doc/releases/changelog-dev.md, pennylane/transforms/draw.py, tests/transforms/test_draw_mpl.py
This PR adds the `expansion_strategy` keyword to `draw_mpl`.
=> add `expansion_strategy` keyword to `qml.draw_mpl`

pennylane/transforms/tape_expand.py, tests/transforms/test_tape_expand.py
**Context:**
Attempting to apply a custom decomposition inside a for loop would cause an error:
```python
for i in range(2):
custom_decomps={'MultiRZ': qml.MultiRZ.compute_decomposition}
dev = qml.device('lightning.qubit', wires=2, custom_decomps=custom_decomps)
@qml.qnode(dev, diff_method='adjoint')
def cost(theta):
qml.Hadamard(wires=0)
qml.Hadamard(wires=1)
qml.MultiRZ(theta, wires=[1, 0])
return qml.expval(qml.PauliX(1))
x = np.array(0.5, requires_grad=True)
cost(x)
```
```
File "/home/josh/xanadu/pennylane/pennylane/operation.py", line 1098, in expand
self.decomposition()
File "/home/josh/xanadu/pennylane/pennylane/operation.py", line 991, in decomposition
return self.compute_decomposition(
TypeError: decomposition() got an unexpected keyword …
```
=> Fix bug when using `for` loops with custom decompositions

doc/releases/changelog-dev.md, pennylane/templates/subroutines/grover.py, tests/templates/test_subroutines/test_grover.py
As of PR #2121 , `qml.MultiControlledX` prefers a single wires keyword argument of the form control_wires+target_wire. If passed a separate `control_wires` keyword argument, it raises a warning but still works.  This PR changes the syntax for creating a `MultiControlledX` in the decomposition for the `GroverOperator`.  Now it will no longer raise a warning.
=> Update `MultiControlledX` call in `GroverOperator`

doc/releases/changelog-dev.md, pennylane/transforms/qfunc_transforms.py, tests/transforms/test_qfunc_transform.py
**Context:** Decorated functions do not correctly display their signatures in the docs
**Description of the Change:** If a Sphinx build is detected, the `@qfunc_transform` decorator will simply return the function unchanged, allowing Sphinx to correctly introspect the signature.
**Benefits:** As above.
**Related GitHub Issues:** Fixes #2283
=> Ensures that `@qfunc_transform` decorated functions display their signatures in the docs

doc/releases/changelog-dev.md, pennylane/gradients/finite_difference.py, pennylane/gradients/param_shift_hessian.py, pennylane/gradients/parameter_shift.py, pennylane/gradients/parameter_shift_cv.py, tests/gradients/test_finite_difference.py, tests/gradients/test_param_shift_hessian.py, tests/gradients/test_parameter_shift.py, tests/gradients/test_parameter_shift_cv.py, tests/test_quantum_gradients.py, tests/transforms/test_specs.py
Fixes a bug in `qml.gradients.param_shift_hessian` which errors when the diff methods are zero for all parameters. For example in the following scenario:
```py
dev = qml.device('default.qubit', wires=4)
def circuit(params):
qml.Rot(*params, wires=0)
return qml.probs([2,3])
params = np.array([0.5, 0.5, 0.5], requires_grad=True)
qml.gradients.param_shift_hessian(circuit)(params)
```
```py
>>> ValueError: need at least one array to stack
```
Both `param_shift` and `param_shift_hessian` assume that the `results` value passed to their post-processing functions (from batched tape execution) has at least one element. Thus, scenarios which do not generate any tapes need to be checked for beforehand:
https://github.com/PennyLaneAI/pennylane/blob/e1b15d27cc5a4a882b552c936580dd903fe3b …
=> Minor gradient fixes

.github/workflows/tests.yml, doc/releases/changelog-dev.md, pennylane/debugging.py, pennylane/ops/snapshot.py, tests/test_debugging.py
Now that https://github.com/PennyLaneAI/pennylane-lightning/issues/242 is resolved, the temporary fixes to make snapshot not break lightning can be removed.
=> Snapshot: remove temporary fixes for lightning device

doc/introduction/measurements.rst, doc/releases/changelog-dev.md, pennylane/measurements.py, pennylane/operation.py, pennylane/transforms/condition.py, tests/test_measurements.py, tests/transforms/test_condition.py
**Context:**
Continuation of https://github.com/PennyLaneAI/pennylane/pull/2275 adding further docstring examples and polishing the docs.
Added:
Updated:
Fixed:
The reason was that examples like
```python
m = qml.measure(0)
qml.cond(m, RY)(0.3, wires=0)
qml.cond(~m, RX)(1.234, wires=0)
```
were producing unexpected results. The tests were amended accordingly.
**Benefits:**
More docs and fixes.
N/A
N/A
=> Extend the conditional operations documentation

pennylane/operation.py, pennylane/ops/functions/generator.py, tests/ops/functions/test_generator.py
**Context:** 
- In previous versions of PennyLane, `Operator.generator` was a property, that returned a list of the form `[type, float]` or `[array, float]`.
- In the current master, this has been changed. `Operator.generator` is now a _method_, and it returns an Operator _instance_.
- In #2256, a high-level `qml.generator()` function was added, intended to be the user-facing interface to `Operator.generator()`.
**Description of the Change:** A small modification to `qml.generator()` has been made, to ensure it continues to work with old-style operators that define the `Operator.generator` property. In addition, a deprecation warning is raised.
**Benefits:** `qml.generator()` should work with old-style operators.
**Possible Drawbacks:** This backwards compatibility is constrained, in that …
=> Add `qml.generator(op)` backwards compatibility

pennylane/operation.py, pennylane/ops/identity.py, pennylane/ops/qubit/arithmetic_ops.py, pennylane/ops/qubit/non_parametric_ops.py
Amend docstring examples for `compute_matrix` and `compute_eigvals` to get the correct formatting in the output.
This is meant to avoid confusion that users might have if they don't get the same output as in the docs.
=> Amend docstring examples for `compute_matrix` and `compute_eigvals`

doc/releases/changelog-dev.md, pennylane/ops/qubit/matrix_ops.py, tests/ops/qubit/test_matrix_ops.py
**Context**
By default, operations don't have a decomposition defined and raise `DecompositionUndefinedError` with the changes in https://github.com/PennyLaneAI/pennylane/pull/2024. Operations can, however, define there own decompositions.
`qml.QubitUnitary` has a custom decomposition defined. Its controlled version, `qml.ControlledQubitUnitary` inherits from `qml.QubitUnitary`, but doesn't have a decomposition defined. This, however, breaks examples because `qml.QubitUnitary`'s `compute_decomposition` is being called when a decomposition of `qml.ControlledQubitUnitary` is attempted (see related issue).
**Changes**
Explicitly defines the `qml.ControlledQubitUnitary.compute_decomposition` method as is in the `Operator` class to raise `DecompositionUndefinedError`.
**Related issue**
Closes …
=> ControlledQubitUnitary should raise `DecompositionUndefinedError`

doc/releases/changelog-dev.md, pennylane/transforms/qcut.py, tests/transforms/test_qcut.py
**Context:**
Many practical applications of quantum circuits require sampling measurements. Here we begin extending the existing manual circuit cutting pipeline to support sampling measurements.
The existing `qcut.tape_to_graph` method has been extended to convert a sampling in the computational basis over all wires in a circuit. The single sampling measurement is converted into distinct nodes in the computational graph; one for each wire. 
**Benefits:**
First step toward supporting cutting circuit with sampling measurements.
~~Does not support sample measurements containing observables.~~
#2297 sampling with and without observables in a single circuit causes an error. As such, the sample nodes added to the …
=> Extend `qcut.tape_to_graph` to support sampling measurements

.github/workflows/tests.yml, setup.py
Pins to Lightning `>=0.22` in the `setup.py` file such that the most recent released version of PennyLane-Lightning is being pulled when installing PennyLane in a clean environment.
=> Pin Lightning `>=0.22`

doc/releases/changelog-dev.md, pennylane/transforms/defer_measurements.py, tests/transforms/test_condition.py, tests/transforms/test_defer_measurements.py
**Context:**
The conditional measurement added gates that were not defined.
Following the @antalszava 's suggestion I just changed `tape.queue` for `tape.operations + tape.measurements`. The issue originally was that `tape.queue` contains the underlying annotated queue that doesn't describe the circuit itself. Instead, a circuit would have to be iterated using `tape.operations + tape.measurements`.
[(#2327)](https://github.com/PennyLaneAI/pennylane/issues/2327)
=> Fix queuing unexpected operators with `qml.measure`

doc/releases/changelog-dev.md, pennylane/transforms/qcut.py, tests/transforms/test_qcut.py
**Context:**
Adds an expansion function to `cut_circuit`, allowing support for circuits that contain `WireCut` operations nested in operations or sub-tapes.
=> Circuit cutting: Add expansion to cut_circuit transform

tests/transforms/test_defer_measurements.py
Updates certain test cases for `defer_measurements` where tapes are being used with a `return` statement resulting in false-positive test passes.
=> Update some `defer_measurements` test cases

pennylane/ops/cv.py, tests/ops/test_cv_ops.py
Upon trying to delete the old text circuit drawing infrastructure, I learned that the cv state preparation operations have no individual testing.
This PR adds testing of initialization and class properties.
It also changes the documentation for `wires` type to reflect the fact we support arbitrary wire labels, not just integers.
=> Add testing for cv state prep operations and update documentation

pennylane/operation.py
The recent PR introducing the `has_matrix` property also introduced a linting error.  This silences that error.
=> silence pylint issue

pennylane/transforms/qmc.py, tests/drawer/test_tape_mpl.py, tests/gradients/test_general_shift_rules.py, tests/grouping/test_group_observables.py, tests/optimize/test_gradient_descent.py, tests/test_operation.py, tests/test_prob.py, tests/test_qnode.py, tests/transforms/test_commutation_dag.py, tests/transforms/test_decompositions.py, tests/transforms/test_get_unitary_matrix.py, tests/transforms/test_optimization/test_commute_controlled.py, tests/transforms/test_optimization/test_optimization_utils.py, tests/transforms/test_optimization/test_single_qubit_fusion.py, tests/transforms/test_unitary_to_rot.py
The following bug during import has been fixed which resulted in skipped tests:
```py
pytest.importskip("tf")
```
The following warnings have been eliminated from the PennyLane tests:
- `UserWarning: The control_wires keyword will be removed soon. Use wires = (control_wires, target_wire) instead. See the documentation for more information.`
- `UserWarning: The method get_parameter_shift is deprecated. Use the methods of the gradients module for general parameter-shift rules instead.`
- `UserWarning: get_unitary_matrix is deprecated, and will be removed in an upcoming release. For extracting matrices of operations and quantum functions, please use qml.matrix().`
- `PytestRemovedIn8Warning: Passing None has been deprecated.`
- `UserWarning: 'update_stepsize' is deprecated. Stepsize value …
=> Fix import error and (some) warnings in the test suite

doc/releases/changelog-dev.md, pennylane/devices/default_mixed.py, tests/devices/test_default_mixed.py, tests/devices/test_default_qubit.py
Following #2356 , this PR makes `"default.mixed"` skip identities as well.
=> Skip identities in default.mixed

doc/requirements.txt, requirements-ci.txt
**Context:**
Installation part of the CI checks for documentation is failing because of `jinja2` version `3.1.0` that was released today. 
This PR pins `jinja2` to version `3.0.3`
=> Pin jinja2 for CI checks to `3.0.3`

doc/development/adding_operators.rst, doc/development/plugins.rst
The section on how to add operators to a plugin was outdated. Instead of rewriting it, I simply link to the up-to-date guide on creating custom operators.
=> Fix outdated section on custom ops in "How to add a plugin"

doc/releases/changelog-dev.md, pennylane/transforms/specs.py, tests/transforms/test_specs.py
Fixes #2393 
This PR adds the `expansion_strategy` keyword argument to the `qml.specs` transform.  Using this keyword, users can calculate the specifications of the circuit that will actually be executed by the device using `expansion_strategy="device"`.
=> Add `expansion_strategy` to `specs` transform

.github/workflows/docker.yml, doc/releases/changelog-dev.md, docker/pennylane.dockerfile, docker/qchem.dockerfile
**Context:** The docker build on …
=> Ensure Lightning test wheels are used in docker image

pennylane/optimize/nesterov_momentum.py, pennylane/optimize/shot_adaptive.py
Ignores the linting issues in `pennylane/optimize/nesterov_momentum.py` and `pennylane/optimize/shot_adaptive.py` that were "discovered" by Codefactor in https://github.com/PennyLaneAI/pennylane/pull/2363:
=> Ignore different arguments linting error (NesterovMomentum and ShotAdaptive optimizers)

doc/releases/changelog-dev.md, pennylane/transforms/qcut.py
**Context:**
Fixes minor typos in docstings of `qcut` module
=> Fix minor docstring typos

doc/releases/changelog-dev.md, pennylane/ops/qubit/matrix_ops.py, tests/ops/qubit/test_matrix_ops.py
**Context:** Due to a unitarity check, `qml.DiagonalQubitUnitary` did not work with `@jax.jit` and `@tf.function`.
**Description of the Change:** Uses `qml.math.is_abstract` to avoid the unitarity check if a JIT is detected.
**Benefits:** The operation now works with JIT compilation.
**Possible Drawbacks:** TensorFlow is very slow to compile, so the test added to ensure that `@tf.function` works takes 12 seconds :( Should we remove it?
=> Add support for JIT when using `DiagonalQubitUnitary`

tests/transforms/test_qcut.py
**Context:**
In test `tests/transforms/test_qcut.py::test_device_wires`, the argument `use_opt_einsum` was provided as a positional argument to `cut_circuit` which now gets interpreted as the `auto_cutter` argument due to argument order change in PR #2428. This caused kahypar to be called, leading to an import error in the test.
Passing `use_opt_einsum` as keyword argument.
**Benefits:**
fixes test in master branch
=> fixes test due to positional argument `use_opt_einsum`

doc/development/release_notes.md, doc/releases/changelog-0.22.2.md, doc/releases/changelog-0.23.0.md, doc/releases/changelog-dev.md, pennylane/_version.py
Updates PennyLane as we're entering a new development version (release of v0.23.0 coming up):
* Moves the v0.23.0 changelog into a separate file
* Updates the dev changelog file to have empty sections
* Increments the version number to v0.24.0-dev
Note: QChem is not being released, what's more, the subpackage is being deprecated.
See the same PR for the [v0.23.0 bump](https://github.com/PennyLaneAI/pennylane/pull/2295).
=> Incrementing the version number to `v0.24.0-dev`

doc/releases/changelog-0.23.0.md, pennylane/optimize/nesterov_momentum.py, tests/optimize/test_optimize.py
This bug was discovered through [the "Variational Classifier" demo](https://github.com/PennyLaneAI/qml/runs/6085549063?check_suite_focus=true#step:8:2432).
In the Nesterov Momentum Optimizer, there was confusion between the index of an argument in the total arguments list and the index in the *trainable-only* arguments list.  Non-trainable arguments were shifted using the gradient of a trainable argument after them in the list. Since `BasisState` has to have zero and one only, this shifting caused execution to fail.
=> Bugfix for Nesterov Momentum Optimier

pennylane/templates/tensornetworks/mera.py
In the documentation for the MERA template, a link wasn't rendering correctly and the output of the drawer had a extra blank line, removing code rendering for the output.
=> Fix formatting issues for MERA template

pennylane/transforms/qcut.py
**Context:**
Returns in one of the Qcut function does not render correctly, this PR fixes it.
=> Fix qcut doc render

pennylane/operation.py, tests/test_operation.py
Currently, `Operator.has_matrix` detects whether or not either `compute_matrix` or `get_matrix` is overridden from the `Operator` version.  As `Operation` itself overrides `compute_matrix`, everything inheriting from `Operation` seemed to have a matrix defined.  This led to incorrect results for a number of templates.
=> [Bug] `Operation.has_matrix` incorrect when no matrix

pennylane/transforms/transpile.py
Use `qml.eigvals` because `MeasurementProcess.eigvals` is being deprecated and a warning is raised when the transpile transform is used.
```py
dev = qml.device('default.qubit', wires=4)
@qml.transforms.transpile(coupling_map=[(0, 1), (1, 2), (2, 3)])
def circuit(param):
qml.CNOT(wires=[0, 2])
qml.CNOT(wires=[0, 3])
qml.PhaseShift(param, wires=0)
return qml.probs(wires=[0, 1, 2, 3])
```
=> Use `qml.eigvals` in `qml.transforms.transpile` to have no deprecation warning

doc/introduction/measurements.rst, pennylane/transforms/control.py, pennylane/transforms/qcut.py
Contains fixes for:
- `qml.ctrl` docstring: non-existent variable, type declaration, spelling
- Bell example on [measurements page](https://pennylane.readthedocs.io/en/stable/introduction/measurements.html#combined-measurements) (fixes #2455)
=> Documentation fixes for the v0.23.0 release

doc/releases/changelog-0.23.0.md, pennylane/interfaces/execution.py, tests/test_qnode.py
Closes #2150
Raises the following warning when a QNode is executed repeatedly with caching turned on and shot noise enabled: 
```
UserWarning: Cached execution with finite shots detected: note that the shot noise will be the same on all results from executions with identical arguments.
```
Example:
```py
params = np.random.randn(2, 2, 3)
observable_as_array = np.array([[ 1. +0.j,  0. +0.j,  0. +0.j,  0. +0.j],
[ 0. +0.j,  0.4+0.j, 21.6+0.j,  0. +0.j],
[ 0. +0.j, 21.6+0.j, -0.4+0.j,  0. +0.j],
[ 0. +0.j,  0. +0.j,  0. +0.j, -1. +0.j]])
dev = qml.device('default.qubit', wires=2, shots=42)
@qml.qnode(dev, diff_method='parameter-shift', cache={})
def circuit(params):
qml.templates.layers.StronglyEntanglingLayers(params, …
```
=> Issue a warning about repeated cached executions with shot noise

doc/code/qml_qchem.rst, pennylane/qchem/openfermion_obs.py
**Context:** The new qchem API page was not correctly listing available functions. The `molecular_hamiltonian` function also had a few rendering errors.
**Description of the Change:** Modifies the `qchem.rst` so that it lists available functions according to import location.
**Benefits:** Easier to navigate the documentation.
**Possible Drawbacks:** Not sure if anything is being listed that we don't want to appear in the documentation. If this is the case, we should not be importing these functions/classes into `pennylane/qchem/__init__.py`.
Alternatively, if you want to organize these functions, you could replace the `automodapi` with `autosummary`, and manually list which functions to document.
@soranjh one more question: the function to import operators, `qml.qchem.import_operator`. I …
=> Fix QChem documentation

doc/releases/changelog-dev.md, pennylane/qchem/observable_hf.py, pennylane/qchem/tapering.py, tests/qchem/hf_tests/test_tapering.py
**Context:**
This PR removes the dependency of `_generate_qubit_operator` from the `hf` module. It also adds a consistency check to manually add wires to the tapered observable if some go missing due to the `simplify()` routine. 
1. Replaces `_generate_qubit_operator` from `hf` module with the `jordan_wigner` from unified `qchem` module.
2. Adds consistency check for tapered wires in`qml.taper`. This allows us to return consistent observables in the case of tapering of non-Hamiltonian observables. 
3. Replaced the `test_hf_energy` unittest with a newer `test_taper_obs` unittest that uses the above consistency check.
4. Fix a minor documentation issue with `jordan_wigner`.
**Benefits:**
Removes dependency for the deprecated `hf` module and addresses wires …
=> Remove `hf` dependency in qubit tapering

doc/releases/changelog-dev.md, pennylane/operation.py, pennylane/transforms/tape_expand.py, tests/optimize/test_qng.py, tests/test_operation.py
**Context:**
When using `QNGOptimizer` with `DoubleExcitation` an error occurred because the `DoubleExcitation` generator is a Hamiltonian and there is no diagonalization method.
A function has been added to check if the generator is a Hamiltonian with more than one term (since if it has only one term it can be treated as a simple operator). If it is a Hamiltonian, we expand the operation.
**Benefits:**
QNGOptimizer can now be used with more gates
Perhaps in other cases it is better not to expand (?)
#2502
=> QNGOptimizer_Hamiltonian 

doc/releases/changelog-dev.md, pennylane/drawer/mpldrawer.py, pennylane/fourier/visualize.py, pennylane/ops/qubit/hamiltonian.py, tests/fourier/test_coefficients.py, tests/ops/functions/test_generator.py, tests/ops/qubit/test_matrix_ops.py
This PR handles several lines that were missing code coverage by either:
* explicitly specifying the lines will not be covered by our tests
* fixing logic that won't ever be covered
* adding tests
=> Improved code coverage

doc/releases/changelog-dev.md, pennylane/templates/subroutines/commuting_evolution.py, tests/templates/test_subroutines/test_commuting_evolution.py
Fixes #2520
There was some confusion as to the parameters, and during expansion, both `ApproxTimeEvolution` and its decomposition were being queued.
=> fix commuting evolution bug

doc/introduction/interfaces.rst
Moves the "interface" section to the top (since this is used by beginners, while the current "gradient" section is more advanced).
Adapts the language to move from "interface" to "automatic differentiation framework".
=> Improve quickstart: gradient section 

doc/introduction/operations.rst
Added explanation of what an op function is.
Changed "operation" to "operator" everywhere.
Added quicklinks to top
Removed section on pauli grouping, which will appear in new Quickstart section added in a follow-up PR
=> Improve Quickstart: Op section

doc/releases/changelog-dev.md, pennylane/operation.py, pennylane/ops/qubit/hamiltonian.py, tests/ops/qubit/test_hamiltonian.py, tests/test_operation.py
**Context:**
Given a Hamiltonian object `H` and an observable object (eg. `qml.PauliX(0)`), the tensor product: 
```python 
dev = qml.device("default.qubit", wires=3)
def circ(op):
qml.Hadamard(0)
qml.CNOT(wires=[0,1]) 
return qml.expval(op)
```
```
>>> op1 = H @ qml.PauliX(0)
>>> op2 = qml.PauliX(0) @ H   
>>>
>>> circ(op1)  # works as expected 
>>> circ(op2) # fails due to an error accessing the EigenValues of a tensor observable
```
The `__matmul__` method in the `Observable` class checks if the other object is an instance of `Hamiltonian`. In this case it will differ the matrix multiplication to the `Hamiltonian` classes implementation. Also a `__rmatmul__` method is implemented for the `Hamiltonian` class to allow for the above. …
=> Fix commutativity of `Hamiltonian` and `Observable` in tensor product

pennylane/ops/identity.py
Lints the `identity.py` file after #2225 due to new CodeFactor issues:
=> Lint `identity.py`

doc/releases/changelog-dev.md, pennylane/interfaces/__init__.py, pennylane/interfaces/execution.py, pennylane/qnode.py, tests/interfaces/test_autograd.py, tests/test_qnode.py
Fixes #2546 
Now if you specify QNodes like:
```
qml.QNode(qfunc, qml.device('default.qubit', wires=1), interface="tensorflow", diff_method="backprop")
```
It will map the device to `default.qubit.tf` and using backpropagation instead of silently switching to a different `diff_method`.
In solving this bug, I substituted `qml.interfaces.INTERFACE_MAP` for `qml.interfaces.INTERFACE_NAMES`, which maps in the opposite direction.  This allowed from some readability improvements. `qml.interfaces.INTERFACE_MAP` maps provided name to canonical name, instead of canonical name to list of acceptable provided names.
=> [Bugfix] Interface name variations dispatch to correct backprop device

doc/releases/changelog-dev.md, pennylane/operation.py, pennylane/tape/tape.py, tests/test_operation.py
I decided to make this change because the current behaviour was causing problems for a different PR I was working on. Also, this behaviour has always confused and annoyed me.
The problem I was encountering dealt with something like this situation:
```
>>> with qml.tape.QuantumTape() as tape:
ob = qml.PauliX(0).inv() @ qml.PauliY(1)
>>> ob
PauliX(wires=[0]) @ PauliY(wires=[1])
```
Because the `PauliX` gate was "owned" by the tensor, it never gets inverted when the queue is being processed.  This was so far an invisible bug because tensors and Hamiltonians tend to contain `Operation`'s that are self-inverses.
I can't figure out why we are using the queue metadata in this situation, and removing this behaviour does not cause any tests to fail.
So this is just a tiny bit of cleaning.
=> `op.inv()` method only updates itself and not the queue

doc/releases/changelog-dev.md, pennylane/operation.py, pennylane/queuing.py, tests/test_operation.py, tests/test_queuing.py
The `qml.queuing.Queue` class is a vestigial holdover from the early implementation that never ended up being used in anything.  This PR removes this object and it's unit tests.
=> Remove `qml.queuing.Queue` class

.github/workflows/tests.yml, .github/workflows/upload.yml, doc/requirements.txt
**Context:**
The new version of …
=> Solution for the protobuf breaking changes problems

doc/_static/draw_mpl/draw_mpl_examples.py, doc/_static/drawer/mpldrawer_examples.py, doc/_static/style/style_examples.py, doc/_static/tape_mpl/tape_mpl_examples.py, doc/conf.py, pennylane/gradients/parameter_shift_hessian.py, pennylane/measurements.py, pyproject.toml, tests/templates/test_embeddings/test_basis.py
**Context:**
Running black from the main `pennylane` folder results in:
`No Python files are present to be formatted. Nothing to do` :sleeping:
* Updates the `include` pattern in `pyproject.toml`;
* Runs black on `pennylane` and `tests`;
* Runs `black .` that formats some Python files in the `doc` folder too.
**Benefits:**
`black` can be run again.
N/A
N/A
=> Fix the include pattern for `black` in `pyproject.toml`

doc/releases/changelog-dev.md, pennylane/ops/qubit/hamiltonian.py, tests/ops/qubit/test_hamiltonian.py
Currently, IPython displays Hamiltonians via their `repr` representation:
```
>>> 1.0 * qml.PauliX(0)
<Hamiltonian: terms=1, wires=[0]>
```
This doesn't tell us much about what's actually in the Hamiltonian, so I find myself always having to use `print(H)` instead of simply `H` when playing around with Hamiltonians in the REPL.
This PR defines the `_ipython_display` method for Hamiltonians, so now it prints out the full `str` representation.
```
>>> 1.0 * qml.PauliX(0)
(1.0) [X0]
```
=> IPython displays a `Hamiltonian`'s `str` representation instead of `repr`

doc/releases/changelog-dev.md, pennylane/devices/tests/test_gates.py
While #2222 added `default.qubit` support for several non-decomposable `Adjoint` gates, they were not added to the device test suite.  This PR adds the following ops to the device test suite:
* `adjoint(S)`
* `adjoint(T)`
* `adjoint(SX)`
* `adjoint(SISWAP)`
* `adjoint(ISWAP)`
=> Add adjoint ops to device test suite

doc/releases/changelog-dev.md, pennylane/utils.py
cc @mlxd 
**Context:**
Currently the `sparse_hamiltonian` generation code is pretty slow for large Hamiltonians. For example, for a 24 qubit Hamiltonian representing a CO2 molecule, generation of *each* coeff-op pair takes about 10s. This is problematic when there are 6000+ such pairs. Some timing I did suggests that most of the time is spent adding the temporary sparse matrices representing coeff-op pairs into the "overall" Hamiltonian `matrix`. There is also some performance lost by unnecessarily `kron`-ing identity matrices, when we know that `I_m kron I_n = I_{m+n}`. 
There are a few changes made here:
- coeff-op matrices are accumulated in a list until there are about 100 of them and then added together, and then this object is added into the overall …
=> Trial performance improvements to sparse Hamiltonian building

doc/releases/changelog-dev.md, pennylane/ops/op_math/adjoint_class.py, pennylane/ops/op_math/pow_class.py, tests/ops/op_math/test_adjoint_op.py, tests/ops/op_math/test_pow_op.py
This PR updates the `Adjoint` and `Pow` symbolic operators to also have the new `ndim_params` and `batch_size` properties added recently in #2575.  It also adds the `is_hermitian` property to the `Adjoint` symbolic operator.
This PR should fix the failing build for the `tutorial_classical_kernels.py` demo.
=> Adding batching support for symbolic operators

pennylane/devices/tests/test_properties.py
**Context**
The `test_returns_state` test case from the device test suite contains logic that would fail if a device has `returns_state=False` set explicitly. This issue hasn't arisen before because we don't have such qubit devices in our ecosystem (as the devices would simply not set the define the `returns_state` key in their `capabilities`.
**Changes**
Changes `test_returns_state`.
**Checking this PR**
The `temp_state_false` branch in PennyLane-Qiskit contains a small modification of the Aer device that sets `returns_state=False`.
Checking out the branch for this PR and the `temp_state_false` branch in PennyLane-Qiskit allows running
`pl-device-test --device=qiskit.aer --tb=short --skip-ops --shots=None -k 'test_returns_state'` for a check to the correctness of this PR.
=> Update `test_returns_state` in the device test suite

pennylane/ops/qubit/hamiltonian.py, tests/ops/qubit/test_hamiltonian.py
This PR adds a cutoff of 15 terms to the `_ipython_display_` of Hamiltonians.  If the Hamiltonian has 15 or above terms, IPython will merely display the `repr` instead of the `str`.
=> Adds a cutoff for Hamiltonian `_ipython_display`

doc/releases/changelog-dev.md, pennylane/drawer/tape_mpl.py, pennylane/drawer/tape_text.py, pennylane/ops/qubit/observables.py, tests/drawer/test_tape_mpl.py, tests/drawer/test_tape_text.py, tests/interfaces/test_tensorflow_qnode.py, tests/interfaces/test_torch_qnode.py, tests/transforms/test_defer_measurements.py
**Context:**
Text drawing had no difference between 0 and 1 control values. Similarly, mpl drawer was missing `ControlledQubitUnitary` in its special cases
Changes text drawer to have different symbols for 0 and 1 control values. ~~Also, add `ControlledQubitUnitary` as a special case in mpl drawer.~~ Adds logic in mpl drawer to consider `control_values`
**Benefits:**
Better visual circuits.
Closes #2660
=> Make visual changes for 0 and 1 control values [unitaryhack]

pennylane/qnn/torch.py
Add example for new `init_method` in `qnn.TorchLayer` to docs. This feature was added in https://github.com/PennyLaneAI/pennylane/pull/2678 but the doc-string was not updated. The example is taken from a PR comment of the Author.
=> Add example for new `init_method` in `qnn.TorchLayer` to docs

doc/releases/changelog-dev.md, pennylane/ops/qubit/hamiltonian.py, pennylane/vqe/vqe.py, tests/ops/qubit/test_hamiltonian.py
**Context:**
Given a hamiltonian object, if one were to perform in-place addition, the `h.wires` attribute was not updated to consider new wires from the added hamiltonian. 
eg. 
```
>>> H = qml.Hamiltonian([1., 2.], [qml.PauliX(0), qml.PauliY(1)])
>>> H2 = qml.Hamiltonian([1.], [qml.PauliZ(2)])
>>>
>>> H += H2 
>>> print(H.wires)
<Wires = [0, 1]>  
>>> # should be <Wires = [0, 1, 2]>
```
Added logic which updates `H.wires` once an in place addition has occurred. 
Based on this user reported [issue](https://github.com/PennyLaneAI/pennylane/issues/2706)
=> Wires not updated for a hamiltonian with in-place addition

pennylane/ops/qubit/non_parametric_ops.py
**Context:**
Fix the matrix printed in the `ECR.compute_matrix()` method documentation.
=> Fix rendering of matrix rep of ECR

tests/transforms/test_qcut.py
There is some failing test if you run `pytest tests/` and some interfaces are not installed. We add corresponding markers to those tests.
=> Update test markers in qcut

doc/releases/changelog-dev.md, pennylane/ops/op_math/adjoint_class.py, tests/ops/op_math/test_adjoint_op.py
Fixes #2765 
```pycon
>>> base = qml.PauliX(0)
>>> adj1 = qml.adjoint(base)
>>> adj2 = qml.adjoint(adj1)
>>> adj2.expand().circuit
[PauliX(wires=[0])]
```
=> [bugfix] adjoint of adjoint expands queues base operation

tests/test_qaoa.py
One test case is failing with `numpy==1.23.0` due to a freshly failing equality check. The failure is due to potentially small differences in Hamiltonian coefficients ([see log here](https://github.com/PennyLaneAI/pennylane/runs/7015030142?check_suite_focus=true#step:11:246)), part of the error output:
```
E     Full diff:
E       [
E        -6.693147180559945,
E        -6.0,
E        -5.594534891891835,
E        -5.306852819440055,
E        -5.083709268125845,
E     -  -4.901387711331891,
E     ?                   -
E     +  -4.90138771133189,
E        54.0,
E        12.0,
E        -12.0,
E        -6.0,
E        -6.0,
E        -12.0,
E        6.0,
E        12.0,
E        -6.0,
E        -6.0,
E        -12.0,
E        6.0,
E        12.0,
E        -6.0,
E        -6.0,
E        6.0,
E …
```
=> Update QAOA test because of NumPy version 1.23.0

.github/workflows/tests.yml, codecov.yml
**Context:**
Currently it upload the coverage report for every single job, creating temporary failed codecov action.
After each jobs create an artifact with the coverage report, at the end it creates a new job that is uploading the artifacts and it sends the coverages report to codecov all at once.
=> Codecov: single upload for coverage reports

tests/test_measurements.py
Not entirely sure why, but some tests set backprop for the forward pass with `default.mixed` and have been skipped before. Now we can allow these cases to work too.
=> Remove some test skips now that `default.mixed` supports backprop

doc/releases/changelog-dev.md, pennylane/_qubit_device.py, tests/devices/test_default_mixed_autograd.py, tests/devices/test_default_mixed_jax.py, tests/devices/test_default_mixed_tf.py, tests/devices/test_default_mixed_torch.py, tests/devices/test_default_qubit_autograd.py, tests/devices/test_default_qubit_jax.py, tests/devices/test_default_qubit_tf.py, tests/devices/test_default_qubit_torch.py, tests/test_measurements.py, tests/transforms/test_condition.py
**Context:**
When `qml.state` and `qml.density_matrix` have been added, custom wire labels have not yet been allowed.
Recent changes of creating the quantum information module and its density matrix capabilities have allowed a simple way for `qml.density_matrix` to add support.
* Removes the validation check that raises an error for custom wires;
* Maps the custom wire labels to device wires when computing the density matrix in `QubitDevice`.
**Benefits:**
Devices and circuits with custom wires labels are compatible with `qml.state` and `qml.density_matrix`.
N/A
N/A
=> `qml.state` and `qml.density_matrix` custom wires

.github/CONTRIBUTING.md
**Context:**
The link to the requirements-dev.txt file in the contributing.md was broken.
**Benefits:**
Fixes #2789
=> Fixed doc link in contributing.md

doc/releases/changelog-dev.md, pennylane/_qubit_device.py
The `QubitDevice.sample` method differs from `Device.sample`. Yet, they have the same docstring.
This PR creates a custom `QubitDevice.sample` docstring.
Closes #2811
=> Define dedicated `QubitDevice.sample` docstring

doc/releases/changelog-dev.md, pennylane/_qubit_device.py, pennylane/_qutrit_device.py, tests/test_qubit_device.py, tests/test_qutrit_device.py
This PR changes `QubitDevice.generate_samples` and `QubitDevice.generate_basis_states` to use `self.states_to_binary` instead of `QubitDevice.states_to_binary`.
=> Use custom `states_to_binary` method in `QubitDevice`'s

pennylane/interfaces/autograd.py, tests/devices/test_custom_return_obj.py
This contains suggested improvements to #2808 @puzzleshark
=> Custom return type

doc/releases/changelog-dev.md, pennylane/gradients/parameter_shift.py, tests/gradients/test_parameter_shift.py
This PR restructures `param_shift`. In particular, it introduces additional helper methods, trying to modularize the main for loop of `expval_param_shift`.
In addition, this restructuring fixed #2833, as this bug was caused by flawed bookkeeping of unshifted coefficients (It worked for second order derivatives because usually then all operations require the unshifted tape.
Related issue: #2833
=> Restructure `param_shift` and fix bug in unshifted term bookkeeping

doc/releases/changelog-dev.md, pennylane/_qubit_device.py
Now that we have the `Adjoint` symbolic op and can represent the adjoint of an operation in all cases without relying on in-place modification, we can go back and tidy the `QubitDevice.adjoint_jacobian` method.
=> Adjoint diff now uses adjoint instead of in-place inversion

doc/releases/changelog-dev.md, pennylane/operation.py, pennylane/ops/qubit/hamiltonian.py, tests/test_operation.py
Add support to addition of operators and scalars.
Example:
```python
sum_op = 5 + qml.PauliX(0)
print(sum_op)
```
Prints:
```
PauliX(wires=[0]) + 5*(Identity(wires=[0]))
```
Add `__sub__`, `__rsub__` and `__neg__` dunder methods to the `Operator` class.
=> Addition of operators and scalars + extra dunder methods

pennylane/resource/first_quantization.py, pennylane/resource/second_quantization.py
**Context:**
This PR makes `numpy.integer` an accepted type for number of electrons and number of spin-orbitals.
**Benefits:**
=> Support numpy integer type in resource estimation functions

doc/releases/changelog-dev.md, pennylane/math/__init__.py, pennylane/math/multi_dispatch.py, tests/math/test_functions.py
The exponential wrapper #2799 creating `Exp(op, coeff)` requires matrix exponentiation for its matrix.  This PR adds `expm` to the `math` module that dispatches to the different versions in the different interfaces.
Numpy and autograd do not have their own version of matrix exponentiation. Instead, these types of matrices will rely on SciPy's function. Therefore, `expm` will not be autograd-differentiable.
=> Add `qml.math.expm` for matrix exponentiation

doc/development/release_notes.md, doc/releases/changelog-0.24.0.md, doc/releases/changelog-0.25.0.md, pennylane/_version.py
Updates PennyLane as we're entering a new development version (release of v0.25.0 coming up):
Preparation of release candidate:
* Rename changelog-dev.md to changelog-0.25.0.md
* Increments the version number to v0.25.0
* Change changelog-dev reference to changelog-0.25 reference in release_notes.md
```
rc    master
|     |
|     - add changelog-dev.md, add changelog-dev reference to release_notes.md, bump version to 0.26.0-dev
|    /
|   /
|  /
| /
|/
- (**THIS PR**) rename changelog-dev.md to changelog-0.25.0.md, change changelog-dev reference to changelog-0.25 reference in release_notes.md, move "current release" label from changelog-0.24 to changelog-0.25, change version from 0.25.0-dev to 0.25.0
|
| 
```
=> Preparation for release candidate `v0.25.0`

doc/releases/changelog-0.25.0.md
In the translation of [this comment](https://github.com/PennyLaneAI/pennylane/pull/2627/#issuecomment-1177240093) into the changelog entry in #2868 I made a logical mistake, which is fixed here. It is a mere flip of the Boolean `supports_broadcasting` in the capabilities dictionary, and the original statement was that
>  The device does not explicitly update the `_capabilities` dictionary of the class to contain `supports_broadcasting: False`
is problematic. In the changelog, I wrote that 
> The custom device maintains the flag `"supports_broadcasting": False` in its capabilities dictionary
is problematic, which is the opposite.
=> Fix relevant typo regarding broadcasting in changelog

tests/returntypes/test_new_return_types_qnode.py
Adds test cases for `lightning.qubit` on the forward pass.
=> [Return-types] Test Lightning forward pass

tests/optimize/test_optimize_shot_adapative.py
**Context:**
One of the tests for the Shot adaptive optimizer fails stochastically at times:
https://github.com/PennyLaneAI/pennylane/runs/7749282768?check_suite_focus=true#step:11:467
Adds a seed and uses flaky.
**Benefits:**
No stochastic CI test failures.
N/A
N/A
=> Shot adapt test fix

doc/development/adding_operators.rst, doc/development/plugins.rst
Now that we rely on `dev.stopping_condition` instead of purely `dev.operations` to determine whether or not an operation is supported, we need to update the developer guide to reflect this change.
=> Update development guide to explain `dev.stopping.condition`

pennylane/ops/op_math/controlled_class.py
Some minor changes to the examples in the docstring.
=> Fix symbolic `Controlled` operator documentation

doc/releases/changelog-0.25.0.md, pennylane/resource/first_quantization.py, pennylane/resource/second_quantization.py
**Context:**
This PR reorganises the docstrings of `DoubleFactorization` and `FirstQuantization`  classes in `resource` module. 
- The Usage Details section is converted to Examples.
- The theoretical details are brought to a new Theory section.
**Benefits:**
=> Modify resource docs

doc/releases/changelog-0.25.0.md, pennylane/ops/functions/equal.py, tests/ops/functions/test_equal.py
Fixes #2945 
Now we have 
```
>>> qml.equal(qml.RX(1.0, wires=0), qml.RX(1.0, wires=0).inv())
False
```
=> `qml.equal` considers in-place inversion.

pennylane/ops/op_math/prod.py
Some examples for `qml.prod` need correction in their outputs.
=> Correct `qml.prod` example outputs

pennylane/math/utils.py, pennylane/ops/functions/equal.py, tests/math/test_functions.py, tests/ops/functions/test_equal.py
**Context:**
```py
pl_tensor = qml.numpy.array(0.3, requires_grad=True)
torch_tensor = torch.tensor(0.3, requires_grad=True)
qml.math.allclose(pl_tensor, torch_tensor)
```
Raises
```py
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```
Updates `qml.math.allclose` to catch `RuntimeError`. This way trainable Torch tensors are correctly converted to NumPy.
**Benefits:**
`qml.math.allclose` works with Torch Tensors that have `requires_grad=True` set.
N/A
N/A
=> Update `qml.math.allclose` to work for trainable Torch tensors (motivated by `qml.equal`)

pennylane/templates/subroutines/flip_sign.py
Formats and corrects the `qml.Flipsign` docstring example.
=> Update `qml.Flipsign` docs example

doc/releases/changelog-0.25.0.md, pennylane/ops/op_math/adjoint_class.py, pennylane/ops/op_math/pow_class.py, pennylane/ops/op_math/prod.py, pennylane/ops/op_math/sprod.py, pennylane/ops/op_math/sum.py, tests/ops/op_math/test_adjoint_op.py, tests/ops/op_math/test_pow_op.py, tests/ops/op_math/test_prod.py, tests/ops/op_math/test_sprod.py, tests/ops/op_math/test_sum.py
**Context:**
`qml.matrix()` was not compatible with some arithmetic operators and instances of the `Hamiltonian` class.
Update the `matrix()` class method for the arithmetic operator classes to use the top level `qml.matrix()` method.
=> Matrix incompatible for `Hamiltonian` objects in Arithmetic Operators

.github/workflows/tests-gpu.yml, doc/releases/changelog-dev.md
**Context:** Currently the GPU tests run on the `labeled` event with the `gpu` label being added even if the PR the label is being added to is Closed/Merged. This is wasteful since the number of GPU runners we have are limited.
**Description of the Change:** This PR updates the conditional check for the GPU tests running on only run on open PRs.
**Benefits:** Better utilization of self-hosted runners
**Possible Drawbacks:** 
None. Unless we have a new situation where we'd like GPU tests to run on already merged PRs, but do not see that as being the case.
None.
=> Updated GPU Tests workflow file to only run if the pull_request is in open state

doc/releases/changelog-dev.md, pennylane/operation.py, pennylane/ops/identity.py, pennylane/ops/op_math/pow_class.py, pennylane/ops/op_math/sprod.py, pennylane/ops/op_math/sum.py, pennylane/ops/qubit/non_parametric_ops.py, pennylane/ops/qubit/observables.py, pennylane/ops/qutrit/observables.py
**Context:**
The current docstrings are incorrect, saying that the diagonalizing gates implemented $U$, the unitary such that $O = U \Sigma U^{\dagger}$, where $O$ is the original operation and $\Sigma$ the diagonal matrix. However, the diagonalizing gates actually implement $U^{\dagger}$, since $\langle \psi | O | \psi \rangle = \langle \psi | U \Sigma U^{\dagger} | \psi \rangle$, making $U^{\dagger} | \psi \rangle$ the actual state being measured in the $Z$-basis.
Corrects the docstrings for diagonalizing gates in all relevant operations to say that the diagonalizing gates implement $U^{\dagger}$.
**Benefits:**
=> Fix docstrings for diagonalizing gates

doc/releases/changelog-dev.md, pennylane/ops/qubit/non_parametric_ops.py, pennylane/tape/tape.py, pennylane/templates/subroutines/qpe.py, pennylane/transforms/adjoint_metric_tensor.py, pennylane/transforms/qmc.py, tests/templates/test_subroutines/test_qpe.py
In preparation for deprecating in-place inversion with `Operation.inv`, this PR eliminates its use internally in PennyLane.
=> Remove use of in place inversion

README.md
**Context:** New ReadTheDocs badge
The current RTD badge on the pennylane README uses https://shield.io, which unfortunately does not support the Business tier hosting of RTD. 
The new solution is to use the badge that RTD themselves generate for each project. 
This PR updates the RTD docs badge with the new links.
**Benefits:**
Old badge will go stale once the current community RTD builds are disabled. This new badge reflects the updated status.
No logo available with the new badge
None
=> Updated ReadTheDocs badge to new pennylane docs url

doc/releases/changelog-dev.md, pennylane/ops/qubit/non_parametric_ops.py, tests/ops/qubit/test_non_parametric_ops.py
In our compilation functions, only Barriers where `only_visual=False` affect the output of the compilation.  If `only_visual=True`, the Barriers are removed prior to compilation.
We should mimic this behaviour with the `qml.simplify` pipeline. With this PR and #2982 , we get:
```python
>>> qml.simplify( qml.S(0) @ qml.Barrier(0, only_visual=True) @ qml.S(0) )
PauliX(wires=[0])
>>> qml.simplify( qml.S(0) @ qml.Barrier(0, only_visual=False) @ qml.S(0) )
S(wires=[0]) @ Barrier(wires=[0]) @ S(wires=[0])
```
=> simplify `Barriers` to the `Identity` if `only_visual=True`

doc/releases/changelog-dev.md, pennylane/math/single_dispatch.py, pennylane/ops/functions/is_commuting.py, pennylane/ops/qubit/parametric_ops.py, tests/ops/functions/test_simplify.py, tests/ops/op_math/test_adjoint_op.py, tests/ops/op_math/test_prod.py, tests/ops/qubit/test_parametric_ops.py
**Context:**
Part of the new `simplify` pipeline for operator arithmetic
Overwrite the default `Operation.simplify` method for most parametric operations. These simplify methods take the rotation angles and mods them by `2 * np.pi`.
=> Add simplify method to parametric ops

doc/releases/changelog-dev.md, pennylane/ops/functions/simplify.py, tests/ops/functions/test_simplify.py
In current master, if we try to take the gradient of a simplified qnode with jax:
```
@qml.qnode(qml.device('default.qubit.jax', wires=1), interface='jax')
@qml.simplify
def circuit(x):
qml.adjoint(qml.RX(x, wires=0))
x = jax.numpy.array(0.1)
jax.grad(circuit)(x)
```
We get:
```
File /jax/_src/api.py:1091, in _check_scalar(x)
1089 if isinstance(aval, ShapedArray):
1090   if aval.shape != ():
-> 1091     raise TypeError(msg(f"had shape: {aval.shape}"))
1092 else:
1093   raise TypeError(msg(f"had abstract value {aval}"))
TypeError: Gradient only defined for scalar-output functions. Output had shape: (1,).
```
This is because `qml.simplify` returns a tuple of the simplified measurements.  We should return just the measurement itself if only one measurement …
=> [Bug] Fix `qml.simplify` output shape differences

doc/code/qml_fourier.rst
**Context:**
`qml.fourier.spectrum` was deprecated and replaced with `circuit_spectrum` in #1681
Update the qml_fourier doc to match the latest code
**Benefits:**
Docs are more up-to-date as a whole
N/A
N/A
=> fix fourier docs to use circuit_spectrum

doc/releases/changelog-dev.md, pennylane/grouping/utils.py, tests/grouping/test_grouping_utils.py
For [PennyLane Lightning PR #349](https://github.com/PennyLaneAI/pennylane-lightning/pull/349), I am trying to get adjoint differentiation working with operator arithmetic observables.
On that PR branch, I try:
```
dev = qml.device('lightning.qubit', wires=2)
@qml.qnode(dev, diff_method="adjoint")
def circuit(x):
qml.RX(x, wires=0)
return qml.expval(qml.s_prod(2.0, qml.PauliZ(0)))
x = qml.numpy.array(1.0)
circuit(x)
```
Only to get the error (tail end of traceback only):
```
File ~/Prog/pennylane-lightning/pennylane_lightning/_serialize.py:66, in _obs_has_kernel(ob)
57 def _obs_has_kernel(ob: Observable) -> bool:
58     """Returns True if the input observable has a supported kernel in the C++ backend.
59 
60     Args:
(...)
64         bool: indicating whether ``obs`` has a dedicated …
```
=> `qml.grouping.is_pauli_word` returns false for non-observables

.github/workflows/tests-gpu.yml, .github/workflows/tests.yml, tests/qnn/test_keras.py
**Context:**
Previously some tests were failing with a modern TF+Python installation.
Added test runners for Python 3.10. Updated the CI version of TF to 2.10.0 and PyTorch to 1.11.0. 
Also fixed the failing tests.
=> Add test runners for Python 3.10 and update TF and PyTorch versions

doc/releases/changelog-dev.md, pennylane/grouping/__init__.py, pennylane/grouping/utils.py, pennylane/ops/functions/is_commuting.py, tests/grouping/test_grouping_utils.py, tests/grouping/test_pauli_group.py, tests/ops/functions/test_is_commuting.py, tests/test_qaoa.py
**Context:**
There are currently two different implementations of `is_commuting()`: one at the top-level for a variety of operators, and another in `pennylane/grouping/utils.py` specifically for Pauli words. These should be in the same place to avoid drift, give a simpler user interface and ease future development, so I'm putting them in the same place (`qml.is_commuting`)
- Move the Pauli word is_commuting logic to `qml.is_commuting()` (thereby removing `qml.grouping.utils.is_commuting()`), and try to check this before other checks
- If it deems one or both operators to not be Pauli words, check if either are Tensors
- If they are, raise an exception
- Else, carry on
- Explicitly remove support for Prod and Sum classes (as well as Tensors) since we do not …
=> Move pauli word logic from `qml.grouping.utils.is_commuting` to `qml.is_commuting`

doc/development/release_notes.md, doc/releases/changelog-0.25.1.md, doc/releases/changelog-0.26.0.md, pennylane/_version.py
Updates PennyLane as we're entering a new development version (release of v0.25.0 coming up):
Preparation of release candidate:
* Rename changelog-dev.md to changelog-0.26.0.md
* Increments version from 0.26.0-dev to 0.26.0
* Change changelog-dev reference to changelog-0.26 reference in release_notes.md
```
rc    master
|     |
|     - add changelog-dev.md, add changelog-dev reference to release_notes.md, bump version to 0.26.0-dev
|    /
|   /
|  /
| /
|/
- (**THIS PR**) rename changelog-dev.md to changelog-0.26.0.md, change changelog-dev reference to changelog-0.26 reference in release_notes.md, move "current release" label from changelog-0.25.1 to changelog-0.26, change version from 0.26.0-dev to 0.26.0
|
| 
```
=> Preparation for release candidate `v0.26.0`

tests/optimize/test_optimize_shot_adapative.py
**Context:**
The `test_single_argument_step` test fails stochastically, e.g., [see log here](https://github.com/PennyLaneAI/pennylane/actions/runs/3044307643/jobs/4904553461#step:11:207).
Have it use `flaky`.
=> Have `test_single_argument_step` use `flaky`

doc/releases/changelog-0.26.0.md, pennylane/tape/tape.py, tests/tape/test_tape.py
**Context:**
When measuring non-commuting observables in a tape we raise an error. This error is not very descriptive relative to the many cases in which it could be raised
Update the error message raised, based on if we measure samples, probs, counts, etc. 
[Issue](https://github.com/PennyLaneAI/pennylane/issues/3051)
=> Update Error message non commuting ops are measured

pennylane/measurements.py, tests/shadow/test_shadow_expval.py, tests/shadow/test_shadow_measurement.py
**Context:**
The shape of `ShadowMeasurementProcess` returns the wrong shape.
Fix the shape of `ShadowMeasurementProcess` to match the output shape of the tape execution.
=> Fix shape of `ShadowMeasurementProcess`

doc/introduction/operations.rst
Copies over only the documentation changes from #3071 . That way the docs can get into the release. @mudit2812
=> Qutrit docs of the release

doc/introduction/measurements.rst, pennylane/_qubit_device.py, pennylane/measurements.py, pennylane/ops/qubit/non_parametric_ops.py
The other non_parametric_ops do not define a docstring for `compute_sparse_matrix`, so they inherit the more detailed (though maybe less relevant) docstring from the parent class. For consistency, I'm making Hadamard do the same. We can give them better docstrings later (or now!) if we prefer that.
Saw we changed "Per" to "By" in the changelog entry for the `all_outcomes` feature, so I'm doing it in the code as well.
=> Consistent docstring for Hadamard and other docs

pennylane/ops/op_math/prod.py, pennylane/ops/op_math/sum.py
**Context:**
Remove the doc-string defined in class and use the default defined in the operator.
=> removed inconsistent doc-string, use operator defined default

.github/workflows/tests.yml
**Context:**
We've been experiencing failures with Codecov.
Adds token usage for the Codecov uploader. Tokenless uploads seem to be limited with Codecov and may hit issues making it fail intermittently.
=> Use token with Codecov uploader

doc/releases/changelog-dev.md, pennylane/math/quantum.py, tests/qinfo/test_fidelity.py
**Context:**
While testing PLCC, I ultimately avoided using `qml.math.fidelity` because it wasn't working for trainable states with autograd. Turns out, this is only true if you do `fidelity(non_trainable, trainable)`. Any other combo seems to work fine. Anyway, the reason was `np.linalg.norm` not getting along nicely with an intermediate 1D-ArrayBox while calculating the overlap in `fidelity()`.
Replace `np.linalg.norm` with `np.abs` in `qml.math.fidelity` for the case where both states are 2D (pure) vectors
**Benefits:**
The user will no longer see an error when doing `qml.math.fidelity(non_trainable_state, trainable_state)`
None. But there may be more weird edge-cases not considered in the fidelity method. We'll fix those as they …
=> make fidelity of vectors differentiable

doc/releases/changelog-dev.md, pennylane/templates/embeddings/amplitude.py, tests/templates/test_embeddings/test_amplitude.py
This PR fixes #3165 by replacing `qml.math.concatenate` by `qml.math.hstack`.
A test that fails on master because it uses `pad_with` like the example in #3165 is added.
=> Make `AmplitudeEmbedding` JIT-compatible

doc/releases/changelog-dev.md, pennylane/math/multi_dispatch.py, tests/math/test_multi_dispatch.py
Contains just part of #3021 , but that PR was also going to fix batching for operator arithmetic.  Operator arithmetic batching will take more PR's and thought.
The following code:
```
import warnings
warnings.simplefilter("error")
with qml.tape.QuantumTape() as tape:
obs = qml.op_sum(qml.s_prod(torch.tensor(1.2), qml.PauliX(0)), qml.PauliZ(0))
qml.expval(obs)
with qml.tape.Unwrap(tape):
print(tape.get_parameters())
print(obs.parameters)
```
Will still raise errors, but that will be because of batching and not because of unwrapping.  So there will be one less warning.
The warning raised by unwrapping the nested data will no longer exist.
=> Avoid ragged arrays when unwrapping nested parameters

doc/introduction/interfaces.rst, pennylane/gradients/__init__.py
Explains the usage of the `max_diff` arg more in the docs to explain higher-order derivatives with an example.
=> Document the `max_diff` arg more in the docs to explain higher-order derivatives

doc/releases/changelog-dev.md, pennylane/ops/qubit/qchem_ops.py, tests/ops/qubit/test_qchem_ops.py
**Context:** New decomposition for `OrbitalDecomposition`.
**Description of the Change:** Decomposes into `SingleExcitation` gates instead of more elementary gates (e.g. control gates, `Hadamard`, etc.)
**Benefits:** 
There are two really big advantages to decomposing down into SingleExcitation gates:
- `default.qubit` and `lightning` natively support `SingleExcitation`, so the execution will be faster
- `SingleExcitation` has a parameter-shift rule defined, so less circuits will be executed to get the gradient
**Related GitHub Issues:** https://github.com/PennyLaneAI/pennylane/issues/3169
=> New `OrbitalRotation` decomposition

doc/releases/changelog-dev.md, pennylane/ops/op_math/adjoint_class.py, tests/ops/op_math/test_adjoint_op.py
The matrix for adjoint now works with batched parameters:
```
>>> base = qml.RX(np.array([1.2, 2.3]), 0)
>>> op = qml.adjoint(base, lazy=True)
>>> op.matrix()
tensor([[[0.82533561-0.j        , 0.        +0.56464247j],
[0.        +0.56464247j, 0.82533561-0.j        ]],
[[0.40848744-0.j        , 0.        +0.91276394j],
[0.        +0.91276394j, 0.40848744-0.j        ]]], requires_grad=True)
```
=> Adjoint batching support to `Adjoint` wrapper

tests/transforms/test_unitary_to_rot.py
https://github.com/PennyLaneAI/pennylane/issues/1412 works now on `master` - as noted there, this PR adds param-shift as a tested `diff_method`.
From the issue:
> I've just run into this in the development of https://github.com/PennyLaneAI/pennylane/pull/1552. Once it is resolved, it would be nice to update the test
test_gradient_unitary_to_rot_two_qubit_jax in the test_unitary_to_rot.py file to include parameter-shift in addition to backprop.
Closes https://github.com/PennyLaneAI/pennylane/issues/1412.
=> Use param-shift too for `test_gradient_unitary_to_rot_two_qubit_jax`

doc/releases/changelog-dev.md, pennylane/queuing.py, tests/tape/test_tape.py
**Context:**
A bug was reported which demonstrated a scenario where `QueuingManager.stop_recording` called from within a tape raises an unexpected error (when some expected error is raised within the `stop_recording` block). If you `yield` in python, and the code you yielded to raises an exception, the rest of your code doesn't run. We had some cleanup code after `yield` in `stop_recording` that *must* be run before exiting a tape.
Restore previously active contexts after a `stop_recording` context even when the yielded block raises some error.
**Benefits:**
A bug will be squashed.
None.
Fixes #3103
=> clean up after catching errors within a stop_recording context

doc/releases/changelog-dev.md, pennylane/ops/qubit/matrix_ops.py, tests/ops/qubit/test_matrix_ops.py
Fixes #3190 
`ControlledQubitUnitary.pow` now copies over the control values of the original operation.
While there, I added the `ControlledQubitUnitary.control_values` property, because it makes life easier.  While `Controlled` also has the `control_values` property, they differ in types, as `ControlledQubitUnitary` still uses the old string-based representation, not the iterable of booleans representation. 
We should go back and fix that up at some point.
=> Fix `ControlledQubitUnitary.pow`

doc/releases/changelog-dev.md, pennylane/ops/op_math/composite.py, tests/ops/functions/test_eigvals.py, tests/ops/op_math/test_prod.py, tests/ops/op_math/test_sum.py
**Context:**
When working with linear combinations of operations. If the expressions are not fully simplified, then there may be sub-operators which are not hermitian. When asking for the eigenvalues of such operators, the default pipeline assumes hermiticity and will automatically cast to `float` types (losing information about the complex parts). 
We update the pipeline to support complex eigenvalues here. 
**Related Issues:** 
[issue 3198](https://github.com/PennyLaneAI/pennylane/issues/3198)
[sc-28321]
=> Change `eigh` to `eig` to support computing the eigenvalues of non-hermitian observables

tests/transforms/test_insert_ops.py
Issue #3103 was closed automatically, but let's add one more test as per Antal's request in the closing PR.
This test demonstrates that the reported bug specifically has been fixed.
Note that if (when?) we support non-commuting observables, this will no longer raise an error and the test will fail (it will hit the `assert False` line). If we don't want this to happen, we can leave the tests as is (because the other PR more generally tests what happens when a downstream error occurs). I'm of the opinion that this is still a value-add, because we can simply remove this test when this circuit no longer raises an error!
=> test to show noise transform fails properly

pennylane/measurements.py
Amends a docstring: `shadow_expval` could take an iterable of observables too.
=> Shadow expval docstring

.github/workflows/tests-gpu.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Switch from deprecated `set-output` GH actions usage

doc/releases/changelog-dev.md, pennylane/ops/functions/simplify.py, pennylane/transforms/batch_transform.py, pennylane/transforms/hamiltonian_expand.py, pennylane/transforms/op_transforms.py, pennylane/transforms/split_non_commuting.py, tests/ops/functions/test_matrix.py, tests/transforms/test_batch_transform.py, tests/transforms/test_hamiltonian_expand.py, tests/transforms/test_op_transform.py, tests/transforms/test_split_non_commuting.py
Now that `QuantumTape` inherits from `QuantumScript`, many locations only really need the parent `QuantumScript` and not the queuing part of the object.
This PR begins by switching `isinstance` checks and changing dispatch behaviour in some transforms.
With this PR, we will now be able to do things like:
```pycon
>>> qs = qml.tape.QuantumScript([qml.S(0), qml.T(0)])
>>> qml.matrix(qs)
array([[ 1.        +0.j        ,  0.        +0.j        ],
[ 0.        +0.j        , -0.70710678+0.70710678j]])
>>> qs2 = qml.tape.QuantumScript(measurements=[qml.expval(qml.PauliX(0) + qml.PauliY(0))])
>>> scripts, fn = qml.transforms.hamiltonian_expand(qs2)
>>> scripts[0].circuit, scripts[1].circuit
([expval(PauliX(wires=[0]))], [expval(PauliY(wires=[0]))])
```
=> Better integrating `QuantumScript`

pennylane/data/__init__.py, pennylane/data/data_manager.py, pennylane/data/dataset.py, tests/data/test_dataset.py, tests/data/test_dataset_access.py
Two notes for reviewers:
- I made a comment below, please lmk what you think
- I think this PR is easiest to review one commit at a time, because each commit does one logical thing. You can filter by commit in the "Files changed" tab. I'd also shift-click the first two to view them together to make the diff nicer.
Does a handful of things:
- Lazy init, non-lazy `__getattribute__` (requires care with standard vs. non-standard)
- `from_dataset` turned into copy constructor
- Better `list_datasets()` docstring example
- Rename `data_type` to `data_name`
- Description type check/format
- `layout` can be an iterable, so (1,2) -> "1x2"
- `bondlength` can be a number, so `0.46` is accepted, as well as `"0.46"`. `1` will become `"1.0"`
- Everything else must be a string
- Provide a separate …
=> Data manager fixups

doc/releases/changelog-dev.md, pennylane/ops/op_math/exp.py, pennylane/ops/qubit/parametric_ops.py, tests/ops/op_math/test_exp.py, tests/ops/qubit/test_parametric_ops.py
Right now, the `Exp` class doesn't have a decomposition.
This PR decomposes `Exp` into `PauliRot` if:
* The coefficient is purely imaginary
* The base operator is a pauli word
For example:
```pycon
>>> op = qml.exp(qml.PauliX(0) @ qml.PauliY(1), -0.5j * 1.234)
>>> op.decomposition()
[PauliRot(-1.234, XY, wires=[0, 1])]
```
It also updates the repr method for `PauliRot`, because it was missing crucial information.
=> Decompose `Exp` into `PauliRot` if possible

doc/releases/changelog-dev.md, pennylane/devices/default_qubit.py, tests/devices/test_default_qubit.py
**Context:**
See #3228. default.qubit wouldn't ensure Hamiltonian wires existed on the device before measuring the expectation value of it.
Try to map the Hamiltonian's wires to the device's wires on `default.qubit` when `shots=None` upon measuring expval.
**Benefits:**
`expval` will raise a WireError as expected when the device doesn't have the wires expected by the Hamiltonian.
N/A
Fixes #3228
=> map_wires in expval(H) to ensure device wires used

doc/releases/changelog-0.27.0.md, pennylane/ops/qubit/observables.py, tests/ops/functions/test_eigvals.py, tests/ops/qubit/test_sparse.py
Fixes #3272 .
Currently, `SparseHamiltonian` does not perform any validation on the shape of the matrix.  This leads to confusing errors downstream if the shape does not match the wires.
This PR just adds a simple check on the shape, and raises an error if the sparse matrix is not the right shape.
This is a rapid check, so I do not see any problems adding it in.
=> Add shape validation to `SparseHamiltonian`

doc/releases/changelog-0.27.0.md, pennylane/interfaces/jax_jit.py, tests/interfaces/test_jax.py
* Updates the changelog item to use double-precision;
* Lowers the required version of JAX lib because there's no 0.3.17 version available version on PyPi.
=> Fix pure callback changelog & JAX version validation

pennylane/pauli/pauli_arithmetic.py, tests/pauli/test_pauli_arithmetic.py
Update the display of an empty PauliWord from `()` to `I`, as it functionally behaves like Identity.
=> Make the Pauli display nice

pennylane/gradients/parameter_shift.py, tests/returntypes/test_parameter_shift_new.py
The following fails:
```py
qml.enable_return()
dev = qml.device("default.qubit", wires=2)
def circuit(x):
qml.RX(x, 0)
return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliX(1))
recipes = ([[1, 1, 0], [-1e5, 1, -1e5]],)
x = pnp.array(0.4, requires_grad=True)
circuit(x)
tapes, fn = qml.gradients.param_shift(circuit.tape, gradient_recipes=recipes)
print( fn(qml.execute(tapes, dev, None)))
```
The scope should be:
* Tapes with multiple returned measurements together with;
* Gradient recipes that contain unshifted terms.
**Changes**
The issue is because `r0` is not being indexed in an aux function here:
https://github.com/PennyLaneAI/pennylane/blob/21b35b6ad368729b0cb9a10071af8ca4c518538c/pennylane/gradients/parameter_shift.py#L169
=> [BUG] [Return-types] Fix param shift recipe

doc/introduction/data.rst, doc/releases/changelog-0.27.0.md, pennylane/data/data_manager.py, pennylane/data/dataset.py, tests/data/test_dataset.py
**Context:**
The Dataset class is the core of the new data module being introduced in 0.27. While it is functional and complete, the repr is rather ugly. It will be heavily featured in documentation, so it should be improved before we announce this new offering.
Introduce a `__repr__` for the Dataset class. Below are example standard and non-standard reprs:
```pycon
>>> qml.data.load('qchem', molname='H2', basis='STO-3G', bondlength=0.74)[0]
<Dataset = data name: qchem, description: H2/STO-3G/0.74, attributes: ['molecule', 'hamiltonian', ...]>
>>> qml.data.Dataset(foo=3, bar=4, baz=5)
<Dataset = attributes: ['foo', 'bar', ...]>
```
**Benefits:**
- The return value from `qml.data.load` and `qml.data.Dataset` will be beautiful
- The docs/demos for the datasets …
=> Introduce a Dataset repr

doc/releases/changelog-0.27.0.md, pennylane/math/utils.py
Just a small fix. I think this is actually not new to `v0.27` but `get_interface` has been added extensively in https://github.com/PennyLaneAI/pennylane/pull/3136 so it is worth highlighting this behavior.
=> fix get interface doc string

tests/returntypes/test_jax_new.py, tests/returntypes/test_parameter_shift_shot_vec_new.py
Found a `print` statement in https://github.com/PennyLaneAI/pennylane/pull/3267/ that looks like a debugging relic.
Checked through search and found more print statements from new return types project, also fixed here.
=> remove debugging prints in tests

pennylane/pauli/pauli_arithmetic.py
Adds missing punctuation to docstring examples
Also adds output example and slight change to docstring to clarify what PauliWord and PauliSentence do.
=> pauli_arithmetic docstring edits

pennylane/pauli/utils.py
**Context:**
is_pauli_word sounds like it checks if something is a Pauli word, but technically it just checks if all the operators are Pauli operators or Identity. 
Add a note in the docstring mentioning that this doesn't do what it sounds like it does.
#3334
=> update is_pauli_word docstring

pennylane/ops/op_math/exp.py, tests/ops/op_math/test_exp.py
**Context:**
The `has_decomposition` and `decomposition` methods to decompose an `Exp` into `PauliRot` returns incorrect results if the base operator for the `Exp` is a Tensor object with multiple Pauli operators acting on the same wire, i.e. `qml.PauliX(0) @ qml.PauliY(0)`.
The `has_decomposition` method now includes a check for overlapping wires if the base observable is a Tensor object. It raises a NotImplementedError if there is overlap in the wires.
=> Pauli rot bug fix

doc/releases/changelog-0.27.0.md, setup.py
This PR merely adds the "Python 3.11" classification to the PennyLane package for the 0.27 release.  Adding CI checks to master will occur in #3276 .  This PR has not yet been merged due to optional requirements that do not have Python 3.11 support yet, like tensorflow, torch at the currently pinned version, and cvxpy. These should not be blockers for adding the classification to the core package.
=> Add python 3.11 classification

doc/releases/changelog-dev.md, pennylane/interfaces/execution.py, tests/interfaces/test_autograd.py, tests/returntypes/test_autograd_new.py
Fixes #3368 .
Currently, device batch transformations occur with the number of shots originally specified on the device, not the number of shots used for the execution.  In the cases where the device has no shots but the execution does, this leads to errors if we are taking the expectation value of a Hamiltonian.
```python
@qml.qnode(qml.device('default.qubit', wires=2), diff_method=None)
def circuit():
return qml.expval(2.0 * qml.PauliX(0))
circuit(shots=20)
```
This quick fix merely overrides the device shots for the duration of `batch_transform`.
This bug highlights the need to:
* Remove the shots specification and move it to some sort of "execution config" data class
* Make device preprocessing depend on the execution config data class
=> batch transform occurs with the correct number of shots

doc/releases/changelog-dev.md, pennylane/ops/functions/matrix.py, tests/ops/functions/test_matrix.py, tests/ops/qubit/test_non_parametric_ops.py
**Context:**
`qml.matrix(op)` would pass for Barrier and WireCut, whereas `op.matrix()` wouldn't. This was because `qml.matrix()` is wrapped with `op_transform` so it tries to expand a tape containing just that operation, and the expansion is validation (they have trivial decompositions).
`qml.matrix()` now fails if `op.matrix()` fails, and the subsequent effort at tape expansion results in a tape with no ~operations~ wires.
**Benefits:**
`qml.matrix(op)` and `op.matrix()` are now consistent. `qml.matrix()` works as expected.
Maybe some operator without a matrix shouldn't fail? I think there are no drawbacks.
Fixes #3330
=> qml.matrix with tape expansion should fail if there are no operators

doc/releases/changelog-dev.md, pennylane/templates/embeddings/amplitude.py, tests/templates/test_embeddings/test_amplitude.py
**Context:**
The `AmplitudeEmbedding` template has an optional argument `pad_with` that pads the input features if the shape is smaller than the dimension of the feature space. Passing a value for this argument is incompatible with some interfaces if the input features  is an interface-specific tensor.
Allow passing in `pad_with` argument even if `features` is a tensor. Add tests for `pad_with` for all interfaces.
https://github.com/PennyLaneAI/pennylane/issues/3379
=> Support `pad_with` argument in `AmplitudeEmbedding` for all interfaces

doc/releases/changelog-dev.md, pennylane/tape/tape.py, tests/qchem/test_structure.py, tests/tape/test_tape.py
The _obs_sharing_wires value is not updated after expansion in the original, therefore rotations are added each you call expansion.
**Example:**
```
with QuantumTape() as tape:
qml.RX(0.1, wires=[0])
qml.RY(0.2, wires=[1])
qml.expval(qml.PauliZ(0) @ qml.PauliX(1))
qml.expval(qml.PauliZ(0))
expand_tape = tape.expand()
print(tape.circuit)
expand_tape = tape.expand()
print(tape.circuit)
```
Before changes:
```
[RX(0.1, wires=[0]), RY(0.2, wires=[1]), CNOT(wires=[0, 1]), RY(-1.5707963267948966, wires=[1]), expval(PauliZ(wires=[0]) @ PauliZ(wires=[1])), expval(PauliZ(wires=[0]))]
[RX(0.1, wires=[0]), RY(0.2, wires=[1]), CNOT(wires=[0, 1]), RY(-1.5707963267948966, wires=[1]), RY(-1.5707963267948966, wires=[1]), expval(PauliZ(wires=[0]) @ …
```
=> Fix non updated _obs_sharing_wires

doc/releases/changelog-dev.md, pennylane/ops/op_math/controlled_class.py
Remove private `_wires` setter. Use `map_wires` instead.
This fix assumes that the `Controlled` class is immutable: two instances that are instantiated with the same arguments will always be equal.
=> Fix Contolled.map_wires

doc/releases/changelog-dev.md, pennylane/operation.py, pennylane/ops/identity.py, pennylane/ops/qubit/matrix_ops.py, pennylane/ops/qubit/non_parametric_ops.py, pennylane/ops/qubit/observables.py, pennylane/ops/qubit/parametric_ops.py, pennylane/ops/qutrit/non_parametric_ops.py, pennylane/ops/qutrit/observables.py
In https://github.com/PennyLaneAI/pennylane/pull/2981/ it was found, that some documentation notations are incorrect.
Further occurrences mentioning what `diagonalizing_gates` implements were found.
This PR searched for:
> If :attr:diagonalizing_gates are specified and implement a unitary :math:`U`
And replaced by
> If :attr:`diagonalizing_gates` are specified and implement a unitary :math:`U^{dagger}`
One further occurrence was found manually.
=> Fix more mentions of `U` to be `U^{dagger}` for diagonalizing gates

doc/development/deprecations.rst, doc/releases/changelog-dev.md, pennylane/transforms/measurement_grouping.py, tests/transforms/test_measurement_grouping.py
Deprecate `qml.transforms.measurement_grouping` in favour of `qml.transforms.hamiltonian_expand`
=> Deprecate transforms.measurement_grouping

doc/development/plugins.rst, doc/releases/changelog-dev.md, pennylane/_qubit_device.py, tests/test_qubit_device.py, tests/test_qutrit_device.py
From:
```python
def statistics(self, observables, shot_range=None, bin_size=None, circuit=None):
```
To:
```python
def statistics(self, circuit: QuantumScript, shot_range=None, bin_size=None):
```
For this breaking change, we will need to update the following plugins:
1. `pennylane-lightning-gpu`: https://github.com/PennyLaneAI/pennylane-lightning-gpu/pull/78
2. `pennylane-qiskit`: https://github.com/PennyLaneAI/pennylane-qiskit/pull/236
3. `pennylane-honeywell`: https://github.com/PennyLaneAI/pennylane-honeywell/pull/35
**Note:** `observables` can still be accessed inside the `statistics` method by using `circuit.observables`.
=> Change `QubitDevice.statistics` signature

doc/development/deprecations.rst, doc/releases/changelog-dev.md, pennylane/operation.py, pennylane/ops/op_math/adjoint_class.py, tests/ops/op_math/test_adjoint_op.py, tests/test_operation.py
Remove `qml.Operation.get_parameter_shift` (deprecated in v0.22)
=> Remove get paramter shift

doc/releases/changelog-dev.md, pennylane/_qubit_device.py, pennylane/measurements/counts.py, pennylane/measurements/sample.py, tests/measurements/test_sample.py
**Context:**
Previously `qml.sample` produced incorrect results when shot vectors are used:
```python3
dev = qml.device("default.qubit", wires=2, shots=(5, 10))
def circuit():
qml.Hadamard(wires=0)
return qml.sample(wires=[0, 1])
```
```
>>> circuit()
(tensor([[0, 0],
[0, 1],
[0, 1],
[0, 1],
[0, 1]], dtype=int64, requires_grad=True), tensor([[1, 0],
[1, 0],
[1, 0],
[1, 0],
[0, 0],
[0, 0],
[1, 0],
[1, 0],
[1, 1],
[1, 1]], dtype=int64, requires_grad=True))
```
The reshape logic in the qubit device was missing a transpose. This PR adds the transpose. Also fixed a broken test that would have failed on master.
https://github.com/PennyLaneAI/pennylane/issues/3412
=> Fix `qml.sample` for shot vectors

doc/development/deprecations.rst, pennylane/__init__.py
**Context:**
Grouping module is now deprecated, we used to raise a `DeprecationWarning`, but this gets ignored by default, resulting in no error message being displayed. 
Raise `UserWarning` instead so that it is raised correctly.
=> Update grouping warning from `DeprecationWarning` to `UserWarning`

doc/releases/changelog-dev.md, pennylane/_device.py, tests/test_device.py
=> Allow devices to specify if they want to disregard grouping

doc/development/deprecations.rst, doc/releases/changelog-dev.md, pennylane/transforms/qfunc_transforms.py, tests/transforms/test_qfunc_transform.py
**Context:**
It's not used anywhere in the codebase anymore, and we don't want any new code to use it
Add a deprecation warning when `make_tape` is used.
**Benefits:**
People will know to use `make_qscript` instead.
N/A
=> deprecate make_tape

pennylane/operation.py, pennylane/ops/op_math/exp.py, pennylane/ops/qubit/hamiltonian.py, tests/ops/op_math/test_exp.py, tests/test_operation.py
We had a couple of problems to fix to get `Evolution` working with parameter shift gradients.
First, the shape of `RX.parameter_frequencies` is different from that in the default `Operator.parameter_frequencies` definition.  This PR adds a layer of nesting to `Operator.parameter_frequencies` so it matches that returned by classes like `RX`.
Second, now `Hamiltonian.simplify` returns an instance of itself and adheres to the stated interface for that method. This was causing problems with decomposing the exponential operator. I'm unsure if it was affecting the gradients, but it was giving me errors.
As for changes to `Exp`, it now has `Exp.__copy__` and `Exp.hash`.
I also make `coeff` and `param` properties dynamically inferred from the data.
@lillian542 Feel free to merge this into your PR …
=> Get parameter shift gradients with the new `Evolution` operator

doc/code/qml.rst, doc/code/qml_data.rst, doc/code/qml_drawer.rst, doc/code/qml_fourier.rst, doc/code/qml_kernels.rst, doc/code/qml_math.rst, doc/code/qml_operation.rst, doc/code/qml_pauli.rst, doc/code/qml_qaoa.rst, doc/code/qml_qchem.rst, doc/code/qml_qinfo.rst, doc/code/qml_queuing.rst, doc/code/qml_resource.rst, doc/code/qml_tape.rst, doc/code/qml_utils.rst, doc/code/qml_wires.rst, doc/conf.py
1. Add `automodapi_inheritance_diagram = False` sphinx variable to avoid calling `:no-inheritance-diagram:` in every doc page.
2. Remove `:no-inheritance-diagram:` where used and add `:inheritance-diagram:` where needed.
3. Remove the inheritance diagram from `qml.rst` because it is incomprehensible: [see here](https://docs.pennylane.ai/en/stable/code/qml.html#class-inheritance-diagram)
=> Sphinx: do NOT add an inheritance diagram by default

pennylane/gradients/__init__.py, pennylane/gradients/finite_difference.py, pennylane/gradients/parameter_shift.py, pennylane/ops/op_math/sprod.py, pennylane/ops/op_math/sum.py, tests/ops/op_math/test_sprod.py, tests/ops/op_math/test_sum.py
**Context:**
Examples in docstrings and a couple of tests use `gradient_fn` or `grad_method` kwarg in the qnode. These don't work, the kwarg the qnode expects is `diff_method`.
Changed to `diff_method`.
**Benefits:**
Not inaccurate.
N/A
#3499
=> Docs update - change qnode kwarg to diff_method

tests/returntypes/transforms/test_batch_input_new.py, tests/returntypes/transforms/test_batch_params_new.py
**Context:**
Previously, `xfail` markers were used on some transform tests before the PyTorch interface for the new return types was implemented. These markers were not removed when the PR that implemented the interface was merged.
Removed the `xfail` markers for some torch tests. Also updated those tests to remove the stacking, since PyTorch allows returning and differentiating tuples.
=> [Return-types] Remove `xfail` markers for torch tests

doc/releases/changelog-dev.md, pennylane/data/data_manager.py, pennylane/data/dataset.py
**Context:**
Windows uses `\` as a path separator. Unfortunately, the datasets module matches local paths to S3 bucket paths and doesn't expect local paths to use anything other than `/`.
Convert windows paths to unix-like paths before sending requests to S3.
**Benefits:**
The dataset module will work as expected on Windows
N/A (well.. encouraging people to continue development on Windows is a grey area but I digress 😄 )
N/A
=> add support for windows filepaths in dataset module

doc/releases/changelog-dev.md, pennylane/_qubit_device.py, pennylane/devices/tests/test_measurements.py, pennylane/measurements/classical_shadow.py, pennylane/measurements/counts.py, pennylane/measurements/expval.py, pennylane/measurements/measurements.py, pennylane/measurements/mutual_info.py, pennylane/measurements/probs.py, pennylane/measurements/sample.py, pennylane/measurements/state.py, pennylane/measurements/var.py, pennylane/measurements/vn_entropy.py, tests/measurements/test_measurements.py
- Remove `method_name` attribute from `MeasurementProcess` (it was added in this release cycle).
- Add `measurement_map` attribute to `QubitDevice`.
Devices can now define the name of the method used to override any measurement process:
```python
from pennylane.devices import DefaultQubit
from pennylane.measurements import SampleMP
class NewDevice(DefaultQubit):
def __init__(self, shots, wires):
super().__init__(shots=shots, wires=wires)
self.measurement_map[SampleMP] = "sample_measurement"
def sample_measurement(self, measurement, shot_range=None, bin_size=None):
return 2
dev = NewDevice(wires=2, shots=1000)
def circuit():
return qml.sample()
print(circuit())
```
Returns
```
2
```
=> Add `measurement_map` attribute to `QubitDevice`

doc/releases/changelog-dev.md, pennylane/tape/operation_recorder.py
**Context:**
Started this in #3467, moved to its own PR. Part of an ongoing effort to stop using `QuantumTape` in pennylane.
`OperationRecorder` used to inherit from `QuantumTape`. This PR updates it to mimic `QuantumTape` and inherit from `AnnotatedQueue` + `QuantumScript`.
**Benefits:**
We'll be able to move forward with the replacement of the QuantumTape class.
N/A
N/A
=> Remove QuantumTape from OperationRecorder

doc/introduction/data.rst, doc/releases/changelog-dev.md, pennylane/data/data_manager.py
**Context:**
Pickled files can execute malicious code while unpickling. We use the pickle module to handle storage and compression/decompression of PennyLane datasets and plan to allow users to upload their own data in the future. Therefore it is important to give a warning about the potential for malicious code.
Added a warning to the documentation for `qml.data.load`.
**Benefits:**
Users become aware of the dangers of pickled files and are more careful in the future when user-uploaded datasets become available.
Users think that downloading a dataset from PennyLane is unsafe. This can be solved by transitioning to another form of storage and compression in the future.
=> Add pickle warning to datasets

pennylane/devices/tests/test_measurements.py
Stop using `samples` and `state` in tests to make tests more generic.
Add operations to all circuits (cirq crashes if circuit has no operations).
Skip test if shots is not None.
=> Fix plugin test matrix

doc/development/adding_operators.rst, doc/development/guide/architecture.rst, doc/introduction/interfaces/jax.rst, doc/releases/changelog-0.18.0.md, doc/releases/changelog-0.21.0.md, doc/releases/changelog-0.22.0.md, doc/releases/changelog-0.23.0.md, doc/releases/changelog-0.24.0.md, doc/releases/changelog-0.27.0.md, doc/releases/changelog-0.28.0.md, pennylane/gradients/finite_difference.py, pennylane/gradients/gradient_transform.py, pennylane/gradients/hessian_transform.py, pennylane/gradients/jvp.py, pennylane/gradients/parameter_shift.py, pennylane/interfaces/jax.py, pennylane/interfaces/jax_jit.py, pennylane/math/multi_dispatch.py, pennylane/math/utils.py, pennylane/qnode.py, pennylane/return_types.py, pennylane/transforms/decompositions/two_qubit_unitary.py, tests/interfaces/test_jax_qnode.py, tests/math/test_functions.py, tests/returntypes/jax/test_jax_jit_qnode_new.py, tests/returntypes/jax/test_jax_qnode_new.py, tests/tape/test_unwrap.py
JAX v0.4.1 was released, changing some behaviours around using `DeviceArray` and moving towards the usage of `jax.Array` as a unified array (https://github.com/google/jax/releases/tag/jax-v0.4.1).
This PR moves towards using `jax.Array` everywhere.
Note that the earlier `jax==0.3.24` and `jaxlib==0.3.24` should also be compatible with the changes.
=> Fix test failures due to `jax.Array` (JAX `v0.4.1`)

doc/releases/changelog-0.28.0.md, pennylane/_device.py, pennylane/_qubit_device.py, pennylane/devices/tests/test_measurements.py, pennylane/measurements/__init__.py, pennylane/measurements/classical_shadow.py, pennylane/measurements/measurements.py, pennylane/ops/functions/map_wires.py, pennylane/ops/functions/simplify.py, pennylane/qnode.py, pennylane/shadows/transforms.py, pennylane/tape/tape.py, pennylane/transforms/adjoint_metric_tensor.py, pennylane/transforms/batch_transform.py, pennylane/transforms/commutation_dag.py, pennylane/transforms/condition.py, pennylane/transforms/hamiltonian_expand.py, pennylane/transforms/insert_ops.py, pennylane/transforms/metric_tensor.py, pennylane/transforms/qcut/tapes.py, pennylane/transforms/qfunc_transforms.py, pennylane/transforms/zx/converter.py, tests/measurements/test_measurements.py, tests/transforms/test_zx.py
we're planning to rename QuantumScript back to QuantumTape in two releases (first we need to deprecate `with QuantumTape()`), so we shouldn't start advertising QuantumScript only for it to disappear in two releases.
Do I need a changelog entry for this?
=> change qscript to tape in public facing content

doc/development/deprecations.rst, pennylane/_device.py, pennylane/transforms/__init__.py, pennylane/transforms/batch_transform.py, pennylane/transforms/measurement_grouping.py, pennylane/transforms/split_tape.py, tests/interfaces/test_autograd_qnode.py, tests/interfaces/test_jax_qnode.py, tests/interfaces/test_tensorflow_qnode.py, tests/interfaces/test_torch_qnode.py, tests/returntypes/autograd/test_autograd_qnode_new.py, tests/returntypes/jax/test_jax_jit_qnode_new.py, tests/returntypes/jax/test_jax_qnode_new.py, tests/returntypes/tf/test_tensorflow_qnode_new.py, tests/returntypes/torch/test_torch_qnode_new.py, tests/test_qnode.py, tests/transforms/test_batch_transform.py, tests/transforms/test_split_tape.py
I'm righting my wrongs that are coming up in #3264
=> put back QuantumTape naming in split_qscript

pennylane/ops/functions/equal.py, pennylane/pauli/pauli_arithmetic.py
Small fixes to links in the PauliWord methods
The hyperlinks dont work. Is this behavior new?
=> [Docs fix Pauli words]

pennylane/operation.py, pennylane/ops/identity.py, pennylane/ops/qubit/matrix_ops.py, pennylane/ops/qubit/non_parametric_ops.py, pennylane/ops/qubit/observables.py, pennylane/ops/qubit/parametric_ops.py, pennylane/ops/qutrit/non_parametric_ops.py, pennylane/ops/qutrit/observables.py
This PR patches the documentation change introduced in #3409 . It switches `U^{dagger}` to `U^{\dagger}`
=> Doc fix: add backslash to `\dagger`

pennylane/interfaces/jax_jit_tuple.py, pennylane/return_types.py
* Creates a new `JAX Usage Details` section;
* Moves the existing JAX examples to the new section;
* Renames existing `Usage Details for <ML framework>` section titles to `<ML framework> Usage Details`;
* Adds the gotchas on JAX Hessian.
=> Add JAX Hessian gotcha to `enable_return` docs

pennylane/measurements/expval.py, pennylane/measurements/measurements.py, pennylane/measurements/var.py, tests/measurements/test_expval.py, tests/measurements/test_var.py
- Remove useless usage of `_permute_wires` (`qml.probs` already does permutation).
- Remove `_permute_wires` from `MP`.
=> Remove `MeasurementProcess._permute_wires` method.

doc/development/deprecations.rst, pennylane/_qubit_device.py, tests/test_qubit_device.py
User warning warns not to pass a list to `dev.statistics`, but instead to pass a `QuantumTape`.
Deprecations document warns users not to use the `observables` kwarg, but instead to use `circuit`.
This PR updates the user warning to also warn about the deprecation of the `observables` kwarg, and the `deprecations.rst` file to also mention deprecation of passing a list instead of a tape.
=> Statistics deprecation

.github/workflows/upload.yml
**Context:**
Upload action failed to trigger for 0.28 release of PL due to another inconsistency between the .yml action files. Here we unify torch version between test and upload yml actions.
=> Update `upload.yml` to use same version of Torch as tests

doc/releases/changelog-dev.md, pennylane/pauli/pauli_arithmetic.py, tests/pauli/test_pauli_arithmetic.py
By default, unpickling a dictionary calls `__setitem__`.
```python
import pickle
op = qml.PauliX(0)
pic = pickle.dumps(op)
pickle.loads(pic)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [4], line 1
----> 1 pickle.loads(pic)
File pennylane/pennylane/pauli/pauli_arithmetic.py:130, in PauliWord.__setitem__(self, key, item)
128 def __setitem__(self, key, item):
129     """Restrict setting items after instantiation."""
--> 130     raise TypeError("PauliWord object does not support assignment")
TypeError: PauliWord object does not support assignment
```
To avoid this, `PauliWord` will now define `__reduce__()`.  See …
=> Make Pauli Word pickleable

doc/releases/changelog-dev.md, pennylane/pauli/pauli_arithmetic.py, tests/pauli/test_pauli_arithmetic.py
Avoid using `SProd` when `coeff=1`
=> Improve `PauliSentence.operation()` method

doc/releases/changelog-dev.md, pennylane/transforms/zx/converter.py, tests/transforms/test_zx.py
**Context:**
The wires for the Y decomposition was always assumed to be 0.
It changes the wires to be `op.wires`
=> Fix wires for PauliY and RY in the `to_zx` function

doc/releases/changelog-dev.md, requirements-ci.txt, setup.py
We are currently getting errors in circuit cutting tests, see https://github.com/PennyLaneAI/pennylane/actions/runs/3872906008/jobs/6602308449
This PR attempts to fix that problem by pinning `networkx` to be less than 3.0.
=> Pin networkx < 3.0

doc/releases/changelog-dev.md, pennylane/ops/channel.py, tests/ops/test_channel_ops.py
**Context:**
The non-unitary channels in PennyLane have some incompatibilities with the interfaces.
This PR fixes differentiability of the Kraus matrices of all channels, except for `QubitChannel` and `ThermalRelaxationChannel`.
It also introduces tests for all fixed channels.
**Benefits:**
Differentiability support.
Code complexity and performance reductions, as usual for interface support.
Fixes #3608 
Blocks newly added tests in #3584
=> Support various channels with interfaces

doc/releases/changelog-dev.md, pennylane/operation.py, pennylane/ops/qubit/hamiltonian.py, tests/ops/qubit/test_hamiltonian.py, tests/test_operation.py, tests/tests_passing_pylint.txt
**Context:**
If we have two objects with both the `__add__` and `__radd__` method, when summing A + B , `B.__radd__` is ONLY called if `A.__add__` returns `NotImplemented`
Return `NotImplemented` in all dunder methods. This allows for `B.__radd__` to be called.
Fixes https://github.com/PennyLaneAI/pennylane/issues/3627
=> Return `NotImplemented` in dunder methods

doc/releases/changelog-dev.md, pennylane/operation.py, tests/test_operation.py
Set `Tensor._batch_size` to None in `__init__` to avoid getting an error when calling this attribute.
=> Set `Tensor._batch_size` to None

doc/releases/changelog-dev.md, pennylane/ops/qutrit/observables.py, tests/ops/qutrit/test_qutrit_observables.py, tests/test_operation.py, tests/tests_passing_pylint.txt
**Context:**
Currently, when initializing GellMann operators, the representation that is displayed does not include the index of the GellMann operator, so it is unclear what operation is being performed.  
```
coeffs = [2, f1]
obs = [qml.GellMann(wires=0, index=1), qml.GellMann(wires=0, index=2)]
H = ParametrizedHamiltonian(coeffs, obs)
H(2, 4)
>>>(2*(GellMann(wires=[0]))) + (10*(GellMann(wires=[0])))
```
A `__repr__` method is added to specify how to display the operators. The behaviour is now:
```
H(2, 4)
>>>(2*(GellMann1(wires=[0]))) + (10*(GellMann2(wires=[0])))
```
=> More specific representation for GellMann ops

.github/workflows/docker.yml, .github/workflows/format.yml, .github/workflows/pylint.yml, .github/workflows/tests.yml, .github/workflows/upload.yml
Doing the same as @AmintorDusko did in PennyLaneAI/pennylane-lightning#345.
If you push to a branch twice in quick succession, the re-ran CI flows are auto-cancelled likely due to a bug. This doesn't happen in lightning after the version bump, so I'm doing the same here.
=> bump cancel-workflow-action to latest version

doc/releases/changelog-dev.md, pennylane/operation.py, tests/test_operation.py
**Context:**
The `_batch_size` attribute of `Tensor` was not copied properly when using `Tensor.map_wires` or `Tensor.__copy__`
Change that.
**Benefits:**
The following works:
```pycon
>>> op = copy.copy(qml.PauliZ(0) @ qml.PauliX(1))
>>> op.batch_size
None
```
N/A
#3660
=> Fix `_batch_size` of copies and wire mappings of `Tensor`

pennylane/tape/qscript.py, tests/tape/test_qscript.py
**Context:**
Following this PR https://github.com/PennyLaneAI/pennylane/pull/3667
This PR adds a warning for the `get_operation` tape method, it also let the user to turn on the new behavior.
**Benefits:**
It allows to integrate the changes of `_par_info`.
-
=> Add warning for `get_operation`

doc/releases/changelog-dev.md, pennylane/pauli/conversion.py, pennylane/pauli/utils.py, tests/pauli/test_pauli_utils.py
- Add support for `Prod`, `SProd` and `Hamiltonian` in `is_pauli_word` and `pauli_word_to_string`.
- Return `False` if given a `Hamiltonian` with more than one term.
=> Improve pauli utils

.github/workflows/tests.yml
Some return type tests are run twice, this PR addresses this issue by adding `not return` marker.
=> Remove return type tests from the core tests

doc/releases/changelog-dev.md, pennylane/ops/functions/dot.py, pennylane/pulse/parametrized_hamiltonian.py, tests/ops/functions/test_dot.py
The use of `qml.dot` inside `ParametrizedHamiltonian` adds the restriction that `qml.dot` must be jittable.
This restricts us to improve this function by adding, for example, conditional results.
=> Stop using `qml.dot` inside `ParametrizedHamiltonian`

doc/releases/changelog-dev.md, pennylane/operation.py, tests/test_operation.py
- Set `self._pauli_rep` to `None`. (Fixes https://github.com/PennyLaneAI/pennylane/issues/3709)
- Add `Tensor.data` setter: some `map_wires` methods (such as `Composite.map_wires`) use data setters.
=> Improve `Tensor` class

doc/introduction/measurements.rst
`qml.purity` was missing from the quickstart.
=> add purity to quickstart for measurements

tests/measurements/test_classical_shadow.py
This test was marked as flaky in #3710, but it was flaky because it depends on some randomness. Those tests should fix a seed, so I'm doing that in this PR. I just picked 42 because it's in a whole bunch of other tests (and might perhaps involve some deeper meaning??) and this test passes with it.
=> fix a seed instead of setting test as flaky

doc/releases/changelog-dev.md, pennylane/gradients/parameter_shift.py, tests/gradients/test_parameter_shift.py, tests/returntypes/paramshift/test_parameter_shift_new.py
**Context:**
When computing the derivative of a variance using a gradient recipe with unshifted terms, the unshifted tape is produced and evaluated twice.
See #3178 
The post-processing function of the expectation value parameter-shift is given an attribute that indicates whether it expects the first result in the results list passed to it to be from the unshifted tape. If this is the case, the variance parameter-shift logic does not add the unshifted expectation value tape $\langle H\rangle$ that is required in the chain rule
$\frac{\partial}{\partial \theta} Var[H] = \frac{\partial}{\partial \theta} \langle H^2\rangle - 2 \langle H\rangle \frac{\partial}{\partial \theta} \langle H\rangle$
**Benefits:**
Saves quantum resources.
N/A …
=> Reuse unshifted evaluation when computing parameter shift derivatives of variances

doc/releases/changelog-dev.md, pennylane/kernels/utils.py, tests/kernels/test_kernels.py, tests/tests_passing_pylint.txt
**Context:**
There are two utility functions in `pennylane/kernels/utils.py`: `square_kernel_matrix` and `kernel_matrix`. They are written for Numpy, and partially for Autograd.
This PR makes the two functions fully compatible with Autograd, JAX, Tensorflow and PyTorch.
In addition it adds batching support to the functions, allowing the kernel to return a one-dimensional instead of a scalar output.
**Benefits:**
Differentiation/interface support. One can now make use of shot vector execution together with kernels.
usual overhead of `qml.math`.
implements #2492
=> Support autodiff and batching in kernel matrix functions

pennylane/qnode.py, tests/devices/test_lightning_qubit.py, tests/test_qnode.py
With the "auto" interface raises an error at initialization of QNode if the device does not support backprop.
It allows checks for all diff_method expect `best` and `backprop` as they require the interface.
=> Add check for auto interface and device that do not support backprop

doc/releases/changelog-dev.md, pennylane/drawer/tape_mpl.py, pennylane/drawer/tape_text.py, pennylane/drawer/utils.py, tests/drawer/test_drawer_utils.py, tests/drawer/test_tape_mpl.py, tests/drawer/test_tape_text.py
**Context:** When drawing operations where controls are nested (e.g., a controlled controlled operation, or nested use of `qml.ctrl`, not all the control wires were identified as such, and would be drawn using the label of the operation being applied under the control.
**Description of the Change:** Updates the tape text drawer to handle the special case of controlled operations when drawing
**Benefits:** Tapes are now drawn correctly :tada:
**Possible Drawbacks:** Matplotlib case was also affected; have visually inspected that the results are now correct, but not sure how to write the tests.
**Related GitHub Issues:** #3702
=> Fix bug related to labeling of nested controlled operations in drawer

.github/workflows/tests.yml
**Context:**
Jax 0.4.4 breaks the default qubit Jax device because some functions became abstract: https://github.com/google/jax/discussions/14548
Pin Jax temporarly in the test suit to `0.4.3`
=> Pin jax to `0.4.3`

pennylane/devices/default_qubit_jax.py, pennylane/pulse/jax_utils.py, pennylane/pulse/parametrized_evolution.py, pennylane/pulse/parametrized_hamiltonian_pytree.py, tests/pulse/test_parametrized_hamiltonian_pytree.py
Copied over the code from https://github.com/PennyLaneAI/pennylane/pull/3763
This PR adds a jax pytree version of a `ParametrizedHamiltonian`, where the `dot` computation is delayed until the hamiltonian is multiplied with another matrix. This PR introduces a huge performance boost when simulating pulse programs.
=> Add pytree version of `ParametrizedHamiltonian`

doc/development/deprecations.rst, doc/releases/changelog-0.29.0.md, pennylane/ops/op_math/evolution.py, pennylane/optimize/lie_algebra.py, pennylane/qaoa/layers.py, pennylane/templates/subroutines/approx_time_evolution.py, pennylane/templates/subroutines/commuting_evolution.py, tests/ops/op_math/test_evolution.py, tests/templates/test_subroutines/test_commuting_evolution.py, tests/test_qaoa.py
`qml.evolve` is not at feature parity with `ApproxTimeEvolution` and should not have been replaced (Two demos are failing)
=> Undeprecate `ApproxTimeEvolution`

doc/releases/changelog-0.29.0.md, pennylane/math/quantum.py, pennylane/ops/qubit/parametric_ops.py, pennylane/qnode.py, pennylane/tape/qscript.py, tests/tape/test_qscript.py, tests/test_qnode.py
* Fixed some docs (see changes)
* Fixed issue where calling a qnode within an `AnnotatedQueue` would add diagonalizing gates for the measurements to the queue.
=> Minor fixes for v0.29 release

pennylane/qchem/factorization.py, tests/qchem/test_factorization.py
**Context:** one-body tensor wasn't being copied in `qml.qchem._chemist_transform`, which lead to it being changed (in place) whenever `qml.basis_rotation` was being called.
**Description of the Change:** added `.copy()`, when building the `chemist_one_body_coeffs` when one-body tensors are provided. 
**Benefits:** in-place manipulation of one-body tensors wouldn't happen.
=> Copy one-electron integrals inside `_chemist_transform`

doc/releases/changelog-0.29.0.md, pennylane/math/single_dispatch.py, pennylane/measurements/measurements.py, pennylane/ops/functions/equal.py, pennylane/ops/qubit/observables.py, tests/measurements/test_measurements.py, tests/ops/functions/test_equal.py, tests/ops/qubit/test_observables.py
This PR does some minor fixes on four different things.
1) Using the keyword arguments when comparing observables and eigenvalues of measurements with `qml.equal`
2) Don't request the eigenvalues to compare if the measurements contain observables in `qml.equal`.  We don't want to calculate the eigenvalues of large observables if we don't have to
3) Don't cast the input to `qml.Hermitian` with `qml.math.asarray` unless the input is a list.  This was casting autograd arrays to numpy arrays, potentially losing trainability information.
4) Include the manual eigenvalues `_eigvals` in the representation of a Measurement process when relevant.
=> Fix equal for measurements with observables, measurement process repr, Hermitian casting fix

pennylane/transforms/sign_expand/sign_expand.py
**Context:**
The transform `sign_expand` was not compatible with Qnodes.
This PR makes the `sign_expand` compatible with QNodes and also fix the documentation.
=> Fix sign expand

pennylane/qnode.py, tests/test_qnode.py
**Context:**
We added a warning when the device is switched in QNode call.
This PR removes the warning and set the tracker from the old device to the new device.
**Benefits:**
Tracker is still working.
The device is still switched, creating potential issues.
=> Remove auto warning and swtich tracker

doc/releases/changelog-0.29.0.md
These are some quick final changes before the release.
=> 0.29 changelog updates

doc/introduction/interfaces/numpy.rst, doc/releases/changelog-0.29.0.md
**Context:**
NumPy interface doc …
=> Promote warning about vanilla version of NumPy to RST warning.

pennylane/_qubit_device.py, pennylane/data/dataset.py, pennylane/devices/default_qubit.py, pennylane/devices/default_qubit_jax.py, pennylane/drawer/style.py, pennylane/gradients/parameter_shift.py, pennylane/math/is_independent.py, pennylane/operation.py, pennylane/ops/functions/eigvals.py, pennylane/ops/op_math/controlled.py, pennylane/ops/qubit/matrix_ops.py, pennylane/ops/qubit/parametric_ops.py, pennylane/ops/qutrit/matrix_ops.py, pennylane/qchem/convert.py, pennylane/qchem/molecule.py, pennylane/qnode.py, pennylane/tape/qscript.py, pennylane/templates/embeddings/amplitude.py, pennylane/templates/subroutines/qmc.py, pennylane/transforms/qcut/tapes.py
as title says. the new line in python code is not reflected as a new line or a space in printed strings, so these should be added. I basically searched the regex `[^\s]["']$\n\s*['"][^\s]` (non-whitespace, then a close-quote, then a new line, optional leading white-space, an open-quote, then another non-whitespace character) after seeing it a few times and manually picked out the troublesome ones. Manually "filtered out" the escape sequences and docstrings that matched my search, but there weren't too many.
=> fix strings that wrap around without a space

doc/releases/changelog-0.29.0.md, pennylane/ops/functions/evolve.py, pennylane/pulse/__init__.py, pennylane/pulse/convenience_functions.py, pennylane/pulse/parametrized_evolution.py
Ensures users can execute with finite shots (though differentiation is not supported)
=> Use default.qubit.jax instead of default.qubit

doc/releases/changelog-dev.md, pennylane/data/data_manager.py, tests/data/test_dataset_access.py
**Context:**
I used sets to ensure that we only request files that exist, but this potentially shuffles the order of generated datasets. This is unexpected for the user.
After using sets to determine which datasets actually exist on S3, use a list comprehension to sort the parameter according to the list provided by the user.
**Benefits:**
The ordering of datasets will now be stable in subsequent calls, and have some expected order. Note that it will go in order of parameters saved in S3 metadata, _not_ in order of kwargs provided by user. This means that if a user gives `load(bondlength=[1,2], molname=[y, x])`, it will first sort by `molname` and not by `bondlength` (because `molname` comes before `bondlength` in the stored metadata).
**Possible …
=> ensure provided order of dataset parameters is preserved

doc/releases/changelog-dev.md, pennylane/devices/qubit/apply_operation.py, tests/devices/qubit/test_apply_operation.py
Tensorflow doesn't support slicing on states with more than 8 dimensions. So if we try and run the code:
```
state = create_initial_state(range(10), like='tensorflow')
apply_operation(qml.PauliZ(9), state)
```
We get:
```
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
Cell In[7], line 2
1 state = create_initial_state(range(10), like='tensorflow')
----> 2 apply_operation(qml.PauliZ(9), state)
File Python.framework/Versions/3.10/lib/python3.10/functools.py:889, in singledispatch.<locals>.wrapper(*args, **kw)
885 if not args:
886     raise TypeError(f'{funcname} requires at least '
887                     '1 positional argument')
--> 889 return dispatch(args[0].__class__)(*args, **kw) …
```
=> fix `devices.qubit.apply_operation` with large tf states

pennylane/ops/qubit/parametric_ops.py, tests/ops/qubit/test_parametric_ops.py
**Context:**
Our datasets were created using `pickle` and PennyLane, but an older version of it (ie. before this past Monday). As a result, the parametric ops are namespaced in `pennylane.ops.qubit.parametric_ops`, but that module no longer exists as of #3789. So, unpickling those datasets fails:
```pycon
>>> import pennylane as qml
>>> nh3 = qml.data.load("qchem", molname="NH3", basis="STO-3G", bondlength=1.49)[0]
File "<stdin>", line 1, in <module>
File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/data/data_manager.py", line 272, in load
Dataset(data_name, real_folder, folder.replace(pathsep, "_"), docstring, standard=True)
File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/data/dataset.py", line 148, in __init__ …
```
=> add back parametric_ops file for backwards pickle support

doc/releases/changelog-dev.md, pennylane/ops/qubit/observables.py, tests/ops/qubit/test_sparse.py
Updated `SparseHamiltonian` to use `AnyWires` instead of `AllWires`.
=> `SparseHamiltonian` uses `AnyWires

tests/returntypes/transforms/test_metric_tensor_new.py
Two markers were forgotten in `test_metric_tensor_new`
=> Jax marker in metric tensor tests & fix docker build

doc/releases/changelog-dev.md, pennylane/operation.py, pennylane/ops/op_math/composite.py, pennylane/ops/op_math/symbolicop.py, tests/test_operation.py
Change `Operator.num_wires` from an abstract value to `AnyWires`. This will make adding new operators slightly easier if the operator acts on arbitrary wires.
=> Change `Operator.num_wires` to `AnyWires`

pennylane/devices/default_qubit.py, pennylane/ops/qubit/parametric_ops_multi_qubit.py, tests/devices/qubit/test_sampling.py
**Context:**
The first sampling test would occasionally be off by a bit and fail, so I figured doubling the shots wouldn't hurt. The second one is just slow.
- Increase the number of shots in a test to reduce intermittent failures
- Mark a slow test as slow to help CI (it takes about 12 seconds)
- Reverse the indentation in DefaultQubit.expval because it was bugging me
- Re-do a whitespace fix that was accidentally un-done while splitting parametric_ops.py
**Benefits:**
- The test suite is better
- The code looks cleaner/more consistent
N/A
=> give flaky test more shots; mark slow test as such; linting

pennylane/pulse/parametrized_evolution.py, tests/pulse/test_parametrized_evolution.py
For hardware, we dont need jax as a requirement for `ParametrizedEvolution`
Works in principle but requires the user to use `qml.pulse.ParametrizedEvolution(H, params, t)` instead of `qml.evolve(H)(params, t)`
=> [WIP] Move no-jax-warning in ParametrizedEvolution

pennylane/ops/qubit/parametric_ops_multi_qubit.py, tests/ops/qubit/test_attributes.py, tests/ops/qubit/test_parametric_ops.py
**Context:**
PCPhase gates were designed to be primarily used in the QSVT workflow. Swapping to this convention will allow them to be more directly applied to the workflow without having to keep track of additional global phases.
In the previous implementation of `PCPhase(phi, dim, wires)`, the first `dim` number of entries along the diagonal in the matrix were phase shifted by `e^(i * phi)` while the remaining `2**n - dim` entries of the diagonal were left alone (set to 1). 
This convention is swapped to one in which the remaining `2**n - dim` entries of the diagonal were set to `e^(-i * phi)`. Note, these two conventions only differ by a global phase. 
**Benefits:**
By absorbing the global phase into the representation, we get a cleaner implementation of …
=> Amend PCPhase operator to support RZ convention

doc/releases/changelog-dev.md, pennylane/operation.py
One-line PR!
**Context:**
If someone checks `op.num_wires == 0` and it is `AllWires`, they will get a false positive. We want to avoid this, because they are not logically the same:
```pycon
>>> AllWires == 0
True
```
Now it's -2.
```pycon
>>> AllWires == 0, AllWires == -2
(False, True)
```
**Benefits:**
Although `num_wires = 0` doesn't _really_ make sense, `num_wires = -2` _reaaaally_ doesn't make sense, so there will be no ambiguity.
Maybe some external user manually checks for `0` assuming it means `AllWires`? It's kinda against the spirit of enums, but you never know. I added this in the "Improvements" section of the changelog and not the "Breaking Changes" section to avoid thinking of this as "breaking" for that reason.
=> set AllWires to be non-zero

doc/releases/changelog-dev.md, pennylane/ops/op_math/evolution.py, pennylane/ops/op_math/exp.py, pennylane/ops/op_math/pow.py, pennylane/ops/op_math/sprod.py, pennylane/ops/op_math/symbolicop.py, tests/ops/op_math/test_evolution.py, tests/ops/op_math/test_exp.py, tests/ops/op_math/test_prod.py, tests/ops/op_math/test_sum.py, tests/ops/op_math/test_symbolic_op.py
**Context:**
We want all operator data to be as flat as possible. Also, I had previously done this for Sum and Prod, but didn't test the consequential result which is that their data can now be considered trainable.
1. Move identical data logic from SProd and Exp to the parent class, ScalarSymbolicOp. Note that while doing this, I also made the data for `Exp` flat.
2. Add a custom `data` property definition to Pow so it keeps its old behaviour of treating `z` as a hyperparameter (eg. excluded from `op.data`)
3. The `copy` dunder for Exp was moved to the parent class so its siblings can have it too : )
4. Add tests to ensure Exp, Sum and Prod data is trainable (there was already an SProd test that actually measures the gradient)
**Benefits:**
- It is easier …
=> Update ScalarSymbolicOps and trainability

doc/development/deprecations.rst
See above.
(I also didn't realize `ExpvalCost` had been deprecated since v0.24. Definitely shouldn't get pushed back beyond v0.31)
=> Update ExpvalCost removal to v0.31
