pennylane/optimize/adagrad.py, pennylane/optimize/adam.py, pennylane/optimize/rms_prop.py
Addressing Issue #131 for Adam, Adagrad and RMSprop.
=> Make numerical stability offset user-defined

pennylane/plugins/default_gaussian.py
No description because discussed with @josh146 on slack before.
=> Removed two probably superfluous lines of code

.github/CONTRIBUTING.md, README.rst, doc/research.rst
=> Updated readme and contributing to include link to the Xanadu Quantum Software Competition

tests/test_variable.py
This relates to #99. I think there would be a fixture based way to do the testing of the different lists. But I still prefer this clear `assert ((A[i] == B[i]) for i in range(n)) ` way since it is very independent and pythonic. @josh146 Let me know if this is okay or should we make it more pytest-ty and use fixtures.
=> PyTest refactoring of test_variable.py

pennylane/init.py
I added a little more detail to the description of Interferometer parameter initialization functions `interferometer_normal` and `interferometer_uniform`. 
**Benefits:**
Avoids any confusion and helps the user decipher the output of these functions without having to look up Interferometer function itself.
=> Documentation: add more details to Interferometer initialization functions

.github/CHANGELOG.md, pennylane/_version.py, pennylane/plugins/default_gaussian.py, pennylane/plugins/default_qubit.py
**Description of the Change:** updated the changelog to reflect (merged) PRs. Incremented the version number to `0.4.0-dev0` to reflect the development status of master.
=> Updated the changelog and version number

pennylane/plugins/default_gaussian.py, pennylane/plugins/default_qubit.py, setup.py
* Remove non-working shebang from setup.py.
* Remove unused imports from setup.py.
* Update required pennylane version in plugins.
**Benefits:**
* Remove code that isn't used / doing what it intended.
* Can't think of any.
* None.
=> Remove unused shebang and imports from setup.py.

tests/conftest.py, tests/test_configuration.py
Ported the file `test_configuration.py` from unittest to pytest.
#99
=> Refactor test_configuration.py

tests/conftest.py, tests/test_tfe.py
The file was copy-pasted from the refactored test_torch.py and retuned
to fit TensorFlow by comparing with the old test.
Issues: #99
=> Refactor test_tfe.py

.github/CHANGELOG.md, doc/requirements.txt, pennylane/_version.py, pennylane/optimize/qng.py, pennylane/plugins/default_gaussian.py, pennylane/plugins/default_qubit.py
* Version number updated to 0.5.0
* Changelog updated
=> Updates the changelog and version number for the 0.5.0 release

examples/pennylane_run_data_reuploading_classifier.py
**Description of the Change:** moves an errant speech mark to the correct location
=> Fix punctuation in the data re-uploading tutorial

.github/CHANGELOG.md, examples/pennylane_run_variational_quantum_eigensolver.py
Fix #324 by changing zorder parameter in contour lines in VQE tutorial
**Benefits:**
n/a
n/a
n/a
=> Fix #324 Missing plot lines in VQE tutorial

examples/pennylane_run_barren_plateaus.py
Created a random seed to make sure the results are reproducible and the plot does not get weird values for the 2 qubit case
=> created a random seed

doc/introduction/configuration.rst
Updates the configuration page in the Introduction section of the docs
=> Polish config page

doc/introduction/configuration.rst, doc/introduction/pennylane.rst
=> Extend intro docs page

doc/index.rst, doc/introduction/chemistry.rst
Ported over the quantum chemistry quickstart, and simplified it slightly.
=> Added quantum chemistry quickstart

doc/introduction/chemistry.rst, qchem/pennylane_qchem/qchem.py, qchem/tests/test_generate_hamiltonian.py, qchem/tests/test_generate_mol_hamiltonian.py
This PR modifies `generate_hamiltonian()` so that its output is a PL Hamiltonian
=> Change output of generate_hamiltonian()

.github/workflows/main.yml
**Context:** It is sometimes difficult to find issues and errors in the documentation build on PRs.
**Description of the Change:** Adds a GitHub action to build the documentation on new PRs, and place inline errors on the changed code where errors are detected.
**Benefits:** Will allow rendering issues to be detected automatically.
=> Added a pull request docs check

doc/introduction/circuits.rst, doc/introduction/operations.rst, pennylane/collections/qnode_collection.py, pennylane/vqe/vqe.py
**Context:** Polishes the docs and fixes a bug before release.
* Adds section to circuits.rst to introduce collections
* Fixes a few typos in operations.rst
* Fixes a bug where the QNode collection was returning an inconsistent shape for the autograd interface.
**Benefits:** Polishing and consistency.
=> Adds an introduction to QNode collections, and fixes a consistency bug

.github/CHANGELOG.md, pennylane/_version.py
Incrementing the version number before release
=> Incrementing the version number to 0.8.0

.github/CHANGELOG.md, pennylane/_version.py, pennylane/beta/plugins/default_tensor.py, pennylane/plugins/default_gaussian.py, pennylane/plugins/default_qubit.py
**Context:** A few bugs have been found and fixed since the latest version of PL was released. This bugfix release is to address those bugs.
* Updates the version number and changelog in preparation for release.
=> Version bump to v0.8.1

README.rst, doc/conf.py, doc/index.rst
**Context:** Old author list was outdated.
* Updates the author list for the paper to match the latest paper version.
* Replaces named authorship of the code with a link to the GitHub contributors graph, which is more maintainable in the long term.
**Benefits:** up to date/maintainability.
=> Update author list

pennylane/operation.py
Current error message is incorrect.
=> Fix typo in operations.py

pennylane/vqe/vqe.py
@josh146 let me know if you prefer a different format for the type in brackets
=> Fix typo and adding missing arg

pennylane/_queuing_context.py
After #548 was merged a better phrasing for the docstring came up. This PR solely changes this docstring.
=> Adjust wording of QueuingContext docstring

.github/CHANGELOG.md
=> #773 changelog

pennylane/_queuing.py, pennylane/beta/devices/default_tensor.py, pennylane/circuit_drawer/representation_resolver.py, pennylane/devices/default_gaussian.py, pennylane/devices/default_qubit.py, pennylane/devices/tests/test_gates.py, pennylane/init.py, pennylane/operation.py, pennylane/ops/qubit.py, pennylane/qaoa/mixers.py, pennylane/qnodes/base.py, pennylane/qnodes/decorator.py, pennylane/qnodes/jacobian.py, pennylane/qnodes/rev.py, pennylane/templates/broadcast.py, pennylane/templates/embeddings/displacement.py, pennylane/utils.py, pennylane/wires.py
Black has released a new version with changes to the formatting. 
To avoid cluttering other PRs, this branch simply checked out master and ran ``black -l 100 pennylane/*``.
=> Update code base to latest black version

.github/workflows/tests.yml
=> Attempt to fix codecov

.github/CHANGELOG.md, pennylane/ops/qubit.py, tests/ops/test_qubit_ops.py
This PR adds a decomposition of the CRot gate into elementary gates, along with an accompanying test.
=> Add decomposition for CRot gate

pennylane/devices/default_qubit_tf.py
seems like a copy and paste miss.
=> Fixed imag in tf device

pennylane/__init__.py
=> Added draw import

pennylane/tape/qnode.py
=> Remove print statement

.github/CHANGELOG.md, pennylane/math/autograd_box.py, pennylane/math/fn.py, pennylane/math/jax_box.py, pennylane/math/numpy_box.py, pennylane/math/tf_box.py, pennylane/math/torch_box.py, tests/math/test_functions.py
**Context:**
Added `qml.math.squeeze`
`qml.math` now supports the `squeeze` operation`.
Fixes #1009
=> Added squeeze to qml.math

tests/tape/tapes/test_rewind.py
Two minor tests, but more coming.
=> two device tests

.github/CHANGELOG.md
=> Update changelog for #1088

pennylane/devices/default_qubit_jax.py, tests/devices/test_default_qubit_jax.py
Fixes CRot not being differentiable.
=> Fixed CRot not being differentiable.

pennylane/_device.py, tests/test_device.py
=> Shot vector property

doc/introduction/chemistry.rst
Fixes qchem intro to accommodate new changes
=> Updates qchem intro

README.md, unitaryhack.md
Adding a landing page for the repo for unitaryHACK.
After approval and merging, we can mark and add additional issues
=> Adding summary docs for unitaryHACK

unitaryhack.md
Adds issues #1304  #1305  #1306 to list of unitaryHACK issues.
=> Add decomposition issues to unitaryHACK list

.github/CHANGELOG.md
CHANGELOG.md update for PR  #1312
=> Update CHANGELOG.md for TensorFlow doc typo #1312

doc/introduction/operations.rst
Adds the `IsingXX` and the `CPhase` gates to `operation.rst`.
=> Add some recently added operations to the `operation.rst` file

doc/introduction/operations.rst, pennylane/ops/qubit.py, tests/ops/test_qubit_ops.py, unitaryhack.md
Updates small things related to `IsingXX` and `IsingZZ` operations:
* Adjusts the gradient recipe
* Adds tests for the decomposition and the matrix of the operator
=> Minor updates to recent ops additions

.github/CHANGELOG.md, pennylane/_grad.py, pennylane/qaoa/cycle.py
=> Fix equation typo in qaoa.cycle loss Hamiltonian docstring

.github/CHANGELOG.md, pennylane/qaoa/cost.py
=> fix typo in qaoa.cost.max_weight_cycle docstring

pennylane/_qubit_device.py
Updates one input type and the output type of the `states_to_binary` method.
=> Update documenting array arguments in the docstrings of `_qubit_device.py`

.github/CHANGELOG.md, pennylane/_version.py, qchem/CHANGELOG.md, qchem/pennylane_qchem/_version.py
**Context:**
A new release is on the way, and the master branch can be used to merge features for the next release in line.
Increments version to v0.19.0-dev.
**Benefits:**
=> Increment version number to 0.19.0-dev

doc/releases/changelog-dev.md, pennylane/grouping/transformations.py, pennylane/ops/qubit/parametric_ops.py, pennylane/templates/broadcast.py, pennylane/templates/layer.py, pennylane/templates/subroutines/arbitrary_unitary.py, pennylane/templates/subroutines/interferometer.py, tests/templates/test_broadcast.py, tests/templates/test_layer.py
Merges the following commit into the release candidate branch:
Remove template decorator from PennyLane functions (#1808)
=> Remove template decorator from PennyLane functions (#1808) (into release candidate)

doc/releases/changelog-0.19.0.md, pennylane/optimize/qng.py, tests/optimize/test_qng.py
Merge the following commits from the rc branch to master:
* https://github.com/PennyLaneAI/pennylane/commit/e768d39b1a4c433a875840c0eacc09697df187f3
* https://github.com/PennyLaneAI/pennylane/commit/b9fc6d4b1e94c521270106470434769074c29fc3
=> Merge rc to master

doc/releases/changelog-dev.md, pennylane/_device.py
Same as #1840, just targetting the release candidate branch.
=> Update `expand_fn` (rc)

doc/releases/changelog-0.19.0.md, pennylane/math/multi_dispatch.py, pennylane/tape/tape.py, tests/math/test_functions.py, tests/transforms/test_metric_tensor.py
Merges the accumulated commits from `v0.19.0-rc` to `master`.
The changes mostly come from the following two PRs:
* https://github.com/PennyLaneAI/pennylane/pull/1836
* https://github.com/PennyLaneAI/pennylane/pull/1842
=> Merge rc into master

qchem/CHANGELOG.md, qchem/pennylane_qchem/qchem/structure.py, qchem/tests/test_meanfield.py
Merges https://github.com/PennyLaneAI/pennylane/pull/1854 into the release candidate release notes branch to make it available in the release.
=> #1854 into the release candidate

doc/releases/changelog-dev.md, pennylane/templates/embeddings/basis.py
add example for BasisEmbedding in documentation
**Benefits:**
better documentation
none
#1735 #1727
=> Add example for BasisEmbedding

doc/releases/changelog-dev.md, pennylane/templates/state_preparations/mottonen.py
add documentation example for MottonenStatePreparation
**Benefits:**
better documentation
none
#1735 #1727
=> Add example to MottonenStatePreparation

doc/releases/changelog-dev.md, pennylane/optimize/adagrad.py, pennylane/optimize/adam.py, tests/optimize/test_optimize.py
**Context:** The optimizer tests refactor #1919 revealed issues in two of the optimizer classes.
**Description of the Change:** The following bugs are fixed.
Adagrad optimizer:
- The `apply_grad` method which applies a gradient step to a set of trainable parameters does not do so correctly, due to a missing index increment (`trained_index` in [adagrad.py#L76](https://github.com/PennyLaneAI/pennylane/blob/d705f0e3cc51bd876c8b910cd25b85bfc08694b0/pennylane/optimize/adagrad.py#L76)).
Adam optimizer:
- The docstring for this class contains some error in the optimizer update rules, which are based on the paper [arXiv:1412.6980](https://arxiv.org/abs/1412.6980). The update rules are computed using biased first and second moment terms. A bias correction can then be applied to either the moments …
=> Fix Adagrad/Adam optimizer bugs

doc/releases/changelog-dev.md, pennylane/templates/subroutines/interferometer.py
add documentation example to Interferometer
**Benefits:**
better documentation
none
#1727 #1735
=> Add example to Interferometer

doc/releases/changelog-dev.md, pennylane/drawer/circuit_drawer.py, pennylane/drawer/grid.py, pennylane/drawer/representation_resolver.py, pennylane/templates/subroutines/commuting_evolution.py
Recent PR's have allowed code factor complaints into master.  These flags now occur in open PR's due to merge with master commits.  This PR fixes all current warnings.
=> Code factor fixes

pennylane/fourier/reconstruct.py, pennylane/ops/qubit/state_preparation.py
=> Update docs of `qml.fourier.reconstruct` and `qml.QubitDensityMatrix`

doc/introduction/measurements.rst, doc/introduction/operations.rst, pennylane/hf/molecule.py, pennylane/measure.py, pennylane/ops/channel.py, pennylane/ops/qubit/state_preparation.py, pennylane/transforms/optimization/merge_amplitude_embedding.py
This just tidies up some documentation.
=> minor doc fixes

pennylane/templates/subroutines/commuting_evolution.py
**Context:**
Fix the docstrings types of kwargs.
=> Fix docstrings for `CommutingEvolution`

pennylane/gradients/general_shift_rules.py
**Context:**
Updated doc-string example to match the result of running the code
=> updated docstring example

pennylane/templates/state_preparations/arbitrary_state_preparation.py
=> Fix typo in Arbitrary State Preparation

pennylane/operation.py, pennylane/ops/identity.py, pennylane/ops/qubit/non_parametric_ops.py, pennylane/ops/qubit/observables.py, pennylane/tape/reversible.py, pennylane/transforms/adjoint_metric_tensor.py
The latest merge from master broke the dev branch, this PR is supposed to fix it.
CodeFactor also started working again, which uncovered a few missing pylint comments.
=> [OpRefactor] Fix dev branch after merging master

pennylane/operation.py, pennylane/ops/qubit/hamiltonian.py
CodeFactor decided on a separate PR to work again and unveiled a few issues that accumulated from happily merging. This should address them all.
=> [OpRefactor] Fix codefactor

doc/releases/changelog-dev.md, pennylane/devices/default_mixed.py, pennylane/operation.py, pennylane/ops/channel.py, tests/ops/test_channel_ops.py, tests/test_operation.py
**Context:**
The usual changes, this time for the kraus matrices
Renamed methods and changed kind of methods. Add docstrings everywhere.
=> [OpRefactor] Update kraus representations

doc/releases/changelog-dev.md, qchem/CHANGELOG.md
**Context:**
Modifies the changelog for fixing the psi4 [2090](https://github.com/PennyLaneAI/pennylane/issues/2090) bug.
=> Modify changelog for psi4 bug fix

doc/releases/changelog-dev.md, pennylane/drawer/tape_text.py, pennylane/templates/subroutines/interferometer.py
**Context:**
After checking new features, some minor fixes are needed.
=> Small fixes for upcoming release

doc/introduction/interfaces/jax.rst, doc/releases/changelog-dev.md
As per https://discuss.pennylane.ai/t/pennylane-0-20-qml-sample-not-jittable-anymore/1664
=> Fix JAX `qml.sample` example in the docs

pennylane/transforms/commutation_dag.py
**Context:**
It removes the return None, as it is impossible to test it because the function covers all cases.
=> Small change in `_both_controlled` function for more coverage

doc/releases/changelog-dev.md, pennylane/_grad.py, pennylane/transforms/commutation_dag.py, tests/test_finite_diff.py
=> Fix some rendering issues in the changelog

pennylane/measurements.py, pennylane/transforms/condition.py
Fixes the linting issues introduced by #2211.
=> Fix conditional operation linting

pennylane/tape/tape.py
=> Linting fix in `tape.py`

qchem/pennylane_qchem/qchem/structure.py
=> Remove unused wires import (linting)

pennylane/transforms/qcut.py
Fixes issues shown here: https://github.com/PennyLaneAI/pennylane/runs/5793036160
=> Fix pylint issues in qcut module

.github/workflows/tests.yml
Update Codecov version to 3 in the tests workflow.
=> Update tests workflow with Codecov version 3

.github/workflows/docs.yml
Adds an explanation to the `.github/workflows/docs.yml` file on its purpose.
=> Comment in the Sphinx docs check file

pennylane/templates/subroutines/hilbert_schmidt.py
This PR improve the documentation for the `LocalHilbertSchmidt` template.
=> Improve `LocalHilbertSchmidt` template doc

doc/development/release_notes.md, doc/releases/changelog-0.23.0.md, doc/releases/changelog-0.23.1.md
**Context:**
Merges the changelog changes from #2548 to `master`.
=> Merge changelog changes after `v0.23.1` release

tests/ops/qubit/test_parametric_ops.py
Same as #2696 just targetting the rc branch.
=> Update phase decomp test (rc)

pennylane/ops/qubit/parametric_ops.py
This PR improves the documentation for Ising gates.
=> Improve ising gates documentation

pennylane/qinfo/transforms.py, tests/qinfo/test_fidelity.py
**Context:**
This PR fixes the use of dictionnary in the tuple argument.
=> Fix kwargs for fidelity

pennylane/transforms/batch_partial.py
Update the outdated documentation.
=> Documentation changes for `batch_partial`

pennylane/math/__init__.py, pennylane/math/quantum.py, pennylane/measurements.py, pennylane/ops/qubit/parametric_ops.py, pennylane/qinfo/transforms.py, tests/math/test_entropies_math.py, tests/qinfo/test_entropies.py, tests/qinfo/test_fidelity.py
**Context:**
It adds some more examples and move tests from math to qinfo. It also fixes some renders issues in Ising operations.
=> Fix doc quantum information and ising

pennylane/ops/qubit/observables.py
**Context:**
The documentation for `class SparseHamiltonian` needs to be updated.
Updates `class SparseHamiltonian` sparse format in documentation.
**Benefits:**
=> Update to class SparseHamiltonian documentation

tests/ops/qubit/test_parametric_ops.py
found that some tests were using fixed value in place of the parameterized parameter
fixed that
=> fix some test typos

pennylane/math/quantum.py, pennylane/measurements.py, pennylane/qinfo/transforms.py
It adds some see also sections for entropy and fidelity.
Closes https://github.com/PennyLaneAI/pennylane/issues/2764
=> Add See also section to vn entropy and fidelity

doc/releases/changelog-dev.md, pennylane/ops/qubit/parametric_ops.py, tests/devices/test_default_qubit_torch.py, tests/gate_data.py
**Context:** Torch GPU tests fail …
=> Fix data locality issues for Torch GPU usage

tests/ops/op_math/test_adjoint_op.py
#2900 accidentally let in an untested piece of logic.  This adds a test covering that case.
=> Add a test for logic that accidentally got in untested

doc/introduction/measurements.rst, pennylane/operation.py, pennylane/transforms/mitigate.py
Minor documentation improvements for the release.
=> Minor documentation fixes

doc/releases/changelog-0.25.0.md, pennylane/transforms/broadcast_expand.py
Add a warning for broadcasting and templates.
=> Warning for broadcasting and templates.

.github/workflows/tests-gpu.yml
**Context:**
Currently GPU based unittests are not being run when changes to pennylane occur. This pull request adds a new GitHub Actions workflow that runs gpu marked unittests.
A new workflow will run in the two scenarios below:
- A new commit is pushed to the master branch
- An open pull request is assigned the label `gpu`
Either of these scenarios will cause the new workflow included in this pull request to trigger. Which will run the gpu marked unitests.
**Benefits:**
Enable running of gpu unittests.
Currently, Github does not offer GPU based hosted runners; [though they are in the roadmap as a possible future offering](https://github.com/github/roadmap/issues/505). As it stands, the only way to process GPU based Actions …
=> Added new GitHub Actions workflow to run gpu marked unittests on gpu runners

doc/releases/changelog-0.25.0.md, doc/releases/changelog-0.25.1.md, doc/releases/changelog-dev.md
Merge the changelog changes from bugfix release `0.25.1`.
=> Merge release `0.25.1` into master

README.md, doc/index.rst
Probably doesn't warrant a new entry? It's just a tiny language fix.
- [?] Add a new entry to the `doc/releases/changelog-dev.md` file, summarizing the
=> Added hyphenation to 'device-indepenent'

doc/releases/changelog-0.26.0.md, pennylane/ops/functions/is_hermitian.py, pennylane/ops/functions/is_unitary.py, pennylane/ops/functions/simplify.py
Updates the output of some doc examples before the v0.26.0 release.
=> Update docs for v0.26

doc/releases/changelog-0.26.0.md, setup.py
It bumps lightning to version `0.26` for the release.
=> Bump lightning 0.26

doc/conf.py, doc/requirements.txt
=> Use the PennyLane Sphinx Theme

pennylane/qnode.py
Improve code quality of `qnode.py` file.
NO changes made to the functionality of the code.
=> QNode improve code quality

pennylane/data/dataset.py, tests/data/test_dataset.py
see title. will do write to file later, might need to save the wire_map to make that work
=> build hamiltonian from terms when read from file

pennylane/drawer/tape_mpl.py, tests/drawer/test_draw_mpl.py
Follows #3247, ensuring that MPL isn't a hard requirement for PennyLane
=> don't panic if matplotlib isn't installed

doc/development/release_notes.md, doc/releases/changelog-dev.md, pennylane/_version.py
**Context:**
After creating the RC branch we need to update changes made to the change log in master
- add changelog-dev.md
- add changelog-dev reference to release_notes.md
- bump version to 0.X+1.0-dev
https://github.com/PennyLaneAI/pennylane/pull/3044
=> Update changelog post rc branch creation for V0.27

doc/releases/changelog-0.27.0.md, pennylane/drawer/tape_mpl.py, pennylane/ops/functions/map_wires.py, pennylane/qchem/tapering.py, pennylane/templates/subroutines/flip_sign.py
Doc changes for `qml.qchem.taper_operation`, `qml.map_wires`, and `qml.drawer.tape_mpl`.
=> Various documentation changes

pennylane/gradients/__init__.py, pennylane/gradients/jvp.py, pennylane/ops/functions/equal.py, pennylane/pauli/utils.py
docs updates while validating changes for the release
=> various updates for 0.27

doc/development/deprecations.rst
**Context:**
Add grouping module to the pending deprecations page
=> [doc] Added grouping to pending deprecations page

doc/code/qml_pauli.rst, pennylane/pauli/pauli_arithmetic.py
Make sure module documentation highlights the new `PauliWord` and `PauliSentence` classes
=> Add module documentation for the pauli module

setup.py
Bump lightning version, wait for it to release, then we can merge and release PennyLane 👍🏼
=> Bump lightning version to `0.27` in preparation for the release

pennylane/_qubit_device.py
Improve code in `_qubit_device.py`.
=> Improve `QubitDevice` code

tests/measurements/test_expval.py, tests/measurements/test_var.py
Increase the number of shots in 2 flaky tests to ensure that the tolerance is met.
=> Fix flaky tests

doc/introduction/operations.rst
Very quick change. Goes into the function table here: https://docs.pennylane.ai/en/stable/introduction/operations.html
=> add pow to the operation intro doc

tests/returntypes/transforms/test_qcut_new.py
Remove with tape from the new cut test file.
=> Change tape to queue in the return types qcut file

doc/development/release_notes.md, doc/releases/changelog-dev.md, pennylane/_version.py
**Context:**
After creating the RC branch we need to update changes made to the change log in master
- add changelog-dev.md
- add changelog-dev reference to release_notes.md
- bump version to 0.X+1.0-dev
https://github.com/PennyLaneAI/pennylane/pull/3277
=> Update changelog post rc branch creation for V0.28

pennylane/ops/functions/equal.py, tests/ops/functions/test_equal.py
=> Extend qml.equal to compare Prods

doc/development/guide/architecture.rst
Fixes documentation is: https://docs.pennylane.ai/en/stable/development/guide/architecture.html?highlight=MeasurementProcess#measurementprocess
=> Fix documentation on measurement processes

pennylane/ops/qubit/non_parametric_ops.py, pennylane/pauli/conversion.py, tests/ops/qubit/test_non_parametric_ops.py
Fixes some parts of the documentation before the v0.28.0 release.
=> v0.28.0 doc fixes

doc/releases/changelog-0.28.0.md
From #3405, I believe this should be treated as an improvement rather than a breaking change. I've updated the wording to fit this, but feel free to propose/add changes here.
=> move the map_wires changelog entry from breaking to improvement

setup.py
**Context:**
bump the version of PennyLane-lightning
https://github.com/PennyLaneAI/pennylane/pull/3348
=> Bump lightning version to 0.28 in preparation for the release

pennylane/ops/op_math/controlled_class.py
=> Add broadcasting for Controlled class

tests/qchem/test_molecule.py
It adds a fix for this error https://github.com/PennyLaneAI/pennylane/actions/runs/3984755105/jobs/6831327031#step:4:3540
=> Add import or skip for basisset and fix docker

doc/releases/changelog-dev.md, pennylane/ops/qubit/parametric_ops.py
=> Update parametric_ops.py documentation

tests/measurements/test_classical_shadow.py
The changed test is randomly failing, this PR adds a flaky decorator with 5 runs.
=> Flaky added to classical shadow `return_distribution` test

doc/conf.py, doc/requirements.txt
Comparing the docs for the `simplify` function:
* Master:
* This PR:
=> Sphinx: Remove types from signatures.

tests/returntypes/gradients/test_spsa_gradient_shot_vec_new.py
**Context:**
This kind of failure appear sporadically. https://github.com/PennyLaneAI/pennylane/actions/runs/4107025637/jobs/7086007064
This PR change the tolerance from 0.30 to 0.31
=> Change tol for SPSA test (failing randomly)

.github/workflows/docs.yml
Sphinx GH action is now using `PennyLaneAI`.
=> Update sphinx action

tests/devices/test_lightning_qubit.py
Update lightning test due to this PR https://github.com/PennyLaneAI/pennylane-lightning/pull/416
=> Fix test lightning in rc branch

doc/development/deprecations.rst, doc/releases/changelog-0.29.0.md, pennylane/ops/op_math/evolution.py, pennylane/optimize/lie_algebra.py, pennylane/qaoa/layers.py, pennylane/templates/subroutines/approx_time_evolution.py, pennylane/templates/subroutines/commuting_evolution.py, tests/devices/test_lightning_qubit.py, tests/ops/op_math/test_evolution.py, tests/templates/test_subroutines/test_commuting_evolution.py, tests/test_qaoa.py
**Context:**
Merge the RC branch in master ( #3797 #3801)
=> Merge rc in master

doc/releases/changelog-0.29.0.md, pennylane/qnode.py
this PR is against Tom's changelog update branch
=> add details to changelog for marginal_prob bug

pennylane/__init__.py, pennylane/drawer/draw.py, pennylane/measurements/classical_shadow.py, pennylane/measurements/counts.py, pennylane/measurements/probs.py, pennylane/measurements/sample.py, pennylane/measurements/state.py, pennylane/measurements/var.py, pennylane/measurements/vn_entropy.py, pennylane/ops/functions/generator.py, pennylane/ops/functions/matrix.py, pennylane/ops/op_math/pow.py, pennylane/pauli/conversion.py, pennylane/qchem/tapering.py, pennylane/return_types.py, pennylane/transforms/metric_tensor.py, pennylane/transforms/optimization/pattern_matching.py, pennylane/transforms/qcut/montecarlo.py
This PR adds some fixes to the documentation of functions that did not get updated for the v0.29 release.
~~Note: More changes are being added, so PR has been marked as draft for now.~~
=> Docstring fixes for unchanged functions

README.md, pennylane/tape/qscript.py
=> fix docker link; remove old inv comment

tests/measurements/test_mid_measure.py
PR #3811  accidentally left a line untested, and it's now causing problems with new PR's.
=> test untested line to fix code coverage

pennylane/devices/experimental/device_api.py
=> Device api doc typo fixes

pennylane/gradients/hadamard_gradient.py, tests/returntypes/gradients/test_hadamard_grad.py
**Context:**
Hadamard grad returns wrong results when we have multiple operations generating multiple tapes like (CR).
Update the idx correctly.
=> Fix hadamard grad

doc/development/deprecations.rst
We missed a few removals this release. These have been updated to be removed in next release.
=> Update deprecations page

pennylane/gradients/pulse_gradient.py
quick fix for the [coverage issue](https://github.com/PennyLaneAI/pennylane/runs/12138478941) in the [pulse gradient transform PR](https://github.com/PennyLaneAI/pennylane/pull/3780) that was accidentally automerged.
=> Fix coverage missing from 3780

.github/workflows/tests.yml
Update Torch in the CI tests to 2.0.0 !
=> Update to torch 2.0.0

.github/workflows/tests.yml, tests/devices/test_default_mixed_torch.py, tests/ops/functions/test_dot.py, tests/tests_passing_pylint.txt
- Fix linting issues.
- Remove continue on error in the CI checks.
=> Fix pylint

doc/releases/changelog-dev.md, pennylane/resource/__init__.py, pennylane/resource/resource.py, tests/resource/test_resource.py
=> Add a `ResourcesOperation` class to support resource estimation of custom operations

doc/introduction/circuits.rst, doc/introduction/compiling_circuits.rst, doc/introduction/data.rst, doc/introduction/inspecting_circuits.rst, doc/introduction/interfaces.rst, doc/introduction/interfaces/jax.rst, doc/introduction/interfaces/numpy.rst, doc/introduction/interfaces/tf.rst, doc/introduction/interfaces/torch.rst, doc/introduction/measurements.rst, doc/introduction/unsupported_gradients.rst
This PR updates the output of quickstart documentation to reflect the change in output shape from the new return type specification, and other recent changes.
=> Update quickstart documentation

doc/code/qml_pauli.rst, pennylane/gradients/__init__.py, pennylane/transforms/batch_params.py, pennylane/transforms/decompositions/single_qubit_unitary.py, pennylane/transforms/defer_measurements.py, pennylane/transforms/optimization/pattern_matching.py, pennylane/transforms/optimization/undo_swaps.py, pennylane/transforms/qmc.py, pennylane/transforms/specs.py, pennylane/transforms/split_non_commuting.py, pennylane/transforms/zx/converter.py
Various small documentation tidying changes.
=> Cleaning the documentation

doc/development/deprecations.rst, pennylane/resource/resource.py, pennylane/tape/qscript.py, tests/legacy/test_qscript_old.py, tests/resource/test_resource.py, tests/tape/test_qscript.py, tests/tape/test_tape.py, tests/transforms/test_specs.py
**Context:**
Added a new quantity `gate_sizes` to the `Resources` object.
=> Add `gate_sizes` to the `Resources` object and deprecate it from `qml.specs`

pennylane/resource/resource.py, pennylane/transforms/specs.py, tests/resource/test_resource.py
=> fix merge conflict

.readthedocs.yml, doc/requirements.txt
=> Update RTD build OS to Ubuntu 22.04

doc/releases/changelog-dev.md, pennylane/measurements/shots.py, tests/measurements/test_shots.py
**Context:**
Add nice repr and str methods to the `Shots` class to allow for easier printing and representation of the class
=> Add a `repr` and `str` to the `Shots` class

doc/releases/changelog-dev.md, pennylane/tape/qscript.py, pennylane/tape/tape.py, tests/tape/test_qscript.py, tests/tape/test_tape.py
Added changes that were missed in the PR that added shots to `QuantumScript`.
=> Additional changes for `QuantumScript.shots`

doc/introduction/interfaces.rst, doc/releases/changelog-dev.md, pennylane/_grad.py
From https://discuss.pennylane.ai/t/get-gradient-of-quantum-circuit-with-pytorch-interface/2994#post_1
=> Added warning in grad docstring

doc/development/release_notes.md, doc/releases/changelog-0.31.0.md, doc/releases/changelog-dev.md, pennylane/_version.py
do NOT merge until RC branch is created and base branch is updated to master
=> Incrementing the version number to `v0.32.0-dev`

doc/releases/changelog-dev.md
the template for the changelog was updated, but sneakily hidden far down the release guide. I'll make it more visible in a PR there, but for now, this should be updated here too :)
=> add emojis to changelog

.github/workflows/interface-unit-tests.yml
Update Jax version in the CI to 0.4.13.
=> Update jax version to 0.4.13

doc/code/qml_qinfo.rst, pennylane/interfaces/execution.py, pennylane/optimize/riemannian_gradient.py, pennylane/qinfo/transforms.py, pennylane/shadows/transforms.py, tests/legacy/test_legacy_fisher_old.py, tests/legacy/test_legacy_split_non_commuting_old.py, tests/legacy/test_legacy_transforms_old.py, tests/qinfo/test_fisher.py, tests/shadow/test_shadow_transforms.py
**Context:**
Update the batch transforms to the new transform API.
Update `_replace_obs`, `_make_probs`, and `algebra_commutator`.
=> Update `_replace_obs`, `_make_probs`, and `algebra_commutator` batch transforms

pennylane/interfaces/execution.py, pennylane/transforms/batch_input.py, pennylane/transforms/batch_params.py, pennylane/transforms/core/transform_dispatcher.py, tests/devices/test_default_mixed_jax.py, tests/legacy/test_legacy_batch_input_old.py, tests/transforms/test_batch_input.py, tests/transforms/test_batch_params.py, tests/transforms/test_experimental/test_transform_dispatcher.py, tests/transforms/test_experimental/test_transform_program.py
**Context:**
Update the batch transforms to the new transform API.
Update `batch_input` and `batch_params`.
=> Update `batch_input` and `batch_params` transforms

pennylane/transforms/broadcast_expand.py, pennylane/transforms/mitigate.py, pennylane/transforms/sign_expand/sign_expand.py, tests/legacy/test_legacy_mitigate_old.py, tests/transforms/test_broadcast_expand.py, tests/transforms/test_mitigate.py, tests/transforms/test_sign_expand.py
**Context:**
Update the batch transforms to the new transform API.
Update `broadcast_expand`, `sign_expand`, `fold_global`, and `mitigate_with_zne`.
=> Update `broadcast_expand`, `sign_expand`, `fold_global`, and `mitigate_with_zne`

.github/workflows/format.yml, .github/workflows/pylint.yml, .github/workflows/tests-gpu.yml, .github/workflows/upload.yml
Update some actions that were still using 3.8 Python
=> Remove python 3.8 from GH actions

doc/releases/changelog-dev.md, pennylane/pulse/transmon.py, tests/pulse/test_transmon.py
My bad, sorry! Got confused and didnt realize that $b^\dagger b = \frac{1}{2} (1 - Z)$ already has a factor 1/2!
Reverting https://github.com/PennyLaneAI/pennylane/pull/4465
=> Reverse factor 1/2 in transmon_interaction

doc/development/release_notes.md, doc/releases/changelog-0.31.1.md, doc/releases/changelog-0.32.0.md, pennylane/_version.py
**Context:**
Updating current version to 0.32.0 everywhere.
**Benefits:**
=> 0.32.0 pre-release changes

doc/development/release_notes.md, doc/releases/changelog-dev.md, pennylane/_version.py
=> Incrementing version to `0.33.0-dev`

tests/logging/test_logging_autograd.py
Hopefully helps the CI. Looks like logging was being enabled during collection, not when running the logging tests.
=> Enable logging during test instead of during collection

.github/workflows/rc_sync.yml
As title says. I replaced @timmysilv as a reviewer with myself.
=> Update daily rc sync reviewer

pennylane/drawer/style.py, pennylane/math/fidelity.py, pennylane/measurements/mid_measure.py, pennylane/operation.py, pennylane/pauli/pauli_arithmetic.py, pennylane/qchem/hamiltonian.py, pennylane/qchem/observable_hf.py
=> little fixups from timmysilv for the 0.32 release

pennylane/transforms/core/transform.py, pennylane/transforms/core/transform_dispatcher.py, pennylane/transforms/qcut/__init__.py, pennylane/transforms/qcut/cutcircuit.py, pennylane/transforms/qcut/montecarlo.py, tests/legacy/test_legacy_qcut_old.py, tests/transforms/test_experimental/test_transform_dispatcher.py, tests/transforms/test_qcut.py
**Context:**
Update the batch transforms to the new transform API.
Update `cut_circuit` and `cut_circuit_mc`.
=> Update qcut transforms

setup.py
=> Update lightning requirement

doc/development/deprecations.rst, doc/releases/changelog-dev.md, pennylane/gradients/spsa_gradient.py, tests/gradients/finite_diff/test_spsa_gradient.py
Complete deprecation cycle for `sampler_seed` kwarg in `spsa_grad`
=> Remove sampler_seed from spsa_grad

pennylane/transforms/hamiltonian_expand.py
**Context:**
* Updated `hamiltonian_expand` and `sum_expand` to use new `transform` decorator.
**Benefits:**
Integration with new API
=> Update `hamiltonian_expand`, `sum_expand`

.github/workflows/interface-unit-tests.yml
=> bump jax version to v0.14.17

pennylane/transforms/core/transform_dispatcher.py
Transform dispatcher inherits docs from the transform.
=> Fix transforms docs

.github/workflows/interface-unit-tests.yml
=> bump jax version

doc/conf.py, doc/introduction/compiling_circuits.rst, pennylane/compiler/__init__.py, pennylane/compiler/qjit_api.py
**Context:** Catalyst frontend is being integrated into PL
**Description of the Change:** Attempt to add Catalyst to intersphinx to help with cross referencing of docs
**Benefits:**
[sc-46399]
=> Compiler documentation

doc/development/release_notes.md, doc/releases/changelog-dev.md, pennylane/_version.py
|      PR 2:
|     - add changelog-dev.md, add changelog-dev reference to release_notes.md,
|     - bump version to 0.X+1.0-dev
|     - Update rc_sync.yml to replace the previous release manager with your username as a PR reviewer on the last line
=> Bump version to `0.34.0-dev`

doc/releases/changelog-dev.md, pennylane/templates/subroutines/arbitrary_unitary.py, tests/templates/test_subroutines/test_arbitrary_unitary.py
`ArbitraryUnitary` does not support batching yet.
This PR adds batching support.
=> Support batching with `ArbitraryUnitary`

pennylane/__init__.py
**Context:**
Found in a previous PR. This docstring is quite stale, so I've updated the device list along with a few other things.
- Remove the interface-specific devices from the list (just use default.qubit!)
- Add lightning.qubit, default.qutrit, default.mixed, and a suggestion to use `qml.about()` to check what you have
- mention that some devices (eg default.qubit) may not need wires
- change the shots example to use a shot vector to suggest that it's possible/advertise the feature
**Benefits:**
people know about all the features available to them!
still keeping this up-to-date? maybe we should just remove the explicit list of devices? I don't think it's too bad.
=> update qml.device docs

doc/releases/changelog-0.33.1.md
=> remove unused changelog categories

pennylane/pauli/pauli_arithmetic.py
Speeds up `PauliWord.__or__` by computing whether the two Pauli words commute manually, rather than inferring this information from the coefficient, which apparently is quite slow.
For this, `PauliWord` receives a new method `commutes_with`.
=> [DLA] Speed up `PauliWord.__or__`

tests/devices/qubit/test_sampling.py
=> try to fix sporadically failing sampling test

doc/releases/changelog-dev.md, pennylane/gradients/finite_difference.py
Fixes #4953  [sc-52180]
This problem does seem to M1's, but this does seem to fix it.
=> fix bus failure with tensorflow autograph

setup.py
updates `setup.py` file to specify `pennyLane-lightning >= 0.34`
=> Update setup file

.github/workflows/rc_sync.yml, doc/development/release_notes.md, doc/releases/changelog-0.34.0.md, doc/releases/changelog-dev.md, pennylane/_version.py, pennylane/devices/qubit/measure.py, pennylane/ops/functions/assert_valid.py, pennylane/ops/qubit/matrix_ops.py, pennylane/ops/qubit/special_unitary.py, pennylane/resource/first_quantization.py, pennylane/resource/second_quantization.py, pennylane/transforms/__init__.py, pennylane/transforms/split_non_commuting.py, tests/ops/functions/conftest.py, tests/ops/functions/test_assert_valid.py, tests/transforms/test_split_non_commuting.py
merge master into rc branch - needed merge conflicts resolved
=> Merge conflict fix

doc/releases/changelog-0.34.0.md, doc/releases/changelog-dev.md, pennylane/qchem/openfermion_obs.py
**Context: There are a couple typos …
=> Correcting minor typos in openfermion_obs.py

pennylane/qchem/convert.py
Currently: https://docs.pennylane.ai/en/stable/code/api/pennylane.import_operator.html
=> Fix broken URL

tests/interfaces/test_jacobian_products.py
Codecov is failing due to these tests not being covered.
=> Added tests for Lightning VJP error coverage

.github/workflows/format.yml, doc/releases/changelog-dev.md, requirements-dev.txt
**Context:**
Black just released …
=> Pin black to 23.12.

pennylane/compiler/compiler.py, tests/test_compiler.py
- Remove unnecessary fixture
- Remove the compiler cache
=> Remove compiler version cache

pennylane/ops/op_math/controlled_ops.py
**Context:**
After https://github.com/PennyLaneAI/pennylane/pull/5199, some doc examples in `controlled_ops.py` need updating
Update doc examples with correct outputs
=> Update examples in docs of controlled_ops.py

doc/development/deprecations.rst, doc/releases/changelog-0.35.0.md, pennylane/math/quantum.py, pennylane/ops/functions/commutator.py, pennylane/ops/op_math/controlled.py, tests/transforms/test_mitigate.py
See the commit history of this PR for a detailed breakdown of the changes.
=> Fix typos and documentation issues found during QA

doc/releases/changelog-0.35.0.md, pennylane/devices/__init__.py
Not much in terms of validation on my end!
=> remove duplicate entry, render qutrit mixed helpers

doc/development/guide/deprecations_removals.rst
Just minimal fixes to some typos in the docs.
=> Pietro/fixes for 0.35 release

setup.py
Bump lightning in setup.py to 0.35 now that it is released
=> Bump lightning

doc/releases/changelog-0.35.0.md, doc/releases/changelog-0.35.1.md, pennylane/_qubit_device.py, setup.py, tests/devices/test_lightning_qubit.py
**Context:**
Some of the changes made to the v0.35.1 RC branch have not yet been merged into `master`.
* Merged the `v0.35.1-rc` branch into `master`. 
**Benefits:**
* The PennyLane-Lightning bug fixes will be present in `master`.
* The v0.35.1 release notes will be available in `master`.
_N/A_
_N/A_
=> Merge v0.35.1 changes into `master`

pennylane/gradients/gradient_transform.py, pennylane/gradients/hadamard_gradient.py, pennylane/gradients/hamiltonian_grad.py, pennylane/gradients/parameter_shift.py, pennylane/ops/op_math/sum.py, tests/gradients/core/test_pulse_odegen.py, tests/gradients/parameter_shift/test_parameter_shift_shot_vec.py, tests/interfaces/test_autograd.py
[sc-58388] [sc-58386]
**Context:** …
=> Update `interfaces` and `gradients` to work with new operator arithmetic

pennylane/data/attributes/operator/operator.py
**Context:** Loading `Hamiltonians` from already uploaded datasets was failing as `qml.Hamiltonian` was mocks `qml.ops.LinearCombination`.  This fixed it by importing legacy Hamiltonian on top as `LegacyHamiltonian`
**Benefits:**
=> Fix `Hamiltonian` loading for datasets

doc/development/release_notes.md, doc/releases/changelog-0.35.0.md, doc/releases/changelog-0.36.0.md, pennylane/_version.py
- Increment version number
- Updates to the changelog and release notes
=> Preparation for release candidate v0.36.0

doc/development/deprecations.rst, pennylane/devices/default_qutrit_mixed.py
2 very minor corrections to documentation added in this release
=> Make 2 small changes to docs

doc/releases/changelog-0.36.0.md
**Context:**
We have added dynamical Lie algebra support to PennyLane and want to advertise it to the user.
Adds a section in the release notes.
=> Release notes v0.36 - dynamical Lie algebras

doc/releases/changelog-0.36.0.md
https://app.shortcut.com/xanaduai/story/61896/the-qutrit-section-of-the-release-notes-is-finalized
=> Release notes v0.36 — qutrits

doc/releases/changelog-0.36.0.md, pennylane/transforms/compile.py, pennylane/workflow/return_types_spec.rst
This PR contains all the required changes coming from [quality checks](https://docs.google.com/spreadsheets/d/1nU7bw0Gx4qIkiSrjWPHlhRuokxBGZW3KQoqMamLcRfY/edit#gid=875363335)
=> Adjustments for various PRs necessary for version 0.36

doc/releases/changelog-0.36.0.md
**Context:**
We want to communicate the new error estimation functionality in v0.36 to the user.
Adds a section in the release notes describing the change and sharing code examples.
=> Release notes v0.36 — error estimation section

pennylane/pauli/dla/lie_closure.py, pennylane/pauli/dla/structure_constants.py
Some outputs had a different wire order than reported in the documentation.
=> Minor release doc fixes

README.md, doc/index.rst
How it looks in the README: https://github.com/PennyLaneAI/pennylane/blob/trbromley-patch-1/README.md
How it looks in the docs: https://xanaduai-pennylane--5705.com.readthedocs.build/en/5705/
=> Update positioning in README

pennylane/templates/layers/gate_fabric.py
**Context:** Fixing doc typos that I found while working on #5643 (which has been closed)
=> Removed repetition in doc

.github/workflows/install_deps/action.yml
=> pin scipy with jax

pennylane/devices/execution_config.py
=> Update `ExecutionConfig`'s `mcm_config` default value

.pylintrc, doc/code/qml.rst, doc/development/guide/installation.rst, doc/releases/changelog-dev.md, doc/requirements.txt, pennylane/__init__.py, pennylane/numpy/random.py, requirements-ci.txt, requirements.txt, setup.py, tests/.pylintrc
Reverts PennyLaneAI/pennylane#5782
=> Revert "Removing `semantic_version` from required packages"

doc/releases/changelog-dev.md, tests/fermi/test_bravyi_kitaev.py, tests/fermi/test_fermi_mapping.py, tests/fermi/test_parity_mapping.py
**Context:**
Improve tests for mapping when input type is FermiSentence
Added more tests for mapping schemes with different cases
**Benefits:**
Improved testing
=> Improve tests for mapping schemes with FermiSentence

pennylane/devices/default_qubit.py, pennylane/devices/qubit/simulate.py, pennylane/measurements/__init__.py, pennylane/measurements/mid_measure.py, pennylane/workflow/qnode.py, tests/devices/default_qubit/test_default_qubit_native_mcm.py, tests/test_qnode.py
=> `tree-traversal` work with `shots=None`

doc/releases/changelog-0.37.0.md, pennylane/capture/explanations.md, pennylane/io.py, pennylane/ops/qutrit/channel.py, pennylane/transforms/split_non_commuting.py
Quality check for PRs related to PennyLane 0.37
=> Quality check for PRs related to `PennyLane 0.37`

doc/development/guide/installation.rst, pennylane/debugging/snapshot.py, pennylane/devices/__init__.py, pennylane/devices/default_tensor.py, pennylane/noise/noise_model.py, pennylane/ops/meta.py, pennylane/ops/qutrit/channel.py, tests/devices/default_tensor/test_default_tensor.py, tests/test_compiler.py, tests/test_debugging.py
As name says. I've left information about each change that is added in the first 6 commit messages.
=> Minor doc/code fixes for 0.37 release

.github/workflows/install_deps/action.yml
=> Update TF pinned version in CI

doc/development/deprecations.rst, doc/releases/changelog-dev.md, pennylane/qcut/cutcircuit.py, pennylane/resource/specs.py, pennylane/transforms/core/transform.py, pennylane/transforms/core/transform_program.py, pennylane/transforms/hamiltonian_expand.py, tests/interfaces/default_qubit_2_integration/test_jax_jit_qnode_default_qubit_2.py, tests/interfaces/default_qubit_2_integration/test_jax_qnode_default_qubit_2.py, tests/resource/test_specs.py, tests/test_debugging.py, tests/test_qnode.py, tests/transforms/core/test_transform_dispatcher.py, tests/transforms/test_hamiltonian_expand.py, tests/transforms/test_qcut.py, tests/workflow/test_construct_batch.py
[[sc-64018](https://app.shortcut.com/xanaduai/story/64018)]
=> Deprecate `sum_expand` and `hamiltonian_expand`

doc/releases/changelog-dev.md
Note that for this PR, we're just sorting the entries into categories. The entries themselves can be changed later.
=> v0.38 changelog parse round 2

pennylane/transforms/diagonalize_measurements.py, tests/transforms/test_diagonalize_measurements.py
Fixes recent failures with legacy opmath.
=> Fix tests for legacy opmath

doc/development/release_notes.md, doc/releases/changelog-0.37.0.md, doc/releases/changelog-0.38.0.md, pennylane/_version.py
As name says. 1st PR needed for the release
=> Preparation for 0.38 release candidate

doc/development/release_notes.md, doc/releases/changelog-dev.md, pennylane/_version.py
As name says. Had to open a new PR due to merge conflicts.
=> Bump dev version to 0.39

.github/workflows/rc_sync.yml
As name says. Making myself a reviewer for the daily RC sync.
=> Update reviewer for RC sync workflow

pennylane/workflow/interfaces/jax_jit.py, tests/interfaces/test_jax_jit.py
Missed some edge cases in PR #6108.
**Related Shortcut Stories:**
[sc-65313] [sc-59327]
=> fix counts on all wires edge cases

doc/releases/changelog-0.38.0.md, pennylane/pytrees/serialization.py, tests/data/attributes/test_pytree.py, tests/pytrees/test_serialization.py
#6155 was merged into `master` instead of the RC branch. This PR is cherry picking that commit into the RC branch.
=> Cherry pick datasets bugfix into RC branch

.github/stable/external.txt, .github/workflows/install_deps/action.yml, pennylane/compiler/compiler.py, setup.py
Bumping catalyst and lightning versions across PL.
=> Final updates before 0.38 release

doc/releases/changelog-0.38.1.md
=> Remove useless sections from changelog

pennylane/__init__.py
Just one more suggestion for this PR
=> Additional suggestion

doc/introduction/compiling_workflows.rst, pennylane/compiler/__init__.py, pennylane/compiler/qjit_api.py
**Context:**
**Benefits:**
[sc-70009]
=> Add link to Catalyst device page

pennylane/ops/op_math/exp.py
Added a fix to ensure resources are correct for exponentials with Identity operators.
=> Added a special if clause for Identity terms in the Hamiltonian

pennylane/optimize/gradient_descent.py, pennylane/optimize/nesterov_momentum.py, pennylane/optimize/shot_adaptive.py
We fix a couple of typos in the doc discovered while reviewing #6240
=> Fix a couple of typos in the doc

.github/workflows/docs.yml, .github/workflows/rc_sync.yml
**Context:** Move repo-sync action …
=> Attempt fix for borked action

doc/introduction/compiling_circuits.rst, pennylane/devices/preprocess.py, pennylane/transforms/decompose.py, tests/transforms/test_decompose_transform.py
Rephrase some potentially ambiguities in the doc.
This is a separate PR since this is a non-trivial doc update. All minor doc-fixes will be consolidated in a separate PR.
=> Update docs for the new decompose transform

.github/workflows/rc_sync.yml
=> Simplify and fix the RC sync

doc/releases/changelog-0.39.0.md
Small changes to doc for PL 0.39
=> Small doc changes

doc/code/qml_noise.rst, doc/development/legacy_plugins.rst, doc/development/plugins.rst, doc/releases/changelog-0.39.0.md, pennylane/data/data_manager/graphql.py, pennylane/devices/qubit/__init__.py, pennylane/devices/qutrit_mixed/__init__.py, pennylane/noise/noise_model.py, pennylane/transforms/add_noise.py, pennylane/workflow/construct_tape.py
As name says. Info about changes in commit messages.
=> Mudit's doc fixes for 0.39 FF QA

doc/releases/changelog-0.39.0.md, pennylane/ops/op_math/adjoint.py, pennylane/ops/op_math/controlled.py, tests/ops/op_math/test_adjoint.py, tests/ops/op_math/test_controlled.py, tests/ops/op_math/test_prod.py
This PR is a copy of this [other one](https://github.com/PennyLaneAI/pennylane/pull/6284) pointing to v0.39.0-rc0
[[sc-73690](https://app.shortcut.com/xanaduai/story/73690)]
=> Fix bug where unexpected queuing occurs in qml.ctrl among other functions

doc/development/adding_operators.rst, doc/introduction/inspecting_circuits.rst, doc/introduction/operations.rst, doc/releases/changelog-0.39.0.md, pennylane/ops/op_math/controlled.py, pennylane/ops/op_math/controlled_ops.py, pennylane/ops/op_math/linear_combination.py, pennylane/ops/op_math/pow.py, pennylane/ops/qubit/hamiltonian.py, pennylane/ops/qubit/non_parametric_ops.py, pennylane/ops/qubit/parametric_ops_multi_qubit.py, pennylane/ops/qubit/parametric_ops_single_qubit.py, pennylane/ops/qubit/qchem_ops.py, pennylane/queuing.py, pennylane/tape/qscript.py, pennylane/tape/tape.py, pennylane/templates/embeddings/iqp.py, pennylane/templates/subroutines/aqft.py, pennylane/templates/subroutines/qft.py, pennylane/transforms/convert_to_numpy_parameters.py, pennylane/transforms/zx/converter.py, tests/ops/op_math/test_adjoint.py, tests/ops/op_math/test_controlled.py, tests/ops/op_math/test_evolution.py, tests/ops/op_math/test_exp.py, tests/ops/op_math/test_pow_op.py, tests/ops/qubit/test_non_parametric_ops.py
Reverts PennyLaneAI/pennylane#6493
=> Revert "Adding string representation for some operators"

doc/development/deprecations.rst, doc/releases/changelog-0.39.0.md
Changes to inaccurate deprecations and changelog
=> Small fixes

.github/workflows/check_in_artifact.yml, .github/workflows/docs.yml, .github/workflows/tests.yml, doc/conf.py
Docs workflow has been failing quite consistently on the step that updates the stable dependencies. This PR updates the workflow to use the new `check_in_artifact.yml` workflow for the dependency update instead of doing it on its own.
Successful workflow run [here](https://github.com/PennyLaneAI/pennylane/actions/runs/11725687588)
Successful stable deps PR [here](https://github.com/PennyLaneAI/pennylane/pull/6547)
[sc-77818]
=> Fix docs workflow

doc/releases/changelog-dev.md, pennylane/workflow/qnode.py
As the name suggests! 😅 
[sc-76836]
=> Fix `qtape/tape` deprecation warning

doc/releases/changelog-dev.md
I forgot to add a changelog entry to https://github.com/PennyLaneAI/pennylane/pull/6701 (Oooooooops)
=> Add changelog entry for previous PR

.github/workflows/tests-labs.yml
**Context:**
Somehow failing CI tests were merged. This PR fixes these tests.
Modified H2S.hdf5 file to have the appropriate data. Modified github workflow file to import the appropriate plugins.
=> Bug fix to address failures in labs CI for PES generation

pennylane/labs/vibronic/v2/matrix_ops.py, pennylane/labs/vibronic/v2/test_matrix.py, pennylane/labs/vibronic/v2/utils.py, pennylane/labs/vibronic/v2/vibronic_hamiltonian.py, pennylane/labs/vibronic/v2/vibronic_matrix.py, pennylane/labs/vibronic/v2/vibronic_tree.py
=> matrix norm method

pennylane/devices/default_tensor.py, pennylane/templates/embeddings/amplitude.py
Description of changes in commit messages
=> Mudit's documentation fixes for v0.40.0

.github/workflows/tests.yml
=> Update test workflow to be skipped for docs branch

doc/releases/changelog-0.40.0.md
This PR will be a landing page for other PRs for individual changelog sections
=> v0.40 Changelog

.github/stable/external.txt, pennylane/compiler/compiler.py, setup.py
Don't merge until Lightning and Catalyst are released.
=> Bump minimum Lightning and Catalyst versions

pennylane/labs/vibronic/vibronic/vibronic_matrix.py, pennylane/labs/vibronic/vibronic/vibronic_tree.py
=> Vibronic sparse

pennylane/labs/vibronic/hamiltonians/benchmark.py, pennylane/labs/vibronic/tests/test_norms.py, pennylane/labs/vibronic/vibronic/vibronic_tree.py
=> switch to generators

pennylane/labs/vibronic/hamiltonians/benchmark.py, pennylane/labs/vibronic/tests/test_matrix.py, pennylane/labs/vibronic/tests/test_norms.py, pennylane/labs/vibronic/vibronic/vibronic_hamiltonian.py, pennylane/labs/vibronic/vibronic/vibronic_matrix.py, pennylane/labs/vibronic/vibronic/vibronic_tree.py
refactor sparse into optional feature
=> make sparse an optional feature

doc/code/qml_pauli.rst, pennylane/fourier/reconstruct.py, pennylane/labs/dla/cartan_subalgebra.py, pennylane/labs/dla/lie_closure_dense.py, pennylane/labs/dla/structure_constants_dense.py, pennylane/labs/dla/variational_kak.py, pennylane/optimize/qnspsa.py, pennylane/pauli/dla/center.py, pennylane/pauli/dla/lie_closure.py, pennylane/pauli/dla/structure_constants.py, pennylane/pulse/__init__.py, pennylane/shadows/__init__.py, pennylane/shadows/classical_shadow.py
Fixing static links to demos in the PL repo
=> Fix static demo links in docs

doc/releases/changelog-dev.md, pennylane/data/data_manager/__init__.py, pennylane/devices/capabilities.py, pennylane/ops/op_math/decompositions/two_qubit_unitary.py, pennylane/qchem/dipole.py, pennylane/qchem/vibrational/taylor_ham.py, pennylane/qcut/utils.py, pennylane/templates/subroutines/all_singles_doubles.py, pennylane/workflow/interfaces/jax_jit.py, tests/data/data_manager/test_dataset_access.py, tests/qchem/test_dipole.py, tests/qchem/vibrational/test_taylor_ham.py
**Context:**
After running the latest version of `pylint` on our codebase, several important errors were highlighted. 
This PR updates the source code to follow best practices.
**Description of the Change:** 
Restructured some logic to fix certain errors.
**Benefits:** Improved code quality.
**Possible Drawbacks:** `too-many-arguments` and `too-many-positional-arguments` will not be addressed in this PR.
[sc-84776]
=> Fix certain `pylint=3.3.4` errors in source code

.github/workflows/tests-gpu.yml
**Context:**
Same as https://github.com/PennyLaneAI/pennylane/pull/7005, but for gpu test yml file
**Benefits:**
=> Update `tests-gpu.yml` file 

doc/releases/changelog-dev.md, pennylane/devices/default_tensor.py
Default tensor docs differentiation clarification.
I didn't do any of the checks below.
=> Default tensor docs differentiation clarification

doc/releases/changelog-dev.md, pennylane/ops/qubit/matrix_ops.py
=> Docfix qubit unitary

doc/development/release_notes.md, doc/releases/changelog-dev.md, pennylane/_version.py
- **Remove rc0 from version number**
- **Changes to set up 0.42.0 dev branch**
=> 0.42.0 setup

doc/releases/changelog-0.41.0.md
**Context:** v0.41 changelog
**Description of the Change:** Program capture
**Benefits:**
=> v0.41 changelog: program capture

doc/releases/changelog-0.41.0.md
**Context:** v0.41 changelog
**Description of the Change:** Just decompositions
**Benefits:**
=> v0.41.0 changelog: decomps

doc/releases/changelog-0.41.0.md
v0.41 changelog: QROM state prep and qml.liealg examples
=> v0.41 changelog: QROM state prep and qml.liealg examples

doc/releases/changelog-0.41.0.md
=> Changelog: add qualtran and sparse execution

doc/releases/changelog-dev.md, pennylane/ops/qubit/non_parametric_ops.py, tests/ops/qubit/test_non_parametric_ops.py
**Context:**
**Benefits:**
Fixes https://github.com/PennyLaneAI/pennylane/issues/7359
[sc-90233]
=> [BugFix] Fix powers of ISWAP and SISWAP

pennylane/ops/functions/eigvals.py, pennylane/qchem/factorization.py, tests/fermi/test_bravyi_kitaev.py, tests/fermi/test_parity_mapping.py
**Context:**
As title
**Benefits:**
This helps a lot when developers search for the correct method!
=> spell check: `tranform` -> `transform`

doc/development/deprecations.rst, doc/releases/changelog-dev.md, pennylane/__init__.py
**Context:**
Forgot to add this information in https://github.com/PennyLaneAI/pennylane/pull/7292.
- Add section to changelog
- Add section to `deprecations.rst`
**Benefits:** Better UX.
=> add deprecation information for new `exceptions` module

doc/development/deprecations.rst, doc/releases/changelog-dev.md, pennylane/drawer/mpldrawer.py
**Context:**
Rendering issue,
**Benefits:** 
Now renders correctly,
=> fix rendering in `deprecations.rst`

pennylane/labs/resource_estimation/ops/qubit/parametric_ops_single_qubit.py, pennylane/labs/tests/resource_estimation/ops/qubit/test_parametric_ops_single_qubit.py
**Context:**
Add single qubit ResourceOperators
**Benefits:**
[sc-91013]
=> Add single qubit operators

pennylane/liealg/structure_constants.py
**Context:**
Latest `autoray` release broke our CI. This PR updates the source code to fixes a work-around we had.
[sc-95004]
=> update `math.diagonal` call in `structure_constants.py` to work with latest `autoray` version

pennylane/ops/functions/assert_valid.py
=> Explicitly list out kwargs in `assert_valid`

doc/releases/changelog-dev.md, pennylane/templates/subroutines/mod_exp.py, tests/templates/test_subroutines/test_mod_exp.py
**Context:** We would like the ModExp to have a quantum function based decomposition that is compatible with the new decomposition system.
**Description of the Change:** Adds a quantum function based decomposition and resource keys, params.
**Benefits:** Makes the template compatible with the new system.
**Related ShortCut Stories:** [sc-94488]
=> ModExp qfunc decomp

doc/releases/changelog-dev.md, pennylane/templates/subroutines/mod_exp.py, pennylane/templates/subroutines/multiplier.py, tests/templates/test_subroutines/test_mod_exp.py, tests/templates/test_subroutines/test_multiplier.py
**Context:** We would like the Multiplier to have a quantum function based decomposition that is compatible with the new decomposition system.
**Description of the Change:** Adds a quantum function based decomposition and resource keys, params.
**Benefits:** Makes the template compatible with the new system.
**Related ShortCut Stories:** [sc-94486]
=> Multiplier qfunc decomp

doc/development/deprecations.rst, doc/releases/changelog-dev.md
**Context:**
Weird merge conflict artifact after https://github.com/PennyLaneAI/pennylane/pull/7928/files.
=> fix outdated entry in `deprecations.rst` page

doc/releases/changelog-dev.md, pennylane/shadows/classical_shadow.py
side-quest for https://github.com/PennyLaneAI/pennylane/issues/7970
=> fix docs in ClassicalShadow.entropy

README.md, doc/releases/changelog-dev.md
**Context:**
Links with `.html` lead to 404 pages.
[sc-98494]
=> chore: update links in `README.md` to be correct

pennylane/labs/tests/trotter_error/product_formulas/test_bch.py, pennylane/labs/trotter_error/product_formulas/bch.py, pennylane/labs/trotter_error/product_formulas/error.py
Reverts PennyLaneAI/pennylane#8062
=> Revert "Trotter error: top-k important commutators"

doc/releases/changelog-dev.md, pennylane/workflow/_setup_transform_program.py, pennylane/workflow/construct_execution_config.py, pennylane/workflow/construct_tape.py, pennylane/workflow/get_best_diff_method.py, pennylane/workflow/qnode.py, pennylane/workflow/resolution.py, pennylane/workflow/run.py
**Context:**
Easy PR to just add some type hints in our workflow module.
**Benefits:** Better static type checking
=> chore: improve type hinting in `workflow` module

pennylane/devices/qubit/dq_interpreter.py, pennylane/liealg/horizontal_cartan_subalgebra.py, pennylane/noise/mitigate.py, tests/ops/op_math/test_controlled.py, tests/ops/op_math/test_decompositions.py
**Context:**
**Benefits:**
[sc-99495]
=> Resolve some old todo comments

doc/releases/changelog-dev.md, pennylane/workflow/construct_batch.py, tests/workflow/test_construct_batch.py
**Context:**
This was a local helper that is no longer getting used. We are fine to just get rid of it.
**Benefits:**
=> Remove `workflow.construct_batch.expand_fn_transform`

pennylane/math/decomposition.py
=> Use dtype-specific machine epsilon for small perturbation

doc/releases/changelog-dev.md, pennylane/workflow/construct_batch.py, pennylane/workflow/construct_tape.py
=> update documentation to add sphinx deprecation warning for `level=None`

pennylane/estimator/templates/subroutines.py, pennylane/liealg/horizontal_cartan_subalgebra.py, pennylane/ops/op_math/decompositions/unitary_decompositions.py
**Context:**
Some templates had an outdated function signature for the recently updated `resource_decomp` method.
=> Fix the function docstring of the `resource_decomp` method for some templates

.github/workflows/upload-nightly-rc-release.yml, pennylane/_version.py
Script loses context of the RC branch.
=> fix nightly rc release script
