PennyLaneAI/pennylane

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/measurements/classical_shadow.py
tests/measurements/test_classical_shadow.py

**Context:**
The `seed_recipes` argument has been deprecated since v0.28 and was scheduled to be removed in v0.30
* Removed `seed_recipes` argument from `classical_shadow` and `shadow_expval`
**Benefits:**

Remove `seed_recipes` argument from `classical_shadow` and `shadow_expval`

---

doc/releases/changelog-dev.md
pennylane/operation.py
tests/test_operation.py

Currently, `Operator` converts tuples to `np.ndarray`  upon initialization:
```
>>> op = qml.BasisState([1,0], wires=(0,1))
>>> op.data
[array([1, 0])]
```
But it does not do the same thing with tuples. Somehow previously, operators like `BasisState` could accept tuples as their parameters, and at some point (we think in `Unwrap`), they got converted to the expected `np.ndarray`.  Since this no longer happens in `Unwrap`, we now explicitly convert tuples to numpy arrays as well.
Lightning tests used tuples, and thus expected this behaviour to still exist. Instead of changing those tests, I think it makes to continue accept tuples in addition to just lists.
Note: I moved some things around in `test_operation.py` so the tests would be a little bit better organized.

`Operator` converts `tuple` to `np.ndarray`

---

doc/releases/changelog-dev.md
pennylane/math/multi_dispatch.py
pennylane/math/single_dispatch.py
pennylane/measurements/expval.py
tests/devices/qubit/test_measure.py
tests/math/test_multi_dispatch.py

In PR #3903 I was enocuntering problems with differentiating the result of measuring a Hamiltonian when coefficients were marked with `requires_grad=False`.
The source of the problem was `qml.math.dot`. Even when the inputs were autograd arrays or array boxes, the output would be a numpy array, not an autograd array. This would then confuse autograd downstream of that operation. This fixes that problem and unblocks #3903 .

Fix `qml.math.dot` for autograd

---

doc/releases/changelog-dev.md
pennylane/_version.py
pennylane/pulse/__init__.py
pennylane/pulse/transmon.py

Making `drive` non user-facing.
Pro:
- functionality already provided by `rydberg_drive` or `transmon_drive(amp, phase, 0, wires)`
- less maintenance
Con:
- one off extra work: for code quality it would make sense to remove the function alltogether and just have `rydberg_drive`
- lose the nice "theoretical background page that relates the Hamiltonians for different conventions / fields (though could still keep/move those in `rydberg_drive` and `transmon_drive`
Background:
Originally thought we could unify all drives because they are doing the same. While this is indeed the case, it makes sense to have different functions for different physical systems because conventions are different. I.e. for Rydberg atoms where all qubits have the same energy gap, it makes more sense to talk about …

Make `drive` non user-facing

---

pennylane/templates/subroutines/qsvt.py
tests/templates/test_subroutines/test_qsvt.py

**Context:**
Calling `qml.matrix(qml.qsvt(*args))` gave the incorrect matrix.
Updated `qml.QSVT.compute_matrix` to use the equation operation order when computing the matrix.
**Benefits:**
QSVT now gives the correct matrix

Reverse operation order in QSVT compute_matrix, update tests

---

doc/releases/changelog-0.30.0.md
pennylane/operation.py
pennylane/ops/qubit/hamiltonian.py
tests/ops/qubit/test_hamiltonian.py
tests/test_operation.py

Currently we have:
```
>>> H = qml.PauliX(0) + qml.PauliY(0)
>>> t = qml.PauliZ(1) @ qml.PauliZ(2)
>>> H @ t
(2) [Y0 X0 Z1 Z2]
>>> t @ H
PauliY(wires=[0]) @ PauliX(wires=[0]) @ PauliZ(wires=[1]) @ PauliZ(wires=[2]) @ <Hamiltonian: terms=2, wires=[0]>
```
Which are both wrong. 
This PR makes it so the above will be correct. The lightning tests were expecting to be able to multiply tensors and hamiltonians, so this PR is necessary to get their tests passing.

Fix tensors multiplying Hamiltonians

---

doc/releases/changelog-0.30.0.md
pennylane/ops/qubit/matrix_ops.py

This PR slightly modifies the initial lines of the docstrings of `DiagonalQubitUnitary` and `QubitUnitary` in order to clarify that their inputs actually are trainable, and not fixed.

Clarify `(Diagonal)QubitUnitary` docstrings regarding trainability

---

doc/releases/changelog-0.30.0.md
pennylane/ops/op_math/controlled.py
tests/ops/op_math/test_controlled.py
tests/ops/op_math/test_controlled_decompositions.py

Due to a problem found by @KetpuntoG in comparing default qubit and lightning:
```
dev = qml.device("lightning.qubit", wires = 2)
def circuit():
qml.Hadamard(wires = 0)
qml.QuantumPhaseEstimation(qml.matrix(qml.Hadamard)(wires = 0), [0], [1])
return qml.probs(wires = [0,1])
circuit()
```
We discovered that the global phase ignored by the new decompositions does in fact change the results in certain situations.
Therefore as a quick fix before the release, we are turning off the fancy decompositions. When we have a way to handle the global phase, we can add it back in.

Remove fancy ctrl decomps

---

setup.py

This PR bumps the required lightning version to v0.30.
This will not work until the lightning wheels have been uploaded to PyPI. Once that happens, this PR can be merged.  Then we can create the PL release.

bump lightning version to 0.30

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/__init__.py
pennylane/devices/qubit/sampling.py
tests/devices/qubit/test_sampling.py

**Context:**
Part of the effort to integrate the new device API.
Add a new function in `devices/qubit/sampling.py` that takes as input a `SampleMeasurement` and a state, and returns the result of that measurement.
**Benefits:**
This function can be called from `simulate()` to get the sample measurement results.
None

Add sample measurement function for new device API

---

doc/releases/changelog-dev.md
pennylane/interfaces/autograd.py

This patch of code is for making PL compatible with the `pennylane-sf` plugin.  Given the plugin will not be supported by pennylane v0.30 and above, we no longer need this patch.

Remove patch for the pennylane-sf plugin

---

doc/introduction/operations.rst

As the title says, `qml.CH` was missing from the list of operations on the "operations" page.

Add CH to the list of operations

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/sampling.py
pennylane/measurements/shots.py
tests/devices/qubit/test_sampling.py
tests/measurements/test_shots.py

**Context:**
Part of the effort to integrate the new device API.
Add shot-vector support to `measure_with_samples` in `devices/qubit/sampling.py`.
**Benefits:**
This function can now be called from `simulate()` with shot vectors.
None

Add shot vector support to sample measurements

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/measure.py
pennylane/devices/qubit/sampling.py
pennylane/devices/qubit/simulate.py
tests/devices/experimental/test_default_qubit_2.py
tests/devices/qubit/test_sampling.py
tests/devices/qubit/test_simulate.py

**Context:**
Part of the effort to integrate the new device API.
Update `simulate.py` to work with sample-based measurements.
**Benefits:**
Progress on integrating new device API 🎉

Integrate sample-based measurement with `simulate`

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/preprocess.py
pennylane/gradients/hadamard_gradient.py
pennylane/gradients/pulse_gradient.py
pennylane/ops/functions/simplify.py
pennylane/qinfo/transforms.py
pennylane/shadows/transforms.py
pennylane/transforms/convert_to_numpy_parameters.py
pennylane/transforms/hamiltonian_expand.py
pennylane/transforms/qfunc_transforms.py
pennylane/transforms/sign_expand/sign_expand.py
tests/devices/qubit/test_preprocess.py
tests/gradients/core/test_hadamard_gradient.py
tests/gradients/core/test_pulse_gradient.py
tests/ops/functions/test_simplify.py
tests/qinfo/test_fisher.py
tests/transforms/test_convert_to_numpy_parameters.py
tests/transforms/test_hamiltonian_expand.py
tests/transforms/test_qfunc_transform.py
tests/transforms/test_sign_expand.py

**Context:**
Recently the `shots` attribute was put onto the `QuantumScript` class. Most of the transforms in the PennyLane repo have yet to be updated for this change.
Update the tape transforms to copy the `shots` attribute when creating a new tape.
**Benefits:**
Tape transforms now work fully with the new location of `shots`.
None

Update tape transforms to copy `shots` attribute

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/preprocess.py
tests/devices/qubit/test_preprocess.py

**Context:**
Part of the effort to integrate the new device API. Support for sample-based measurements was recently added 🎉
Add a new validation check to `preprocess.py`. This checks if analytic executions only contains `StateMeasurements` and finite-shot executions only contains `SampleMeasurements`.
**Benefits:**
Feedback is provided to the user if an invalid set of measurements (e.g. state and sample) is executed.
Might be slightly slower, but this is a one-time check at the start of the execution.

Add measurement validation to `preprocess.py`

---

pennylane/devices/experimental/default_qubit_2.py
pennylane/devices/experimental/device_api.py
tests/devices/experimental/test_default_qubit_2.py
tests/devices/experimental/test_device_api.py

I initially didn't add tests for the `experimental.Device` interface, as any class that implements this interface should test the behaviour of all methods.
But at the end of the day, it doesn't hurt to test the "default" behavior of the interface.
This even allowed me to find some minor changes that needed to be made, such as:
*  changing the `isisntance` check to `QuantumScript` instead of `QuantumTape`
* defaulting the `execution_config` to `None` instead of `DefaultExecutionConfig` for the `supports_*` methods
Mostly, this will keep us from getting code coverage complaints every time we tweak the `device_api.py` file.

Adds tests for the `experimental.Device` abstract base class

---

.pre-commit-config.yaml

It sucks as is. CI will still fail if you violate our test linting requirements, but this doesn't happen often enough to merit enduring this pre-commit hook. Making a better hook is non-trivial as it stands, so we can look into this later. I'll open a draft PR once this is merged and see what I can do, but for now, we should disable it

remove the pylint test pre-commit hook

---

.github/workflows/tests.yml
requirements-ci.txt

This was added in #3276 to allow for 3.11 support, but now the wheels exist (cvxopt/cvxopt#228)! I'm just un-doing the changes done in that python upgrade PR.

always install cvxpy/cvxopt in test CI now that there are 3.11 wheels

---

doc/releases/changelog-dev.md
pennylane/devices/experimental/default_qubit_2.py
tests/devices/experimental/test_default_qubit_2.py

**Context:**
Part of the effort to integrate the new device API. Support for sample-based measurements was recently added 🎉, and the API allowed for passing in a `np.Generator` object.
Add a `seed` keyword argument to the `__init__` method of `DefaultQubit2`. This is used to create a `np.Generator` object within the device upon initialization. This generator would then be passed to downstream calls of `simulate`.
**Benefits:**
Allows the user to seed the random number generator at the device level 🎉 
None

Allow `DefaultQubit2` to be initialized with a random seed

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/sampling.py
pennylane/measurements/sample.py
tests/devices/experimental/test_default_qubit_2.py
tests/devices/qubit/test_sampling.py

**Context:**
Part of the effort to integrate the new device API. Support for sample-based measurements was recently added, though currently it doesn't allow for `Hamiltonian` and `Sum` observables.
Extend the `measure_with_samples` function to be able to handle these cases. We simply sum over the results for each term in the object.
**Benefits:**
The user can now use `Hamiltonian` and `Sum` observables with finite shots. 🎉 
None

Allow `Hamiltonian` and `Sum` observables in sample measurements

---

pennylane/qnn/torch.py
tests/legacy/qnn/test_qnn_torch_old.py
tests/qnn/test_qnn_torch.py

**Context:**
`TorchLayer` is already able to be saved using the usual PyTorch syntax.
Add documentation on how to do it. Also add tests in case it breaks in the future.

Add documentation and tests for `TorchLayer` saving

---

doc/releases/changelog-dev.md
pennylane/_device.py
pennylane/gradients/finite_difference.py
pennylane/gradients/gradient_transform.py
pennylane/gradients/hadamard_gradient.py
pennylane/gradients/jvp.py
pennylane/gradients/parameter_shift.py
pennylane/gradients/pulse_gradient.py
pennylane/gradients/spsa_gradient.py
pennylane/gradients/vjp.py
pennylane/measurements/shots.py
pennylane/optimize/shot_adaptive.py
tests/measurements/test_shots.py

**Context:**
The gradients module needs updating to the new Shots class, so this does that. Once the interfaces module does this as well, we'll be near rid of any old Shots usage internally.
- Add a `num_copies` property to the `Shots` class, as various gradient methods were computing it on their own before
- Update all gradients to use the new `Shots` type internally. The outward-facing functions (eg. `qml.gradients.param_shift`) accept vanilla python types and cast to a `Shots` object for you so the user doesn't need to know, but the private functions across the module now expect a strongly-type `Shots` object
- Little fix-up to `shot_adaptive` for the case where it set `device.shot_tuple = [(1, 1)]`. The old shots "API" considered this to be partitioned …

use Shots class in gradients module

---

doc/releases/changelog-dev.md
pennylane/pauli/utils.py
tests/ops/qubit/test_hamiltonian.py
tests/pauli/test_pauli_utils.py

Fixes #4155 
```
>>> binary_repr = qml.pauli.pauli_to_binary(qml.Identity("b"), wire_map={"a": 0, "b": 1})
>>> qml.pauli.binary_to_pauli(binary_repr, wire_map={"a": 0, "b": 1})
Identity(wires=['a'])
```
Converting an `Identity` to a binary form and back removes the wires it was originally on.  This causes problems when computing the grouping indices on a Hamiltonian because the original operation and the returned operation are no longer the same.
This problem can be circumvented by making all identities identical:
```
>>> qml.pauli.are_identical_pauli_words(qml.Identity("a"), qml.Identity("b"))
True
```
Given the two terms do inherently represent the same thing, this decision should be fine.

Treat identities as equivalent in `pauli.are_identical_pauli_words`

---

doc/releases/changelog-dev.md
pennylane/pauli/conversion.py
pennylane/pauli/pauli_arithmetic.py
tests/pauli/test_conversion.py
tests/pauli/test_pauli_arithmetic.py

**Context:**
Fixes an issue where empty hamiltonians `qml.Hamiltonian([], [])` could not be converted to PauliSentences via `qml.pauli_sentence()`. 
- Add check for empty hamiltonian and return empty PauliSentence (PS)
- Fix print for empty PS, "I" --> "0 * I". Since an empty PS is the null operator.
Fixes https://github.com/PennyLaneAI/pennylane/issues/4134

Empty hamiltonians are compatible with `qml.pauli_sentence()`

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/sampling.py
pennylane/measurements/counts.py
tests/devices/experimental/test_default_qubit_2.py
tests/measurements/test_counts.py

**Context:**
Part of the effort to integrate the new device API. Most measurements are supported with only a few weird edge cases (including counts).
Previous behaviour:
```
>>> dev = DefaultQubit2()
>>> qs1 = qml.tape.QuantumScript([qml.RY(1.4, wires=0)], [qml.counts(wires=[0, 1])], shots=15)
>>> dev.execute(qs1)
{'FalseFalse': 9, 'TrueFalse': 6}
>>> qs2 = qml.tape.QuantumScript([qml.RY(1.4, wires=0)], [qml.counts(qml.PauliZ(0))], shots=15)
>>> dev.execute(qs2)
{tensor(-1, requires_grad=True): 10, tensor(1, requires_grad=True): 5}
```
New behaviour:
```
>>> dev = DefaultQubit2()
>>> qs1 = qml.tape.QuantumScript([qml.RY(1.4, wires=0)], [qml.counts(wires=[0, 1])], shots=15)
>>> dev.execute(qs1)
{'00': 9, '10': 6}
>>> qs2 = qml.tape.QuantumScript([qml.RY(1.4, …
```

Fix `qml.counts` measurement in new device

---

doc/releases/changelog-dev.md
pennylane/interfaces/jax.py
pennylane/interfaces/jax_jit_tuple.py
tests/interfaces/test_jax.py

**Context:**
The jax code was wrongly iterating over `[[res1, res2, ...], jacs]` instead of `[res1, res2, ...]` but it slipped by undetected because you'd need 3 or more tapes to be executed to hit an IndexError.
Remove the unnecessary tracing stuff and match what jax-jit does.
**Benefits:**
Code now works as expected
It's a bit hacky, but it gets the job done.

do the same in jax as in jax-jit for getting results in execute_fwd

---

doc/releases/changelog-dev.md
tests/qinfo/test_entropies.py
tests/qinfo/test_fidelity.py
tests/qinfo/test_purity.py
tests/qinfo/test_reduced_dm.py
tests/qinfo/test_trace_distance.py

Currently the quantum information functions in `qml.math` and the QNode transforms in `qml.qinfo` do not support broadcasting. Support for this will be added in a sequence of 3 PRs, of which this is the last. The individual aims of the PRs are roughly:
1. (done) Split `qml.math.reduced_dm` into two functions, `qml.math.reduced_dm_from_sv` and `qml.math.reduced_dm_from_dm`, each of which supports broadcasting. Also begin a deprecation cycle for `qml.math.reduced_dm`. [#4173](https://github.com/PennyLaneAI/pennylane/pull/4173)
2. (done) Support broadcasting for each of the remaining quantum info functions in `qml.math`. Also change their signatures to accept only a density matrix, and begin a deprecation cycle for passing in state vectors. …

[QInfo broadcasting (3/3)] Support quantum information QNode transforms

---

doc/development/adding_operators.rst
doc/releases/changelog-dev.md
pennylane/operation.py
pennylane/ops/channel.py
pennylane/ops/op_math/prod.py
pennylane/ops/op_math/sum.py
pennylane/ops/qubit/matrix_ops.py
pennylane/ops/qubit/parametric_ops_multi_qubit.py
pennylane/qchem/dipole.py
pennylane/qchem/hamiltonian.py
pennylane/qchem/hartree_fock.py
pennylane/qchem/integrals.py
pennylane/qchem/matrices.py
pennylane/templates/subroutines/qsvt.py

**Context:**
The documentation about [adding operators](https://github.com/PennyLaneAI/pennylane/blob/master/doc/development/adding_operators.rst?plain=1#L98) and [`Operator.compute_matrix()`](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/operation.py#L708) contain some confusing notes.
Variable-length argument lists (e.g. `foo(*args)`) are not always indicated in the respective docstrings.
The documentation is improved. Variable-length argument lists are indicated according to the [Google Styleguide](https://google.github.io/styleguide/pyguide.html).
**Benefits:**
Users can understand more easily how to pass arguments to functions and methods. Confusing notes are resolved.
n/a
n/a

Fix unclear documentation and indicate variable-length argument lists.

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/sprod.py
pennylane/ops/op_math/symbolicop.py
tests/ops/op_math/test_sprod.py

Fixes #4248 . [sc-40236]
Basically, tensorflow will not perform type promotion when things of two different types are multiplied.  Since the matrices for `PauliX` and `PauliZ` are integers, when multiplied by anything else, the resulting matrix is integer.  So we need to do manual type promotion on *both* the scalar and the matrix, not just the scalar.
Problematic example:
```
>>> op = tf.Variable(0.1) * qml.PauliX(0)
>>> op.matrix()
<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[0, 0],
[0, 0]])>
```

fix sprod matrix

---

doc/releases/changelog-dev.md
pennylane/interfaces/torch.py
tests/interfaces/default_qubit_2_integration/test_torch_default_qubit_2.py

**Context:**
Integrating the interfaces with the new device interface. Same as #4137, but with torch!
- Convert tuples to lists when changing them in place, but otherwise nothing in code
- add tests
**Benefits:**
Torch works with the new device interface
some tests feel a bit more silly, like using a lambda (as the torch docs recommend) to skip non-trainable params when computing the jacobian, and then asserting that the non-trainable param had no effect on the jacobian. but that's the beauty of torch:) had to skip a few tests for not being torch-y

torch integration for DefaultQubit2

---

pennylane/fermi/conversion.py
pennylane/qchem/observable_hf.py

**Context:**
The call signature in docs for `jordan_wigner` is ugly due to `singledispatch`
Nest the dispatching inside the function so that sphinx doesn't make the call signature at the top ugly

move dispatching into function to fix docstrings

---

doc/releases/changelog-dev.md
pennylane/fermi/fermionic.py
tests/fermi/test_fermionic.py

**Context:**
This should work in principal:
```
k = np.array([2.0, 3.0])
k[0] * FermiC(1)
```
but if its a `pennylane.numpy` array it raises an error at `len(k[0])`
Use `qml.math.size` instead of `len`

Fix bug in fermi op arithmetic for np.array([1, 2])[0]

---

doc/releases/changelog-dev.md
pennylane/ops/functions/bind_new_parameters.py
tests/ops/functions/test_bind_new_parameters.py

**Context:**
Some template operations and other operators whose `data` does not match the parameters of the class interface were causing `bind_new_parameters` to break.
* Added `bind_new_parameters` dispatch for `PCPhase`, `ApproxTimeEvolution`, `CommutingEvolution`, `FermionicDoubleExcitation`.
**Benefits:**
`bind_new_parameters` will not fail for the operators mentioned above.

Add more registered dispatches to `bind_new_parameters`

---

doc/releases/changelog-0.31.0.md
pennylane/devices/default_qubit.py
tests/devices/test_default_qubit.py

**Context:**
Thanks to the recent change #4251, trainable parameters in `Sum` objects are now supported also when taking the `expval` of these operators.
The changed execution path uses the `pennylane.devices.qubit.measure.measure` without the `is_state_batched` argument.
This PR adds the `is_state_batched` argument to the `measure` call, adding support for broadcasted QNodes that take `expval(Sum)`.
**Benefits:**
Fixes broadcasted expvals of `Sum` instances.
N/A
Fixes #4274

Fix `expval` of `Sum` with broadcasting

---

pennylane/pauli/utils.py
pennylane/transforms/core/transform.py
pennylane/transforms/decompositions/single_qubit_unitary.py

Minor documentation changes to these 3 functions.
For `is_pauli_word`, the usage of `singledispatch` caused the function to appear multiple times in the documentation builds:
To fix this, the `singledispatch` decorator was moved to decorate a private function instead. This function is called from `is_pauli_word`.

Documentation fixes to `is_pauli_word`, `transform`, and `one_qubit_decomposition`

---

doc/development/deprecations.rst
pennylane/qchem/convert.py
pennylane/qchem/observable_hf.py
pennylane/qchem/tapering.py
pennylane/transforms/qcut/cutcircuit.py
setup.py

- The URL in setup.py is old (and because I changed it, the pylint pre-commit hook made me add a docstring)
- deprecations.rst needs ReST code-blocks, not markdown
- qchem/convert.py had an example that didn't render because it needed a new line
- the rest of the QChem changes are just to fix links to other classes in public functions
- The QCut PR itself was fine, but got me thinking I should validate the existing QCut doc. minor touch-ups there

Various things while validating changes for 0.31

---

doc/releases/changelog-0.31.0.md
pennylane/fermi/__init__.py
pennylane/fermi/fermionic.py
tests/fermi/test_fermionic.py

**Context:**
The function  `string_to_fermi_word` is renamed to `from_string` for user convenience. 
**Benefits:**

Rename `string_to_fermi_word` to `from_string`

---

doc/development/deprecations.rst
pennylane/ops/qubit/matrix_ops.py
pennylane/qnn/keras.py
tests/ops/qubit/test_matrix_ops.py

* Updated `KerasLayer` docstring to change shape in example to `TensorShape` from tuple.
* Updated `DiagonalQubitUnitary.compute_decomposition` to correctly calculate the coefficients if the diagonal is of a real dtype by casting to `complex128`.
* Updated `deprecations.rst` for grammar.
**Benefits:**

Minor fixes for v0.31

---

.readthedocs.yml

The class inheritance diagram [stopped rendering](https://docs.pennylane.ai/en/latest/code/qml_tape.html#class-inheritance-diagram) for the tape module ever since changing the base image for the RTD builder (#4086, which was needed for a bugfix re: SSL packages being installed). readthedocs/readthedocs.org#8800 suggests that this should fix it

Add graphviz apt

---

pennylane/operation.py

**Context:**
Currently the `compute_eigvals` method in operators contains the note "See also eigvals and eigvals." (e.g. [here](https://docs.pennylane.ai/en/stable/code/api/pennylane.U3.html#pennylane.U3.compute_eigvals))
Link one to the method `eigvals` of the respective class and the other one directly to `pennylane.eigvals()`.

Make links to qml.eigvals and the eigvals method appear distinctly.

---

doc/releases/changelog-dev.md
pennylane/drawer/mpldrawer.py
tests/drawer/test_mpldrawer.py

**Context:**
While working on `MPLDrawer.cond`, I realized that the the drawing of controlled ops will hide control indicators if they are between target wires.
Raise a warning if some control indicators are not visible in `draw_mpl`
**Benefits:**
The user will not have to wonder why their circuit drawing isn't identical to their circuit
The circuit drawing is still incorrect
Fixes #4221

raise warning if control indicators are hidden in drawer

---

pennylane/ops/op_math/__init__.py

In the current docs build, the controlled operations `qml.CY`, `qml.CZ` and `qml.ControlledQubitUnitary` have duplicate entries: one for `qml` and one for `qml.ops.op_math`.
This change removes the second one. This way, the doc links in the qml/ops/op_math point to the unique `qml.` entry.

remove duplicate controlled operation entries

---

pennylane/qnn/keras.py
pennylane/qnn/torch.py

The docstring for `TorchLayer` and `KerasLayer` classes currently refer to ```func:`~.Qnode` ```, while actually referring to the class.

ML layers docstring typo

---

doc/requirements.txt
pennylane/qchem/integrals.py
requirements.txt
setup.py

same as #4066. ~blocked until lightning is out.~ it's out
scipy needs to be pinned because they just released a new version (1.11). Collecting tests failed at [this line](https://github.com/PennyLaneAI/pennylane/blob/d6955cf1e704b8cc9a274c843c51705d097f9a0d/tests/optimize/test_adaptive.py#L27) because it called scipy's `factorial2` somewhere along the line. That function used to return 1.0 for negative values, but returns 0 in the latest scipy. We tried a forward fix (see commits), but this came with other failures, one of which being an incompatibility with cvxpy (see scipy/scipy#18749, fix PR already proposed). So, for this release, we will pin scipy.

bump lightning to 0.31 in setup.py, pin scipy to [1.8,1.10]

---

doc/releases/changelog-dev.md
pennylane/devices/default_qutrit.py
tests/devices/test_default_qutrit.py

**Context:**
Many non-parametric qutrit operations don't have available adjoints in PennyLane, because of which using `qml.adjoint` with these operations was not working with `DefaultQutrit`.
* Added `Adjoint(op)` to list of supported operations in `DefaultQutrit`for non-parametric qutrit operations.
**Benefits:**
Adjoint operations work correctly on `DefaultQutrit`.
#4347

[BUG FIX] Add support for adjoint operations in `default.qutrit`

---

pennylane/templates/subroutines/qmc.py
pennylane/templates/subroutines/qpe.py

The docs for the QPE and QMC templates use Sphinx auto-numbered lists and aren't rendering correctly. There are other places we use auto-numbered lists, but those all render correctly. The difference between these other places and QPE/QMC is that the other lists are located in separate `Usage Details` sections, while the list for QPE/QMC is located in the top-level docstring. 
While I couldn't figure out what was causing this, I decided a workaround is to just move the list to the `Usage Details` sections. This seems more logical to me anyways since the point of the list in these two cases is to break down the template's intended usage.

Fix QPE/QMC documentation rendering

---

doc/releases/changelog-dev.md
pennylane/transforms/optimization/merge_amplitude_embedding.py
tests/transforms/test_optimization/test_merge_amplitude_embedding.py

**Context:**
If the `AmplitudeEmbeddings` inside a QNode each have a batch dimension, and that QNode is decorated with `merge_amplitude_embedding`, then the batch dimensions would not be broadcasted over correctly. This is illustrated with the below example:
```python
@qml.qnode(qml.device('default.qubit', wires=2))
@qml.transforms.merge_amplitude_embedding
def circuit(m1, m2):
qml.AmplitudeEmbedding(m1, wires=0)
qml.AmplitudeEmbedding(m2, wires=1)
return  qml.expval(qml.PauliZ(0))
m1 = np.array([[1, 0], [0, 1]])  # batch size 2
m2 = np.array([[0, 1], [1, 0]])  # batch size 2
```
```
>>> circuit(m1, m2)
tensor([ 1.,  1., -1., -1.], requires_grad=True)
```
The output above has a batch size of 4, which is incorrect.
See the Github issue below for more details. …

Support broadcasting in `merge_amplitude_embedding`

---

doc/releases/changelog-dev.md
pennylane/templates/subroutines/approx_time_evolution.py

**Context:**
The docstring of `compute_decomposition` for `ApproxTimeEvolution` is slightly misleading with the `coeffs_and_time` argument.
Adds an example to the docstring to clear things up.
https://discuss.pennylane.ai/t/approxtimeevo-decomposition-bug/3178/2

ApproxTimeEvolution.compute_decomposition docstring has example

---

doc/releases/changelog-dev.md
pennylane/interfaces/jax.py
pennylane/interfaces/jax_jit.py
pennylane/interfaces/jax_jit_tuple.py
pennylane/interfaces/tensorflow.py
pennylane/interfaces/tensorflow_autograph.py
pennylane/pulse/parametrized_evolution.py
pennylane/tape/qscript.py
tests/gradients/core/test_pulse_generator_gradient.py
tests/tape/test_qscript.py
tests/tape/test_tape.py

**Context:**
Part of the effort towards `QuantumScript` immutability. In the end we want to deprecate `QuantumScript.set_parameters` altogether.
Define a new function `bind_new_parameters_tape` that takes a tape and the new parameters, and returns a new tape. The original tape is unmodified.
Update the `jax`, `jax-jit`, `tensorflow`, and `tensorflow-autograph` interfaces to call this new `bind_new_parameters_tape` function instead of `QuantumScript.set_parameters`.

Update `interfaces` module to use `bind_new_parameters`

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/simulate.py
pennylane/gradients/jvp.py
pennylane/interfaces/jax.py
pennylane/interfaces/jax_jit_tuple.py
pennylane/tape/qscript.py
tests/gradients/core/test_jvp.py
tests/interfaces/default_qubit_2_integration/test_jax_jit_qnode_default_qubit_2.py
tests/interfaces/test_jax_jit_qnode.py

**Context:**
All interfaces should work with the new device, and that includes jax-jit!
Add jax-jit QNode support. This involved a few little things:
1. a certain simulation was missing the `is_state_batched` arg when calling `measure`, so I fixed that
2. jax-jit expected all result types to match, so I cast a bunch of things to tuples (because those are better than lists 💪)
3. The `shape_dtype` thing is a weird thing that I can't explain easily in words, but I will give the low-down. The helper function that generates shape objects says "if only 1 measurement and only 1 tape, return `shapes[0]`", but the function that interpreted it assumed that it was always a list of shape objects. This was only found because a) the new devices does some pre-processing …

Jax jit qnode integration with DefaultQubit2

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/__init__.py
pennylane/devices/qubit/adjoint_jacobian.py
tests/devices/qubit/test_adjoint_jacobian.py

**Context:**
Part of the new device capability changes. This PR is one step closer to supporting JVP and VJP computations on the device.
Add two functions to `devices/qubit/adjoint_jacobian.py`, one that computes the VJP and the other the JVP, both using the adjoint diff method and without needing the full jacobian.
Advantages:
1. Less memory usage
2. If a tangent is zero, the bra and ket corresponding to that trainable parameter do not need to be dotted, saving some computation.
3. If a cotangent is zero, the entire observable can be ignored

Add `adjoint_jvp` and `adjoint_vjp` functions for new device

---

doc/releases/changelog-dev.md
pennylane/operation.py
pennylane/ops/qubit/hamiltonian.py
tests/ops/qubit/test_hamiltonian.py
tests/ops/qutrit/test_qutrit_observables.py

**Context:**
Fixes #4341 .
* Update `Observable._obs_data()` to include the index of `qml.GellMann` in the parameter list.
* Update `Hamiltonian._obs_data()` to include the index of `qml.GellMann` in the parameter list.
<ins>**Note:**</ins>
I would still recommend using the new operator arithmetic with qutrits. The generators of parametric qutrit gates are instances of `Prod` and `Sum`, not `qml.Hamiltonian`. So, try using `qml.dot` instead of `qml.Hamiltonian` with qutrit observables.
**Benefits:**
Comparison of instances of `qml.GellMann`, `Hamiltonian`s and `Tensor`s containing `qml.GellMann` is correct.
#4341

Fix `qml.GellMann` observable data

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/controlled.py
tests/ops/op_math/test_controlled.py

**Context:**
Same motivation as #4339 (to make my tutorial look nicer), except it actually works! Turns out we don't pass the base to `ctrl` directly in `defer_measurements`, but we instead give it a lambda. So we need a callable argument to `ctrl` to also take advantage of `ctrl`'s custom logic.
Use `ctrl` instead of `Controlled` inside the wrapper function created when a callable is passed to `ctrl`
**Benefits:**
Operators queued in some callable passed to `ctrl` also get the custom processing from `ctrl`
N/A
Expands on #4339

call ctrl again if given a function; non-custom op in tests

---

doc/releases/changelog-dev.md
pennylane/fermi/conversion.py
tests/qchem/test_hamiltonians.py

**Context:**
The `jordan_wigner` function gives a type casting error when an active space is defined for the Hamiltonian. This PR fixes this issue by using correct types.
The in-place addition of the Pauli sentence in `jordan_wigner`  is modified and the new test  `test_diff_hamiltonian_active_space` is added.
**Benefits:**

Correct `jordan_wigner` to work with active space

---

doc/releases/changelog-dev.md
pennylane/interfaces/jax_jit_tuple.py

For ADR PR #67 https://github.com/PennyLaneAI/adrs/pull/67 with prototype PR #4368 I have been spending time going through `jax_jit_tuple.py` to figure out if and how we can integrate device jacobian products.
To better understand the file, I have made some stylistic improvements. So though a lot of things are moved around, the code is the exact same.
Some of these stylistic improvements include:
* A few more docstrings with examples and adding some explicit documentation on closure variables to docstrings.
* Eliminating some single line functions: `process_single_shape` and `_filter_zero_tangents`
* Switching some iterates and append patterns with function + tuple with generator pattern.
* Switch `_jac_shape_dtype_tuple` for a batch of tapes with `jac_shape_dtype_struct` for a single …

Improve readability for `interfaces/jax_jit_tuple.py`

---

pennylane/math/multi_dispatch.py
tests/devices/qubit/test_apply_operation.py

**Context:**
Autoray released a new version that changed the dispatch logic of some functions with multiple arguments, namely `add` and `multiply`. This was breaking some tests.
For `qml.math.add`, the only issue is with PyTorch since `torch.add` doesn't support NumPy arguments. The original overriden function switched the order of the arguments so that it dispatches via NumPy instead, but that doesn't work with the new autoray dispatch logic. Here we just cast both arguments to PyTorch tensors.
For `qml.math.multiply`, this is only used in one of the tests, and we simply cast the argument to `np.complex128`.

Fixes for new autoray version

---

requirements.txt
setup.py

A recent release of autoray broke some stuff, so we pin the autoray version to the one that was concurrent with the last release.

Pin autoray to 0.6.3

---

doc/releases/changelog-dev.md
pennylane/circuit_graph.py
pennylane/operation.py
pennylane/ops/functions/equal.py
pennylane/transforms/metric_tensor.py
tests/circuit_graph/test_circuit_graph.py
tests/legacy/test_legacy_qscript_old.py
tests/ops/functions/test_equal.py
tests/tape/test_qscript.py
tests/tape/test_tape.py

**Context:**
Operator `__eq__` and `__hash__` will soon be updated to return `qml.equal` and `Operator.hash` respectively. This PR removes direct and indirect uses of `Operator.__eq__` from the PennyLane codebase so that changes to the dunder methods don't cause unexpected behaviour or errors.
* Updated `CircuitGraph` to not use sets, and manually check for references rather than using `==`.
* Updated `metric_tensor` to not use `==` between Operators.
* Updated `qml.equal` to compare shadow Hamiltonians correctly for `shadow_expval` comparison.
* Updated tests accordingly.
**Benefits:**
`Operator.__eq__` and `Operator.__hash__` can be updated without breaking PennyLane.
Minor breaking changes by returning lists instead of sets in …

Changes to remove use of `Operator.__eq__`

---

pennylane/data/data_manager/foldermap.py

we were always saying "molname" as the identifier when saying an invalid one was provided.
Before:
```pycon
>>> qml.data.load("qchem", molname="H2", bondlength=100)
...
File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/data/data_manager/foldermap.py", line 168, in __getitem__
elem = self.__curr_level[__key]
KeyError: '100.0'
The above exception was the direct cause of the following exception:
...
File "/Users/matthews/src/github.com/PennyLaneAI/pennylane/pennylane/data/data_manager/foldermap.py", line 143, in find
raise ValueError(
ValueError: molname '100.0' is not available. Available values are: ['0.5', '0.54', '0.58', '0.62', '0.66', '0.7', '0.74', '0.742', '0.78', '0.82', '0.86', '0.9', '0.94', …
```

raise error with actual identifier name

---

tests/pytest.ini

**Context:** This PR fixes current …

Fixing pytest: no longer turn warning into error

---

doc/releases/changelog-dev.md
pennylane/__init__.py
pennylane/math/multi_dispatch.py
tests/test_device.py

Fix jax.ad deprecation.

---

doc/releases/changelog-0.31.1.md
pennylane/data/data_manager/__init__.py
tests/data/data_manager/test_dataset_access.py

**Context:**
Requests for datasets with '+' in the name (e.g `NH3+`) fail because '+' is a special character in URLs. This bug would also occur for other characters like '%', '$', etc
Uses `urllib.parse.quote` to replace special characters in the dataset path with their escape codes.
**Benefits:**
Can download datasets with special characters in their name.
None

Escape special characters in Dataset URL

---

pennylane/data/attributes/operator/operator.py
tests/data/attributes/operator/test_operator.py

**Context:**
Discussed on Slack, operators are queued upon deserialization, which is unexpected.
Wrap operator deserialization (in other words, construction) in a `stop_recording` context to ensure operators are not queued merely by being referenced.
**Benefits:**
User expectations are met
N/A

BUGFIX: ensure that operators are not queued upon deserialization

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/controlled_ops.py
tests/ops/op_math/test_controlled_decompositions.py

**Context:**
In #4355, we changed the way tapes get expanded. Part of this says `if op.has_decomposition: use op.decomposition()`. Unfortunately, sometimes, instances of `ControlledQubitUnitary` will report `has_decomposition=True` when it does not really have one. This is especially unfortunate because it makes [qml builds fail](https://github.com/PennyLaneAI/qml/actions/runs/5674935721/job/15379372776)
Override `ControlledQubitUnitary.has_decomposition` to double-check its truthiness by trying to get its decomposition in a try-except, returning False if a `DecompositionUndefinedError` is caught.
**Benefits:**
No more lies! qml builds pass!
If the operator _does_ have a decomposition, we have to evaluate it twice. I think the …

fix `has_decomposition` for ControlledQubitUnitary

---

doc/conf.py
doc/robots.txt

**Context:** This PR adds a new robots.txt to the output of the docs build
This stated in the context, the robots.txt file is in lieu of marking the builds in ReadTheDocs as hidden. We want the latest version of docs to show up on the flyout menu when a user goes to docs.pennylane.ai.
The robots.txt will mark the /latest and /v0.30.0/ builds as disallowed for indexing so they are not shown as results on google.
**Benefits:**
Marking builds as hidden on ReadTheDocs achieve this same behavior, but it also hides the build from the flyout menu, which is not desired in this case.
None.
N/A.

[sc-36527]: Add new robots.txt to doc build to hide latest build from search engine

---

pennylane/data/base/dataset.py
pennylane/data/data_manager/__init__.py
pennylane/data/data_manager/foldermap.py
tests/data/data_manager/test_dataset_access.py
tests/data/test_dataset.py

**Context:**
Accessing `identifiers` on a dataset for which all identifier attributes are not downloaded results in an `AttributeError`:
```
>>> dset = qml.data.load(
'qchem', 
molname='H3', 
basis='STO-3G', 
bondlength='0.5', 
attributes=['molname'])[0]
>>> dset.identifiers #AttributeError
```
`Dataset.identifiers` will only return identifiers that are available on the dataset. The above example now looks like:
```
>>> dset.identifiers
{'molname': 'H3'}
```
**Benefits:**
Removes unexpected and potentially confusing error.

Fix Attribute Error when accessing identifiers on partial dataset

---

doc/releases/changelog-dev.md
pennylane/devices/default_qubit.py
pennylane/operation.py
tests/test_operation.py

In all the matrix methods across PennyLane, we use the kwarg `wire_order` to specify the wire order to which we stick when building the matrix. However, `Tensor.sparse_matrix()` uses `wires` instead. This can cause issues in combination with other classes such as [`SProd`](https://github.com/PennyLaneAI/pennylane/blob/46745da8f78dcef4c8e8e8f4a4d41e66d87371eb/pennylane/ops/op_math/sprod.py#L247), as noted in #4411.
Here, I add a `wire_order` kwarg to the method in order to fix the compatibility issues and adhere to the convention. However, I am preserving `wires` to avoid any potential issues or nuances with already existing user pipelines, but raising an error when both are provided.
[sc-42945]

Adding a `wire_order` kwarg to `Tensor.sparse_matrix()`

---

doc/releases/changelog-dev.md
pennylane/optimize/qnspsa.py
tests/optimize/test_qnspsa.py

Fixes #4420 
The operator method `Operator.adjoint` is for defining a custom decomposition for the adjoint of an operator, and is only defined for cases where the adjoint is another fundamental gate.  `qml.adjoint` is the more public, always works version of `Operator.adjoint`.

QNSPSA bugfix

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/preprocess.py
pennylane/tape/tape.py
tests/devices/qubit/test_preprocess.py

**Context:**
Working towards the goal of support LCUs in Pennylane. This PR allows StatePrep operations to be called in the middle of a circuit without raising errors.
- Removed an error the used to be raised if more than 1 `StatePrep` operation was present in the circuit. 
- The `expand_fn()` in `device/qubit/preprocess.py` is updated to allow the first operation in the circuit to remain un-expanded if it is a `StatePrep` operation, otherwise expanding all other instances of `StatePrep`

Support `StatePrep` mid-circuit for `DefaultQubit2`

---

doc/releases/changelog-dev.md
pennylane/drawer/drawable_layers.py
pennylane/drawer/tape_mpl.py
pennylane/measurements/mid_measure.py
pennylane/transforms/condition.py
pennylane/transforms/defer_measurements.py
tests/devices/qubit/test_preprocess.py
tests/measurements/test_mid_measure.py

**Context:**
Updates for mid-circuit measurement overhaul. This change is being made instead of #4408 
* Changed signature of `MeasurementValue` constructor to accept a list of `MidMeasureMP`s rather than their ids.
**Benefits:**
* `MeasurementValue`s store references to their respective `MidMeasureMP`s, so `MidMeasureMP`s can be used without queuing with `qml.measure`.

`MeasurementValue` accepts `MidMeasureMP`s instead of IDs in constructor

---

doc/releases/changelog-dev.md
pennylane/operation.py
tests/test_operation.py

**Context:**
Subtraction of new opmath was broken when the operator being subtracted is a prod. See bug report for details, but in short, this used to happen:
```pycon
>>> qml.PauliZ(0) - qml.prod(qml.PauliX(0), qml.PauliY(1))
PauliZ(wires=[0]) + ([-1*(PauliX(wires=[0])) -1*(PauliY(wires=[1]))]*(Identity(wires=[0])))
```
That's right, the old scalar for the second term was a numpy array of SProds, with an Identity as base. But now this happens:
```pycon
>>> qml.PauliZ(0) - qml.prod(qml.PauliX(0), qml.PauliY(1))
PauliZ(wires=[0]) + (-1*(PauliX(wires=[0]) @ PauliY(wires=[1])))
```
use `qml.s_prod(-1, other)` instead of `qml.math.multiply(-1, other)` to create the second term being added (assuming `other` is an operator)
**Benefits:**
No more bug!
**Possible …

bugfix: substraction works with new opmath

---

doc/releases/changelog-dev.md
pennylane/_device.py
pennylane/gradients/finite_difference.py
pennylane/gradients/general_shift_rules.py
pennylane/gradients/gradient_transform.py
pennylane/gradients/hadamard_gradient.py
pennylane/gradients/jvp.py
pennylane/gradients/parameter_shift.py
pennylane/gradients/parameter_shift_cv.py
pennylane/gradients/pulse_generator_gradient.py
pennylane/gradients/pulse_gradient.py
pennylane/gradients/spsa_gradient.py
pennylane/gradients/vjp.py
pennylane/interfaces/autograd.py
pennylane/interfaces/jax.py
pennylane/interfaces/jax_jit_tuple.py
pennylane/interfaces/tensorflow.py
pennylane/interfaces/tensorflow_autograph.py
tests/gradients/core/test_gradient_transform.py
tests/gradients/core/test_pulse_generator_gradient.py
tests/gradients/finite_diff/test_finite_difference_shot_vec.py
tests/gradients/finite_diff/test_spsa_gradient_shot_vec.py
tests/gradients/parameter_shift/test_parameter_shift_shot_vec.py

**Context:**
By the time tapes reach the `gradients` module, they will have shots assigned directly onto them. This means the shots don't need to be passed around while the tapes themselves are being passed around.
Remove all extraneous references to shot values when they are already on tapes in gradient-related code
**Benefits:**
Less likely to make duplication errors, cleaner code, easier to work with
Making (and reviewing) this change is ugly.

Remove the `shots` kwarg from the gradients module

---

doc/releases/changelog-dev.md
pennylane/pulse/transmon.py
tests/pulse/test_transmon.py

Changing $\omega \mapsto \omega/2$, this is important for resonance conditions in the drive, which otherwise leads to mismatches (and confusion).

Fix coefficient in `qml.pulse.transmon_interaction`

---

doc/releases/changelog-dev.md
tests/interfaces/default_qubit_2_integration/test_jax_jit_qnode_default_qubit_2.py
tests/interfaces/default_qubit_2_integration/test_jax_qnode_default_qubit_2.py
tests/interfaces/default_qubit_2_integration/test_torch_qnode_default_qubit_2.py
tests/interfaces/test_autograd_qnode.py
tests/interfaces/test_jax_jit_qnode.py
tests/interfaces/test_jax_qnode.py
tests/interfaces/test_tensorflow_qnode.py
tests/interfaces/test_torch_qnode.py
tests/legacy/test_legacy_autograd_qnode_old.py
tests/legacy/test_legacy_jax_qnode_old.py
tests/legacy/test_legacy_tensorflow_qnode_old.py
tests/legacy/test_legacy_torch_qnode_old.py

**Context:**
In a recent PR #4165 a bug in the seed setting behaviour of `spsa_grad` was fixed. Some tests did not use the predefined `SEED_FOR_SPSA` or didn't set a seed at all and were missed in the previous PR (#4165).
Remaining tests are changed to properly set a pseud-random number generator when differentiating with SPSA.
**Benefits:**
Deterministic tests.
n/a
n/a

Adapt remaining tests to use the new and fixed SPSA seed setting format.

---

requirements-dev.txt

**Context:**
`requirements-dev.txt` is supposed to be a list of additional packages that might be useful if contributing to pennylane. `requests` is used as part of the data module (to talk to the S3 database) and is already a requirement of PL itself, so it doesn't belong here. Plus, there's a dependabot security warning about an old `requests` version that we aren't even pinned to, but this makes it look like we might support it.
Remove `requests` from requirements-dev.txt
**Benefits:**
The requirements file only has what it should.
N/A

Remove requests from dev requirements

---

doc/releases/changelog-dev.md
pennylane/math/__init__.py
pennylane/math/single_dispatch.py
tests/math/test_functions.py

Fixes #4492 [sc-43886]
The autoray version of `get_dtype_name` breaks with array boxes. This patch makes it so that `get_dtype_name` is called on the value of the array box.

[BUGFIX] Fix `math.get_dtype_name` for `ArrayBox`

---

doc/code/qml_qchem.rst
doc/introduction/chemistry.rst
doc/releases/changelog-0.32.0.md
pennylane/__init__.py

**Context:**
Docs change to switch import of `import_state` to `qml.qchem` level. 
**Benefits:**

Changed import_state to qml.qchem-level import

---

pennylane/devices/experimental/default_qubit_2.py
pennylane/logging/configuration.py
pennylane/pulse/transmon.py
pennylane/tape/tape.py

- Remove default values for kwargs in docstring for `qml.device.DefaultQubit2`. This makes the code more in line with Google-style docstrings
- Fix rendering of example for `qml.logging.enable_logging`
- Fix rendering of math for `qml.pulse.transmon_drive`. Also add newlines after function definition in the example since the previous is incorrect syntax
- Add an example to `qml.tape.tape.expand_tape_state_prep`

Minor documentation changes

---

doc/introduction/chemistry.rst

**Context:**
Update PySCF link in `chemistry.rst`.
**Benefits:**

Update PySCF link in chemistry doc

---

doc/code/qml_measurements.rst
pennylane/measurements/__init__.py
pennylane/measurements/mid_measure.py
pennylane/optimize/adaptive.py

* `list_of_ops.remove(op)` causes operator hash warning to be raised. This PR fixes it in the `AdaptiveOptimizer`.
* Removed `MeasurementValueError`.

More 0.32 related fixes

---

pennylane/drawer/style.py
pennylane/transforms/defer_measurements.py
tests/transforms/test_defer_measurements.py

**Context:**
The teleportation tutorial I wrote has "mid-circuit" measurements with custom labels, and I'd also like it to use the new `pennylane` MPL style, but they both aren't very compatible.
- Set `cur_wire` to `None` in `defer_measurements` if there are no wires being reused to allow for custom wire labels in the case when wires don't _need_ to be reused
- Change the way we check for a font in `qml.drawer.style` because the current way requires MPL >= 3.6, but `qml` is built with MPL 3.5
**Benefits:**
The tutorial will work without any changes (except me setting the style to pennylane for all to see!)
N/A
PennyLaneAI/qml#812

bugfixes to unblock teleportation tutorial

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/queuing.py
pennylane/tape/operation_recorder.py
pennylane/tape/qscript.py
pennylane/tape/tape.py
tests/tape/test_qscript.py
tests/templates/test_subroutines/test_qsvt.py

The empty third list returned by `process_queue` is removed, and a deprecation warning is added when the `prep` kwarg is used in `QuantumScript`

Deprecate prep kwarg and remove third list from process_queue

---

doc/releases/changelog-dev.md
pennylane/devices/__init__.py
pennylane/devices/qubit/__init__.py
pennylane/devices/qubit/adjoint_jacobian.py
pennylane/devices/qubit/apply_operation.py
pennylane/devices/qubit/preprocess.py
pennylane/devices/qubit/sampling.py
pennylane/devices/qubit/simulate.py

I am open to notable variation in the docs here, just lmk! I mostly just wanted to get this PR going.
**Context:**
The `devices.qubit` functions are very useful, and people should be able to see them! They're still a little unstable, so I'm inclined to leave those warnings in the docs for now, but they should be visible.
Add the `devices.qubit` qubit-simulation functions at the bottom of the `qml.devices` sub-page in the "Internal" section (check it out [here](https://xanaduai-pennylane--4555.com.readthedocs.build/en/4555/code/qml_devices.html#module-pennylane.devices.qubit)!)
**Benefits:**
Nice pretty docs to show users all the cool features and helper functions we have
It's still kinda unstable while we ramp up DQ2, but it should be …

render docs for devices.qubit functions

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/templates/layers/random.py
tests/templates/test_layers/test_random.py

The ``RandomLayers.compute_decomposition`` keyword argument ``ratio_imprivitive`` has been changed to
``ratio_imprim`` to match the call signature of the operation. This PR completes the deprecation cycle by removing the option to use ``ratio_imprivitive``.

Remove ratio_imprivitive kwarg in favour of ratio_imprim

---

doc/releases/changelog-dev.md
pennylane/math/single_dispatch.py
pennylane/measurements/state.py
tests/measurements/test_state.py

**Context:**
In the new device interface, a device need not have wires. In the case when it does provide wires, it would be best if measurement processes that don't require wires at all (`state()`, `sample()`, `probs()`) know to expand over the extra wires. To be able to do this, they need to save the wires somewhere, and `self.wires` kinda makes sense for this:)
- Allow initialization of a `StateMP` with wires (now that it doesn't indicate a density-matrix measurement).
- When given a strict subset of wires, `process_state` pads the state with zeros for all other wire axes
- When given a different `wire_order` from `self.wires`, `process_state` will transpose the state to match the MP wires
**Note on wire ordering:**
I use the convention that …

StateMP accepts wires

---

tests/gradients/finite_diff/test_spsa_gradient.py

No clue why regular CI doesn't catch this, but [docker CI does](https://github.com/PennyLaneAI/pennylane/actions/runs/6102750018/job/16561865816#step:4:4086). A lot.

fix np.random.seed usage

---

doc/releases/changelog-dev.md
pennylane/measurements/probs.py
tests/measurements/test_expval.py

**Context:**
Tensorflow Autograph forces discipline upon me that I do not want! It doesn't like when something returns `None` sometimes and a tuple at other times. I thought I fixed `Probability.process_state` in #4470 because a test failed with `tf.function`. Unfortunately, I put the code into a state where Autograph could no longer properly compile it, so it traced all Tensors with shape `<unknown>`, and *that* made anything shape-related afterwards fail. This includes `qml.math.dot`, which `expval.process_state` does. Though I knew this was related to the problem, only yesterday was I able to single it out. And last night I realized, I ought not try to invent a fix. I should just copy from `default.qubit(.tf)`! So this PR takes code structure from …

fix probs.process_state with tf.function and batching

---

doc/releases/changelog-dev.md
pennylane/math/single_dispatch.py
tests/math/test_functions.py

**Context:**
Basically, if you call `qml.math.take(x, indices=your_indices, axis=2, like="torch")`, it returns `x[:, :, your_indices]` (with `axis` placeholder colons, in this case 2). If `axis` is -1, we would return `x[indices]` (because `[vals] * -1` gives an empty list). That's wrong.
`qml.math.take` for torch with `axis=-1` correctly returns `x[..., indices]` instead of `x[indices]`.
**Benefits:**
`qml.math.take` works with `torch` and `axis=-1`.
First reported in #4589

fix torch take with axis=-1

---

.github/workflows/interface-unit-tests.yml

A new version of jax has been released. This PR attempts to bump the version in the CI 🤞

[CI] Bump jax version to v0.4.16

---

tests/conftest.py
tests/devices/test_default_qubit_jax.py

This is just a quality-of-life improvement for developers. When running the tests locally, I always get a bunch of failures not due to my change, but due to using float32 with jax instead of float64.
This just makes it so that float64 mode is always enabled.

Tests always enable jax float64

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/sampling.py
pennylane/measurements/measurements.py
pennylane/measurements/probs.py
pennylane/measurements/state.py
tests/drawer/test_tape_mpl.py
tests/measurements/legacy/test_expval_legacy.py
tests/measurements/legacy/test_probs_legacy.py
tests/measurements/legacy/test_var_legacy.py
tests/measurements/test_state.py

**Context:**
While porting to DQ2, we're discovering that some features are not at parity with DQL. These are a few more. `ProbabilityMP.process_state()` thought the input was not flat! What!!
- Change `ProbabilityMP.process_state` to assume the input is flat (I just copy-pasted the contents of `marginal_prob` and used the new `get_batch_size` helper, I didn't change `_count_samples`, Git just thinks I did).
- Fix `StateMP.process_state` so it returns the correct shape when batched
- Fix `StateMP.process_state` so it always returns complex values, even if the inputs are not complex
- Update the docstring for `process_state` to state (haha) this assumption
**Benefits:**
- Feature parity with DQL
- Better standardization, cleaner code, better code reuse

`process_state` assumes flat, `state()` is always complex

---

doc/releases/changelog-dev.md
pennylane/qnn/torch.py
tests/qnn/test_qnn_torch.py

Fixes bug #4584 
`torch.nn.Module` has some special `__getattr__` logic that we are ignoring if the qnode has been initialized.  This bugfix makes it so the `qnn.TorchLayer.__getattr__` uses `torch.nn.Module.__getattr__` if the requested property is not on the QNode.

Fix `qnn.TorchLayer` attributes

---

pennylane/qnode.py
tests/transforms/test_zx.py

Remove post processing applied by qnode when there are no parameters for informative transforms.

No qnode post processing on informative transforms

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/apply_operation.py
pennylane/gradients/pulse_generator_gradient.py
tests/devices/qubit/test_apply_operation.py
tests/gradients/core/test_pulse_generator_gradient.py
tests/gradients/core/test_pulse_gradient.py

**Context:**
Enabling this was missed in the DQ2 switch-over. We originally said that `ParametrizedEvolution` should fail to apply to broadcasted states, but `pulse_generator` and `stoch_pulse_grad` have custom handling for certain cases, so we ought not be so decisive in `apply_operation`. That said, if the inputted state is batched but the operator is not, then we're in trouble.
- Only raise the batched-state-ParametrizedEvolution error when the op is not itself batched
- put shots on tapes created by `pulse_generator` (missed in gradient uses tape shots upgrade)
- change `test_jax` at the bottom of each gradient test file to use `"backprop"` instead of `None` for the `gradient_fn`. This worked as-is on `DefaultQubitJax` because it has a …

fix and enable pulse gradient with broadcasting on new device

---

doc/releases/changelog-dev.md
pennylane/devices/default_qubit.py

Add comment on multiprocessing.

---

doc/releases/changelog-dev.md
pennylane/ops/qubit/state_preparation.py
tests/ops/qubit/test_state_prep.py

**Context:**
It's been failing all over since switching DQL with DQ2
Cast inputted values to float before making state vector
**Benefits:**
Float inputs are accepted and CI is fixed, parity with DQL
N/A
PennyLaneAI/pennylane-rigetti#142

BasisState accepts floats

---

doc/releases/changelog-dev.md
pennylane/devices/tests/conftest.py

The pasqal device was unable to be tested with the device test suite because it kept the `control_radius=2` as a string instead of converting `2` to an integer.
This change converts any kwargs to int or float if they can be converted to ints or floats.

device test suite: convert kwargs values to ints and floats

---

doc/releases/changelog-dev.md
pennylane/_device.py
pennylane/gradients/parameter_shift_cv.py
pennylane/ops/functions/map_wires.py
pennylane/optimize/adaptive.py
pennylane/optimize/riemannian_gradient.py
pennylane/qnode.py
pennylane/tape/qscript.py
pennylane/tape/tape.py
pennylane/transforms/compile.py
pennylane/transforms/convert_to_numpy_parameters.py
pennylane/transforms/core/transform_dispatcher.py
pennylane/transforms/defer_measurements.py
pennylane/transforms/optimization/cancel_inverses.py
pennylane/transforms/optimization/commute_controlled.py
pennylane/transforms/optimization/merge_amplitude_embedding.py
pennylane/transforms/optimization/merge_rotations.py
pennylane/transforms/optimization/pattern_matching.py
pennylane/transforms/optimization/remove_barrier.py
pennylane/transforms/optimization/single_qubit_fusion.py
pennylane/transforms/optimization/undo_swaps.py
pennylane/transforms/transpile.py
pennylane/transforms/unitary_to_rot.py
tests/ops/functions/test_map_wires.py
tests/optimize/test_adaptive.py
tests/tape/test_qscript.py
tests/transforms/test_experimental/test_transform_dispatcher.py

**Context:**
`_qfunc_output` is a pain to keep track of, and we only need it for QNode handling. `QNode._qfunc_output` still exists, but `tape._qfunc_output` does not.
- Remove `tape._qfunc_output`
- update qnode.construct to not use `make_qscript` so it can get the tape result shape
- remove squeezing logic from `param_shift_cv` (the only other place that used `tape._qfunc_output`) because it doesn't accept parameter broadcasting, shot vectors, or multiple measurements, so it really never needs it
- if I saw a transform creating a QuantumTape explicitly, I changed it to create `type(tape)` so QuantumScript in = QuantumScript out
- qfunc_transform is the only other place that needed the qfunc output, so I added some handling there that's quite similar to …

remove _qfunc_output from tape

---

doc/releases/changelog-dev.md
pennylane/devices/default_qubit.py
tests/devices/test_default_qubit_tracking.py

DQL included results in the tracker, DQ2 currently does not. Results for each call of `execute` added here.

Include results on tracker for default.qubit

---

doc/releases/changelog-dev.md
pennylane/transforms/qcut/cutcircuit.py
tests/transforms/test_qcut.py

**Context:** `qml.cut_circuit` does not work for quantum circuits which computes the expectation values of Hamiltonians with more than one term.
**Description of the Change:** Use `qml.transforms.hamiltonian_expand` to extend support for Hamiltonians.
**Benefits:** Circuit cutting could be used on more realistic circuits. 
**Possible Drawbacks:** The Number of tapes to be computed increases and might give rise to possible overhead in the new scenario. 
**Related GitHub Issues:** #3672

Hamiltonian support for Circuit Cutting

---

tests/ops/qubit/test_parametric_ops.py
tests/test_vqe.py
tests/transforms/test_hamiltonian_expand.py

**Context:**
After updating to the new device API, codecov was unhappy with the lost coverage [here](https://app.codecov.io/gh/PennyLaneAI/pennylane/pull/4436/indirect-changes?src=pr&el=tree-more). Coverage loss was reported in:
1. testing TF support for `compute_eigvals` for `PCPhase` and `IsingZZ`
2. one line in interfaces/torch.py
3. one line in transforms/hamiltonian_expand.py
Added tests for points 1 and 3. 
Reintroduced running `test_vqe.py` test `test_optimize_torch` with DQL (in addition to DQ2) to maintain code coverage from before the device swap, as its not clear if that line is reachable with DQ2.
**Benefits:**
Code coverage didn't decrease when switching device API

Increase codecov coverage

---

doc/releases/changelog-dev.md
pennylane/templates/subroutines/grover.py
tests/templates/test_subroutines/test_grover.py

The default to `GroverOperator` for work wires was `None`. Unfortunately this was being interpreted as `work_wires = Wires([None,])`.  This PR makes it so that `work_wires=None` is interpreted as `work_wires = Wires([])`.
Fixes https://github.com/PennyLaneAI/pennylane-qiskit/issues/339

Fix grover operator work wires

---

doc/releases/changelog-dev.md
pennylane/qchem/integrals.py

Recreate qchem slicing PR

---

doc/development/release_notes.md
doc/releases/changelog-0.32.0.md
doc/releases/changelog-0.33.0.md
pennylane/_version.py

PR 1:
- rename changelog-dev.md to changelog-0.X.0.md,
- change changelog-dev reference to changelog-0.X reference in release_notes.md,
- move "current release" label from changelog-0.X-1 to changelog-0.X,
- In changelog-0.X.0.md update title from 0.X.0-dev to 0.X.0
- change _version.py reference from 0.X.0-dev to 0.X.0

0.33 pre-release changes

---

pennylane/drawer/draw.py
pennylane/transforms/tape_expand.py

**Context:**
Sometimes, tapes will use standard wires (eg. `[0, 1, 2]`) but will report them out of order, depending on the order in which they are used. If we are drawing a qnode (in other words, a circuit bound to a device), we have the true wire order available to us.
Use the device wire order wherever possible in drawing logic
**Benefits:**
We don't accidentally draw in funky wire orders like `[1, 0]`. See the docstring that I changed in `tape_expand` as an example (before this PR, it would swap wires without the `wire_order` specified)
N/A
first found in #4711

Always draw with device wires first

---

pennylane/drawer/draw.py
pennylane/transforms/tape_expand.py
tests/drawer/test_draw_mpl.py

**Context:**
This is already being done in the text drawer, I'm just copying it over for consistency.
If expansion_strategy is _not_ "device" but we're drawing a QNode with a new device, run the QNode transform program on the tape before drawing it. This is for draw_mpl, it's already present for `draw`
**Benefits:**
Parity between the two draw tools
N/A
done in #4595 for the text drawer

run qnode transforms on new device with draw_mpl as well

---

setup.py
tests/test_queuing.py

* Bump lightning requirement in `setup.py`.
* I updated `WrappedObj.__eq__` for a bug fix, but forgot to add a test for the change, which is causing code cov to fail for the rc-master merge. Added it here

Bump lightning; `WrappedObj` coverage fix

---

doc/development/deprecations.rst
doc/introduction/interfaces.rst
doc/releases/changelog-dev.md
pennylane/gradients/__init__.py
pennylane/gradients/pulse_gradient_odegen.py
tests/gradients/core/test_pulse_odegen.py

**Context:**
`pulse_generator` has been deprecated in favour of `pulse_odegen`. This completes the deprecation cycle.
Remove `pulse_generator`.
[sc-47810]

remove pulse_generator

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/symbolicop.py
tests/ops/op_math/test_symbolic_op.py

We discovered a difference between `default.qubit` and `default.qubit.legacy` over their treatment of the evolution of hamiltonians:
```python
dev = qml.device('default.qubit', wires=3)
​
coeffs = [0.1, 0.2]
operators = [qml.PauliZ(0) @ qml.PauliZ(1), qml.PauliZ(0) @ qml.PauliZ(2)]
hamiltonian = qml.Hamiltonian(coeffs, operators)
​
def f():
qml.evolve(hamiltonian, 0.5)
return qml.density_matrix([0])
​
f()
```
Previously `qml.evolve(hamiltonain, t)` worked because `Evolution` was hardcoded as an accepted observable. This meant it became an accepted operation as well, even though it stated it didn't have a matrix.
In `ScalarSymbolicOp`, the parent for `Evolution`, we added a special logical pathway for the matrix if the target is a Hamiltonian, but we didn't include that …

State that `Evolution` has matrix if target is `Hamiltonian`

---

doc/releases/changelog-dev.md
pennylane/interfaces/jax.py
pennylane/interfaces/jax_jit.py
pennylane/tape/qscript.py
tests/interfaces/default_qubit_2_integration/test_jax_jit_qnode_default_qubit_2.py

[sc-48174] Fixes #4689 
Jax jit now works with shot vectors.
```
>>> dev = qml.device("default.qubit")
>>> @qml.qnode(dev, interface="jax")
... def f(p):
...     qml.RX(p, 0)
...     qml.CNOT([0, 1])
...     return qml.expval(qml.PauliZ(0))
... 
>>> f_jitted = jax.jit(f, static_argnames=["shots"])
>>> f_jitted(jax.numpy.array(np.pi / 2), shots=(10, 10))
```

Jax jit support for shot vectors

---

.github/workflows/interface-unit-tests.yml

Bumping version of JAX from 0.4.19 to 0.4.20 in the CI

bump jax version

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/simulate.py
tests/devices/default_qubit/test_default_qubit.py
tests/gradients/finite_diff/test_finite_difference_shot_vec.py

Fixes #4779 . [sc-49381]
When creating an initial state, `get_final_state` was using `tape.op_wires` for the wire order, even though the simulation always occurred using the wire order `(0,1,2,3,...)`.  Sometimes `tape.op_wires` would have a different order, leading to a mismatch.
Now we use `sorted(circuit.op_wires)`, so they will always be in the monotonically increasing integers used by the simulation.

Fix the wire order of state prep operations in `default.qubit`

---

pennylane/transforms/batch_input.py
pennylane/transforms/batch_params.py
pennylane/transforms/qcut/cutcircuit.py
pennylane/transforms/qcut/montecarlo.py
tests/templates/test_subroutines/test_controlled_sequence.py

**Context:**
new transforms should use `partial` if they require additional args. most docs were already updated, but some were missed
try to update some docs (and a test) to not use deprecated transform syntax
**Benefits:**
less deprecated code being used, less warnings!
you had to spend a minute or two reviewing this.

use partial in transform docs

---

doc/releases/changelog-dev.md
pennylane/transforms/defer_measurements.py
tests/transforms/test_defer_measurements.py

**Context:**
When making terminal measurements on wires with mid-circuit measurements, the circuit was not being transformed correctly. This PR fixes that.
Wires are considered to be reused by `defer_measurements` when a measured wire has operators *and* terminal measurements applied to it after mid-circuit measurements.
**Benefits:**
[sc-49507]

[BUGFIX] Qubit reuse for terminal measurements on wires with mid-circuit measurements

---

pennylane/compiler/compiler.py

From the doc page of [pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html):
> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.
PR #4783 updates all occurrences of …

[Compiler] Use importlib instead of pkg_resources

---

.github/workflows/interface-unit-tests.yml
doc/releases/changelog-0.33.1.md
pennylane/gradients/vjp.py
pennylane/math/multi_dispatch.py
tests/gradients/core/test_vjp.py
tests/gradients/finite_diff/test_finite_difference.py

**Context:** v0.33.1 backport of PR …

Create VJP perf fix

---

docker/interfaces/gpu-cuda/cuda-base.dockerfile
docker/pennylane.dockerfile

latest docker build on master failing because it doesn't have pytest-benchmark: https://github.com/PennyLaneAI/pennylane/actions/runs/6801575137/job/18492742357

fix requirements to make docker builds pass

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/simulate.py
tests/devices/qubit/test_simulate.py

**Context:**
In the past, QNodes would return pennylane tensors by default if there was no specific interface set. However, I introduced some funniness when I added `qml.math.pad` [here](https://github.com/PennyLaneAI/pennylane/blob/4eecda939f862d62662751e791ba58bb0fc13508/pennylane/devices/qubit/simulate.py#L90). For some reason, when given a pennylane tensor, it would return a vanilla numpy array.
Provide the `like` parameter to `qml.math.pad` when expanding the statevector over all wires.
**Benefits:**
Consistency with past versions of PennyLane
What in tarnation. I can't make any sense of interfaces anymore.

ensure the correct interface is returned in expand_state

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/__init__.py
pennylane/operation.py
pennylane/ops/functions/generator.py
pennylane/ops/op_math/controlled.py
pennylane/tape/qscript.py
pennylane/transforms/__init__.py
pennylane/transforms/batch_transform.py
pennylane/transforms/core/transform_dispatcher.py
pennylane/transforms/op_transforms.py
pennylane/transforms/qfunc_transforms.py
pennylane/vqe/vqe.py

**Context:**
When we deprecate features, it's hard to identify that we've done it.
Replace all deprecation warning categories with the new `PennyLaneDeprecationWarning`
**Benefits:**
We can add a pytest.ini filter to make this into failures on plugins!
```
[pytest]
filterwarnings =
error::pennylane.PennyLaneDeprecationWarning
```
(I ran a test locally with a plugin that was setting `Observable.return_type` and saw that it raised the error)
N/A

create a PL-specific deprecation warning

---

doc/releases/changelog-dev.md
pennylane/templates/embeddings/amplitude.py
tests/templates/test_embeddings/test_amplitude.py

**Context:**
The padding and normalization step in `AmplitudeEmbedding` previously used a manual for loop, making it incompatible with Tensorflow `tf.function(jit_compile=True)`.
The preprocessing now process the whole batch of features simultaneously, using numpy-like broadcasting instead.
(This also should be faster, usually).
Also, the tests have been complemented to test Tensorflow JITting with padding, and padding/non-padding tests have been combined into a single test function.
**Benefits:**
Support of Tensorflow,including JIT compilation in Tensorflow.
(probably) a speedup.
Strictly speaking, the previous implementation allowed for different feature vector lengths across the batching dimension (because the padding happens …

Allow batching in `AmplitudeEmbedding` with Tensorflow

---

doc/releases/changelog-dev.md
pennylane/_qubit_device.py
pennylane/devices/qubit/adjoint_jacobian.py
tests/devices/qubit/test_adjoint_jacobian.py
tests/gradients/core/test_adjoint_diff.py

**Context:**
The adjoint method of `DefaultQubitLegacy` uses two incompatible ways to quantify tape parameters: It sets up the number of tape parameters correctly using `tape.get_parameters(trainable_only=False)` but checks whether an operation comes with a parameter via `grad_method is not None`. This lead to a bug where, for example, `QubitUnitary` disrupts the parameter counting.
As all operations with more than one parameter are being decomposed/raised an error upon anyways,  this PR changes the way to detect parametrized operations to `op.num_params==1`.
**Benefits:**
Bug fix: Correct adjoint method derivatives even when using `QubitUnitary` and other operations that have `grad_method=None` but have parameters.
N/A
**Related …

Fix parameter counting in `DefaultQubitLegacy` adjoint method

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/ops/op_math/controlled.py
tests/drawer/test_tape_mpl.py
tests/ops/op_math/test_controlled.py
tests/ops/op_math/test_controlled_ops.py

**Context:**
This warning was added eons ago (#2634), but it pre-dates our deprecation management page so it slipped through the cracks.
Remove the support for passing `control_values` as a string to `qml.ctrl`
**Benefits:**
Deprecation cycle is now complete!
It wasn't on our deprecations page and was therefore never formally scheduled for removal. But you know.. it's been almost 10 releases.
NOTE: I want to see PennyLaneAI/plugin-test-matrix#57 merged and get a look at the matrix before we merge this into master. Too many things breaking at once 😓

stop allowing string control_values for ctrl

---

.github/workflows/docker.yml
tests/gradients/core/test_hadamard_gradient.py
tests/gradients/finite_diff/test_finite_difference_shot_vec.py
tests/ops/op_math/test_prod.py
tests/ops/op_math/test_sprod.py
tests/ops/op_math/test_sum.py

I ran the docker build on this PR to make sure it passed - [here](https://github.com/PennyLaneAI/pennylane/actions/runs/6855919680/job/18641996969?pr=4833)'s the passing run.
**Context:**
docker builds are still failing! we gotta stop the failures!
- use the qualified `qml.QuantumFunctionError` because docker tests seem to care
- change a FD test tolerance from 0.07 to 0.08 because it fails (barely - probably a new numpy thing, idk)
- delete old `hadamard_grad` test that checked for ragged array warnings because it can't happen anymore, and for some reason it was triggering a numpy deprecation warning on Docker CI only
**Benefits:**
docker builds pass!
although I know _what_ caused failures, I am not always sure of _why_. but avoiding …

fix docker builds

---

tests/pytest.ini

confirmed locally that it works, and it won't be raised if the warning is caught/suppressed in a test

test: turn PL deprecation warnings into errors

---

.github/workflows/interface-unit-tests.yml
pennylane/math/single_dispatch.py

For some reason in 2.15, the `ndim()` of an abstract tensor with shape specified as `None` was -1, so it didn't raise an error, and didn't get handled with [this exception handling](https://github.com/PennyLaneAI/pennylane/blob/aab9ed91110ac95938fe2275625e1845970d5a9c/pennylane/operation.py#L1091)
**Description of the change**
`qml.math.ndim(tensor)` always returns `len(tensor.shape)` for tensorflow. this will still raise errors as expected for abstract tensors with abstract shapes (only happens when the user specifies the shape as None before compiling a function).
ran a bunch of tests (tf interface tests, the `tf.function` test that failed in test_operation.py) locally with python 3.9, TF 2.10 just to make sure I didn't break old versions of tensorflow, they all passed 🙌

bump tensorflow to 2.15 in CI

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/simulate.py
pennylane/measurements/state.py
pennylane/tape/qscript.py
tests/interfaces/default_qubit_2_integration/test_torch_default_qubit_2.py
tests/measurements/test_state.py

**Context:**
I wrote the same function twice, differing only by state flattening, to get the DQ upgrade done. It's starting to cause trouble.
Greatly simplified the state re-arrangement logic. There used to be a whole mess of things happening, but now things are much more straightforward.
1. `simulate` first puts things in our "standard" order, and this means that if any measured wires are not also operator wires, they are put to the _end_ of our tape wires. Therefore, for each measured-only wire, we just have to stack a `zeros_like(state)` to the last axis of our final state! `simulate` never tried to transpose wires back to a different ordering, so that was always wasted work.
2. `StateMP.process_state` _always_ receives the full state, and never needed to …

simplify state reordering logic

---

doc/releases/changelog-dev.md
pennylane/transforms/optimization/merge_amplitude_embedding.py
tests/transforms/test_optimization/test_merge_amplitude_embedding.py

**Context:**
`merge_amplitude_embedding` was not following transform conventions, so it didn't work as expected with QNodes.
- stop the transform from depending on the new AmplitudeEmbedding on being queued, and actually add it to the transformed tape
- tidy up the transform because it was using some unnecessary copies of lists and I felt like it
- fix test that was asserting an incorrect answer (both tests that I changed were failing without the fix because they depended on queuing)
**Benefits:**
bug squashed! 🥾 🐞
N/A
Fixes #4830 [sc-50048]

fix merge_amplitude_embedding queuing bug

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/pow.py
pennylane/ops/qubit/matrix_ops.py
tests/ops/op_math/test_controlled_ops.py
tests/ops/op_math/test_pow_op.py
tests/ops/qubit/test_matrix_ops.py

**Context:**
Tensorflow does not have a `matrix_power` function. For non-int powers, we always fall back to scipy, and we noticed that this works with Tensorflow as well! We can use this...
- Whenever trying to raise TF matrices to an integer matrix-power, use `scipy.linalg.fractional_matrix_power`. Until today, we just raised an error. `Pow` is not trainable regardless, so there's no harm in adding this.
- This also indirectly allowed for raising _any_ `QubitUnitary` to a non-int power (eg: `qml.QubitUnitary(np.eye(2), wires=[0]).pow(3.5)`)
**Benefits:**
Less errors! more features!
- Still not differentiable
- `QubitUnitary.pow` looks more complex to support more stuff
Fixes #4825 [sc-49952]

fallback to scipy when linalg.matrix_power isn't available

---

pennylane/transforms/optimization/pattern_matching.py
pennylane/transforms/optimization/remove_barrier.py
tests/transforms/test_compile.py
tests/transforms/test_optimization/test_cancel_inverses.py
tests/transforms/test_optimization/test_commute_controlled.py
tests/transforms/test_optimization/test_undo_swaps.py

**Context:**
While working on #4831, we grew suspicious that similar bugs might exist in other optimization transforms. This PR is the result of that audit.
- make sure optimization-transform tests actually test QNode transforms
- this involved changing some observables to get actual non-zero results
- simplify the `remove_barrier` code
- add a test for `remove_barrier` (in test_compile.py because the qml.compile default pipeline is the only place where it's used) because there are no tests for it!
**Benefits:**
More comfort with the state of this module.
N/A
[sc-50172]

tidy up optimization transform testing

---

doc/releases/changelog-dev.md
pennylane/operation.py
tests/test_operation.py

Currently, `has_matrix` only is automatically `True` if `compute_matrix` is overridden.  If someone overrides `Operator.matrix` but not `Operator.compute_matrix`, they will have to manually set `has_matrix = True`.
This behaviour is a historical remnant from when `Operation` overrode the `Operator.matrix` method to include in-place inversion. As in-place inversion is no longer a thing, we no longer have any reason to keep that behaviour.
With this change, it will be easier for people to write their own custom operators.
This change is motivated by confusion over why an operator with a matrix wasn't supported by `default.qubit`.

`has_matrix` detects if `Operator.matrix` is overridden

---

doc/introduction/compiling_circuits.rst
pennylane/_grad.py
pennylane/compiler/__init__.py
pennylane/compiler/compiler.py
pennylane/compiler/qjit_api.py
tests/test_compiler.py

This PR updates the support and addresses code review suggestions in PR #4692.

[Compiler] Activate integration tests & Update codecov and docstrings

---

doc/releases/changelog-dev.md
pennylane/gradients/jvp.py
pennylane/interfaces/jacobian_products.py
pennylane/interfaces/jax.py
tests/gradients/core/test_jvp.py
tests/interfaces/default_qubit_2_integration/test_jax_default_qubit_2.py
tests/interfaces/test_jax.py

Fixes #4834 [sc-50137]
Long story short, our jvp tools, `qml.gradients.jvp` and `qml.interfaces.jacobian_products._compute_jvps` failed to return proper shapes and values when there is no trainable parameters. This fixes that.
Note to reviewers:
To properly test this fix, I needed integration tests for when the device provides a derivative with a shot vector.  So I added tests for device-provided derivatives with a shotvector.  Those test changes are a little painful, but they seem to work. Similar tests have already been added to autograd and torch in previous PR's.

fix jax jacobians when one circuit not trainable

---

doc/releases/changelog-dev.md
pennylane/operation.py
pennylane/ops/op_math/controlled.py
tests/ops/op_math/test_controlled.py
tests/test_operation.py

**Context:**
The `parameter_frequencies` of `qml.ctrl(op)` are obtained using `qml.eigvals`. If `op.generator` is a `SparseHamiltonian`, `qml.eigvals` only returns one eigenvalue because of the default setting of the kwarg `k`.
**edit:** The same problem appears for the default `qml.operation.parameter_frequencies`.
This PR explicitly sets the `k` kwarg, in order to obtain all eigenvalues of the generator, even if it is a `SparseHamiltonian`.
**edit:** Also sets `k` in `qml.operation.parameter_frequencies`
**Benefits:**
parameter-shift rule for `qml.ctrl(op)` works, also for `op` being a `DoubleExcitation`, e.g.
N/A
Fixed #4898

Fix `parameter_frequencies` of `qml.ctrl(op)` if `op.generator()` is `SparseHamiltonian`

---

tests/shadow/test_shadow_entropies.py

**Context:**
Since the Hamiltonian expectation PR (#4839) has been merged, [docker builds](https://github.com/PennyLaneAI/pennylane/actions/workflows/docker.yml) have been [failing](https://github.com/PennyLaneAI/pennylane/actions/runs/7009886220/job/19069286112) by the tiniest bit (`allclose([0.9965526601952645, 0.9931272102994894, 0.9897395403790262], 1.0, atol=0.01)`. 3e-4. come on 😠 ). I could investigate why.. but this should do the trick too.
Change the atol from 0.01 to 0.02 on this test
**Benefits:**
Docker builds pass and the PennyLane CI thing turns green
I don't know why we're off by 3e-4 compared to before because it only happens on docker and investigating it would be tough. It's certainly a rounding error from the new …

increase the atol for a shadow entropy test

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/adjoint_jacobian.py
pennylane/operation.py
pennylane/ops/op_math/composite.py
pennylane/ops/op_math/pow.py
pennylane/ops/op_math/prod.py
pennylane/ops/op_math/sprod.py
pennylane/ops/op_math/sum.py
pennylane/ops/op_math/symbolicop.py
pennylane/pauli/conversion.py
pennylane/pauli/pauli_interface.py
pennylane/qchem/convert.py
tests/devices/default_qubit/test_default_qubit.py
tests/ops/op_math/test_composite.py
tests/ops/op_math/test_pow_op.py
tests/ops/op_math/test_prod.py
tests/ops/op_math/test_sprod.py
tests/ops/op_math/test_sum.py
tests/ops/op_math/test_symbolic_op.py
tests/ops/qubit/test_non_parametric_ops.py
tests/pauli/test_conversion.py
tests/test_operation.py

**Context:**
The `pauli_rep` property is widely used, and should be made public
- Introduce the `pauli_rep` read-only property to the `Operator` class
- Change all (read) references to `op._pauli_rep` into `op.pauli_rep` (the public version)
**Benefits:**
We're committing to having `pauli_rep` be part of the public API, making it less scary to lean on while moving forward with other improvements (eg. combining all the hamiltonian expansion transforms)
We might want to change things related to it again, and it would require more careful work because it's public. I'm not so worried about this because it has existed (and been used) for a while now.
previously attempted in #4017 
[sc-37494]

make the pauli_rep operator property public

---

doc/releases/changelog-dev.md
pennylane/drawer/tape_text.py
pennylane/drawer/utils.py
tests/drawer/test_drawer_utils.py
tests/drawer/test_tape_text.py

This PR replaces `find_mid_measure_cond_connections` with `cwire_connections`.  It returns very similar information, but is a slight variant that will be easier to use in the matplotlib drawing of classical wires.

Add utility for extracting classical control information to drawer

---

tests/devices/qubit/test_sampling.py

**Context:**
A test in this file keeps intermittently failing (see the [ironic failure] on my other PR updating when we use vanilla numpy) because we're checking a result to be a numpy int, and it is, but we're actually ensuring that it's an _autograd_ numpy int, and it (sometimes?? idk) isn't
Use vanilla numpy in the test and hope that it fixes the issue
**Benefits:**
The test should stop bothering people on unrelated PRs
- it might not fix it
- I don't know why it only started failing recently

test fix: use vanilla numpy to fix jax test

---

doc/releases/changelog-dev.md
pennylane/ops/qubit/parametric_ops_single_qubit.py
pennylane/transforms/decompositions/clifford_t/clifford_t_transform.py
tests/ops/functions/test_assert_valid.py
tests/ops/qubit/test_parametric_ops.py
tests/transforms/test_batch_transform.py
tests/transforms/test_tape_expand.py

as title says. global phase applies a -1 to the exponent. the same was missed in a place in the clifford+T transform, so I updated that as well.

fix the sign on globalphase in phaseshift decomp

---

doc/development/release_notes.md
doc/releases/changelog-0.33.1.md
doc/releases/changelog-0.34.0.md
pennylane/_version.py

Updates PennyLane as we're entering a new development version (release of v0.34.0 coming up):
Preparation of release candidate:
- rename changelog-dev.md to changelog-0.34.0.md,
- change changelog-dev reference to changelog-0.34.0 reference in release_notes.md,
- move "current release" label from changelog-0.33.1 to changelog-0.34.0,
- In changelog-0.34.0.md update title from 0.34.0-dev to 0.34.0
- change _version.py reference from 0.34.0-dev to 0.34.0
```
rc    master
|     |
|      - update changelog for new 0.35.0-dev
|    /
|   /
|  /
| /
|/
- (**THIS PR**) changelog and version updates for 0.34.0 RC branch
|
| 
```

Preparation for release candidate `v0.34.0`

---

doc/releases/changelog-dev.md
pennylane/devices/default_qubit.py
pennylane/devices/default_qubit_legacy.py
pennylane/ops/functions/assert_valid.py
pennylane/ops/op_math/pow.py
tests/ops/functions/conftest.py
tests/ops/op_math/test_pow_op.py

[sc-49618]
We discovered that pow operators are currently not pickleable due to `__new__` black magic.  This PR makes it so `Pow` is updated to use the same behavior as `Adjoint`, which is picklable.

`Pow` operators are now pickleable.

---

doc/introduction/interfaces/jax.rst
pennylane/devices/default_qubit_jax.py
tests/devices/default_qubit/test_default_qubit.py
tests/devices/qubit/test_measure.py
tests/fourier/test_coefficients.py
tests/fourier/test_reconstruct.py
tests/gradients/core/test_adjoint_metric_tensor.py
tests/gradients/core/test_hadamard_gradient.py
tests/gradients/core/test_jvp.py
tests/gradients/core/test_metric_tensor.py
tests/gradients/core/test_vjp.py
tests/gradients/finite_diff/test_finite_difference.py
tests/gradients/finite_diff/test_finite_difference_shot_vec.py
tests/gradients/finite_diff/test_spsa_gradient.py
tests/gradients/finite_diff/test_spsa_gradient_shot_vec.py
tests/gradients/parameter_shift/test_parameter_shift_cv.py
tests/ops/functions/test_matrix.py
tests/ops/op_math/test_decompositions.py
tests/test_return_types_qnode.py
tests/transforms/test_compile.py
tests/transforms/test_optimization/test_cancel_inverses.py
tests/transforms/test_optimization/test_commute_controlled.py
tests/transforms/test_optimization/test_merge_amplitude_embedding.py
tests/transforms/test_optimization/test_merge_rotations.py
tests/transforms/test_optimization/test_single_qubit_fusion.py
tests/transforms/test_optimization/test_undo_swaps.py
tests/transforms/test_unitary_to_rot.py

In more recent versions of jax, the `from jax.config import config` syntax is deprecated.  Instead, we should set x64 suppport via `jax.config.update("jax_enable_x64", True)`.
```
>>> from jax.config import config
/var/folders/k1/0v_kvphn55lgf_45kntf1hqm0000gq/T/ipykernel_28191/927323724.py:1: DeprecationWarning: Accessing jax.config via the jax.config submodule is deprecated.
from jax.config import config
```
This PR removes the reference to this syntax from the docs and the tests.
Since tests are now always run with `jax.config.update("jax_enable_x64", True)` set in the setup, we no longer need to manually set it in each test, so those lines are simply removed.

Remove reference to `from jax.config import config`

---

doc/releases/changelog-dev.md
pennylane/ops/functions/assert_valid.py
pennylane/ops/qubit/matrix_ops.py
pennylane/ops/qubit/special_unitary.py
pennylane/resource/first_quantization.py
pennylane/resource/second_quantization.py
tests/ops/functions/conftest.py
tests/ops/functions/test_assert_valid.py

**Context:**
Continuation of the work I started in #4922 (this is part 1 of the future work listed in that PR)
1. Implement `_flatten` for `BlockEncode` and `SpecialUnitary` to pytreeify those types
2. Organize `tests/ops/functions/conftest.py` to better parametrize tests. The parametrization fixtures are easier to make using the following:
- `_INSTANCES_TO_TEST` is a list of operator instances that couldn't be auto-generated, but do pass validation
- `_INSTANCES_TO_FAIL` is a list of tuples (`(Operator, Type[Exception])`) where the first element is an operator instance that will fail validation, and the second element is the exception type raised during validation. Ideally, it also comes with a comment explaining what's failing/why it should fail.
All test …

Test all operators with assert_valid, or fail with a reason

---

doc/releases/changelog-0.34.0.md
pennylane/interfaces/jax_jit.py
tests/interfaces/default_qubit_2_integration/test_jax_jit_qnode_default_qubit_2.py

Currently PennyLane is raising errors whenever jax-jit is used with single precision. This eliminates those errors.

Jax jit support for single precision mode

---

doc/development/deprecations.rst
doc/introduction/inspecting_circuits.rst
pennylane/debugging.py
pennylane/devices/qubit/apply_operation.py
pennylane/measurements/shots.py
tests/devices/qubit/test_apply_operation.py

**Context:**
Reviewed my PRs, found some stuffs.
- fix code markdown in deprecations file
- add examples to `Shots` docs on creating a new Shots instance by scaling an old one
- bugfix: `Snapshot` wrongly flattened batched states, so I handle it accordingly (for `default.qubit`, at least)
- bugfix: `Snapshot` assumed the current device state is complex, but `default.qubit` does not, so I always cast to complex in `apply_operation` when getting the state. Fixed the associated docs as well.
**Benefits:**
Improved docs, `Snapshot` is fixed up
I am actually changing something (`Snapshot`) right before a release.

update snapshot; little docs changes

---

doc/releases/changelog-0.34.0.md
pennylane/_qubit_device.py
pennylane/measurements/expval.py
pennylane/measurements/var.py
tests/ops/qubit/test_observables.py

This PR supercedes #4971  and fixes #4975 . [sc-52681]
As this is a high priority bug and we have an upcoming release, I am fixing this here.
Nicely this bug can be fixed by removing the specialized logic and just always just the default logic. This will be easier to maintain and extend in the future.

Measuring projectors on a state with parameter broadcasting.

---

pennylane/pauli/pauli_arithmetic.py

**Context:**
Clarify the convention for empty Pauli sentences and Pauli words
Just added docs

Added docs for empty PS and PW convention

---

doc/releases/changelog-0.34.0.md
pennylane/templates/subroutines/controlled_sequence.py
tests/ops/functions/test_iterative_qpe.py
tests/templates/test_subroutines/test_controlled_sequence.py

Recreation of PR #4955 , because the merge conflicts with the RC branch were a mess
**Context:**
The current decomposition of ControlledSequence stops at Power operations (with non-trainable powers). These are rejected by many ML interfaces.
- Added `lazy=False` when creating the power operators.
- Also added a `control_wires` property, because it was returning an empty wires object, and that's confusing. It does mean we have both `control` and `control_wires` returning the same thing. If we don't want both, we could have control_wires raise an error saying it doesn't exist, but it's strange for it to exist and return empty Wires.
**Benefits:**
- `ControlledSequence` can be used with the ML interfaces.
- The people who come after me will not be confused, as …

Update ControlledSequence decomposition

---

doc/releases/changelog-0.34.0.md
pennylane/qnn/keras.py
tests/qnn/test_keras.py

**Context:**
Fixes #4999. We re-implemented the default `setattr` and `getattr` dunders for `KerasLayer` (needed to modify the QNode saved on the layer) but we should have called `super()`, because `keras.layer.Layer` has its own custom implementation that we needed to use. Our `TorchLayer` already calls `super` in these cases.
Note - our existing tests were passing because the weights used had custom names ("w1", "w2", etc.), and this issue only comes up when your weights are named "weights" (which is a rather common case, I'm sure).
- Replace our default-handling of `get/set-attr` dunders with a call to `super()`
- add a test case matching the one in the bug report using the "weights" identifier
**Benefits:**
Models using `KerasLayer` can be saved and …

fix keraslayer set and get attr dunders

---

tests/gradients/parameter_shift/test_parameter_shift.py
tests/gradients/parameter_shift/test_parameter_shift_hessian.py
tests/gradients/parameter_shift/test_parameter_shift_shot_vec.py
tests/interfaces/default_qubit_2_integration/test_autograd_qnode_default_qubit_2.py
tests/interfaces/default_qubit_2_integration/test_jax_jit_qnode_default_qubit_2.py
tests/interfaces/default_qubit_2_integration/test_tensorflow_qnode_default_qubit_2.py
tests/interfaces/test_jax_jit_qnode.py
tests/interfaces/test_tensorflow_qnode.py
tests/kernels/test_kernels.py
tests/ops/op_math/test_controlled.py
tests/ops/op_math/test_controlled_decompositions.py
tests/ops/op_math/test_decompositions.py
tests/pytest.ini
tests/test_qnode.py
tests/test_return_types.py
tests/test_return_types_qnode.py

**Context:**
There is an `xfail_strict` pytest option, which makes xpass (passing tests that are marked as xfail) tests count as failures.
- Add `xfail_strict=true` to pytest.ini
- Fix all tests that were xpassing. I tried to make minimal changes to the tests themselves, but I'm open to more extensive test re-working if we think it's necessary
**Benefits:**
It's nice to have because it tells us if we've fixed old things we didn't know we've fixed, which should help us keep our testing etc. up to date
If a test is decorated as `pytest.mark.xfail`, we seem to get the most out of this functionality. However, if you add a `pytest.xfail` WITHIN a test that would have passed afterwards, pytest doesn't know the difference and calls this a …

set xfail_strict=True

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/drawer/draw.py
pennylane/transforms/core/transform_dispatcher.py
tests/drawer/test_draw.py
tests/shadow/test_shadow_transforms.py
tests/transforms/test_experimental/test_transform_dispatcher.py

**Context:**
We used to advise users to pass transforms additional arguments positionally in transforms being used as decorators. Now, it's forbidden (they need to use `functools.partial`). It has been deprecated for 2 releases, so it's time to remove it.
Raise a `TransformError` if someone uses the old transform decorator syntax
**Benefits:**
Less support for old style of doing things, helps us keep our code cleaner
It felt intuitive for me to turn the warning into an explicit error, but usually we just remove code outright when doing removals. This constructor doesn't have an intuitive way of just removing this functionality, so I feel like raises an error explicitly makes sense
[sc-51278]

remove support for transform arguments without partial in decorators

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/operation.py
pennylane/tape/qscript.py
tests/ops/op_math/test_adjoint.py
tests/ops/op_math/test_pow_op.py
tests/test_operation.py

completing the deprecation cycle. will break braket-*-latest as they haven't moved yet.
[sc-51274]

remove observable.return_type

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/measurements/measurements.py
tests/measurements/test_measurements.py

`mp.name` has always been "Identity", and `mp.data` has always been `[]`. This was needed as a hack in the past, but we don't need it anymore.
This PR deprecates those values, and they will be removed in the next release.
[sc-43949]

deprecate mp.name and mp.data

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/shadows/classical_shadow.py
tests/shadow/test_shadow_entropies.py

completing the deprecation cycle.
[sc-52334]

remove the atol kwarg from ClassicalShadow.entropy

---

doc/requirements.txt

it fails every time because they released a new version on Friday. See [this CI run](https://github.com/PennyLaneAI/pennylane/actions/runs/7528280758/job/20490145370) as an example.
```
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```

pin sphinxcontrib-applehelp in doc requirements

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/ops/functions/matrix.py
tests/ops/functions/test_matrix.py

**Context:**
Wire-ordering can surprise people because PennyLane gives no promises. For example:
```pycon
>>> qs = qml.tape.QuantumScript([qml.Identity(1), qml.CNOT([0, 1])])
>>> qml.matrix(qs)
array([[1., 0., 0., 0.],
[0., 0., 0., 1.],
[0., 0., 1., 0.],
[0., 1., 0., 0.]])
```
This is in wire-order `[1, 0]` because that's the order in which they appeared in the tape. Most users would expect the other way.
Deprecate the default `wire_order=None` value in `qml.matrix` in certain cases. The warning is raised if:
- the object is a tape with more than one wire
- the object is a QNode and the device does not provide wires
- the object is a qfunc
**Benefits:**
Users won't be surprised when they get a matrix in an unexpected wire order
More …

deprecate qml.matrix with wire_order=None

---

doc/code/qml_tape.rst
doc/releases/changelog-dev.md

[sc-54022]
**Context:**
We keep the name `QuantumTape` in documentation, but strictly use its parent `QuantumScript` in PennyLane source code. We use `QuantumScript` because carrying around an unnecessary `AnnotatedQueue` can cause difficulties with parallelism and construction via queuing is substantially more expensive in both memory and time. Queuing can also lead to unintended side effects of things entering the circuit that shouldn't, or things not entering the circuit that should.
This disconnect between documentation and source code is not explained anyone, and a bit confusing.  So this adds some clarification to the module documentation for `qml.tape.`.
Added module documentation.
**Benefits:**
Hopefully this clears up some confusion.
**Possible …

Clarify difference between `QuantumTape` and `QuantumScript`

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/prod.py
pennylane/ops/op_math/sprod.py
pennylane/pauli/utils.py
tests/ops/op_math/test_sprod.py
tests/pauli/test_pauli_utils.py
tests/pulse/test_rydberg.py
tests/test_operation.py

**Context:**
Started in #5031, but missed this upgrade behaviour for `SProd`
If the base provided to `SProd.__init__` is a Tensor or Hamiltonian, auto-upgrade it to new arithmetic operators using `qml.operation.convert_to_opmath`
**Benefits:**
No confusing errors or unexpected behaviour when working with new operator arithmetic.
N/A
Fixes #5060

SProd auto-upgrades tensor and hamiltonian bases

---

doc/releases/changelog-dev.md
pennylane/_device.py
tests/test_device.py

**Context:**
Many plugins are failing because of the deprecation of `MeasurementProcess.name` (#5047). The old device API checks if an object meets the stopping requirement _or_ if it's a measurement (in that order). Due to this ordering, we reference `mp.name` which is now deprecated.
Swap the order of conditions in `_local_tape_expand` to avoid hitting this deprecation warning
**Benefits:**
Plugins will work again!
N/A

legacy device: check if object is measurement before checking stopping_condition

---

doc/releases/changelog-dev.md
pennylane/ops/functions/generator.py
pennylane/ops/op_math/controlled.py
tests/ops/op_math/test_controlled.py

**Context:**
`Controlled.generator` always projects onto the $\ket{1}$ space of the control wire without considering control values.
Now `Controlled.generator` correctly projects the operator based on the control value specified
**Benefits:**
Fixes a bug

BugFix: Controlled.generator correctly projects with control values

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/operation.py
pennylane/ops/qutrit/non_parametric_ops.py
pennylane/ops/qutrit/parametric_ops.py
tests/ops/qutrit/test_qutrit_parametric_ops.py
tests/test_operation.py

This PR relocates the `Operator.validate_subspace()`  method  to the `qml.ops.qutrit.parametric_ops` module.
`Operator.validate_subspace(subspace)` is only employed under a specific set of qutrit operators and is therefore not needed as an official part of the Operator interface.

Deprecate Operator.validate_subspace(subspace)

---

doc/releases/changelog-dev.md
pennylane/_device.py
tests/test_device.py

Same as #5071 but in other places.
I'm a little worried that maybe we shouldn't deprecate `MeasurementProcess.name` at all... seems like we kinda depend on it? My first thought was to just make them more correct (eg. "State", "Probs"), but I don't think any devices have those saved in their `dev.observables` so I suppose this might still be the best way forward

update more spots that use MP.name

---

doc/releases/changelog-dev.md
pennylane/templates/state_preparations/cosine_window.py
tests/templates/test_state_preparations/test_cosine_window.py

**Context:**
When StatePrepBase operations are used at the start of a circuit on a subset of all circuit wires, we want to initialize the system state with all other wires set to the zero-state. `CosineWindow` did not implement this edge-case, and only returned a state spanning the subspace of the wires it acts on regardless of wire order given (it only used `wire_order` for transposition, not expansion)
Update `CosineWindow.state_vector` to expand over unused wires present in the provided `wire_order`
Master:
```pycon
>>> qml.CosineWindow(wires=[0, 1]).state_vector(wire_order=[0, 1, 2]).shape
(2, 2)
```
Branch:
```pycon
>>> qml.CosineWindow(wires=[0, 1]).state_vector(wire_order=[0, 1, 2]).shape
(2, 2, 2)
```
**Benefits:**
No more unexpected errors when …

CosineWindow expands over all circuit wires

---

doc/releases/changelog-dev.md
pennylane/transforms/optimization/undo_swaps.py
pennylane/transforms/split_non_commuting.py
tests/transforms/test_optimization/test_undo_swaps.py
tests/transforms/test_split_non_commuting.py

When exploring in PR #5058, I found bugs in `undo_swaps` and `split_non_commuting`.
[sc-54373]
[sc-54374]
Undo swaps had a fragile way of mapping wires, as it was created before we had `Operator.map_wires`.  Now it works with more general operations.
`split_non_commuting` was not passing the shots along. This was a silent issue on the old device interface, but would be causing problems if it was ever used with the new device interface.

fix `undo_swaps` and `split_non_commuting`

---

tests/math/test_multi_dispatch.py

**Context:**
New version of `scipy` removed many deprecated functions, including `scipy.kron`. This was used in a test, causing CI to fail when using latest `scipy`
Removed problematic test

Remove test using `scipy.kron`

---

doc/releases/changelog-dev.md
pennylane/queuing.py
tests/test_queuing.py

This was originally added in #3182, but I only put the test in `test_tape.py`, so it was accidentally pruned in #3281 (anagram PR!) which isn't ideal. I'm putting it back in `test_queuing.py` where it truly belongs.
I know this PR seems a bit insignificant, but I remember this bug coming up and I don't want it to resurface because of a lack of testing. Plus, the `finally` is much prettier than writing the cleanup code twice 😄 
Not bothering with a changelog entry, but can add if we feel strongly about it

restore test for `stop_recording` cleanup

---

.github/workflows/interface-unit-tests.yml
doc/releases/changelog-dev.md

**Context:**
When the Codecov upload action fails because of network issues or the like, the action reports as passed, then the `codecov` action stays as "Expected" forevermore. This is worse than a failure because it continues to block us but we don't immediately know why. If we knew, we could just re-run it when we find out.
Set the codecov upload action to fail on failure 😄 
**Benefits:**
We will know when it fails to upload, and we can re-run the upload task manually
External contributors might hit this, and although the old ways were also bad, this might be a bit more visibly frightening if you don't know why you got a big red ❌

fail CI if coverage fails to upload

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/controlled.py
tests/ops/op_math/test_controlled.py

**Context:**
Multi-wire controlled `PhaseShift` should not be converted to a one-less-wire controlled `ControlledPhaseShift`
- `qml.ctrl` no longer convert multi-wire controlled `PhaseShift` to a one-less-wire controlled `ControlledPhaseShift`
- Special handling of multi-wire controlled `PhaseShift` in decompositions
**Benefits:**
1. Fixes test failing in lightning
2. Correct decomposition of multi-wire controlled `PhaseShift`

Revert special handling of PhaseShift in ctrl

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/prod.py
tests/ops/op_math/test_prod.py

Revert change to `Prod.pauli_rep` construction order

---

doc/releases/changelog-dev.md
pennylane/math/single_dispatch.py
tests/devices/test_default_mixed_tf.py

**Context:**
`default.mixed` used with tensorflow throws an error when applying a state that is not initialized in `complex128`, originally found here: https://discuss.pennylane.ai/t/error-with-keraslayer-and-amplitude-embedding/3924
`tf.convert_to_tensor` does not work for states that are already `Tensor` objects with a different `dtype`. Use `tf.cast` instead when this is the case.
**Benefits:**
BugFix
https://github.com/PennyLaneAI/pennylane/issues/5085
**Shortcut**
[sc-55061]

BugFix: Tensorflow type promotion error with Tensors

---

pennylane/operation.py
tests/test_operation.py

An edge case I missed in #5070 broke Lightning tests. This is to fix that.

Fix `Tensor.map_wires`

---

doc/releases/changelog-dev.md
pennylane/ops/functions/equal.py
tests/ops/functions/test_equal.py

**Potential** fix for https://github.com/PennyLaneAI/pennylane/issues/5162 and many other related issues  
Simply compares the pauli_rep between operators, when both have one.
[sc-56466]

[BUGFIX] qml.equal via pauli_rep

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/pow.py
tests/ops/functions/test_iterative_qpe.py
tests/ops/op_math/test_pow_op.py

**Context:**
This is a bugfix for #5002 , which was being caused by `Pow.matrix` not being differentiable with tensorflow due to the use of `scipy.linalg.fractional_matrix_power`.
* Updated `Pow._matrix` to do the matrix power operation manually when the scalar is an integer and the interface is "tensorflow". This can be traced by tensorflow, and hence, is diff-compatible.
**Benefits:**
`Pow` is differentiable with tensorflow.
#5002

[BUGFIX] Update `Pow.matrix` to handle integer powers with TensorFlow

---

doc/releases/changelog-dev.md
pennylane/transforms/mitigate.py
tests/transforms/test_mitigate.py

**Context:**
A QNode transformed with `mitigate_with_zne` does not accept parameters with a leading dimension
1. Replace `qml.math.dot` with `qml.math.tensordot` in `_polyfit`
2. Test case added for parameter broadcasting with `mitigate_with_zne`
**Benefits:**
BugFix
https://github.com/PennyLaneAI/pennylane/issues/5100
**Related Shortcut Story:**
[sc-55298]

Add broadcasting support to mitigate_with_zne

---

doc/releases/changelog-dev.md
pennylane/ops/identity.py
pennylane/ops/op_math/controlled.py
tests/ops/qubit/test_parametric_ops.py

**Context:**
The `Tensor` and `Hamiltonian` does not work with `Identity` on no wires, causing issues with `ControlledGlobalPhase` when the `GlobalPhase` acts on no wires.
1. Use `prod` and `s_prod` in place of straight multiplication in the `generator` of `Controlled` and `GlobalPhase`
2. The generator of `GlobalPhase` now contains an identity that acts on the same wires as the `GlobalPhase`.
**Benefits:**
BugFix
https://github.com/PennyLaneAI/pennylane/issues/4578
**Related Shortcut Story:**
[sc-44933]

Use new op math in generator of GlobalPhase and Controlled

---

.github/workflows/tests.yml

git rebase failed [badly](https://github.com/PennyLaneAI/pennylane/actions/runs/7892879771/job/21541221953), so I'm just gonna `git merge origin/master` instead. maybe we could just skip the whole thing.. but idk I don't have great amounts of faith in the checkout bot for some reason. anyway this [worked](https://github.com/PennyLaneAI/pennylane/actions/runs/7893410969/job/21542363385?pr=5201)!

merge instead of rebase so the stable workflow works

---

doc/releases/changelog-dev.md
pennylane/io.py
tests/test_io.py

**Context:**
Currently if you try to use `qml.from_qiskit` without the plugin installed, you get the somewhat non-specific
`ValueError: Converter does not exist. Make sure the required plugin is installed and supports conversion.`
If the "converter does not exist" error is raised when calling `qml.from_qiskit`, the user is shown a more explicit message with instructions for installing the plugin and for contacting the forum if they have issues.

Clear error message if plugin is not installed

---

doc/releases/changelog-dev.md
pennylane/_device.py
pennylane/transforms/mitigate.py
pennylane/workflow/execution.py
pennylane/workflow/jacobian_products.py
tests/interfaces/test_autograd.py
tests/interfaces/test_jax.py
tests/interfaces/test_jax_jit.py
tests/interfaces/test_torch.py

**Context:** In the PennyLane source code, the `map_batch_transform` method is currently used in several locations. However, a new functionality has recently been added to `TransformDispatcher` so that transforms can be dispatched onto a batch of tapes (see #5163).
**Description of the Change:** We replace the current usage of `map_batch_transform` in the source code, taking advantage of the new method `_batch_transform` implemented in the `TransformDispatcher` class.
**Benefits:** Implementing transforms over a batch of tapes without resorting to `map_batch_transform` is much more straightforward.
**Possible Drawbacks:** The new method in `TransformDispatcher` replacing `map_batch_transform` is called only if the transform is applied on a sequence consisting of `qml.tape.QuantumScript` …

Replacing `map_batch_transform` in source code

---

doc/releases/changelog-dev.md
pennylane/ops/identity.py
pennylane/ops/qubit/non_parametric_ops.py
tests/ops/qubit/test_non_parametric_ops.py
tests/ops/test_identity.py

Before, the overwriting of the class name happens in the initialization, which means that it is not overwritten until at least one class instance is initialized. This lead to problems in datasets. Fixed this by globally overwriting the class name instead.
Better long term solution:
Check for instances instead of class names (this is a bigger effort though as this happens in a lot of places in the codebase and, likely, plugins)

[Bugfix] Make sure Identity, X, Y, Z have correct __name__ by default

---

doc/development/release_notes.md
doc/releases/changelog-0.34.0.md
doc/releases/changelog-0.35.0.md
pennylane/_version.py

Updates PennyLane as we're entering a new development version (release of v0.35.0 coming up):
Preparation of release candidate:
- Rename changelog-dev.md to changelog-0.35.0.md
- Increments the version number to v0.35.0
- Change changelog-dev reference to changelog-0.35 reference in release_notes.md
```
rc    master
|     |
|     - add changelog-dev.md, add changelog-dev reference to release_notes.md, bump version to 0.36.0-dev
|    /
|   /
|  /
| /
|/
- (**THIS PR**) rename changelog-dev.md to changelog-0.35.0.md, change changelog-dev reference to changelog-0.35 reference in release_notes.md, move "current release" label from changelog-0.34 to changelog-0.35, change version from 0.35.0-dev to 0.35.0
|
| 
```

Preparation for release candidate 0.35.0

---

.github/workflows/docs.yml

**Context:**
PRs on forks fail the docs CI when trying to upload freeze changes, so I'd like to just skip that part if the PR is from a fork.
Skip those steps if on a fork, as described [here](https://github.com/orgs/community/discussions/25217).
**Benefits:**
External contributor PRs won't fail unexpectedly
N/A - it will run often enough by us internally that the docs freeze file will be kept up-to-date regardless
- Example failure: https://github.com/PennyLaneAI/pennylane/actions/runs/8039250831/job/21956066233?pr=5256
- Confirmed it skips on forks: https://github.com/PennyLaneAI/pennylane/actions/runs/8071064111/job/22049837508?pr=5272

only run doc freeze on non-fork PRs

---

doc/releases/changelog-0.35.0.md
pennylane/drawer/tape_mpl.py
tests/drawer/test_tape_mpl.py

For some reason the `qml.Barrier` operation was not being drawn with the correct `plt.rcParams['lines.color']`, but instead was still using the default value of `lines.color` (`'C0'`). 
I think the color of the vertical lines is decided when the lines are displayed, not when the lines are added to the figure.
As this shows the lines in black:
```
plt.rcParams['lines.color'] = "black"
_, ax = qml.drawer.tape_mpl(tape, style="rcParams")
```
but this shows them in blue.  Which is a strange departure from how other things seem to work in matplotlib.
```
plt.rcParams['lines.color'] = "black"
_, ax = qml.drawer.tape_mpl(tape, style="rcParams")
plt.rcParams['lines.color'] = "blue"
```
Anyway, we just force the color of that lines to match `plt.rcParams['lines.color']` when we add them to the …

Make mpl color for `Barrier` match style sheet

---

doc/releases/changelog-0.35.0.md
pennylane/drawer/draw.py
tests/drawer/test_draw.py
tests/drawer/test_draw_mpl.py
tests/drawer/test_tape_mpl.py

Fixes #5275 [sc-57775]
Basically, we were only applying the transforms before drawing when the user provided `expansion_strategy` wasn't `"device"` and the device was from the new device interface.  This PR makes it so that we always apply all the user transforms before drawing.  This is a quick fix until #5139 can get in.

Apply all user transforms before drawing

---

doc/releases/changelog-0.35.0.md
pennylane/gradients/adjoint_metric_tensor.py
pennylane/transforms/__init__.py
pennylane/transforms/core/transform.py
pennylane/transforms/core/transform_dispatcher.py
pennylane/transforms/core/transform_program.py
pennylane/transforms/tape_expand.py
tests/gradients/core/test_adjoint_metric_tensor.py

**Context:**
The `adjoint_metric_tensor` transform does not work with jax variables because jax variables are not considered trainable parameters until they become tracers.
1. Add a custom expand transform to `adjoint_metric_tensor` that expands trainable parameters based on argnums.
2. Add an optional `use_argnum_in_expand` argument to transform programs to determine whether or not to perform `jax_argnums_to_tape_trainable` on the parameters.
**Benefits:**
BugFix
Adding yet another keyword argument to `transform` may make code look messy.
https://github.com/PennyLaneAI/pennylane/issues/5197
**Related Shortcut Stories:**
[sc-56734]

BugFix: adjoint metric tensor with jax

---

doc/introduction/measurements.rst
pennylane/io.py

**Context:**
The documentation for `qml.from_qiskit()` is lacking in both breadth, depth, and examples.
Note that this PR forks #5259 due to 7d05c63f69eb8ab364a11b2bc49027d2cefc0c30.
* Expanded the `qml.from_qiskit()` docstring.
* Applied analagous style changes to the `qml.from_qiskit_op()` docstring.
* Added a reference target `mid_circuit_measurements`.
**Benefits:**
* Users can use the `qml.from_qiskit()` function with more ease and confidence.
None.
None.

 Expand documentation for `qml.from_qiskit()`

---

pennylane/fermi/conversion.py
tests/fermi/test_parity_mapping.py

**Context:**
The warning in `parity_transform`, informing users to use the mapping consistently, is replaced with a note.
**Benefits:**

Remove warning in `parity_transform` and add a note

---

doc/introduction/interfaces.rst
pennylane/devices/preprocess.py
pennylane/devices/qubit/simulate.py
pennylane/io.py
pennylane/ops/op_math/sum.py
pennylane/transforms/defer_measurements.py
pennylane/workflow/interfaces/tensorflow.py
tests/transforms/test_defer_measurements.py

Following changes have been made:
* `qml.defer_measurements` doesn't work with custom wire labels if any of the measured wires are reused/reset.
* Added a note to `interfaces.rst` to tell users to how see all supported interfaces. Jason pointed out that the [`workflow` internals page](https://docs.pennylane.ai/en/latest/code/qml_workflow.html#supported-interfaces), which uses file names with underscores for the different interfaces (`tensorflow_autograph`, `jax_jit`), might indicate to users that the interface `jax_jit` is a valid one rather than `jax-jit`.
* Grammar fixes, markdown to sphinx code-block conversions, code example doc fixes.
* Tensorflow interface docs for custom gradient functions had a mistake that is resolved here.

Fixes for the 0.35 release

---

doc/development/deprecations.rst
doc/releases/changelog-0.35.0.md
pennylane/ops/op_math/sprod.py
tests/ops/op_math/test_sprod.py

Missed to add `SProd.terms()`, `SProd.ops` and `SProd.coeffs`, fixing this here

Add `SProd.terms()` method

---

pennylane/templates/state_preparations/mottonen.py

GlobalPhase was added to the Mottonen decomp in #5166, but the docstring wasn't updated. this does it

Fix mottonen docstring to account for global phase

---

pennylane/ops/op_math/prod.py
pennylane/ops/op_math/sum.py
tests/ops/op_math/test_prod.py
tests/ops/op_math/test_sum.py

**Context:**
Found out that the updates to `Prod.terms` and `Sum.terms` cause new operators to get queued.
* Added a bunch of `qml.QueuingManager.stop_recording()`s
I didn't add a changelog entry because the changes to `Sum/Prod.terms()` are part of v0.35.
**Benefits:**

`Prod.terms` and `Sum.terms` don't queue operators

---

doc/releases/changelog-0.35.0.md
pennylane/ops/channel.py
tests/ops/test_channel_ops.py

Fixes #5285  [sc-57816]
Adds a `qml.math.is_abstract` check around a validation check that doesn't work with jitting.
I wanted to change `from pennylane import math as np` to `from pennylane import math` in this PR, but I realized that made the PR bigger than it needed to be.
I also had to change a bunch of unnecessary lambda assignments in the test code to standard functions in order to get the file passing pylint.

Make `QubitChannel` compatible with jitting

---

doc/development/guide/architecture.rst
pennylane/math/fidelity.py
pennylane/math/quantum.py
pennylane/math/utils.py
pennylane/measurements/probs.py
pennylane/ops/op_math/controlled.py
pennylane/ops/qubit/special_unitary.py
pennylane/qcut/cutcircuit_mc.py
pennylane/transforms/batch_partial.py
pennylane/transforms/optimization/pattern_matching.py
pennylane/workflow/execution.py
pennylane/workflow/interfaces/jax.py
pennylane/workflow/interfaces/tensorflow.py

Some spelling errors were found during QA. Fixed here.

Address spelling/formatting errors in docs

---

doc/development/deprecations.rst
doc/releases/changelog-0.35.0.md
pennylane/ops/op_math/sprod.py
tests/ops/op_math/test_sprod.py

Merging PR #5287 to add `terms` to `SProd` created problems for Catalyst that won't be resolved before the release. Here the commit pushing it to the RC branch is reverted, and we will return to the change next week.

Revert #5287

---

doc/releases/changelog-dev.md
tests/interfaces/test_jax_qnode.py

**Context:**
`tests/interfaces/test_jax_qnode.py::TestQubitIntegration::test_counts` occasionally fails in CI due to sometimes we only get counts for one outcome.
Adds `all_outcomes=True` in calls to `qml.count` in this test case.
**Benefits:**
Less time wasted rerunning CI tests

Make sure two counts are always returned in test_counts

---

doc/releases/changelog-0.35.1.md
pennylane/_version.py
pennylane/compiler/compiler.py
tests/test_compiler.py

**Context:**
There are two compatibility issues with the v0.35.0 release of PennyLane:
1. The minimum required Catalyst version is now v0.5.0 (#5320).
2. Lightning simulators need special handling of diagonalizing gates when performing sampling measurements (#5343).
This PR cherry-picks the squashed commit corresponding to (1) into the RC branch as the change necessary for (2) is already being made directly to the RC branch.
* Bumped the PennyLane Python package version to `v0.35.1`.
* Cherry-picked the following commits into the RC branch: https://github.com/PennyLaneAI/pennylane/commit/a4f0fff1ad6e3f2b7d048384f43f839b4b0d88e6 and https://github.com/PennyLaneAI/pennylane/commit/79ce676fcebf702f72d1ae88f7948a5be572d6c3.
**Benefits:**
* The latest PennyLane …

Create `v0.35.1` bugfix release

---

doc/releases/changelog-0.35.1.md
pennylane/_qubit_device.py
setup.py
tests/devices/test_lightning_qubit.py

**Context:**
Lightning simulators …

Bugfix: Lightning simulators do not support `rotations` anymore.

---

tests/measurements/test_var.py

**Context:**
``test_value`` in `test_var.py` fails in CI sometimes due to random samples sometimes not having a distribution that is exactly as expected. Increase the number of shots from around 1000 to 5000 such that the sample distribution is closer to the theoretical.
Increasing the number of shots from 1111 to 5000 to reduce the probability of test case failing due to statistical fluctuations
**Benefits:**
Less failing in CI
[sc-58507]

Increase number of shots in `test_value` to avoid failures due to statistic fluctuations

---

pennylane/shadows/classical_shadow.py
tests/measurements/legacy/test_classical_shadow_legacy.py
tests/measurements/test_classical_shadow.py
tests/shadow/test_shadow_class.py

We missed this in the last release. Upgrading classical shadows functionality to play nice with new opmath
[sc-58404]
[sc-58626]

[new opmath] Upgrade classical shadows with new opmath

---

pennylane/pauli/utils.py
tests/ops/qubit/test_hamiltonian.py
tests/pauli/test_pauli_utils.py

Some functionality is old and marked as legacy, some needed fixing. In particular, needed to update functions in `pennylane/pauli/utils.py`

[new opmath 4.1] Update pauli utils

---

tests/measurements/test_sample.py

Only one test needed updating. Data type for eigvals is `float` for `Prod` and `int` for `Tensor`. This is acceptable because what we actually care about here is that the `sample(obs).numeric_type` matches the `obs.eigvals` numeric type. In light of that, the test is updated to check that instead. 
In doing that, we discovered that while the numeric type for Identity is `int` (as expected by the previous implementation of the test), the eigvals on `Identity` are floats, causing the issue #5369. **This particular test currently does not pass, but that is because it reveals a bug, not because the test is wrong.**
The bug is general and not related to the `new_op_math` project, and will be fixed on master (pending decision about how to resolve). The one test failure in `test_sample.py` will …

Update measurement tests for new op math

---

tests/drawer/test_draw.py
tests/drawer/test_tape_text.py

One failing test not marked as `xfail` because it is resolved by #5362.

Update drawer tests for op_math

---

pennylane/_device.py
tests/test_device.py

This PR fixes the following test:
- `tests/test_device.py::TestInternalFunctions::test_device_default_expand_ops`
Files modified in the source code:
- None
[sc-58795]

fixing `tests/test_device.py.test_device_default_expand_ops`

---

pennylane/ops/op_math/linear_combination.py
tests/ops/op_math/test_linear_combination.py

The `eigvals` function inherited from `CompositeOp` was failing for the same reason as `diagonalizing_gates`. Fixed here.
Eigvals function is copy-pasted from `CompositeOp` and only the line indicated by the comment is modified.

Update eigvals function

---

doc/releases/changelog-dev.md

**Context:**
Changelog entries in the deprecations and removals PRs have rendering issues on readthedocs
Replace double quotes with single quotes for code snippets

Fix rendering issues in release doc from deprecations and removals

---

doc/releases/changelog-dev.md
pennylane/devices/default_qutrit.py
pennylane/utils.py
tests/ops/op_math/test_prod.py

[sc-59010]
The `tests/devices/test_default_qutrit.py` tests were failing due to `Prod.eigvals()`.  The eigenvalues were not defined for `Tensor`, but now `Prod` gives it its best effort. Unfortunately, `Prod`'s best effort was not sufficient.
This change improves `qml.utils.expand_vector` so it is compatible with qudit operators.

Make `Prod` compatible with qutrit operators

---

tests/transforms/test_optimization/test_merge_rotations.py
tests/workflow/test_construct_batch.py

"Fixing" `tests/workflow/test_construct_batch.py::TestConstructBatch::test_device_transforms_legacy_interface` by marking it as legacy as it is specifically testing `default.qubit.legacy`. Up for discussion, pelase leave feedback.

[new opmath] Update tests/workflow/

---

pennylane/devices/default_clifford.py
tests/devices/default_qubit/test_default_qubit_preprocessing.py
tests/devices/default_qubit/test_default_qubit_tracking.py
tests/devices/test_default_clifford.py
tests/devices/test_default_qubit_jax.py
tests/devices/test_default_qubit_legacy.py
tests/devices/test_default_qubit_tf.py
tests/devices/test_default_qubit_torch.py
tests/devices/test_preprocess.py
tests/test_queuing.py

Mostly things that simply dont raise an error anymore with new opmath.
Everything related to `qutrit` devices are handled in a separate story
For reviewing, best to run locally using `python -m pytest tests -n auto -k "not qutrit" tests/devices`
Also, make sure to `pip install stim` to not skip the clifford simulator tests
[sc-59008]

[enable new opmath] update tests/devices/

---

pennylane/devices/qutrit_mixed/sampling.py
tests/devices/qutrit_mixed/test_qutrit_mixed_sampling.py

Replace `Hamiltonian` in `qutrit_mixed/sampling.py` with `qml.Hamiltonian` for legacy op-math tests to pass.

Use qml.Hamiltonian instead of Hamiltonian in isinstance checks

---

doc/releases/changelog-dev.md
pennylane/devices/default_clifford.py
tests/devices/test_default_clifford.py

**Context:** A couple of tests failed with the new `stim` release.
**Description of the Change:** Force `int` conversion from `numpy.int64` type and increase the number of shots to improve the robustness of sampling tests.
**Benefits:**
**Possible Drawbacks:** N/A 
**Related GitHub Issues:** N/A

Make Clifford device compatible with the new `stim` release

---

doc/releases/changelog-dev.md
pennylane/ops/qutrit/parametric_ops.py

**Context:**
Updates the defined qutrit op generators to return as either a qml.ops.Hamiltonian or a qml.ops.LinearCombination as part of standardizing generators and keeping them consistent with the `opmath` setting. Previously always returned `sprod` regardless of `if active_new_opmath`.
Use `qml.Hamiltonian` instead of `sprod` to multiply the coefficient on to the operator
**Benefits:**
- The operator type returned will be consistent with the current setting to enable/disable `new_opmath` (i.e. no new opmath operators returned while `disable_new_opmath` is active)
- `isinstance(op.generator(), Hamiltonian)` checks won't break when you switch from old to new opmath

Add relevant comments on qutrit generators

---

doc/releases/changelog-dev.md
pennylane/qinfo/transforms.py
tests/qinfo/test_fisher.py

**Context:**
The `qml.qinfo.quantum_fisher` transform was failing on non-`defualt.qubit` devices:
```
from sklearn import datasets as ds
NUM_WIRES = 4
def get_circuit(data, parameters):
qml.IQPEmbedding(data, wires=range(NUM_WIRES), n_repeats=1)
for i in range(NUM_WIRES):
qml.RX(parameters[i], wires=i)
for j in range(NUM_WIRES-1):
qml.CNOT(wires=[j, j+1])
dev = qml.device("default.mixed", wires=NUM_WIRES)
def qfim(X_train, parameters):
circuit = qml.QNode(get_circuit, dev)
data = np.array(X_train[0], requires_grad=False)
return qml.qinfo.transforms.quantum_fisher(circuit)(data, parameters)
X = ds.load_iris().data
parameters = np.random.random(size=NUM_WIRES, requires_grad=True)
print(qfim(X, …
```

`quantum_fisher` transform on non-`default.qubit` devices

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/composite.py
tests/ops/op_math/test_composite.py

**Context:**
As title says. Previously if `op.overlapping_ops` was not `None`, the `overlapping_ops` of the new operator still had the original wires.
Update `new_op._overlapping_ops` in `CompositeOp.map_wires`.
**Benefits:**

`CompositeOp.map_wires` correctly maps `overlapping_ops`

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/measure.py
pennylane/math/multi_dispatch.py
pennylane/math/single_dispatch.py

**Context:** When Torch has a GPU …

Fix Torch tensor locality with autoray-registered `coerce` method

---

doc/releases/changelog-dev.md
tests/optimize/test_spsa.py
tests/transforms/test_defer_measurements.py

**Context:** This fixes the current …

Fix lightning tests for 0.36 feature changes

---

doc/releases/changelog-dev.md
pennylane/workflow/qnode.py
tests/test_qnode.py

**Context:**
While investigating Issue #5442, I was getting really confused by why my tensorflow execution was giving a torch error. I realized that when the execution fails, we do not properly reset `QNode.interface` back to `"auto"`.  
Pulls a block of the code to a helper method so that we can wrap it in a `try-finally` block.
**Benefits:**
We can continue using a qnode after a failure has occured during execution.
[sc-60047]

Reset qnode after execution error

---

doc/releases/changelog-dev.md
pennylane/optimize/adaptive.py
pennylane/optimize/qnspsa.py
tests/optimize/test_adaptive.py
tests/optimize/test_qnspsa.py

Fixes #5437 .  [sc-59838]
When we started distinguishing vanilla numpy and autograd numpy in our source code, we accidentally switched to using vanilla numpy in the `QNSPSA` optimizer instead of autograd numpy.  This switches it back.

Fix `QNSPSA` Optimizer

---

doc/releases/changelog-dev.md
pennylane/ops/qubit/hamiltonian.py
tests/ops/qubit/test_hamiltonian.py

**Context:**
A user was encountering issues where operations were remaining in the circuit after being used to construct a hamiltonian.
De-queue the arguments to `Hamiltonian.__matmul__`
**Benefits:**
No more things in the circuit that shouldn't be in the circuit.
Fixes #5454 [sc-60158]

dequeue ops in `Hamiltonian.__matmul__`

---

doc/development/deprecations.rst

**Context:** As Centos7 is EOL, we …

Add manylinux2014 migration to deprecations page

---

.github/workflows/interface-unit-tests.yml

We never added the token to the action like [it recommends us to](https://github.com/codecov/codecov-action/tree/v3?tab=readme-ov-file#usage) 🤦 adding the token should result in less intermittent failures like [this one](https://github.com/PennyLaneAI/pennylane/actions/runs/8597929198/job/23566821116?pr=5161), so we might as well.
~@albi3ro  can you confirm that this secret exists in our repo settings?~ confirmed offline

use codecov token in upload action

---

.github/workflows/interface-unit-tests.yml
.github/workflows/tests.yml

**Context:** Fix codecov coverage upload breaking for tests
Codecov recently changed their API where a token has to be specified during coverage upload. Previously this was not needed for public repos. 
According to their docs, this token should still not be needed for forks, so it should be fine for us, however, the token is needed for PRs within the same repo.
**Benefits:**
Fixes codecov upload.

Fix coverage upload to codecov being broken

---

doc/releases/changelog-dev.md
pennylane/drawer/tape_text.py
tests/drawer/test_draw.py

**Context:**
Bug fix for #5499 
Adding labels to layer strings only extends to wires, not classical bits.
**Benefits:**
Drawer works correctly with mid-circuit measurements

Operations/measurements on all wires are drawn correctly with mid-circuit measurements

---

doc/releases/changelog-dev.md
pennylane/devices/tests/conftest.py
pennylane/devices/tests/test_gradients_tf.py
pennylane/devices/tests/test_measurements.py

The new tests added to the device test suite weren't totally compatible with lightning devices. I've updated the failing tests to work now. The tensorflow tests failed because our execution pipeline with tensorflow doesn't correctly respect the dtypes, which is a larger issue for us to resolve, so it will be handled in a different PR. For now I've skipped the failing tests.

Update device tests to work with Lightning devices

---

doc/releases/changelog-dev.md
pennylane/_qubit_device.py

**Context:**
`_qubit_device`'s …

Introduce special diagonalize procedure around ProbabilityMP measurements for Lightning 

---

doc/releases/changelog-dev.md
pennylane/_qubit_device.py
pennylane/measurements/counts.py
tests/measurements/test_counts.py
tests/test_qubit_device.py

**Context:**
[sc-61314] Issue #5513 was being caused by samples that were converted to decimals to be cast to `int8`. This caused overflow with 8 or more wires, resulting in negative values being present in the counts dictionary.
* Update `qml.counts.process_samples` and `QubitDevice._samples_to_counts` to cast to `int64` instead of `int8`.
**Benefits:**
No more overflow issues with `qml.counts`.
#5513

Cast samples to `int64` instead of `int8` in `qml.counts`

---

doc/releases/changelog-dev.md
pennylane/math/multi_dispatch.py
tests/math/test_multi_dispatch.py

Fixes https://github.com/PennyLaneAI/pennylane/issues/5542
**Relevant Shortcut Stories:**
[sc-61616]

Fixing kron compatibility `numpy @ torch`

---

pennylane/devices/qubit/sampling.py
pennylane/pauli/grouping/group_observables.py
tests/devices/default_qubit/test_default_qubit_tracking.py
tests/interfaces/default_qubit_2_integration/test_autograd_default_qubit_2.py
tests/interfaces/default_qubit_2_integration/test_jax_default_qubit_2.py
tests/interfaces/default_qubit_2_integration/test_tensorflow_default_qubit_2.py
tests/interfaces/default_qubit_2_integration/test_torch_default_qubit_2.py

**Context:**
PR https://github.com/PennyLaneAI/pennylane/pull/5525 led to two bugs:
- `group_observables` uses `are_identity_pauli_words`, which does not work for legacy `Hamiltonian`.
- `get_num_shots_and_executions` incorrectly counts number of executions for `Sum`
- Converts single-term `Hamiltonian` to `SProd`
- Use the grouping information of `Sum` to correctly count number of executions.
**Related Shortcut Issues:**
[sc-61807]
[sc-61812]
Fixes https://github.com/PennyLaneAI/pennylane/issues/5561

Follow-up bug fixes for `_group_measurements`

---

pennylane/templates/subroutines/fable.py

**Context:**
As pointed out by @isaacdevlugt, Fable template docs are unclear regarding the number of wires needed. This seeks to clarify that.
Docs changed to reflect that the # of wires needed is 2n+1
**Benefits:**
Users don't get confused by the seemingly random additional wire

Doc fix for fable template

---

doc/releases/changelog-dev.md
pennylane/drawer/draw.py
tests/drawer/test_draw.py
tests/drawer/test_draw_mpl.py

**Context:**
Devices may no longer provide a wire order, and we can also draw quantum functions that do not have an intrinsic wire order.  This can lead to the wire order in the drawing being unexpected, like `[4,3,0,1]`.
Tries to sort the wires if no other wires are provided, but fallbacks to the tape wires if sorting fails.
Before:
After: 
**Benefits:**
Nicer looking drawings.
try-except as logical control.
[sc-61203]

Draw sorts wires

---

tests/devices/qubit/test_measure.py
tests/devices/qubit/test_sampling.py
tests/pauli/grouping/test_pauli_group_observables.py
tests/test_qnode_legacy.py

**Context:**
Some newly added test cases failing with legacy opmath
Skip these tests if new opmath is disabled:
`test_measure_identity_no_wires` in `tests/devices/qubit/test_measure.py`
`test_identity_on_no_wires_with_other_observables` in `tests/devices/qubit/test_sampling.py`
`test_observables_on_no_wires_coeffs` in `tests/pauli/grouping/test_pauli_group_observables.py`
`test_multiple_hamiltonian_expansion_finite_shots` in `tests/test_qnode_legacy.py`
**Related Shortcut Issues:**
[sc-62144]
[sc-62143]

Skip tests not supported with new opmath

---

.github/workflows/install_deps/action.yml
pennylane/gradients/__init__.py
pennylane/gradients/classical_jacobian.py
pennylane/gradients/finite_difference.py
pennylane/gradients/general_shift_rules.py
pennylane/gradients/hadamard_gradient.py
pennylane/gradients/jvp.py
pennylane/gradients/parameter_shift.py
pennylane/gradients/parameter_shift_cv.py
pennylane/gradients/parameter_shift_hessian.py
pennylane/gradients/pulse_gradient.py
pennylane/gradients/pulse_gradient_odegen.py
pennylane/gradients/spsa_gradient.py
pennylane/gradients/vjp.py
pennylane/kernels/cost_functions.py
pennylane/kernels/postprocessing.py
pennylane/kernels/utils.py

**Context:**
Docs get out of sync over time.
In particular, the output shape of gradient transforms applied to QNodes was changed in #4945 but not updated in the docs.
Update examples in docs of `qml.gradients` module.
Also updates the `qml.kernels` docs, with a few very small changes.
**Benefits:**

Fix `qml.gradients` docs examples

---

pennylane/operation.py
tests/ops/op_math/test_sum.py
tests/test_operation.py

**Context:**
Fixes latest failures in the legacy opmath tests in the plugin test matrix.
1. `convert_to_opmath` now dequeues the original op.
2. Skip test with `I()` when new opmath is disabled.

BugFix: convert_to_opmath does not dequeue original op

---

doc/development/deprecations.rst
doc/releases/changelog-0.36.0.md

**Context:**
We want to communicate the change in default op arithmetic behaviour happening in v0.36 very clearly to the user.
Adds a section in the release notes and in the deprecations page.

Release notes v0.36 - op arithmetic section and updates to deprecations page

---

doc/releases/changelog-0.36.0.md
pennylane/gradients/gradient_transform.py
pennylane/gradients/parameter_shift.py
tests/gradients/parameter_shift/test_parameter_shift_shot_vec.py

**Context:**
Shot vectors together with the `broadcast=True` feature of `param_shift` suffers from the bug #5598 .
For some shot vector lengths, this bug causes silent wrong results, for other lengths it causes a non-comprehensive error.
This PR explicitly disallows this combination and raises a `NotImplementedError`.
A proper fix is in the works.
**Benefits:**
No silently wrong results and more comprehensive error message.
#5598

Disallow `param_shift(... broadcast=True)` with shot vectors

---

pennylane/templates/subroutines/trotter.py

**Context:**
With new opmath enabled, `TrotterProduct` does not automatically simplify the input Hamiltonian.
Adding a warning to let the user know of this behaviour
[sc-62232]

Add warning to TrotterProduct regarding simplification behaviour

---

doc/releases/changelog-0.36.0.md
pennylane/drawer/tape_mpl.py
pennylane/drawer/tape_text.py
pennylane/drawer/utils.py
tests/transforms/test_defer_measurements.py

**Context:**
`defer_measurements` leaves `MeasurementValue`s in the terminal measurement processes if they are present. This is not friendly with the drawer as the classical wires for those measurement values do not exist when using `defer_measurements`. This PR adds a "hack" fix so that the drawer/MPL drawer work with this scenario.
Add `transform_deferred_measurements_tape` util function, which replaces any `MeasurementValue`s present in the tape after applying `defer_measurements` with wires. This transform is only applied in `tape_text` and `tape_mpl`.
**Benefits:**
Drawer works better with MCMs
Hacky fix, technical debt to implement cleaner fix later
https://github.com/PennyLaneAI/pennylane/issues/5588

Fix `qml.draw/_mpl` to work with deferred measurements circuits that use MCMs in measurements

---

pennylane/devices/preprocess.py
tests/devices/default_qubit/test_default_qubit_preprocessing.py
tests/devices/test_preprocess.py

**Context:**
When adjoint differentiation is used, a warning is incorrectly raised when the parameters of a measured observable is not actually trainable.
Update the `validate_adjoint_trainable_params` to use `qml.operation.is_trainable` instead of `tape.trainable_params`.

More accurate validation of trainable parameters for adjoint diff

---

doc/releases/changelog-0.36.0.md
pennylane/pauli/dla/lie_closure.py
tests/pauli/dla/test_lie_closure.py

Noticed that `lie_closure` was not numerically stable after a [user report](https://discuss.pennylane.ai/t/calculation-of-dynamical-lie-algebra/4309/3)
Fixing that by

[Bugfix] Fix numerical stability of `lie_closure`

---

doc/releases/changelog-0.36.0.md
pennylane/templates/subroutines/trotter.py
tests/templates/test_subroutines/test_trotter.py

**Context:**
Rename the accepted values for the method keyword argument in the TrotterProduct class to be more verbose. 
Change: 
- `method="one-norm"` --> `method="one-norm-bound"`
- `method="commutator"` --> `method="commutator-bound"`

Rename values for `method` kwarg in `TrotterProduct` class

---

doc/code/qml.rst
doc/news/new_opmath.rst
doc/releases/changelog-0.36.0.md

Some links in new opmath page did not work. Used https://github.com/bskinn/sphobjinv to identify the right objects.
The links to `Hamiltonian` class dont work because in `latest` there is no rendered version of that doc

Fix links in news/new_opmath.rst

---

doc/conf.py
pennylane/ops/qubit/hamiltonian.py

Due to the dispatch of `qml.Hamiltonian` that involves removing `Hamiltonian` from the top level in `pennylane/__init__.py`, the doc was not displayed anymore. This fix "hacks" sphinx to add the missing obect back, at least for sphinx.
Optional separate issue: A user seeking out the `qml.Hamiltonian` docs at the top level may be confused because this now dispatches to `LinearCombination` but this is not mentioned there. Added a warning to avoid that confusion.

[Bugfix] Hamiltonian is rendered in top level docs

---

pennylane/ops/functions/dot.py

When `ops` is a `Tensor`, this line:
```
if len(coeffs) != len(ops)
```
raises an error because `Tensor` does not have `len`. Moving the `isinstance` checks for `ops` to the beginning of the function.

Fix error raised when taking dot of a single Tensor

---

.github/stable/external.txt
pennylane/compiler/compiler.py
setup.py
tests/drawer/test_draw_catalyst.py
tests/test_compiler.py

**Description of the Change:** The minimum compiler version needs to be updated due to device API update. This is the last PR to be merged to the release candidate as it depends on Catalyst being updated.

Update minimum compiler version

---

doc/releases/changelog-dev.md
pennylane/fermi/conversion.py
tests/fermi/test_bravyi_kitaev.py

**Context:**
There is a wrong call in bravyi_kitaev when the input object is FermiSentence, which is only observed for some specific inputs that were not covered by our current tests. The PR fixes the bug and adds an extra test to check the accuracy.
**Benefits:**

[BUG] Fix a fermi sentence bug in bravyi_kitaev

---

doc/releases/changelog-dev.md
pennylane/ops/functions/is_commuting.py
tests/ops/functions/test_is_commuting.py

**Context:** ***Part of  deprecations and removals for pennylane-0.37***
**Description of the Change:** Removed the `wire_map` argument from `qml.is_commuting`.
[sc-58988]

Removing the `wire_map` argument from `qml.is_commuting`

---

doc/releases/changelog-dev.md
pennylane/devices/preprocess.py
pennylane/gradients/finite_difference.py
pennylane/gradients/parameter_shift.py
pennylane/transforms/compile.py
pennylane/transforms/optimization/merge_rotations.py
pennylane/transforms/transpile.py
tests/devices/test_preprocess.py

**Context:**
As the `decompose` transform is used in various contexts, it would be nice to specify the error type that should be raised if its not possible to get a suitable decomposition for one of the operators  (i.e. devices raise `DeviceError`, transforms and gradients raise `DecompositionUndefinedError`, catalyst raises `CompileError`)
An error kwarg is added to `decompose` and its helper function `_operator_decomposition_gen` so that the error type can be specified. It continues to default to `DeviceError`
**Benefits:**
We don't have to duplicate many lines of code to get an identical function with a different error type
More kwargs
N/A
**Related Shortcut Stories:** …

Allow specifying error type to be raised by decompose

---

pennylane/devices/__init__.py

**Context:** To use the new `default.tensor` device in PennyLane, we must import the `quimb` Python package. 
The strategy adopted for this was the same previously used for the `default.clifford` device, which depends on the `stim` Python package. That is, when the user imports `pennylane`, the package is imported if installed on the system, otherwise it is not imported. An error is raised if the user explicitly tries to instantiate the device without the package installed.
However, `quimb` frequently raises a warning message when it is imported if `kahypar` is not installed. This causes the following unpleasant situation: if a user has `quimb` installed on the system and imports `pennylane`, the following warning message is raised:
```
UserWarning: Couldn't import `kahypar` - skipping …
```

Removing `DefaultTensor` from `init` file

---

pennylane/operation.py
tests/conftest.py
tests/devices/default_tensor/test_tensor_expval.py
tests/devices/default_tensor/test_tensor_var.py
tests/devices/qubit/test_measure.py
tests/devices/qubit/test_sampling.py
tests/ops/op_math/test_sum.py
tests/pauli/grouping/test_pauli_group_observables.py
tests/test_pytrees.py
tests/test_qnode_legacy.py

- Update `Tensor.eigvals` to use `qml.math.kron` instead of `np.kron`, fixes https://github.com/PennyLaneAI/pennylane/actions/runs/9248166629/job/25438052473
- Adds a `new_opmath_only` fixture that skips tests not meant to work for legacy opmath
- Mark `tests/test_pytrees.py::test_nested_pl_object` as `new_opmath_only` (confirmed with @albi3ro)
- Mark tests in `tests/devices/default_tensor` involving `Hamiltonian` as `new_opmath_only` (confirmed with @PietropaoloFrisoni)

Fix recent failures in legacy opmath

---

doc/code/qml_qchem.rst
doc/introduction/chemistry.rst
pennylane/qchem/molecule.py
pennylane/qchem/openfermion_obs.py

**Context:**
The PR updates the qchem docs after making Molecule the central object in qchem.
**Benefits:**

Update qchem docs to use Molecule everywhere

---

doc/development/guide/installation.rst
doc/development/guide/tests.rst

A duplicate of [#5740](https://github.com/PennyLaneAI/pennylane/pull/5740) due to doc building issues.
Modify Software Tests page of the developer's guide to be requirements-agnostic
**Context:**
Software Tests page was outdated and relied on listing the testing requirements instead of relying on the continuously updated `requirements-dev.txt` file. 
Instructions for installing the development requirements was added to the Installation page and the Requirements section of Software Tests has been modified to be more informative rather than instructive.
**Benefits:**
Less overhead to update the guide later if deps are added/removed.
[[sc-63429](https://app.shortcut.com/xanaduai/story/63429)]

Modify Software Tests page of the developer's guide to be requirements-agnostic

---

doc/releases/changelog-dev.md
pennylane/drawer/draw.py
pennylane/ops/functions/matrix.py
tests/ops/functions/test_matrix.py
tests/pytest.ini

**Context:** Currently `qml.matrix`
breaks when the input is a catalyst-compiled QNode instead of a plain
QNode, and the QNode need to be manually retrieved by the user: 
https://github.com/PennyLaneAI/catalyst/issues/765
It would be beneficial to do this "unwrap" in `qml.matrix` , like those in qml.draw: 
https://github.com/PennyLaneAI/pennylane/blob/59a1e0586e707d057a0c92d4239036afa5312b73/pennylane/drawer/draw.py#L213-L214
**Description of the Change:** 
1. in `pennylane/ops/functions/matrix.py`, in `qml.matrix(op)`, if the input `op` is a catalyst.qjit compiled function, dispatches the behavior to be `qml.matrix(op.user_function)`. 
2. Added a test in `tests/ops/functions/test_matrix.py`
**Benefits:** a qjit compiled qnode can be passed into `qml.matrix` directly to query the matrix …

patch `qml.matrix` to accept qnodes compiled by `catalyst.qjit`

---

codecov.yml

**Context:** The logging module …

Remove coverage for untestable logging functionality

---

doc/releases/changelog-dev.md
pennylane/devices/default_qubit.py
tests/devices/default_qubit/test_default_qubit.py

**Context:**
Validation of the adjoint method did not take device wires into account, leading to the linked issue.
Include `validate_device_wires` in `_supports_adjoint` in `DefaultQubit`.
**Benefits:**
fixes #5760
[sc-64278]

Fix adjoint validation with global measurements

---

.github/workflows/docker.yml
doc/releases/changelog-dev.md

**Context:** As the docker builds …

Disable Docker builds on PR merges

---

.pylintrc
doc/development/guide/installation.rst
doc/releases/changelog-dev.md
doc/requirements.txt
pennylane/__init__.py
pennylane/compiler/compiler.py
pennylane/devices/default_qubit_tf.py
pennylane/devices/default_qubit_torch.py
pennylane/numpy/random.py
pennylane/qnn/keras.py
requirements-ci.txt
requirements.txt
setup.py
tests/.pylintrc

**Context:** In #5754, we forgot to add `packaging` as a new hard requirement for PennyLane. Some developers experienced troubles when importing PL.
**Description of the Change:** We included `packaging` in the relevant contexts as a new required package.
**Benefits:** The user would not experience trouble importing PennyLane if `packaging` is not installed on his/her system.
**Possible Drawbacks:** None that I can think of, except possible issues with external plugins for incompatibilities between the previous workflow of `semantic_version` and the new one of `packaging` (in which case, we can quickly restore the previous `semantic_version` usage where it occurs).
**Related GitHub Issues:** None.
**Related Shortcut Stories:** [sc-64576].

Add `packaging` as a new required package in PennyLane

---

doc/releases/changelog-dev.md
pennylane/devices/default_tensor.py
tests/devices/default_tensor/test_default_tensor.py

**Context:** In the `default.tensor` device, we need to create an initial state (e.g. in the MPS case using the `MPS_computational_state function`) in `quimb`, which requires the number of qubits to be defined.
We have a very cryptic error from `quimb` as soon as we compute something with this device if there is a mismatch between the circuit wires and those on the device. 
To circumvent this issue, we previously made `wires` the last positional argument for this device (as in `lightning.qubit`), checking at runtime if there's a mismatch between the wires on the device and those associated with the circuit.
**Description of the Change:** We now instantiate the `quimb` tensor directly in the `simulate` function. The wires on the device are selected at runtime to match those on the circuit …

Selecting wires of `default.tensor` at runtime if they are not provided by user

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/exp.py
tests/ops/op_math/test_exp.py

**Context:**
The simplified operator of an exponential was not returning the correct number of steps.
`Exp.simplify()`now returns an operator with the correct number of Trotter steps, i.e. equal to the one from the pre-simplified operator.
**Benefits:**
Correct number of Trotter steps is now included after simplification
Fixes #5747
[sc-64181]

include the the num_steps in Exp.simplify

---

doc/releases/changelog-dev.md
pennylane/transforms/split_non_commuting.py
tests/transforms/test_split_non_commuting.py

**Context:**
The post processing function of `split_non_commuting` incorrectly converts the interface of results and erases the trainability of `Hamiltonian` observables
Removes `convert_like` call.
Fixes https://github.com/PennyLaneAI/pennylane/issues/5837
[sc-65649]

Fix bug where `split_non_commuting` erases trainability of observables

---

doc/introduction/measurements.rst
doc/releases/changelog-dev.md
pennylane/capture/__init__.py
pennylane/capture/capture_meta.py
pennylane/capture/capture_qnode.py
pennylane/devices/execution_config.py
pennylane/measurements/measurements.py
pennylane/operation.py
pennylane/workflow/execution.py
pennylane/workflow/qnode.py
tests/capture/test_capture_qnode.py
tests/test_qnode.py

**Context:**
As name says.
* Add new `mcm_method` `"single-branch-statistics"` used to request the original Catalyst way of performing mid-circuit measurements, wherein only a single branch of the execution tree is explored.
* Raise an error if calling a qnode with `mcm_method="single-branch-statistics"` when not using `qml.qjit`.
* `QNode.__init__` now uses a `MCMConfig` dataclass for MCM config arguments
* Updated `capture` module to work with the updates to `QNode`.
* Added new metaclass `ABCCaptureMeta` in the `capture` module to use as the metaclass for `MeasurementProcess` and `Operator`. This way, we don't need to create metaclasses local to the files to which those classes belong.
**Benefits:**

Add `mcm_method="single-branch-statistics"` for the default Catalyst MCM behaviour

---

pennylane/ops/op_math/adjoint.py

Analogous change to create_controlled_op.
Allows to bypass the dispatch of qml.adjoint to catalyst.adjoint, without which it would not be possible for Catalyst to instantiate the PennyLane adjoint operator while benefiting from the additional logic provided by the qml.adjoint user function.
No functional changes.
[sc-65586]
Needed for https://github.com/PennyLaneAI/catalyst/pull/802

Split adjoint to bypass catalyst dispatch

---

pennylane/debugging/__init__.py
pennylane/debugging/debugger.py
pennylane/debugging/snapshot.py
pennylane/debugging/snapshots.py
tests/test_debugging.py

**Context:**
Move the contents of `~/pennylane/debugging.py` to a dedicated module and separated snapshots from PLDB and pldb.

Move `snapshots` and `breakpoint` functionality into a dedicated module

---

doc/releases/changelog-dev.md
pennylane/ops/identity.py
pennylane/ops/op_math/pow.py
tests/ops/op_math/test_pow_op.py

**Context:**
The adjoint of an integer power of an operator is the same power of the adjoint of the operator.
For fractional powers, this does not hold because of branch cuts in the power function.
This PR explicitly disallows computing the (eager) adjoint of a `Pow` operator with fractional power, and raises an `AdjointUndefinedError` in this case.
As a tiny side effect, this PR changes the signature of `Identity.pow` to be compatible with generalized simplification workflows where the keyword argument `z` for the power is passed around explicitly (this popped up in a simplification test of `Pow`)
NB: As usual, a lazy `Adjoint(Pow(base, z=0.2))` is still supported, just can't be evaluated/simplified if that would lead to calling the method `adjoint` of …

Disallow taking the adjoint of fractional power operations

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/controlled_ops.py
tests/ops/op_math/test_controlled_ops.py

**Context:**
A user was doing `qml.CRY(0.1, wires=((0,1), 2)`.  In this case, the control wire should be a single wire with a value `(0,1)`.  Yes, this is weird, but this is how wires work in pennylane.  Instead, it was being interpretted as having two control wires, even though `CRY` is only for singly-controlled `RY` gates.
Some minor slicing changes in how we handle special controlled ops.  
Now we have:
```
>>> qml.CZ(wires=((0,1), 2))
CZ(wires=[(0, 1), 2])
```
Which is consistent with how we treat wires elsewhere in pennylane.
**Benefits:**
Don't end up with a two qubit gate on three qubits.
Still weird, and still not what the user was looking for when they provided wires like that.  But at least now they'll get a better error. …

Fix wire handling on special control wires

---

doc/releases/changelog-dev.md
pennylane/transforms/core/transform_dispatcher.py
tests/transforms/core/test_transform_dispatcher.py

**Context:**
Issue #5843 made me realize when we apply a transform to a qfunc callable, we should use `functools.wraps` to preserve the docstring and signature of the original function.
Adds `functools.wraps` to the transformed qfunc.
**Benefits:**
transformed qfunc's keep information about the original function.
Fixes #5843

transform callables wrap original qfunc

---

pennylane/devices/default_tensor.py

**Context:** `quimb 1.8.2` has been released recently. This PR implements small improvements and updates to `default.tensor` based on new features introduced in the new version of `quimb`.
**Description of the Change:** As above.
**Benefits:** One fewer package to import.
**Possible Drawbacks:** None that I can think of.
**Related GitHub Issues:** None.
**Related Shortcut Stories:** [sc-65970]

Small improvements and updates to `default.tensor` based on `quimb 1.8.2`

---

doc/releases/changelog-dev.md
pennylane/transforms/split_non_commuting.py
tests/transforms/test_split_non_commuting.py

**Context:**
Currently on master, if we apply `split_non_commuting` to a tape with empty measurements, we delete the tape:
```
>>> from pennylane.transforms import split_non_commuting
>>> tape = qml.tape.QuantumScript([qml.X(0)], measurements=[])
>>> tapes, _ = split_non_commuting(tape)
>>> tapes
[]
```
We add a check for `len(measurements) == 0` and just return the tape if there are no measurements to split, so we get:
```
>>> from pennylane.transforms import split_non_commuting
>>> tape = qml.tape.QuantumScript([qml.X(0)], measurements=[])
>>> tapes, _ = split_non_commuting(tape)
>>> tapes
[<QuantumScript: wires=[0], params=0>]
```
**Benefits:**
We don't delete the tape if it has no measurements (came up in catalyst tests)

Bugfix for split_non_commuting when tape measurements is empty

---

doc/releases/changelog-dev.md
pennylane/ops/functions/equal.py
tests/ops/functions/test_equal.py

Fixes bug where `qml.equal` incorrectly returns `True` when a `Tensor` is not equal with another non-`Tensor` observable.

Fix bug in Tensor equal check

---

doc/releases/changelog-dev.md
pennylane/pauli/conversion.py
tests/pauli/test_conversion.py

**Context:** `pauli_decompose` …

Adding an is_abtract check in pauli_decompose so it does not break under jit (either jax.jit or catalyst.qjit)

---

doc/development/deprecations.rst
doc/releases/changelog-0.37.0.md
pennylane/io.py
tests/test_io.py

**Context:**
https://github.com/PennyLaneAI/pennylane/pull/5882 led to deprecation warnings raised in non-applicable scenarios
Only raise deprecation warning if the circuit contains measurements
**Benefits:**
Less confusing deprecation warnings

Raise DeprecationWarning only when the qasm code contains measurements

---

doc/releases/changelog-dev.md
pennylane/tape/qscript.py
tests/tape/test_qscript.py

**Context:**
When investigating some performance issues, I noticed that we weren't caching `QuantumScript.hash`, even though calculating it is a known performance bottleneck.
Make `QuantumScript.hash` a cached property.
**Benefits:**
Much lower classical overhead when we are using caching.
If someone does bad things and mutates the tape in place, they will have to deal with the resulting consequences.

turn QuantumScript.hash into a cached property

---

doc/releases/changelog-0.37.0.md
pennylane/ops/functions/equal.py
pennylane/transforms/dynamic_one_shot.py
tests/ops/functions/test_equal.py

**Context:**
Some changes were added preemptively in #5888 for changes that were being added to Catalyst in https://github.com/PennyLaneAI/catalyst/pull/832, but that PR is not merged, so the changes from #5888 have to be reverted.
Reverted changes from #5888 
Some updates to catalyst-`split_non_commuting` caused test failures in Catalyst in cases where terminal measurements contain mid-circuit measurements, so `qml.equal` was updated to handle abstract measurement values.
**Benefits:**

Revert changes added for MidCircuitMeasure updates

---

pennylane/qinfo/transforms.py
tests/measurements/legacy/test_mutual_info_legacy.py
tests/measurements/test_mutual_info.py
tests/qinfo/test_entropies.py

**Context:**
https://app.shortcut.com/xanaduai/story/66713/deprecate-qml-qinfo-transforms-mutual-info?vc_group_by=day&ct_workflow=all&cf_workflow=500000005
**Benefits:**

Deprecate `qinfo.mutual_info`

---

doc/releases/changelog-0.37.0.md
pennylane/transforms/split_non_commuting.py
tests/transforms/test_split_non_commuting.py

Fall back to wire-based grouping for single `Sum` with non-pauli-word observables
Fixes https://github.com/PennyLaneAI/catalyst/actions/runs/9769748288/job/26969777919

Fix `split_non_commuting` for `Sum` containing non-pauli-word terms

---

pennylane/measurements/vn_entropy.py
pennylane/qinfo/transforms.py
tests/qinfo/test_entropies.py

**Context:**
https://app.shortcut.com/xanaduai/story/66716/deprecate-qml-qinfo-transforms-vn-entropy
**Benefits:**

Deprecate `qinfo.vn_entropy` 

---

pennylane/ops/functions/equal.py

**Context:**
Some contents of the `qml.equal` docstring is outdated.
Updates the `qml.equal` docstrings

Update docstrings of `qml.equal` and `qml.assert_equal`

---

doc/releases/changelog-0.37.0.md
pennylane/devices/tests/test_return_system.py

**Context:**
Lightning-GPU fails …

Fix `test_return_system`

---

doc/releases/changelog-0.37.0.md
pennylane/transforms/split_non_commuting.py
tests/transforms/test_split_non_commuting.py

Honestly, I don't really understand what the root issue is, and I don't really understand why this fixes it.
But it does 🤷
Fixes https://github.com/PennyLaneAI/pennylane/issues/5924
[sc-67508]

Fixes `split_non_commuting` with non-trainable autograd coefficients

---

doc/code/qml_noise.rst
pennylane/boolean_fn.py
pennylane/devices/default_tensor.py
pennylane/drawer/draw.py
pennylane/gradients/parameter_shift.py
pennylane/noise/conditionals.py
pennylane/noise/noise_model.py
pennylane/ops/op_math/pow.py
pennylane/qaoa/layers.py
pennylane/qchem/convert_openfermion.py
pennylane/queuing.py
pennylane/resource/specs.py
pennylane/transforms/add_noise.py
pennylane/transforms/dynamic_one_shot.py
pennylane/workflow/construct_batch.py

**Context:** 
Quality assurance work over several PR's for 0.37 release. 
Changes include:
- Change docstring capitalization and punctuation.
- Add missing imports to examples from docstrings
- Correct results from docstrings examples
- Improve formulation of convoluted sentences.

QA release fixes

---

doc/releases/changelog-dev.md
pennylane/tape/qscript.py
tests/interfaces/default_qubit_2_integration/test_autograd_qnode_default_qubit_2.py
tests/interfaces/test_autograd_qnode.py
tests/tape/test_tape.py

**Context:**
The `interface` property of `QuantumScript` is pretty much unused (always returns `None`) throughout the codebase, with no meaningful tests for it.
The property has been removed.
[[sc-67608](https://app.shortcut.com/xanaduai/story/67608)]

Removed unused `interface` property from `QuantumScript` class

---

pennylane/transforms/__init__.py

Fixing a typo in an example of the `transforms` documentation, discovered by @trbromley and @Jaybsoni.
I checked the entire document with Grammarly and applied some suggested changes. I am not an English speaker, so feel free to point out if something does not sound right.
Edit: as requested on Slack, I'm adding a small section to show the usage of `@partial` for quantum transforms
[sc-68726]

Fixing typo in the documentation + small new section with an example

---

doc/releases/changelog-dev.md
pennylane/ops/channel.py

**Context:** Resolves the #5988
**Description of the Change:** Modified in the constructor and 
**Benefits:** Better parameter name
**Possible Drawbacks:** - 
**Related GitHub Issues:**[(#5988)](https://github.com/PennyLaneAI/pennylane/issues/5988)

Fix typo for qml.ThermalRelaxationError 

---

.github/workflows/core_tests_durations.json
.github/workflows/install_deps/action.yml
doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/operation.py
pennylane/ops/op_math/composite.py
pennylane/ops/op_math/symbolicop.py
tests/ops/op_math/test_composite.py
tests/ops/op_math/test_prod.py
tests/ops/op_math/test_sprod.py
tests/ops/op_math/test_symbolic_op.py
tests/pulse/test_parametrized_evolution.py

**Context:**
`queue_idx` is a private detail of CircuitGraph that seeped into the Operator interface that didn't need to be there. Now we are making it actually private to CircuitGraph.
`queue_idx` attribute has been removed from the `Operator`, `CompositeOp`, and `SymboliOp` classes.
**Benefits:**
Less convolute `Operator` classes (and children classes) and proper encapsulation of attribute.
[#5907]
[sc-67435]

Remove queue idx

---

doc/releases/changelog-dev.md
pennylane/measurements/state.py

**Context:**
The changes made in …

Change casting rules for StateMP to avoid copy in Lightning

---

doc/releases/changelog-dev.md
pennylane/_qubit_device.py
pennylane/workflow/qnode.py

…_shots is deprecated
**Context:** …

Bugfix: dynamic_one_shot is broken for old-API devices

---

tests/ops/op_math/test_linear_combination.py

This test case explicitly tests behaviour with new opmath enabled.

Mark test_mixed_legacy_warning_Hamiltonian as new opmath only

---

.github/workflows/upload-nightly-release.yml

**Context:** This PR updates the …

Update nightly builds to store wheels as artefact before upload

---

pennylane/devices/qubit/simulate.py
pennylane/workflow/qnode.py

Update qml.QNode documentation "main measurements page" links to point to Dynamic quantum circuits page.
**Context:**
- From slack message in #pennylane-oss-qa channel: https://xanaduhq.slack.com/archives/C0743CNS9E3/p1722451700797329.
- links for `main measurement page` in `mcm_method` and `postselect_mode` are inaccurate and should link to Dynamic quantum circuits page instead (https://docs.pennylane.ai/en/stable/introduction/dynamic_quantum_circuits.html#configuring-mid-circuit-measurements)
- Update "main measurements page" links in `mcm_method` and `postselect_mode` to point to Dynamic quantum circuits page (https://docs.pennylane.ai/en/stable/introduction/dynamic_quantum_circuits.html#configuring-mid-circuit-measurements)
**Benefits:**
- Users can get …

Update links in `qml.QNode` docstring

---

doc/releases/changelog-dev.md
pennylane/capture/primitives.py
pennylane/ops/identity.py
tests/capture/test_operators.py

**Context:**
When writing tests for [(#837)](https://github.com/PennyLaneAI/catalyst/pull/837), I found we weren't capturing `Identity` and `GlobalPhase` when they act on zero wires correctly.
Fix the capture of `GlobalPhase` and `Identity` when they act on no wires.
**Benefits:**
[sc-70350]

Fix capture of `GlobalPhase` and `Identity` when they act on no wires

---

pennylane/workflow/execution.py

As name says. Original implementation was using `override_shots` and/or device shots, which is correct, but outdated behaviour. I just changed it to use `tape.shots` instead.

Update how finite shots are validated for MCM configuration

---

doc/releases/changelog-dev.md
pennylane/gradients/fisher.py
pennylane/qinfo/transforms.py

**Context:**
The documentation of `qinfo.quantum_fisher` was not quite precise on when `adjoint_metric_tensor` is being used (successfully), and did not mention potential auxiliary wire requirements.
Make the criterion on using default.qubit precise (because we catch other devices), and mention that for other settings, an auxiliary wire may be required.
**Benefits:**
#6059 
[sc-70300]

Update documentation of `quantum_fisher`

---

doc/releases/changelog-dev.md
pennylane/compiler/qjit_api.py
tests/capture/test_capture_while_loop.py

**Context:** This add support for capturing `while_loop` into plxpr.
**Description of the Change:** The function's behaviour resembles the one for `for_loop`, and works on capturing both `cond_fn` and `body_fn` and executing both of them at runtime.
**Benefits:** `while_loop` will enjoy `plxpr` when capture is enabled
**Possible Drawbacks:** N/A
**Related GitHub Issues:** [sc-66773]

Add support for `while_loop` capture

---

doc/releases/changelog-dev.md
pennylane/compiler/qjit_api.py
tests/capture/test_capture_for_loop.py

**Context:** This adds the default `step=1` and a `range`-like syntax support for single-parameter. 
**Description of the Change:** One can now do the following instead of specifying complete `(0, 3, 1)`:
```py
@for_loop(0, 3)
def f(i):
qml.X(i)
@for_loop(3)
def f(i):
qml.X(i)
```
**Benefits:**
**Related GitHub Issues:** [sc-70477] [sc-70478]

Add default values to `for_loop`

---

pennylane/workflow/qnode.py

**Context:**
- The word 'variational circuit' is not hyperlinked, instead the link it next to the word due to a typo.
- Fix to hyperlink the URL to the text 'variational circuit'.
**Benefits:**

Fix hyperlink typo in `qml.QNode` docstring

---

doc/releases/changelog-dev.md
pennylane/ops/qubit/observables.py
tests/ops/functions/conftest.py
tests/ops/qubit/test_observables.py

**Context:**
Prior to this fix, the `compute_decomposition` method of `Hermitian` returned a `qml.DecompositionUndefinedError` (due to its `Operator` base class inheritance). The desired fix, as laid out by the issue, was to use the existing `pauli_decompose` method to perform the desired decomposition. 
Implemented a custom `compute_decomposition` static method  in `Hermitian` to have it call the existing `pauli_decompose` method. 
<ins>Examples</ins>
```python
>>> op = qml.X(0) + qml.Y(1) + 2 * qml.X(0) @ qml.Z(3)
>>> op_matrix = qml.matrix(op)
>>> qml.Hermitian.compute_decomposition(op_matrix, wires=['a', 'b', 'aux'])
[(
1.0 * (I('a') @ Y('b') @ I('aux'))
+ 1.0 * (X('a') @ I('b') @ I('aux'))
+ 2.0 * (X('a') @ I('b') @ Z('aux'))
)]
>>> op = np.array([[1, …
```

[Closes #6047] Implements custom `compute_decomposition` method in `Hermitian`

---

pennylane/workflow/qnode.py

While reviewing some other QNode code, I realized we were setting and resetting the interface in `QNode.construct`, even though it had absolutely no impact on anything.  This code can safely be removed.
**Benefits:**
Slightly simpler logic in a very complicated, highly coupled piece of code.

Minor `QNode` clean up: remove setting and resetting interface

---

tests/ops/qubit/test_observables.py

After the merge of #6062 , the legacy op math tests in the plugin test matrix fail (see [here](https://github.com/PennyLaneAI/pennylane/actions/runs/10362479768/job/28685492331)), since the test uses the `Operator.matrix` method to verify the decomposition, but the decomposed operator is a legacy `Hamiltonian` with new op math disabled, which doesn't have a matrix. This PR just updates the test to use `qml.matrix` instead of `Operator.matrix`.

Update `Hermitian.decomposition` test to use `qml.matrix`

---

pennylane/workflow/execution.py
pennylane/workflow/qnode.py
tests/devices/test_default_qubit_torch.py

- Added `Literal` type `SUPPORTED_INTERFACE_USER_INPUTS` to `execution.py` and use that to populate the `INTERFACE_MAP` through the `get_args` method.
- Added `SUPPORTED_DIFF_METHODS` `Literal` type in the `QNode` file.
- Added type hints for the rest of the arguments.
[[sc-66109](https://app.shortcut.com/xanaduai/story/66109)]

Added type hints to QNode public functions

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/composite.py
tests/ops/op_math/test_composite.py

Fixes a bug where `CompositeOp.overlapping_ops` changes the original ordering of ops.
Fixes https://github.com/PennyLaneAI/pennylane/issues/6090
[sc-71201]

BugFix: CompositeOp.overlapping_ops maintains the original order of ops.

---

doc/releases/changelog-dev.md
pennylane/data/data_manager/__init__.py
pennylane/pytrees/serialization.py
tests/data/attributes/test_pytree.py
tests/pytrees/test_serialization.py

**Context:**
The Pytrees module was not correctly serializing empty shot vectors, (`Shots(None)`), converting them to an empty list instead of `None`. This resulted in an `IndexError` when deserializing, since `Shots` expects any sequence passed in to contain at least one element.
This resulted in cryptic errors when datasets contained lists of operators with empty shots. The `DatasetList` type would interpret the `IndexError` as the end of the list, instead of a serialization error in one of the elements:
```
>>> dataset = qml.data.Dataset()
>>> dataset.circuits = [1, qml.tape.QuantumScript([qml.X(0)]), 3]
>>> list(iter(dataset.circuits))
[1]
>>> dataset.circuits[2]
3
>>> dataset.circuits[1]
File "<stdin>", line 1, in <module>
File …
```

[BUGFIX] Pytrees: Handle empty shot vector

---

.github/workflows/rc_sync.yml

We originally used to end the dev release version with `dev0`. However, since the nightly releases, the dev version number increases everyday. This change broke the RC sync to master action, which would check for the RC branch's existence using the version number from `master`. I updating the step that computes the RC branch's name to use a regex instead.

Change strategy for determining RC branch version

---

pennylane/transforms/mitigate.py

**Context:**
The example worked until we changed transforms. Now the syntax is a bit off.
Fix how the transforms are called so the example works.

Fix broken example in mitigate_with_zne docstring

---

tests/ops/functions/test_assert_valid.py

In Python 3.12, a test in `test_assert_valid.py` fails due to a slightly different error message.

fix assert valid pickling test

---

doc/releases/changelog-0.38.0.md
pennylane/math/matrix_manipulation.py
tests/ops/op_math/test_prod.py

Calculating the sparse matrix for a product containing a global phase was causing an error:
```
op = qml.GlobalPhase(0.5) @ qml.X(0) @ qml.X(0)
op.sparse_matrix(wire_order=(0,1))
```
`expand_matrix` was not able to handle an operator with no wires.  So this is just a little patch for that case.

Fix sparse matrix with global phase

---

pennylane/devices/qubit/initialize_state.py
pennylane/ops/op_math/linear_combination.py
pennylane/ops/op_math/sum.py
pennylane/ops/qubit/hamiltonian.py
pennylane/transforms/compile.py
tests/devices/qubit/test_initialize_state.py
tests/drawer/test_tape_text.py
tests/ops/op_math/test_adjoint.py
tests/ops/op_math/test_sum.py
tests/transforms/test_compile.py
tests/transforms/test_hamiltonian_expand.py

* Upgrading `qml` to numpy 1.25 caused a bunch of `ComplexWarning`s to show up because we start out with a float initial state, which most likely gets cast into complex during execution. Then, during backprop, the complex state would get cast into float, which would raise the aforementioned warnings.
* `Sum.label` was also overly detailed, causing `qml.draw` to look terrible. I changed the label to be consistent with `LinearCombination` and `Hamiltonian`.
* `qml.compile` was not decomposing state prep ops, which is now changed.

Cast initial state into complex dtype for `default.qubit` + Update `Sum.label` + fix `qml.compile`

---

.github/workflows/docs.yml
.github/workflows/format.yml
.github/workflows/tests-gpu.yml
.github/workflows/tests.yml

**Context:**
CI is being triggered when labels are added to "ready for review" PRs, this removes that undesired behaviour.
`labeled` PR types are removed from workflows
**Benefits:**
Prevents CI from running each time any label is added
When labels are added that intend to affect CI, a followup commit must be made to trigger the CI
- Added and removed labels from this PR in "ready for review" state, CI checks were not triggered. 
- Added `ci:run-full-test-suite` label, CI checks were not triggered until a followup commit was pushed to branch

Rremove labeled PR types from workflows

---

tests/transforms/test_diagonalize_measurements.py

A follow up of https://github.com/PennyLaneAI/pennylane/pull/6252, does the same but with a different test.

Fix failing test in legacy opmath

---

pennylane/devices/tests/conftest.py

**Context:**
We have tests to check that the device works with various differentiation methods, (backprop, param shift, and hadamard).  But we were skipping the test if the device didn't natively support that differentiation method.  parameter shift and hadamard shouldn't need to be natively supported.  Pennylane itself handles that.  So we should always be checking parameter shift and hadamard grad with any device.
**Benefits:**

Test param shift and hadamard in device test suite

---

doc/releases/changelog-dev.md
pennylane/ops/functions/map_wires.py
tests/ops/functions/test_map_wires.py

**Context:**
`qml.map_wires` should be able to apply to anything a transform can apply to.  But it was raising an error when applied to a batch of tapes.  
Defers validation about transform input types to `TransformDispatcher`, allowing `map_wires` to be applied to more things.
**Benefits:**

`map_wires` support for a batch of tapes

---

doc/releases/changelog-dev.md
pennylane/optimize/qng.py
pennylane/optimize/rotosolve.py
pennylane/optimize/shot_adaptive.py
pennylane/optimize/spsa.py

Updates several examples in optimizer docstrings to
- use `pnp` for PennyLane's `numpy` version,
- import tensorflow explicitly and use `tf.constant`/`tf.Variable` with the TensorFlow interface, instead of `np.array(...requires_grad=False/True)`
- use `adjoint_metric_tensor` correctly, namely without passing a device as second argument.
[sc-74479]

Update docstring examples of some optimizers.

---

.github/workflows/interface-unit-tests.yml
requirements-ci.txt
requirements-dev.txt

`requirements-ci.txt`:
* Remove `autoray` upper bound
* Unpin `scipy`
`requirements-dev.txt`:
* Add `pytest-split`. This is selectively installed in CI for tests that are split among multiple runners, but I think it makes sense to include it in the `dev` requirements so that developers can split tests locally and also generate durations artifacts, which has become quite important lately 😅 
* Keeping the above change in mind, I removed the steps from all workflows that manually install `pytest-split` and also install `requirements-dev.txt`.

Update outdated `requirements-dev.txt` and `requirements-ci.txt` dependencies

---

doc/releases/changelog-dev.md
pennylane/devices/tests/conftest.py
pennylane/ops/qubit/parametric_ops_multi_qubit.py
tests/ops/qubit/test_parametric_ops.py

**Context:**
For the input of `PauliRot` the number of wires given must equal the length of the given Pauli word. Otherwise a `ValueError` is raised. For example, `op = qml.PauliRot(0.5, "XY", wires=[0,1,2])` results in `ValueError: The given Pauli word has length 2, length 3 was expected for wires [0,1,2]`.
However, this message can be ambiguous. `op = qml.PauliRot(0.5, "XYZZXYI", wires=[0])` raises the exception `ValueError: The given Pauli word has length 7, length 1 was expected for wires [0]`. It's unclear if "length 1" refers to the length of the Pauli word or the length of the wires.
This PR changes the error message to remove the ambiguity. Now it will say `ValueError: The number of wires must be equal to the length of the Pauli Word. The Pauli word …

Removing ambiguity in `PauliRot` error message.

---

doc/releases/changelog-dev.md
pennylane/compiler/qjit_api.py
pennylane/ops/op_math/condition.py

**Context:**
Currently, some of our higher order primitives store `jax.core.Jaxpr` as the metadata, and some store `jax.core.ClosedJaxpr`.  It can be difficult to remember which one is which, and the consts from the `ClosedJaxpr` are already present in the positional arguments anyway.
Standardize all current HOP's to use `jax.core.Jaxpr` in the metadata.
**Benefits:**
Fewer things developers have to remember when using HOP's.
[sc-74718]

Standardize higher-order primitives to use `jax.core.Jaxpr`

---

doc/releases/changelog-dev.md
setup.py

**Context:** There's a bug in NumPy 2.0.0 that's blocking Catalyst from using the numpy C API with the Stable ABI.
**Description of the Change:** We shift the pin from `<2.0` to `<2.1` in `setup.py` for NumPy in PL. Notice that NumPy 2.1 has additional changes that may/may not play nicely with PL. We aren't worrying (yet) about the subsequent changes in NumPy 2.1
**Benefits:** Resolves the issue in Catalyst underlined in #6341.
**Possible Drawbacks:** None that I can think of (except that we still impose an upper bound to NumPy).
**Related GitHub Issues:** Closes #6341

Bumping `NumPy` allowing `<2.1` instead of `<2.0`

---

doc/releases/changelog-dev.md
pennylane/gradients/fisher.py
setup.py
tests/gradients/core/test_fisher.py

**Context:**
`quantum_fisher` does not respect the classical Jacobian of a QNode, because its `classical_cotransform` is not set.
Set the same classical_cotransform as `adjoint_metric_tensor` and `metric_tensor`.
**Benefits:**
Fixes #6345 
[sc-75092]

Fix cotransform of `quantum_fisher`

---

doc/releases/changelog-dev.md
pennylane/tape/qscript.py
tests/tape/test_qscript.py

**Context:**
1. The existing implementation of `QuantumScript.copy` relies on users to explicitly pass `trainable_params=None` to recalculate trainable params; however, updating `operations` and/or `measurements` often makes the `trainable_params` list outdated.
2. There is a bug that raises an error when explicitly passing `trainable_params=None` to qs.copy
1. If a user passes `trainable_params` explicitly along with `operations` and/or `measurements`, we continue using the user-defined `trainable_params`. However, if updating `operations`/`measurements` and `trainable_params` is not passed, we default to recalculating for the new tape, rather than to copying over the initial tape's `trainable_params` attribute.
2. We stop trying to cast the input …

Fix handling of trainable_params in qs.copy

---

doc/releases/changelog-dev.md
pennylane/data/attributes/operator/operator.py
pennylane/qaoa/mixers.py
pennylane/tape/tape.py
tests/data/attributes/operator/test_operator.py

* Update `bit_flip_mixer` to conditionally create `Tensor`s based on `active_new_opmath()`
* Update `_validate_computational_basis_sampling` to conditionally create `Tensor`s based on `active_new_opmath()`
* Update `qml.data.DatasetOperator` to deserialize `Tensor` into `Prod` if `active_new_opmath()`
[sc-71940]

Miscellaneous `Tensor` deprecation fixes

---

doc/releases/changelog-dev.md
pennylane/gradients/adjoint_metric_tensor.py
tests/gradients/core/test_adjoint_metric_tensor.py

**Context:**
If there is a `StatePrep` op in a circuit, `adjoint_metric_tensor` errors out as described in #6357 
Make `adjoint_metric_tensor` skip over the initial operation of the tape if it is a `StatePrep` op, because it is already considered when creating the initial state internally.
**Benefits:**
Fixes #6357 
#6357 
[sc-75331]

Fix `adjoint_metric_tensor` with `StatePrep`

---

doc/releases/changelog-dev.md
pennylane/ops/functions/matrix.py
tests/ops/functions/conftest.py
tests/ops/functions/test_matrix.py
tests/ops/test_meta.py

**Context:**
Currently, `qml.matrix` raises a `ValueError` for 
- empty `QuantumTape`s
- quantum functions that do not call any operations
- single operations with an empty decomposition
- `QNode`s that do not call any operations, but only if no device wires are given and `wire_order is None`.
In particular, empty `QNode` and `PauliWord`/`PauliSentence`  do not raise an error if `wire_order` is specified.
The Pauli classes even don't raise an error without `wire_order`, which will be a very mild inconsistency that is left untouched by this PR.
This PR changes the above, so that `qml.matrix` always returns the identity matrix on `len(wire_order)` qubits for empty objects, for which currently a `ValueError` is raised.
**Benefits:**
- More objects are …

`qml.matrix` returns identity matrix for empty objects if `wire_order` is specified

---

tests/ops/op_math/test_evolution.py

Failing legacy op math run [here](https://github.com/PennyLaneAI/pennylane/actions/runs/11266288191/job/31330095237). We're just comparing an `SProd` against a `Hamiltonian`, so I've made a small change to the test.

Fix failing `qml.Evolution` test for legacy opmath failures

---

doc/releases/changelog-dev.md
pennylane/templates/subroutines/commuting_evolution.py
tests/templates/test_subroutines/test_commuting_evolution.py

`CommutingEvolution` does not correctly return `None` for its `grad_method` when the `Hamiltonian` is trainable.
[sc-75013]
Fixes https://github.com/PennyLaneAI/pennylane/issues/6340

Fix CommutingEvolution for parameter shift

---

doc/releases/changelog-dev.md
pennylane/workflow/qnode.py
tests/test_qnode.py

**Context:** 
In an effort to reduce the amount of code in the method `QNode.construct`, the validation of `qfunc_output` and `tape.measurement` is moved to private helper function.
**Description of the Change:** Extract validation code block into helper function.
**Benefits:** Improve readability of code.
[sc-72067]

Extract `qfunc_output` and `tape.measurement` validation to private helper function

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/composite.py
pennylane/ops/op_math/prod.py
pennylane/ops/op_math/sprod.py
pennylane/ops/op_math/sum.py
pennylane/ops/op_math/symbolicop.py
tests/ops/op_math/test_composite.py
tests/ops/op_math/test_sprod.py

By default, `qml.sum` and `qml.prod` set `lazy=True`, which keeps its operands nested. Given the recursive nature of such structures, if there are too many levels of nesting, a `RecursionError` would occur when accessing many of the properties and methods. Catching these errors and re-raising a more sensible error message suggesting that the user could either set `lazy=False` or use the `+` and `@` operators instead, which sets `lazy=False`.
**Update**
Extending the behaviour to `SProd`
Fixes https://github.com/PennyLaneAI/pennylane/issues/5948
[sc-67745]

Handle recursion errors in CompositeOp methods

---

doc/releases/changelog-dev.md
tests/ops/op_math/test_pow_op.py

This PR renames `test_simplify_with_adjoint_not_defined` to `test_simplify_with_pow_not_defined` in the `test_pow_ops.py` file. The test is given by the following code.
```
def test_simplify_with_adjoint_not_defined(self):
"""Test the simplify method with an operator that has not defined the op.pow method."""
op = Pow(qml.U2(1, 1, 0), z=3)
simplified_op = op.simplify()
assert isinstance(simplified_op, Pow)
assert op.data == simplified_op.data
assert op.wires == simplified_op.wires
assert op.arithmetic_depth == simplified_op.arithmetic_depth
```
Note the function name says `adjoint` is not defined, but the docstring says that `pow` is not defined. The docstring is correct, since `qml.U2` defines the `adjoint` method.

Rename `test_simplify_with_adjoint_not_defined` in `test_pow_ops.py`

---

pennylane/transforms/mitigate.py

Currently the usage example contains the line of code `qml.SimplifiedTwoDesign.shape(n_wires, n_layers)`. The arguments are the wrong order, so this PR changes it to `qml.SimplifiedTwoDesign.shape(n_layers, n_wires)`.

Fix typo in `qml.transforms.mitigate_with_zne` docstring.

---

doc/releases/changelog-dev.md
pennylane/drawer/draw.py
pennylane/drawer/mpldrawer.py
pennylane/drawer/tape_mpl.py
pennylane/drawer/tape_text.py
tests/drawer/test_draw.py
tests/drawer/test_draw_mpl.py
tests/drawer/test_mpldrawer.py
tests/drawer/test_tape_mpl.py
tests/drawer/test_tape_text.py

**Context:**
Wire labels are drawn by default.
This PR adds an option to hide the wire labels, which can be useful to produce more clean images, for example.
**Benefits:**
A convenient feature.
More options, I suppose.

Option to skip drawing wire labels

---

doc/releases/changelog-dev.md
pennylane/transforms/mitigate.py
tests/transforms/test_mitigate.py

**Context:**
The output tapes of `mitigate_with_zne` loses the `shots` of the original tape.
Use `QuantumScript.copy` to create new tapes within the transform
**Benefits:**
Fixes a bug
Fixes https://github.com/PennyLaneAI/pennylane/issues/6440
[sc-76678]

`mitigate_with_zne` preserves shots on the original tape

---

pennylane/_version.py

**Context:**
When it branched off from `master`, the RC branch version number in `_version.py` was `0.39.0-rc0`, to make sure we didn't merge anything into `master` that would have the `0.39.0` tag and mess things up for Test PyPI. 
Now that the RC branch is separate, this isn't needed (and needs to be updated before release), and it is causing a test that checks the current versioning to fail.
We update the version to `0.39.0`
**Benefits:**
The test stops failing, and the version number is up-do-date for when the RC branch is released

Update version number to 0.39.0

---

doc/releases/changelog-0.39.0.md
pennylane/devices/default_qubit.py
tests/measurements/test_classical_shadow.py
tests/transforms/core/test_transform_dispatcher.py
tests/workflow/test_construct_batch.py

**Context:** WIth `default.qubit`, parameter broadcasting does not work with `shadow_expval` (or `classical_shadow`) as the measurement process.
These latest developments might be relevant for historical reasons:
- In [this PR](https://github.com/PennyLaneAI/pennylane/pull/4238), support for parameter broadcasting was added for `measure` and `measure_with_samples` (presumably as an effort for the new device API). Specifically, a new keyword argument `is_state_batched` has been introduced to these functions to deal with the parameter broadcasting case.
- In [this PR](https://github.com/PennyLaneAI/pennylane/pull/4162), the classical shadow measurement process was integrated into the new device API as well. A new logical branch was integrated into `measure_with_samples` adding a new …

[BUGFIX] `shadow_expval` doesn't work with parameter broadcasting

---

pennylane/drawer/draw.py
pennylane/ops/functions/iterative_qpe.py
pennylane/ops/qubit/state_preparation.py
pennylane/qinfo/transforms.py
pennylane/shadows/transforms.py
pennylane/tape/qscript.py
pennylane/templates/broadcast.py
pennylane/templates/embeddings/basis.py
pennylane/templates/subroutines/qft.py
tests/measurements/test_mutual_info.py

**Context:**
Contains the full set of documentation corrections that were discovered during v0.39.0 quality assurance.
- Typos 
- Improving docstring consistency with the rest of codebase
- Adding deprecation warning blocks in the docs
- Fixing deprecation warnings to indicate removal version
**Benefits:** 
Consistency and correctness.

Polishing Pennylane v0.39.0 Documentation

---

doc/releases/changelog-0.39.0.md
pennylane/optimize/momentum_qng.py
pennylane/optimize/qng.py
pennylane/optimize/qnspsa.py
tests/optimize/test_momentum_qng.py
tests/optimize/test_qng.py

**Context:**
The newly added `MomentumQNGOptimizer` in https://github.com/PennyLaneAI/pennylane/pull/6240 does not use the keyword arguments `approx` and `lam`. 
Pass the unused arguments to `super().__init__`
No tests are added for this, but these two parameters are inherited from the base class, and they are never tested in the existing test module for the base class to begin with.

Pass keyword arguments of `MomentumQNGOptimizer` to base class; Fix `QNGOptimizer` update with singular metric tensor

---

pennylane/optimize/nesterov_momentum.py

This PR fixes a minor typo in `NesterovMomentumOptimizer`'s `compute_grad` method docs.

Fix typo in `NesterovMomentumOptimizer`'s `compute_grad` method docs

---

tests/devices/test_default_qutrit.py
tests/gradients/finite_diff/test_finite_difference_shot_vec.py
tests/gradients/finite_diff/test_spsa_gradient_shot_vec.py
tests/gradients/parameter_shift/test_parameter_shift_shot_vec.py
tests/interfaces/test_jacobian_products.py
tests/measurements/test_classical_shadow.py
tests/templates/test_subroutines/test_amplitude_amplification.py
tests/templates/test_subroutines/test_reflection.py
tests/transforms/test_diagonalize_measurements.py
tests/transforms/test_qcut.py
tests/transforms/test_split_non_commuting.py

Follow up PR to https://github.com/PennyLaneAI/pennylane/pull/6435, fixing seeds for more tests.
See https://github.com/PennyLaneAI/pennylane/actions/runs/11558049719/job/32170809496

Fix seeds for more tests

---

pennylane/spin/lattice.py
tests/spin/test_lattice.py

Documentation previously said `neighbour_order` was limited to "not being more than 1" when `custom_edges` are defined. The phrasing is potentially confusing, as it begs the question what inputs aside from 1 are allowed; physically it doesn't make sense for it to be _less_ than one. 
In practice, it was treating any input `neighbour_order < 1` as `neighbour_order = 1`, and raising an error for any input above 1. In https://github.com/PennyLaneAI/pennylane/pull/6481 we changed the docstring to explicitly say "must be 1" rather than "must not be more than 1". Here we also update the condition for raising the error, and the error message, for consistency with the docstring.

update neighbour_order error in Lattice

---

pennylane/transforms/decompose.py

Codefactor is complaining about `typing.Iterable` not being a valid 2nd argument for `isinstance()` in the RC sync PR (see [here](https://github.com/PennyLaneAI/pennylane/pull/6505/checks?check_run_id=32482041932)). I don't know why it is happening now and didn't happen before, but we stopped using `typing.Iterable` in favour of `collections.abc.Iterable` some time ago, so this PR just updates that.
It is apparently a known issue in pylint to have false positive errors of this type (see [here](https://github.com/pylint-dev/pylint/issues/3507)), and was fixed in v2.7.5. We use v2.7.4...

Update `Iterable` import package in `decompose` transform

---

.github/stable/all_interfaces.txt
.github/stable/torch.txt
.github/workflows/docs.yml
.github/workflows/interface-dependency-versions.yml
.github/workflows/unit-test.yml
doc/requirements.txt
pennylane/workflow/__init__.py

**Context:** The existing CI infra …

Change Torch wheel install variants for CI

---

pennylane/typing.py

**Context:**
Don't need `__args__` anymore after supporting minimum version of `3.10` for Python.
In Python 3.10 and later, `isinstance()` supports direct use of `Union` and `Annotated` types, so `_TensorLike.__args__` won’t be necessary.
**Description of the Change:** Line removal.
**Benefits:** Code clean-up
[sc-77839]

Remove `__args__` method call after minimum Python version bump

---

doc/releases/changelog-dev.md
pennylane/shadows/transforms.py

**Context:**
Follow up PR addressing the `-0.01%` project code coverage issue that slipped through the cracks in #6530.
Removed the relevant check because it was being exclusively tested by a removed unit test (associated with `qml.shadows.shadow_expval`),
Here's the old test that was removed which was testing that logic branch:
```python
...
def test_non_shadow_error(self):
"""Test that an exception is raised when the decorated QNode does not
return shadows"""
dev = qml.device("default.qubit", wires=1, shots=100)
@partial(qml.shadows.shadow_expval, H=qml.PauliZ(0))
def circuit():
qml.Hadamard(0)
msg = "Tape measurement must be ClassicalShadowMP, got 'ExpectationMP'"
with pytest.raises(ValueError, match=msg): …
```

Fix code coverage issue due to `shadow_expval` removal

---

doc/releases/changelog-dev.md
pennylane/data/attributes/operator/operator.py
tests/data/attributes/operator/test_operator.py

**Context:**
We were already converting to `Prod` and `LinearCombination` when downloading datasets that were uploaded using legacy opmath, but we were relying on using the `Hamiltonian` and `Tensor` class in the supported ops mapping to recognize them and know how to handle them. 
As a result, when we removed legacy opmath, we removed the context needed to download legacy datasets.
We add them as keys in the ops dictionary and map them to `LinearCombination` and `Prod`.
**Benefits:**
The datasets will work
[sc-78651][sc-77523]

Allow accessing datasets uploaded using Tensor/legacy Hamiltonian

---

tests/capture/test_base_interpreter.py
tests/capture/test_capture_cond.py
tests/capture/test_capture_diff.py
tests/capture/test_capture_for_loop.py
tests/capture/test_capture_mid_measure.py
tests/capture/test_capture_module.py
tests/capture/test_capture_qnode.py
tests/capture/test_capture_while_loop.py
tests/capture/test_make_plxpr.py
tests/capture/test_measurements_capture.py
tests/capture/test_meta_type.py
tests/capture/test_nested_plxpr.py
tests/capture/test_operators.py
tests/capture/test_templates.py
tests/conftest.py

As name says. Most test files create their own fixture for doing this. I updated the logic to have a single fixture in `conftest,py` that test files can now use instead.
[sc-78687]

Create global fixture for toggling capture in program capture tests

---

.github/workflows/interface-unit-tests.yml

Pinning `quimb` to version 1.8.4 in the workflow file since version 1.9.0 (released on 2024-11-19) broke our CI.
The `default.tensor` device will be updated as soon as possible to be compatible with the newest `quimb` version.

Pinning quimb in CI

---

doc/releases/changelog-dev.md
pennylane/workflow/execution.py
pennylane/workflow/qnode.py
tests/test_qnode.py

**Context:** Issue #6585 indicates that we don't currently allow arguments with types defined in libraries not listed in the supported interfaces. 
In #6225, the convention of treating internally as `interface=None` parameters of the `numpy` interface has been introduced. 
The idea of this PR is to allow non-trainable `qnode` inputs to "just work" as arguments, without any special consideration or treatment. We want to rely on the default `numpy` interface for libraries we know nothing about.
**Description of the Change:** By default, we set `None` as the value of the interface if the latter is not found in the list of supported interfaces. According to the convention introduced in #6225, this should automatically map the interface to `numpy`.
**Benefits:** Now the `qnode` accepts …

[BugFix] `KeyError` when running `QNode(qfun, dev)(graph)` with graph an instance of `networkx` Graph object

---

doc/releases/changelog-dev.md
pennylane/capture/__init__.py
pennylane/capture/primitives.py
pennylane/workflow/_capture_qnode.py
pennylane/workflow/qnode.py

**Context:**
As we are integrating more things with the capture project, we are making changes across the entirety of pennylane. Previously, we stuck most capture related code in the capture module, and then imported in whichever relevant place we needed too.
I don't think this makes sense anymore.  As we are tying together the capture work to more parts of pennylane, the capture code should just be located next to the code it is capturing.
Move `qml.capture.qnode_call` to the workflow module and make it private.
**Benefits:**
Code for managing the workflow is located in the `workflow` module.
This is all experimental, so we should be able to move things around whenever we see fit.  I'm not concerned about this being "breaking". …

move `qnode_call` to the `workflow` module and make it private

---

tests/interfaces/test_autograd.py
tests/interfaces/test_jax.py
tests/interfaces/test_tensorflow.py
tests/interfaces/test_torch.py
tests/pytest.ini

Looks like I accidentally removed the xfail strict in #6549  .  This PR adds it back end, and removes the suppression of deprecation warnings related to legacy op math, as those are now removed.

Fix pytest.ini file

---

doc/releases/changelog-dev.md
pennylane/workflow/_capture_qnode.py
tests/capture/test_capture_qnode.py

Small fix in the syntax of `jax.vmap` and change to associated test

Small fix in the syntax of `jax.vmap`

---

doc/requirements.txt
pennylane/configuration.py
pennylane/devices/capabilities.py
requirements-ci.txt
requirements-dev.txt
requirements.txt
setup.py

`toml` is not maintained anymore, alternatives include:
- `tomlkit`
- `tomli`
- `tomllib` (only available in Python 3.11)
Since `configuration.py` requires the ability to save to a TOML file, and both `tomli` and `tomllib` are read-only, updating the dependency to use `tomlkit` instead.

Change dependency on toml to tomlkit

---

doc/releases/changelog-dev.md
pennylane/qchem/vibrational/pes_generator.py
pennylane/qchem/vibrational/vibrational_class.py
tests/qchem/vibrational/test_vibrational_class.py

**Context:**
Updated the geometry optimization function to perform a single task
**Benefits:**

Update the geometry optimization function

---

tests/capture/test_capture_diff.py
tests/capture/test_capture_mid_measure.py
tests/capture/test_capture_qnode.py
tests/capture/test_measurements_capture.py

**Context:**
The PR making so that the jaxpr is natively executed on the device (#6596) was getting test failures due to a global state change in a different part of the test suite.  This was tracked down to be due to the jax config getting updated so much when running the test suite.  This PR gets rid of all the setting and re-setting of the jax config, leading to the removal of these confusing failures.
**Benefits:**

[Capture] remove x64 mode setting in tests

---

README.md

**Context:**
- Light mode README hero image currently points to the `update-readme-image` branch, it should point to `master`
**Benefits:**

Fix README image link (to master)

---

doc/introduction/interfaces/jax.rst

`prng_key` does not exist anymore. `seed` seems to have taken its place

Update  documentation jax.rst

---

pennylane/measurements/probs.py
tests/measurements/test_probs.py

**Context:**
Previous `ProbsMP.process_density_matrix` has potential to alter the interface. Here we convert it explicitly.
Specifically, when dealing with batched density matrices, the previous `ProbabilityMP` did not track the interface of input `density_matrix`.
```python
from pennylane.measurements import ProbabilityMP as OriginalProbabilityMP
from pennylane.typing import TensorLike
from pennylane.wires import Wires
class CustomProbabilityMP(OriginalProbabilityMP):
"""Custom ProbabilityMP overriding process_density_matrix."""
def process_density_matrix(self, density_matrix: TensorLike, wire_order: Wires):
if len(np.shape(density_matrix)) == 2:
prob = qml.math.diagonal(density_matrix)
else:
prob = qml.math.array( …
```

Explicitly convert `prob` interface in `ProbsMP.process_density_matrix`

---

doc/releases/changelog-dev.md
pennylane/templates/subroutines/grover.py
tests/templates/test_subroutines/test_grover.py

**Context:**
`qml.GroverOperator` now has a `work_wires` property similar to `MultiControlledX`.
**Benefits:** Nice to have.
**Possible Drawbacks:** None identified.
**Related GitHub Issues:** Fixes #6591 
[sc-78409]

Add `work_wires` property to `GroverOperator`

---

doc/releases/changelog-dev.md
pennylane/ops/qubit/matrix_ops.py

**Context:** 
**Description of the Change:** Link fix to `one_qubit_decomposition`
**Benefits:** Link works
**Possible Drawbacks:** Absolutely none—zip—zilch—zéro

`QubitUnitary` docstring link fix

---

doc/introduction/interfaces/numpy.rst
doc/releases/changelog-dev.md
pennylane/_grad.py
pennylane/gradients/classical_jacobian.py
pennylane/math/__init__.py
pennylane/math/grad.py
pennylane/math/single_dispatch.py
tests/math/test_grad.py
tests/test_autograd_grad.py
tests/transforms/test_classical_jacobian.py

**Context:**
We often have to rewrite tests four different ways to test differentiability for each different interface.  This is rather time-intensive and annoying.  By adding and using a `qml.math.grad`, we can write one test that applies to all interfaces.
Adds a `qml.math.grad` and `qml.math.jacobian` with a jax-like interface that can differentiate with respect to any argument inputs.
**Benefits:**
We have several different options for interface, but I decided to do my best to mirror the jax interface.

add qml.math.grad and qml.math.jacobian for differentiating any interface

---

doc/releases/changelog-0.40.0.md
pennylane/ops/functions/equal.py
pennylane/templates/subroutines/basis_rotation.py
tests/ops/functions/test_equal.py
tests/templates/test_subroutines/test_basis_rotation.py

**Context:**
PR #6019 only fixes `BasisRotation` when using backprop on `default.qubit`.  It is not jit compatible on any other device.  This is because `unitary_matrix` was being considered a hyperparameter, not a piece of data.  So we could not detect that the matrix was a tracer and we were in jitting mode, and we could not convert the matrix back into numpy data.
Make `unitary_matrix` a piece of data instead of a hyperparameter. This allows us to detect when it is being jitted.
As a by-product, I also made it valid pytree.
By making `unitary_matrix` a piece of data, we were able to get rid of the custom comparison method in `qml.equal`.
**Benefits:**
[sc-51603] Fixes #6004

Make `BasisRotation` jit compatible

---

doc/development/autograph.rst
pennylane/bose/bosonic_mapping.py
pennylane/capture/autograph/transformer.py
pennylane/ops/functions/dot.py
tests/capture/autograph/test_autograph.py

**Context:**
Pure documentation improvements found during the v0.40 quality assurance process.
Source-code improvements are addressed in #6773.

[v0.40.0 QA] PL Docs Improvements

---

doc/releases/changelog-0.40.0.md
pennylane/labs/vibrational/christiansen_utils.py

Remake of #6791
Context:
Had subprocess.Popen in the original code and should be removed for security purposes
Description of the Change:
Changed to use Python standard lib
Benefits:
Security

remove subprocess and popen

---

pennylane/devices/_legacy_device.py
tests/devices/test_legacy_device.py

Update logic in `LegacyDevice` to check for whether the device supports `LinearCombination` or not.

Mudit's QA fixes for v0.40.0

---

doc/code/qml_noise.rst
doc/development/deprecations.rst
doc/development/plugins.rst
doc/releases/changelog-0.40.0.md
pennylane/capture/base_interpreter.py
pennylane/debugging/snapshot.py
pennylane/devices/__init__.py
pennylane/devices/_qubit_device.py
pennylane/devices/capabilities.py
pennylane/devices/default_clifford.py
pennylane/devices/device_api.py
pennylane/devices/execution_config.py
pennylane/io.py
pennylane/tape/plxpr_conversion.py
pennylane/tape/tape.py
pennylane/transforms/core/transform_program.py
pennylane/transforms/diagonalize_measurements.py
pennylane/workflow/_capture_qnode.py
pennylane/workflow/execution.py
pennylane/workflow/return_types_spec.rst
tests/capture/test_base_interpreter.py
tests/devices/qubit_mixed/conftest.py
tests/drawer/test_drawer_utils.py
tests/test_debugging.py
tests/workflow/interfaces/test_jacobian_products.py

QA PRs checking process for PL 0.40 during feature freeze

---

pennylane/templates/subroutines/gqsp.py

Minor tweak to the docstring wording to unify terminology used to describe the control wire

Update GQSP docs

---

doc/releases/changelog-0.40.0.md

**Context:**
Some entries in the changelog belong in the labs section instead
Moved to labs section of changelog

move labs functionality in changelog

---

pennylane/labs/dla/cartan_subalgebra.py
pennylane/labs/dla/variational_kak.py

following https://github.com/PennyLaneAI/qml/pull/1287 and https://github.com/PennyLaneAI/qml/pull/1294 
cc @dwierichs @justinpickering

[docs] fix links to kak decomposition demo 

---

doc/releases/changelog-0.40.0.md
pennylane/drawer/mpldrawer.py
pennylane/drawer/tape_mpl.py
tests/drawer/test_draw_mpl.py
tests/drawer/test_mpldrawer.py

**Context:**
When using wire labels that aren't integers ordered from largest to smallest (like strings, or a wire_order that isn't "in order"), the custom wire options are applied to the incorrect wire.
```
dev = qml.device('default.qubit', wires=4)
def circuit():
for w in dev.wires:
qml.X(w)
return qml.expval(qml.Z(0))
wire_options = {'color': 'teal',
'linewidth': 5,
3: {'color': 'orange', 'linestyle': '--'}, # wire 3 should be orange and dashed
}
fig, ax = qml.draw_mpl(circuit, wire_order=[1, 3, 0, 2], wire_options=wire_options)()
```
This should make wire 3 orange, but instead makes the wire at _index_ 3 orange:
We update it to fix the bug. This involves modifying the signature of `MPLDrawer`.
**Benefits:**
It works as expected now. …

Bugfix for wire_options

---

pennylane/drawer/mpldrawer.py

I just realized I changed the call signature in `MPLDrawer` in #6805, and forgot to change the actual `Args` section when I was updating the docstring. This PR fixes that.

Fix docstring in MPLDrawer

---

doc/conf.py

- Explicitly enable `search_on_pennylane_ai` feature from PennyLane Docs
- https://github.com/PennyLaneAI/pennylane-sphinx-theme/pull/85
- This related PR can be released separately

sc-81896-disable-search-page-redirect-on-all-docs-projects-except-pennylane-oss

---

doc/releases/changelog-dev.md
pennylane/ops/qubit/state_preparation.py
tests/ops/qubit/test_state_prep.py

**Context:**
PR #6770  accidentally broke lightning, becasue we are now sending numpy data to lightning instead of autograd.  The autograd arrays had slightly different casting rules. With numpy, we are no longer implicitly casting to integers.
Always cast the input to `BasisState` to integers.
**Benefits:**

Cast input to `BasisState` to an int

---

doc/releases/changelog-dev.md
pennylane/math/interface_utils.py
pennylane/workflow/qnode.py
pennylane/workflow/resolution.py
tests/math/test_functions.py
tests/test_qnode.py

**Context:**
`QNode.interface` returns a `str` type,
```python
@property
def interface(self) -> str:
"""The interface used by the QNode"""
return self._interface.value
```
Therefore, this equality will never be true,
```python
from pennylane.math.interface_utils import Interface
>>> "jax" == Interface.JAX
False
```
Moreover, `str` cannot be compared with `Enum` objects at all. 🤯 
- Adjust the `InterfaceEnum` class to have dunder methods to overwrite comparisons. This way it will error out if you try to compare it with a string. 
- Add test coverage for the private helpers in `qnode.py`
Now we have,
```python
from pennylane.math.interface_utils import Interface
>>> "jax" == Interface.JAX
TypeError: Cannot compare Interface with str
```
**Benefits:** Logic is …

Fix `InterfaceEnum` object

---

doc/releases/changelog-dev.md
pennylane/optimize/qnspsa.py
pennylane/optimize/riemannian_gradient.py
pennylane/workflow/execution.py

**Context:**
PR #6822 deprecated the arguments `config` and `inner_transform_program` to `qml.execute`. However, because of some bug in our CI, the `qml.PennyLaneDeprecationWarning` are not being treated as errors. I just happened to find this warning in our CI logs.
Promoted `qml.PennyLaneDeprecationWarning` to a `ValueError` to fish out any deprecated code. Updated said code to use `qml.workflow.run` instead of `qml.execute`. 
[sc-81529]

Fix deprecations that weren't caught by CI

---

pennylane/math/__init__.py
pennylane/workflow/execution.py

**Context:**
Removes unnecessary `replace` that survived after some updates made in #6822. This code just redundantly sets the `interface` and `derivative_order` right after it is set a bit earlier.
**Benefits:** Neater code.

Prune redundant `replace` from `execution.py`

---

doc/releases/changelog-dev.md
pennylane/workflow/construct_batch.py
tests/workflow/test_construct_batch.py

**Context:**
A bug was found in `construct_tape` (and `construct_batch`) while testing behaviour of circuits with mid-circuit measurements for another task: the QNode's `mcm_method` information is never passed to the `construct_batch` function, so it always constructs a tape as if deferred measurements were used.
Create an `mcm_config` from the information stored in `qnode.execution_kwargs` and use it when getting the transform program to apply.
#6902
[sc-83393]

[Bug fix] Use qnode mcm_method information when creating transform program for construct batch

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/noise/conditionals.py

**Context:**
A recently merged PR to deprecate `MP.return_type` missed a line that exists inside `pennylane/noise`, which caused GPU tests failure.
Fixing it in the most straightforward way, replacing the `return_type` with the in-use private attribute `_shortname` that carries the same info. This should be refactored in next cycle.
**Benefits:**
Bug fix
None

Fix return type

---

.github/workflows/interface-unit-tests.yml

Pinning `pyzx` to version `0.8.0` in the workflow file since version `0.9.0` (released on 2025-01-30) broke our CI.

Pin `pyzx==0.8.0` in CI

---

.github/workflows/tests-gpu.yml

**Context:**
Swap `tests-gpu.yml` to using the new self-hosted GPU runner infrastructure.
The current GPU tests use runner infrastructure that is quite old and have accumulated a fair amount of technical debt. As part of an overhaul of the infrastructure, net-new instances have been deployed. 
This pull request updates the tests-gpu workflow to use the newly deployed runners.
**IMPORTANT NOTE** Other than the minor change to `runs-on` the backend changes should be transparent for users of pennylane. Any and all behaviors related to gpu workflows should continue working as they are today.
**Benefits:**
Enable us to use newer infrastructure that have non-deprecated runtimes (backend).
It's possible for a test to fail that used to pass …

Update GPU workflow to use the new self-hosted GPU runner infrastructure

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/controlled.py
tests/ops/op_math/test_controlled.py

**Context:**
A recent deprecation https://github.com/PennyLaneAI/pennylane/pull/6840/ deprecated the usage of `QubitUnitary` type input `base` for instantiation of `ControlledQubitUnitary`.
However, a modification that was equivalent in PennyLane caused unexpected behavior in Catalyst, https://github.com/PennyLaneAI/catalyst/issues/1494.
After investigation, it appears to be the issue with the private method `_try_wrap_in_custom_ctrl_op` of `pennylane/ops/op_math/controlled.py`, since it used to call the deprecated `init` to directly use base as `QubitUnitary`, and to safely deprecate it we decided to locally replace with equivalent `ControlledQubitUnitary(base=op.matrix(), ...)`, this caused Catalyst to received double `QubitUnitary`.
It is also noteable that the call …

Fix double QubitUnitary bug from Catalyst

---

doc/releases/changelog-dev.md
pennylane/noise/conditionals.py

**Context:**  `qml.noise.meas_eq` compares the types of measurement processes, neglecting the wires or operator.
**Description of the Change:** Clarifies the `type` of measurement in the docstring
**Benefits:** N/A
**Possible Drawbacks:** N/A
**Related GitHub Issues:** [sc-83710]

Clarify "type of measurement process" in the `qml.noise.meas_eq` docstring

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/controlled.py
tests/ops/op_math/test_controlled.py

**Context:**
Currently singly-controlled `GlobalPhase` operations are decomposed into an uncontrolled `PhaseShift` operation.
Multi-controlled `GlobalPhase` operations are decomposed into nothing, raising a warning about this being wrong.
This PR decomposes multi-controlled `GlobalPhase` operations into one-less-controlled `PhaseShift` operations instead.
**Benefits:**
Correct decomposition
N/A
[sc-84163]

Add a decomposition for multi-controlled global phases

---

doc/releases/changelog-dev.md
pennylane/wires.py
tests/test_wires.py

**Context:**
Prior to this PR we had the following behaviour,
```python
a = qml.wires.Wires("a")
b = qml.wires.Wires("b")
wires = [a,b,"c"]
>>> print(qml.wires.Wires(wires))
Wires([Wires(['a']), Wires(['b']), 'c'])
>>> print(qml.wires.Wires([0, 1, 2, 3, qml.wires.Wires([4, 5]), None]))
Wires([0, 1, 2, 3, Wires([4, 5]), None])
>>> print(qml.wires.Wires([qml.wires.Wires([(0,0), (0,1)])]))
Wires([Wires([(0, 0), (0, 1)])])
```
Add handling to `_process` that dissolves any `Wires` objects that survived to that point. This results in improved behaviour like,
```python
a = qml.wires.Wires("a")
b = qml.wires.Wires("b")
wires = [a,b,"c"]
>>> print(qml.wires.Wires(wires))
Wires(['a', 'b', 'c'])
>>> print(qml.wires.Wires([0, 1, 2, 3, qml.wires.Wires([4, 5]), None])) …
```

Fixes `Wires` objects as wire labels bug

---

doc/releases/changelog-dev.md
pennylane/capture/base_interpreter.py
tests/capture/test_base_interpreter.py

**Context:**
`PlxprInterpreter__call__` was not flattening arguments before calling `PlxprInterpreter.eval`, which assumes that the arguments are already flat. This caused failures when using pytree arguments.
* Flatten arguments in `PlxprInterpreter.__call__` before calling `PlxprInterpreter.eval`.
**Benefits:**
* Correct behaviour of interpreter
[sc-84650]

Fix `PlxprInterpreter.__call__` to flatten arguments

---

.pylintrc
doc/releases/changelog-dev.md
pennylane/measurements/mid_measure.py

**Context:**
Jax routinely causes `no-member` pylint issues, and jax is outside our control. We shouldn't care about whether or not jax is setting up modules correctly.
Silences all `no-member` warnings from jax.
**Benefits:**
Less developer annoyance.
[sc-84891]

Silence all `no-member` pylint warnings from jax

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/adjoint.py
tests/ops/op_math/test_adjoint.py

**Context:** #6876
**Description of the Change:** add pauli_rep property for adjoint operation
**Benefits:** pauli_rep property is available after adjoint operation
**Possible Drawbacks:** impact downstream functions that relies on pauli_rep 
**Related GitHub Issues:** #6876

add pauli_rep for adjoint op 

---

doc/releases/changelog-dev.md
tests/test_compiler.py

**Context:** [This PR removes unnecessary IO unless explicitly requested by the user, therefore it breaks tests which check for the IR representation.](https://github.com/PennyLaneAI/catalyst/commit/f1ac6b785b5d0d82d9dd9864afef4d35208695f6)
**Description of the Change:** Use `keep_intermediate=True` to output the representation. Cleans up the workspace after it is done.
**Benefits:** Test passes.
**Possible Drawbacks:** Relies on Catalyst internals.

[tests] Fix compile test which checks for intermediate representation

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/dq_interpreter.py
tests/devices/qubit/test_dq_interpreter.py

**Context:**
Saw performance numbers demonstrating that flattened control flow was a bit faster than structured control flow. This got me curious and I investigated.  Looking at the profile generated by PyInstrument, I was able to make a couple changes.
Speed up the copy a little bit by having a manual copy.
Speed up accessing and setting attributes by using manual properties instead of a generic `__getattr__` and `__setattr__`.
**Benefits:**
Performance gets a little bit closer to the flattened version.
The `__getattr__` and `__setattr__` methods were nice and tidy and extensible.
[sc-84834]

Minor performance improvements for DQInterpreter

---

doc/releases/changelog-dev.md
pennylane/data/data_manager/progress/_default/__init__.py
pennylane/devices/qubit_mixed/einsum_manpulation.py
pennylane/optimize/rotosolve.py
pennylane/templates/subroutines/trotter.py

**Context:**
After running the latest `pylint=3.3.4` version on our repository, a few `too-many-arguments` errors were uncovered.
Suppress the errors.
**Benefits:** Closer to being able to upgrade pylint.
[sc-84896]

Fix `too-many-arguments` pylint errors

---

doc/releases/changelog-dev.md
pennylane/measurements/__init__.py
pennylane/measurements/null_measurement.py
tests/measurements/test_null_measurement.py

**Context:**
Performing measurements can consume a non-trivial amount of resources on large problems.  We need to be able to have a dummy measurement process that allows us to use the full pennylane workflow, without spending any amount of resources processing a measurement result.
This will allow us to perform benchmarks on large and remote devices without actually needing to do any additional meausrements.
Adds a `qml.measurements.NullMeasurement` measurement process that always corresponds to `np.array(np.nan)`, with a shape `()` and a dtype `float`. This was chosen so the measurement could be used with jax, program capture, and catalyst.
**Benefits:**
More informative profiles.
Don't know if it's useful outside of profiling. …

add NullMeasurement

---

.github/workflows/unit-test.yml

**Context:**
setuptools has had a release recently that normalizes package names:
References:
- pypa/setuptools#4766
- https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization
Due setuptools 75.8.0 and 75.8.1 outputting completely different package names, we cannot support both, so CI now "pins" to >=75.8.1.
**Benefits:**
Fix CI failures.
We may need to update docs.
This is also another situation where moving away from setup.py to pyproject would yield benefits. As then you can specify the minimum setuptools version as part of the build-backend configuration.
None. [sc-85195](https://app.shortcut.com/xanaduai/story/85195/investigate-issue-with-pennylane-ci-failing-with-uv-b …

Update how PL is installed

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/transforms/compile.py
tests/transforms/test_compile.py

**Context:**
Currently, `qml.compile` has a default of `pipeline=None`, where `None` implies `(commute_controlled, cancel_inverses, merge_rotations, remove_barrier)`.  This is confusing, as `None` usually means "nothing".
Sets the default value to `(commute_controlled, cancel_inverses, merge_rotations, remove_barrier)` and deprecates passing `pipeline=None`.
**Benefits:**
Easier to determine default value from the call siganture.
Just to make sure this looks good in the docs.
Is a deprecation.
[sc-85186]

Deprecate pipeline=None with qml.compile

---

doc/development/guide/architecture.rst
pennylane/ops/op_math/controlled_ops.py
pennylane/workflow/qnode.py
tests/capture/test_base_interpreter.py
tests/ops/op_math/test_controlled_ops.py
tests/test_qnode.py
tests/transforms/test_qmc_transform.py

**Context:**
This release had some rather large scope deprecations and removals. This PR aims to address any potential fuzz that was accidentally missed in the source code.
This PR includes minor adjustments to the deprecation message for,
- `gradient_kwargs` to the `QNode`
- Controlled qubit unitary arguments
**Benefits:** Cleaner code.
**Possible Drawbacks:** None identified.
[sc-82824]

[v0.41 Dep & Rmv] Documentation Audit

---

doc/code/qml_ftqc.rst
doc/index.rst

Adds the `qml.ftqc` module to the docs index so that Sphinx captures the documentation therein.

Add docs for qml.ftqc module

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/controlled.py
tests/ops/op_math/test_controlled.py

**Context:**
`Controlled.has_sparse_matrix` was always true
Fix `Controlled.has_sparse_matrix`.
**Benefits:**'
`Controlled.has_sparse_matrix` is accurate.
Unblock https://github.com/PennyLaneAI/pennylane/pull/6883/
Fixes #7024 [sc-85452]

fix `qml.Controlled.has_sparse_matrix`

---

.github/workflows/tests-gpu.yml
.github/workflows/unit-test.yml

**Context:**
Encountered CI errors [here](https://github.com/PennyLaneAI/pennylane/actions/runs/13774640399/job/38521082003?pr=7042). After speaking with tools, seems like the issue was cache related.
Update `uv` version to latest (0.6.5) and enable efficient cache clean-up.
**Benefits:** Un-blocks CI
**Possible Drawbacks:** None identified
[sc-86173]

[CI] bump `uv` to `v0.6.5` and enable `cache` clean-up

---

doc/releases/changelog-dev.md
tests/math/test_matrix_manipulation.py

**Context:**
A recent test error https://github.com/PennyLaneAI/pennylane/actions/runs/13790909397/job/38570702961?pr=7042 was caused by the fact that there are chances in a recently added test `tests/math/test_matrix_manipulation.py::TestDenmanBeaversIterations::test_valid_positive_definite` to have improper input matrices for this test suite.
For context, this test suite should take a matrix with positive determinant. However, one can check the mentioned test fail to see the error info matrix is negative.
Therefore, we would like to make use of the existing helpers to help this test suite to gaurantee to get positive input.
In the mentioned test file, we made:
- The helper method to be separated from another specific test suite for convenience
- A new …

[CI] Enforce matrix positivity in Denman Beavers iterations tests

---

doc/releases/changelog-dev.md
pennylane/devices/reference_qubit.py

**Context:**
With the release of NumPy 2.0, stricter validation has been introduced for numpy.random.Generator.choice, which now requires that the probability vector p must sum to exactly 1 when cast to float64.
Reference: [NumPy 2.0 documentation – Generator.choice](https://numpy.org/doc/2.0/reference/random/generated/numpy.random.Generator.choice.html#numpy.random.Generator.choice)
> "p must sum to 1 when cast to float64. To ensure this, you may wish to normalize using p = p / np.sum(p, dtype=float)."
This stricter behavior causes our reference.qubit device to fail under NumPy > 2.0, as minor numerical deviations in probability sums can lead to a ValueError: Probabilities do not sum to 1 (see [here](https://github.com/PennyLaneAI/pennylane/actions/runs/13818577424/job/38658179112?pr=7039 …

Ensure probability normalization (sum to one) while using `reference.qubit`

---

doc/releases/changelog-dev.md
pennylane/math/single_dispatch.py
pennylane/measurements/mid_measure.py
tests/measurements/test_mid_measure.py

Remove redundant overload for MCM mod

---

pennylane/ftqc/parametric_midmeasure.py

**Context:**
There are a couple of typos in the docstring examples for `diagonalize_mcms`
We fix the typos
**Benefits:**
The examples are correct

Fix mistakes in docs examples for diagonalize_mcms

---

.github/workflows/tests-labs.yml

**Context:**
- Harden-Runner detection: tj-actions/changed-files action is compromised. This vulnerability exposed build secrets by printing CI/CD secrets in GitHub Actions build logs. [Security Issue Summary](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised).
- This PR upgrades tj-actions from version 45 to version 46 with the vulnerability fix.
**Benefits:**
- Removes tj-actions/changed-files vulnerability.
- None

Upgrading tj-actions version to 46

---

pennylane/ftqc/graph_state_preparation.py
tests/ftqc/test_ftqc_graph_state_prep.py

**Context:** The order of the nodes in a graph is not well defined since the graph structures used for defining qubit connectivity are inherently *unordered* data structures. Mapping the nodes in the graph to the *ordered* sequence of wires can therefore result in ambiguity. This is especially troublesome given that NetworkX uses Python `dict` objects to store a graph's adjacency list. Python `dict` objects are insertion-ordered ([since Python 3.7](https://docs.python.org/3/whatsnew/3.7.html#summary-release-highlights)), therefore it's possible to define the same graph structure with different internal node ordering, depending on the order in which the nodes were inserted into the graph.
`GraphStatePrep` requires a robust, deterministic method to map node labels to wire indices that do …

[FTQC] Improve robustness of GraphStatePrep wire mapping

---

doc/releases/changelog-dev.md
pennylane/capture/base_interpreter.py

**Context:**
The custom pjit call was causing issues in catalyst, as they use the `BaseInterpreter` class. So I've just moved it to `FlattenedInterpreter` so that only execution-style interpreters will have a custom pjit logic.
**Benefits:**

Just update pjit call on `FlattenedInterpreter`

---

doc/releases/changelog-dev.md
pennylane/operation.py
tests/test_operation.py

**Context:**
`qml.operation.gen_is_multiterm_hamiltonian` was never properly updated for new operator arithmetic.
Allow is to work with general generators.
**Benefits:**
The `fourier.qnode_spectrum` works for general generators.
Fixes #7116 
**Related Shortcut Stories:**
[sc-86870]

Fix gen_is_multi_term_hamiltonian

---

doc/releases/changelog-dev.md
pennylane/ops/functions/assert_valid.py
tests/ops/functions/test_assert_valid.py

**Context:**
We have a check in `assert_valid` that ensures that an operator decomposition doesn't include the same type of operator again. This is a relevant check for operators types where a given class will be either supported or not by devices - in this case, a decomposition that returns another instance of the same type of operation will lead to an infinite recursion. 
However, for some operators, this check doesn't make sense. Specifically, an operator with another operation as its base may decompose based on the base operator, leaving the overall operator type intact (for example, `Controlled` operations with an unsupported base). 
This has come up in PR #6921 for the `FromBloq` operator.
- We check that the operator _itself_ is not present in its own …

Update decomposition check in assert_valid

---

doc/releases/changelog-dev.md
tests/capture/workflow/test_capture_qnode.py

**Context:**
Noticed some flaky test [errors](https://github.com/PennyLaneAI/pennylane/actions/runs/13971550371/job/39114663419?pr=7099) in our CI,
```
FAILED tests/capture/workflow/test_capture_qnode.py::TestDevicePreprocessing::test_mcm_execution_deferred_fill_shots[deferred-lightning.qubit] - AssertionError: assert tensor(False, requires_grad=True)
+  where tensor(False, requires_grad=True) = functools.partial(<function do at 0x7f615dfb70a0>, 'isclose')((tensor(441, requires_grad=True) / tensor(559, requires_grad=True)), 1, atol=0.2)
+    where functools.partial(<function do at 0x7f615dfb70a0>, 'isclose') = <module 'pennylane.math' from '/home/runner/work/pennylane/pennylane/pennylane/math/__init__.py'>.isclose
+      where <module 'pennylane.math' from …
```

Fix flaky tests in `test_capture_qnode.py`

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/controlled.py
tests/ops/op_math/test_controlled.py
tests/ops/op_math/test_controlled_ops.py

**Context:**
After implementing the sparse `QubitUnitary`, the `qml.ctrl` over a sparse QU does not work:
```python
>>> op = qml.QubitUnitary(sparse.eye(2), wires=2)
>>> qml.ctrl(op, 3)
MatrixUndefinedError: U is sparse matrix. Use sparse_matrix method instead.
```
Added a conditional branch in `ctrl`
**Benefits:**

Fix the issue that ctrl a sparse QubitUnitary doesn't work

---

doc/releases/changelog-dev.md
pennylane/gradients/parameter_shift_hessian.py
pennylane/math/quantum.py
pennylane/measurements/classical_shadow.py
pennylane/shadows/classical_shadow.py
tests/default_qubit_legacy.py

Reserve ABC for abstract base classes in codebase

---

doc/releases/changelog-dev.md
pennylane/operation.py
pennylane/ops/functions/assert_valid.py
pennylane/templates/subroutines/prepselprep.py
tests/templates/test_subroutines/test_prepselprep.py

**Context:**
`PrepSelPrep` prints the coefficients of the encoded LCU as parameters in its label.
That's very verbose and impractical, see #7159.
Implement a custom `label` method for `PrepSelPrep` that defers the coefficients to the standard matrix cache,
which is also used for all matrix-valued parameters.
Like requested in the linked issue.
**Benefits:**
More readable drawings.
N/A
Resolves #7159
[sc-87444]

Create a custom label method for `PrepSelPrep`

---

doc/releases/changelog-dev.md
pennylane/transforms/decompose.py

**Context:** Recommendation to use `clifford_t_decomposition` in the `decompose` docstring.
**Description of the Change:** Docstring of `qml.transforms.decompose`
**Benefits:** Users hopefully use the "correct" transform when decomposing into Clifford + T.
**Possible Drawbacks:** `clifford_t_decomposition` might be less efficient (more gates and longer runtime) than the decomposition algorithm.

Adds a recommendation to use `clifford_t_decomposition` in the `decompose` docstring.

---

doc/releases/changelog-dev.md
pennylane/ops/qubit/parametric_ops_multi_qubit.py
tests/ops/qubit/test_parametric_ops.py

**Context:**
`PSWAP` does not support parameter broadcasting in its `compute_matrix` and `compute_eigvals` methods.
Add support for parameter broadcasting.
**Benefits:**
More support for broadcasting.
Tiny code/computation growth.
#7180 
[sc-87781]

Make `PSWAP` support parameter broadcasting

---

.github/workflows/rtd-check.yml

**Context:**
There are two jobs named sphinx in pennylane which has made it difficult to identify the right one to turn on in merge queues. The job in rtd-check is a required step and needs to run on merge to master.
Rename sphinx->rtd_check. Add on:push:master to rtd-check.yml
**Benefits:**
merge queues can be activated.
None

Adding push master and renaming sphinx job

---

tests/device_shots_to_analytic.py
tests/gradients/parameter_shift/test_parameter_shift_shot_vec.py

Introduces a `shots_to_analytic` device transformation to the test suite. This function can be used to "mock" shot vector integration tests with analytic results. This way we can make sure the postprocessing and shapes are correct, without also getting the accompanying flakiness of shot vector tests.
**Benefits:**
Less flaky CI.

Mock shot vectors test cases with an analytic simulation

---

.github/workflows/docs.yml
.github/workflows/format.yml
.github/workflows/tests-labs.yml
.github/workflows/tests.yml

**Context:**
Merge queues trigger builds across all items enqueued at once, this is "hogging" the concurrency limit of the org and slowing down time it takes to get a runner.
For the workflows calling `determine-workflow-runner`, swap them over to using large runners if the workflow was triggered by `merge_group` event.
**Benefits:**
Merge queue will not use up the concurrency limit of standard runners.
[sc-88275](https://app.shortcut.com/xanaduai/story/88275/update-merge-queue-to-use-large-runners)

Force usage of large runners on merge queue

---

doc/releases/changelog-0.41.0.md
pennylane/ops/qubit/parametric_ops_multi_qubit.py
tests/ops/qubit/test_parametric_ops.py

**Context:**
#7179 added broadcasting support to the matrix and eigvals of `PSWAP`. However, the broadcasting axis is currently the second (i.e. last) axis in broadcasted eigvals, although PL convention is to have the broadcasting axis first.
Transpose the eigenvalues. This does not change them when there is no broadcasting, and fixed the axis ordering whenever there is broadcasting.
Added tests for broadcasted eigenvalue computation, including ML interface tests.
**Benefits:**
Fixes eigenvalue broadcasting axis ordering.
N/A
[sc-88504]

Fix `PSWAP` eigvals axis ordering with broadcasting 

---

doc/releases/changelog-0.41.0.md
pennylane/transforms/optimization/commute_controlled.py
tests/capture/transforms/test_capture_commute_controlled.py

[sc-88726]
**Context:**
`commute_controlled` isn't working correctly when applying commutable ops after higher order primitives when `direction="left"`.
The following example currently doesn't work in the RC branch:
```python
from functools import partial
import jax
qml.capture.enable()
@qml.capture.expand_plxpr_transforms
@partial(qml.transforms.commute_controlled, direction="left")
def qfunc(theta):
qml.CZ(wires=[0, 2])
qml.S(wires=0)
@qml.for_loop(2)
def loop_fn(i):
qml.X(i)
loop_fn()
qml.Y(1)
qml.CRY(theta, wires=[0, 1])
qml.PhaseShift(theta/2, wires=0)
qml.Toffoli(wires=[0, 1, 2])
qml.T(wires=0)
qml.RZ(theta/2, wires=1)
qml.Y(1)
return qml.expval(qml.Z(0))
```
```pycon
>>> jax.make_jaxpr(qfunc)(1.5) …
```

[Capture] `commute_controlled(direction="left")` works correctly with higher order primitives

---

doc/releases/changelog-0.41.0.md
pennylane/labs/tests/trotter_error/fragments/test_vibronic.py
pennylane/labs/trotter_error/fragments/vibronic_fragments.py

This PR fixes a bug in `vibronic_fragments` that prevents it from returning `RealspaceMatrix` objects with the correct number of electronic states.

Bugfix for vibronic_fragments function

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/decompositions/two_qubit_unitary.py
tests/ops/op_math/test_decompositions.py
tests/ops/qubit/test_matrix_ops.py
tests/templates/test_subroutines/test_qmc.py
tests/transforms/test_unitary_to_rot.py

**Context:**
Fixes issue #7242 …

Fixing bug GlobalPhase in QubitUnitary

---

doc/releases/changelog-0.41.0.md
pennylane/workflow/_capture_qnode.py
tests/transforms/test_decompose_transform_graph.py

**Context:**
The new decomposition still does not support specifying the gate set via a callable stopping condition. Temporarily disable graph for when a device preprocess program is applied.
**Benefits:**
[sc-88853]

BugFix: disable graph for device program

---

doc/releases/changelog-0.41.0.md

To resolve merge conflicts between `v0.41.0-rc0` and `v0.41.0-docs`.

V0.41.0 docs - resolve conflicts

---

pennylane/devices/null_qubit.py

**Context:**
`null_qubit.py` currently imports ExecutionConfig twice.
Removes redundant import of ExecutionConfig
**Benefits:**

Remove duplicate import of ExecutionConfig from NullQubit

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/decompositions/two_qubit_unitary.py
tests/ops/qubit/test_matrix_ops.py

**Context:**
The qubitUnitary decomposition was correct but the overall phase was not queued correctly.
Andrija found the solution  
**Benefits:**
#7242
[sc-88637]

fixing queuing in `QubitUnitary` decomposition

---

doc/development/plugins.rst
doc/releases/changelog-dev.md
pennylane/__init__.py
pennylane/devices/__init__.py
pennylane/devices/_legacy_device.py
pennylane/devices/device_api.py
pennylane/devices/legacy_facade.py
pennylane/devices/tracker.py
pennylane/resource/__init__.py
tests/devices/test_tracker.py

**Context:**
While reviewing some of the module dependency work (#7185 ), I realized we were way overdo for putting the tracker in the devices module.
Move `Tracker` to the devices module.
**Benefits:**
Improved code organization.
[sc-89071]

Move tracker into devices module

---

.github/workflows/tests.yml

**Context:**
Merge queues currently take a long time to process low volumes of PRs. One reason is that the full test suite is run twice, this PR will change things to only runs a lightened test suite.
Changing run_lightened_ci condition to also on merge queues; merge queues run on PRs that are merging to the master branch. 
**Benefits:**
Merge queues will run faster.

Adding light test runs for merge queue pull requests

---

doc/releases/changelog-dev.md
pennylane/capture/base_interpreter.py
tests/devices/qubit/test_dq_interpreter.py

**Context:**
While many circuits can be jit-executed on default qubit with program capture, we cannot yet handle executing abstract conditions. This adds a more informative error to that effect.
If we decide that a full program capture pipeline with worth fully developing and maintaining, we can come back to this, but for now, we can just error out during device execution.
**Benefits:**

Add informative error to capture + jit +  condition on abstract value + default qubit execution

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/transforms/compile.py
tests/transforms/test_compile.py

Removing support for `pipeline=None`

---

.github/workflows/unit-test.yml

Test workflows for updating stable deps were installing dev versions of lightning, but the output file with the frozen deps showed that a stable version of lightning was installed. This was because the step in the workflow that created the frozen deps file was manually removing the `.devX` suffix from the version of pennylane-lightning. This PR removes the suffix removal from that step.

Update unit tests workflows to keep `dev` suffix for pennylane-lightning in frozen deps files

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/ops/op_math/prod.py
pennylane/ops/op_math/sum.py
tests/ops/op_math/test_prod.py
tests/ops/op_math/test_sum.py

Remove `op.ops` and `op.coeffs` for `Sum` and `Prod`

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/workflow/execution.py
tests/workflow/interfaces/execute/test_execute.py

Removing `inner_transform` and `config` keyword arguments in `qml.execute`

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/ops/op_math/prod.py
tests/ops/op_math/test_prod.py

Remove accessing terms of a tensor product (e.g., ``op = X(0) @ X(1)``) via ``op.obs``

---

.github/workflows/docs.yml

**Context:**
As part of the sphinx upgrade, sphinx-action has been upgrade from python 3.9 to 3.10 and sphinx 2.2 to min 7.0. The upgrade has caused issues with the docs workflow as it has introduced new warnings that cause the workflow to fail.
This change will change sphinx-action to use a version fixed to python 3.9 until the [permanent sphinx](https://github.com/PennyLaneAI/pennylane/pull/7212) changes are merged.
**Benefits:**
Sphinx build will not give any more unnecessary warnings.
None

Changing sphinx-action to version 3.9

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/decompositions/unitary_decompositions.py
tests/ops/op_math/test_decompositions.py

Follow up to https://github.com/PennyLaneAI/pennylane/pull/5448, applying the same solution to the 3-cnot case.
Fixes: https://github.com/PennyLaneAI/pennylane/issues/7339
[sc-90052]

BugFix: fix special case discontinuity in two-qubit decomposition

---

doc/releases/changelog-dev.md
pennylane/measurements/counts.py
pennylane/measurements/sample.py
tests/measurements/test_counts.py
tests/measurements/test_sample.py

**Context:**
The `process_counts` functions were added to `CountsMP` and `SamplesMP` a while back, to expand support in cases with `shots` where the initial device results are `counts` instead of `samples`. 
Some cases where these measurement processes included observables (i.e. `qml.counts(qml.Z(0))`, `qml.sample(qml.X("a")`) returned incorrect results, specifically:
```
>>> counts_mp = qml.counts(qml.Z(0))
>>> counts_mp.process_counts({"00": 2, "10": 3}, wire_order=[0, 1])
{"0": 2, "1": 3} 
```
instead of `{-1.0: 3, 1.0: 2}`, and
```
>>> sample_mp = qml.sample(qml.Z(0) @ qml.Z(1))
>>> sample_mp.process_counts({"00": 2, "10": 3}, wire_order=[0, 1])
[[ 1.  1.]
[ 1.  1.]
[-1.  1.]
[-1.  1.]
[-1.  1.]]
```
instead of `[1., 1., -1., -1., -1.]`.
Added/modified …

[Bugfix] Update handling of observables in `process_counts`

---

doc/releases/changelog-dev.md
pennylane/ftqc/parametric_midmeasure.py
tests/ftqc/test_parametric_mid_measure.py

**Context:** The JAX primitive representing arbitrary-basis measurements currently returns a `jax.core.ShapedArray` of type `int64` (or `int32` if `jax.config.jax_enable_x64` is False). However, the corresponding operation in Catalyst returns a `bool`. Having different return types is generally fine, except in certain circumstances when qjit compiling a circuit containing bitwise operations on a measurement result and boolean literals. For instance, the following workload would generate the following Catalyst jaxpr:
```python
dev = qml.device("null.qubit", wires=1)
qml.capture.enable()
@qjit(target="jaxpr")
def foo():
m0 = qml.ftqc.measure_x(0)
x = m0 ^ True
return qml.expval(qml.Z(0))
qml.capture.disable()
```
```pycon
>>> print(foo.jaxpr)  # Output abbreviated for …
```

[FTQC] Change return type of arbitrary-basis measurement primitive from int to bool

---

.github/workflows/docs.yml
.github/workflows/interface-dependency-versions.yml
doc/development/release_notes.md
doc/releases/changelog-0.41.0.md
doc/releases/changelog-0.41.1.md
pennylane/__init__.py
pennylane/capture/capture_operators.py
pennylane/qnn/__init__.py

**Context:** We need a bugfix release for `PennyLane 0.41`.
The reason is that if a user installs PennyLane, then latext JAX, and then imports PennyLane (in this sequence), the following error is raised:
```
AttributeError: jax.core.Primitive was removed in JAX v0.6.0. Use jax.extend.core.Primitive instead, and see https://docs.jax.dev/en/latest/jax.extend.html for details..
```
and there are no further details.
Therefore, we need to raise an informative warning at some point that tells the user that PL is not yet compatible with the latest JAX version.
Notice that this branch was created from the [tag](https://github.com/PennyLaneAI/pennylane/releases/tag/v0.41.0) of the latest PennyLane release, as the PL release guidance recommends.
- This is not a change …

Raising a warning if latest JAX is installed

---

doc/development/release_notes.md
doc/releases/changelog-0.41.0.md
doc/releases/changelog-0.41.1.md
pennylane/capture/capture_operators.py
pennylane/qnn/__init__.py

This PR applies some changes to master coming from [this PR](https://github.com/PennyLaneAI/pennylane/pull/7369/), which has been merged in the release candidate branch for the bugfix release of PennyLane 0.41.1.
More details can be found in the original PR description. This PR aims to update the master branch with the changes currently present in the stable version of PennyLane (0.41.1, no longer 0.41.0)

Manual cherry picking sync from latest rc to master

---

.github/workflows/upload.yml
doc/releases/changelog-dev.md
setup.py

**Context:** The PyPI release process requires more strict adherence to the https://packaging.python.org/en/latest/specifications/binary-distribution-format/ guidelines. `PennyLane` the package name is not compliant with this naming, and requires the released wheels to be named `pennylane`. Older versions of setuptools were less strict about this naming, and forwarded what was requested in the package metadata. Upgrade setuptools and wheel build infrastructure ensures that we adhere with the wheel naming expectations of PyPI.
Additionally, this PR also removes the deprecated license classifier, removing a warning of `SetuptoolsDeprecationWarning: License classifiers are deprecated`.
**Description of the Change:** Replaces the direct call to setup.py for wheel building with a call to …

Update release to adhere to PyPI BDF requirements

---

doc/releases/changelog-dev.md
pennylane/ftqc/parametric_midmeasure.py
tests/ftqc/test_parametric_mid_measure.py

**Context:**
When we diagonalize the parametric mid-circuit measurements to get analytic results to validate our protocols, we swap them out with new, updated measurements. This is currently updated in the conditionals, but not on the measurements. That means that returning parametric mcms when using the `diagonalize_mcms` transform currently fails.
We also update the measurements in the transform - if any MeasurementProcess contains MCMs, we update them based on the existing dictionary that's tracking updated measurement values, and create a copy of the MP with the new MeasurementValue(s) instead of the original ones.
**Benefits:**
We can do this:
```
@diagonalize_mcms
def circ():
qml.H(0)
m = measure_x(0, reset=True)
return qml.expval(m) …
```

Allow returning diagonalized parametric MCMs

---

doc/releases/changelog-dev.md
pennylane/devices/default_mixed.py
pennylane/devices/qubit_mixed/apply_operation.py
pennylane/devices/qubit_mixed/einsum_manpulation.py
pennylane/devices/qubit_mixed/initialize_state.py
pennylane/devices/qubit_mixed/sampling.py
pennylane/measurements/probs.py
tests/devices/qubit_mixed/conftest.py
tests/devices/test_default_mixed.py

**Context:**
See https://github.com/PennyLaneAI/pennylane/issues/7215 for the bug here. Separately recorded as a standalone bug: https://github.com/PennyLaneAI/pennylane/issues/7395
change the `np.` in executable source code to `qml.math.` for agnosticity.
added several tests for `default.mixed` to make sure the trainable parameters are treated well
**Benefits:**
Users would be able to use `default.mixed` on other interfaces e.g. torch cuda
We don't have the GPU test suites for `default.mixed`!
[sc-90500]

[BUG] `default.mixed` np to math

---

doc/releases/changelog-dev.md
pennylane/capture/capture_operators.py

Now that JAX 0.5.3 is supported, we no longer need the warning.
[sc-90873]

Remove `RuntimeWarning` about incompatible JAX versions from `qml.capture`

---

doc/releases/changelog-dev.md
pennylane/ops/qubit/parametric_ops_multi_qubit.py

**Context:**
Doc fix
**Benefits:**

Fix IsingXY doc `\theta` -> `\phi`

---

.github/workflows/interface-unit-tests.yml

CI failures due to an internal error introduced in `cotengra` 0.7.3 release (see issue https://github.com/jcmgray/quimb/issues/300) have already been solved by a bug fix in version 0.7.4, including unit tests to avoid this issue to silently occur again in the future (see [here](https://github.com/jcmgray/cotengra/releases/tag/v0.7.4)).
Ready to unpin `cotengra` version for PennyLane `default.tensor` device (revert https://github.com/PennyLaneAI/pennylane/commit/b671d5e7a9ae9e015a36a029bbdac3346a724b6d).
[sc-91240]

Revert `cotengra` version pin after bug fix in 0.7.4 release

---

doc/releases/changelog-dev.md
pennylane/noise/conditionals.py
pennylane/noise/noise_model.py
tach.toml

**Context:**
The goal of this PR is to isolate the `noise` module as an `tertiary` module.
- Updates `tach.toml` accordingly
- Fixes any errors `tach` identifies
**Benefits:** Module dependency enforcement.
**Possible Drawbacks:** None identified.
[sc-88858]

[circ. deps] enforce `noise` as `tertiary` module

---

pennylane/ftqc/utils.py

**Context:**
Trying to make latest `pylint` happy locally.
Use `def` instead of `lambda` assignment.
**Benefits:**
Conforms to [PEP8](https://peps.python.org/pep-0008/). 

fix `unnecessary-lambda-assignment` in `ftqc/utils.py`

---

doc/releases/changelog-dev.md
pennylane/templates/embeddings/angle.py
pennylane/templates/embeddings/displacement.py
pennylane/templates/embeddings/iqp.py
pennylane/templates/embeddings/qaoaembedding.py
pennylane/templates/embeddings/squeezing.py
pennylane/templates/layers/basic_entangler.py
pennylane/templates/layers/cv_neural_net.py
pennylane/templates/layers/gate_fabric.py
pennylane/templates/layers/particle_conserving_u1.py
pennylane/templates/layers/particle_conserving_u2.py
pennylane/templates/layers/random.py
pennylane/templates/layers/simplified_two_design.py
pennylane/templates/layers/strongly_entangling.py
pennylane/templates/swapnetworks/ccl2.py
pennylane/templates/tensornetworks/mera.py
pennylane/templates/tensornetworks/mps.py
pennylane/templates/tensornetworks/ttn.py
tach.toml

**Context:**
Following our PL module structure, the goal of this PR is to isolate straight forward submodules of `templates` as a `auxiliary` modules.
⚠️ This is a rather large and complex module which is unfortunately interconnected to the `ops` module. Due to this, there are circular import errors when trying to clean-up the `subroutines` and `state_preparations` submodules. 
This PR does the following,
- Updates `tach.toml` to break up `templates` into individual submodules (allows for submodule level enforcement)
- Address any errors that arise
**Benefits:** Module dependency enforcement.
**Possible Drawbacks:** None identified.
[sc-91368]

enforce subset of `templates` submodules as "auxiliary" modules

---

.github/workflows/unit-test.yml
doc/releases/changelog-dev.md
requirements-dev.txt

Using pytest-timeout seems to have caused many tests to slow down significantly. This PR removes it as a CI dependency.
[sc-91511]

Remove `pytest-timeout`

---

doc/releases/changelog-dev.md
pennylane/pulse/__init__.py
pennylane/pulse/hardware_hamiltonian.py

**Context:** The output of [the code example](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/pulse/hardware_hamiltonian.py#L105) in the `qml.pulse.hardware_hamiltonian.drive` function should be consistent with the output from the docs.
**Description of the Change:** There was a [long discussion](https://xanaduhq.slack.com/archives/C0743CNS9E3/p1721665038022359) (almost a year ago!) about this issue. The summary is provided by the following message that @Qottmann posted (you can check that the current output in the doc is recovered with the suggested change):
_we just never updated the example after changing the convention that amplitudes are implicitly multiplied by 2 pi (to account for radians). If you run the example with amplitude = lambda p, t: p * jnp.sin(jnp.pi * t) …

[BugFix] Discrepancy in output values of the example of `qml.pulse.drive`

---

doc/releases/changelog-dev.md

**Context:**
Our changelog got sick due to unknown GH markdown syntax highlight issue, check https://github.com/PennyLaneAI/pennylane/blob/d591f173337302e1ad438460b2d5ae8c294b0f39/doc/releases/changelog-dev.md?plain=1 to see:
And all the lines afterwards got affected:
Still don't know why but at least de-indenting two pieces of codeblock seems solved this problem. Check the results out by view the **"code"** of changelog; note that the rendered version is always good.
**Benefits:**
As mentioned above.
Sllightly cringe if you look carefully into the logic of codeblocks and surrounding texts: they indeed **should** be indented. But apparently simply adding blank lines won't fix this directly; didn't see any other immediately feasible …

De-indenting to save changelog highlight?

---

tests/test_compiler.py

`test_jacobian_fd` is failing and blocking all CI, potentially caused by recent changes in Catalyst. This issue is being investigated (see sc-92105), meanwhile, this test is xfailed in PL core to unblock CI

Xfail `test_jacobian_fd` to unblock CI

---

tests/ftqc/test_decomposition.py

**Context:**
We have a full, device execution E2E test for an execution pipeline that converts a tape to the MBQC formalism and gets results, and it only has 500 shots, because it's slow. So it's flaky, and it's been causing test failures. Seeding the device was not sufficient to fix it.
We mark the test as flaky, and add a comment explaining. 
**Benefits:**
We keep the full E2E test without blocking CI. Unit tests can validate we are doing what we *think* we should be doing, for the steps we identify as important to test, and they're great. But if we've made a mistake in our understanding of the protocol's implementation, or if we are missing a step that is relevant to test, the unit tests won't tell us. This test is a sanity check. It isn't exhaustive …

Mark flaky FTQC test as flaky

---

.github/workflows/interface-unit-tests.yml
tests/test_compiler.py

**Context:**
~external.txt said mitiq==0.44.0 so I don't understand why it's still updating.~ I see it's only `stable`
The mitiq 0.45 is [broken](https://github.com/unitaryfoundation/mitiq/issues/2767) for now and there's no way from PennyLane to fix very soon, so avoid it!
besides, we revert the `xfail` of a compiler test so that it doesn't fail wrongly.
**Benefits:**

Pin `mitiq!=0.45.0`

---

doc/releases/changelog-dev.md
pennylane/qcut/cutcircuit.py
pennylane/qcut/cutcircuit_mc.py
pennylane/qcut/cutstrategy.py
pennylane/qcut/kahypar.py
pennylane/qcut/ops.py
pennylane/qcut/processing.py
pennylane/qcut/tapes.py
pennylane/qcut/utils.py
tach.toml

**Context:**
The goal of this PR is to isolate the `qcut` module as a `tertiary` module.
- Updates `tach.toml` 
- Cleans-up the module's imports
- Adds new `qcut/ops.py` module to prevent intercircular dependencies 🤦🏼 
- Fixes any errors `tach` identifies
**Benefits:** Module dependency enforcement.
[sc-89250]

[circ. deps] enforce `qcut` as "tertiary" module

---

doc/releases/changelog-dev.md
pennylane/ops/functions/assert_valid.py
tests/ops/qubit/test_non_parametric_ops.py

**Context:**
Fractional powers of operators is not unique, therefore removing tests from `assert_valid`. Operators that defines special decompositions for certain fractional powers are tested individually on a case-by-case basis.
**Benefits:**
[sc-92097]

Remove fractional power decomposition test from assert_valid

---

doc/releases/changelog-dev.md
pennylane/__init__.py

**Context:**
Wrong removal version.
Update the deprecation message to say it will be removed in `v0.43`.

fix removal version in deprecation message

---

doc/releases/changelog-dev.md
pennylane/_grad.py
pennylane/capture/capture_diff.py
tests/capture/test_capture_diff.py

**Context:**
`qml.grad` and `qml.jacobian` cannot yet handle arguments with dynamic shapes.
Update our handling of grad and jacobian so that we can handle arguments with dynamic shapes.
**Benefits:**
Improved capture.
The same drawbacks of everything to do with dynamic shapes. They have flaky support from jax and using them couples us to some internal, experimental details.
[sc-89308]

[Capture] grad and jacobian can be captured with dynamic shapes

---

doc/releases/changelog-dev.md
tests/qchem/openfermion_pyscf_tests/conftest.py
tests/qchem/openfermion_pyscf_tests/test_dipole_of.py
tests/qchem/openfermion_pyscf_tests/test_meanfield.py
tests/qchem/openfermion_pyscf_tests/test_molecular_dipole.py
tests/qchem/openfermion_pyscf_tests/test_molecular_hamiltonian.py

------------------------------------------------------------------
**Context:**
[OpenFermion 1.7.1](https://github.com/quantumlib/OpenFermion/releases/tag/v1.7.1) is compatible with numpy2. We need to release those xfails we set up before so that Ci doesn't block anyone irrelevant.
**Benefits:**
Unblock CI
[sc-92720]

No more NP2 `xfail`'s for `OpenFermion` tests

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/apply_operation.py
tests/devices/qubit/test_apply_operation.py

The `PhaseShift` operation was raising an unexpected error when used with a batch size of 1 on the `default.qubit` device (see #6874 and sc-82871). This PR fixes the issue to return the expected output, for example:
```python
@qml.qnode(qml.device("default.qubit"))
def circuit(x):
qml.PhaseShift(x, wires=0)
return qml.expval(qml.Z(0))
params = np.array([1.57])
print(circuit(params))
```
`[1.]`
Fixes https://github.com/PennyLaneAI/pennylane/issues/6874

Fix `PhaseShift` operation with a batch size of 1

---

doc/releases/changelog-dev.md
pennylane/labs/dla/variational_kak.py
pennylane/labs/intermediate_reps/rowcol.py
pennylane/labs/vibrational/christiansen_utils.py
pennylane/labs/zxopt/basic_optimization.py
pennylane/labs/zxopt/full_optimize.py
pennylane/labs/zxopt/full_reduce.py
pennylane/labs/zxopt/todd.py
pennylane/labs/zxopt/util.py

**Context:**
The labs module contains experimental features, some of which require additional packages, causing dependencies that PennyLane itself does not (want to) have.
Currently, these additional packages are imported as soon as any `labs` functionality is imported. 
Change the imports so that they only cause a problem if a function is called that actually requires one of the additional dependencies.
**Benefits:**
Can use `labs.submodule_A` without installing dependencies of `labs.submodule_B`.
Can use `labs.submodule_A.fun_1` without installing dependencies of `labs.submodule_A.fun_2`.
More cumbersome import structure. Not really a problem. We do this with JAX a lot in PennyLane already.
This is an …

Restrict `labs` dependencies to the functions that introduce them

---

doc/releases/changelog-dev.md
pennylane/ops/functions/assert_valid.py

**Context:**
The current decomposition test in `assert_valid` compares the matrix of the decomposed circuit with the matrix of the operator by using `qml.matrix`, but when an operator does not have a well-defined matrix representation, `qml.matrix` simply returns the matrix of the operator's decomposition anyway, which is pointless. 
Change the matrix check for decomposition to use `op.matrix` when `op.has_matrix`
**Benefits:**

Only verify the matrix of a decomposition for ops that has matrix

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/prod.py
tests/ops/op_math/test_prod.py

**Context:**
Simplifying `qml.ops.op_math.Prod` instances via their `simplify` method sometimes swallows global phases, see #7670 .
A mere indentation change, leading to correct consideration of global phases.
**Benefits:**
bug fix.
n/a
fixes #7670.
[sc-93186]

Fix `Prod.simplify()`

---

doc/news/program_capture_sharp_bits.rst
doc/releases/changelog-dev.md

**Context:**
The program capture "sharp bits" documentation page incorrectly states that the only supported devices are `default.qubit` and `lightning.qubit`.
Adds `lightning.kokkos` and `lightning.gpu` to the documentation as devices that support program capture.
**Benefits:**
[sc-93195]

Add missing lightning devices to program capture docs

---

doc/releases/changelog-dev.md
pyproject.toml

As explained in [this issue](https://github.com/PennyLaneAI/pennylane/issues/7660), the project name for PennyLane does not match with the expected binary distribution format naming conventions.
Therefore, we change the name in the `pyproject.toml` file before the next release, and this PR does precisely this.
**Related issues**: Fixes #7660 
[sc-93375]

Renaming PennyLane in `pyproject.toml`

---

doc/releases/changelog-dev.md
pennylane/decomposition/decomposition_graph.py

A simple update of the docstring of code usage examples for `DecompositionGraph`
**Related GitHub Issues:** None

Updating examples for the `DecompositionGraph` class

---

doc/code/qml_io.rst
doc/releases/changelog-dev.md
pennylane/__init__.py
pennylane/io/__init__.py
pennylane/io/qualtran_io.py
tests/io/test_qualtran_io.py

**Context:**
We implement the adapter class `ToBloq` and a user-facing function `to_bloq` that converts a PennyLane Operator or QNode to a Qualtran bloq/cbloq. 
In this PR, we specifically target the ability to convert PennyLane decompositions to their Qualtran equivalent. When a PennyLane Operator is wrapped with the ToBloq class or is wrapped with `qml.to_bloq(..., map_ops=False)`, `decompose_bloq()` will return the PennyLane decomposition. This enables us to use functions in Qualtran, such as `draw_musical_score`, `call_graph()` and many more. 
Important to note that calling `to_bloq()` on basic gates that have **direct** equivalents (e.g. Hadamard, RX...) will **always** return the Qualtran equivalent, even if `map_ops=False`. We do this because in order for some Qualtran …

Add ToBloq adapter class and to_bloq function to convert PennyLane circuits and operators to Qualtran bloqs

---

.github/workflows/interface-unit-tests.yml

`quimb` has released [another version 3 days ago](https://quimb.readthedocs.io/en/latest/changelog.html#v1-11-1-2025-06-20), and as usual this has broken `default.tensor`.
We'lll investigate this as soon as possible, but for now let's pin the `quimb` version in the CI.

Pinning `quimb` to previous version

---

.github/workflows/interface-unit-tests.yml
doc/releases/changelog-dev.md

**Context:**
The problematic version was yanked,
Unpin `mitiq`.

unpin `mitiq` in CI

---

doc/releases/changelog-dev.md
pennylane/debugging/snapshot.py
pennylane/ops/meta.py

**Context:**
Transformations like `combine_global_phases` can reorder or merge operations across a Snapshot, altering what the snapshot captures and potentially leading to confusing results.
Added a warning to the documentation for `qml.snapshots` noting that compilation transforms may move operations past a `Snapshot`, changing the state that is captured.
**Benefits:**
Clarifies expected behavior for users and avoids confusion when snapshots return unexpected results due to circuit transformations.
N/A (doc update only)
None

Add warning to `qml.snapshots` and `qml.Snapshot` for transforms not preserving circuit structure

---

pennylane/compiler/python_compiler/quantum_dialect.py

**Context:** Recent changes in xDSL restrict the use of AnyAttr in AnyOf. See PR [here](https://github.com/xdslproject/xdsl/pull/4510)
**Description of the Change:** We don't need to say `AnyOf(AnyAttr(), AnyAttr())`. We can just say `AnyAttr()` and it means the same thing. We could make this check stricter by using the correct types which in most of the cases are TensorTypes or MemrefTypes, but I think this is ok for now.
**Benefits:** The latest version of xDSL works with the Python compiler.

[Python Compiler] Do not use AnyAttr in AnyOf

---

doc/releases/changelog-dev.md
pennylane/ops/qubit/qchem_ops.py
tests/ops/qubit/test_qchem_ops.py

**Context:**
There are qchem ops `SingleExcitation`, `SingleExcitationPlus` and `SingleExcitationMinus`. 
Improve their decompositions, requiring fewer static entanglers (i.e. CNOT, CY or CZ) and sometimes fewer `T` gates/varying-angle rotations.
The decomposition for `SingleExcitation` already was given in [Anselmetti et al.](https://arxiv.org/pdf/2104.05695)
Some (non-tight) lower bounds for static entangler count and rotation count are given here:
```python
from pennylane.ops.op_math.decompositions.unitary_decompositions import _compute_num_cnots
for cls in [qml.SingleExcitation, qml.SingleExcitationMinus, qml.SingleExcitationPlus]:
op0 = cls(np.random.random(), [0, 1])
n0 = _compute_num_cnots(op0.matrix())
f0 = …
```

Improved decompositions of `SingleExcitation`, `SingleExcitationMinus` and `SingleExcitationPlus`

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/decompositions/rings.py
tests/ops/op_math/decompositions/test_rings.py

**Context:** Missed a change in the changelog.
**Description of the Change:** `method="gridsynth"` in the changelog example. 
**Benefits:**

Fix missing `method` change in changelog

---

doc/releases/changelog-dev.md
pennylane/labs/tests/trotter_error/product_formulas/test_error.py
pennylane/labs/tests/trotter_error/product_formulas/test_pt_integration.py
pennylane/labs/trotter_error/product_formulas/bch.py
pennylane/labs/trotter_error/product_formulas/error.py

This PR implements the "group-by-sums" method for reducing the number of commutators returned by BCH for perturbation theory.

Implement group-by-sums optimization for perturbation_error function

---

.github/workflows/rc_sync.yml
doc/development/release_notes.md
doc/releases/changelog-dev.md
pennylane/_version.py

**Context:**
By-product PR that is created after the `sh ./pennylane_version_bump.sh <your github username>` step in the release guide.
Same changes as the last release: https://github.com/PennyLaneAI/pennylane/pull/7216/files
[sc-94600]

[v0.42.0 release] bump dev version to `v0.43.0`

---

doc/releases/changelog-0.42.0.md
pennylane/io/io.py
tests/io/test_io.py

**Context:** When provided with incorrect QASM syntax, the parser library does not provide helpful error messages. They are mysterious, saying for example that NoneType has no len() or there are no viable candidates, etc.
**Description of the Change:** Catch all errors from the parser and wrap them with an understandable message.
**Benefits:** More clarity for users.
**Possible Drawbacks:** We still don't have very particular or specific error messages that can help us debug.

Raise an understandable error in place of openqasm3's mysterious ones

---

.github/workflows/rc_sync.yml
doc/releases/changelog-dev.md

**Context:**
RC sync action was failing due to an older `setuptools` version.
**Benefits:** Ran the rc sync action in PL against this branch and it worked: https://github.com/PennyLaneAI/pennylane/pull/7819
[sc-94862]

add python configuration step to `rc_sync.yml` 

---

doc/releases/changelog-0.42.0.md
pennylane/ops/qubit/state_preparation.py
tests/ops/qubit/test_state_prep.py

**Context:**
`validate_norm=False` is overriding `normalize=True` in `StatePrep`.
Fix that
**Benefits:**
Bug fix
N/A

Fix `validate_norm` overriding `normalize` in `StatePrep`

---

doc/releases/changelog-0.42.0.md
pennylane/math/decomposition.py
tests/math/test_givens_rotations.py

**Context:**
This PR is a combination of @erick-xanadu's previous [PR1](https://github.com/PennyLaneAI/pennylane/pull/7013) and [PR2](https://github.com/PennyLaneAI/pennylane/pull/7014).
It jax jits the `givens_matrix` from `BasisRotation` when it is within a jit context, which significantly reduces the program size and compilation time of workflows, e.g. the XAS benchmark.
**Benefits:**
This significantly reduces the time for XAS with compilation benchmark ([~5-6x](https://github.com/PennyLaneAI/pennylane-benchmarks/actions/runs/16158349592/job/45616094304#step:10:104)). This undoes most of the performance degradation coming from the bufferization updates in catalyst.
Jax jitting is now part of the Pennylane internals
**Related …

Jax jit givens decomposition

---

README.md

**Context:**
Some images in the `README.md` are not rendering properly on [PyPI](https://pypi.org/project/PennyLane/) because PyPI does not support relative image paths.
This PR updates image references in `README.md` to use absolute URLs pointing to raw GitHub content to ensure images render correctly on both GitHub and PyPI.
**Notes:**
Please note that we had decided to use a relative path for certain images in the past to support GitHub’s dark mode rendering. See https://github.com/PennyLaneAI/pennylane/pull/2341 for more details.

Update README image paths for PyPI compatibility

---

doc/releases/changelog-dev.md
tests/transforms/test_split_to_single_terms.py

**Context:**
`tests/transform/test_split_to_single_terms` somehow escaped our global seeding system. It caused multiple stochastic failure during the release week 07July~11July 2025. Therefore here we seed them.
Whoever involves finite-shot experiments and checks stochastic results shall be seeded.
**Benefits:**
CI stability and reliability.
[sc-90216]

Seed `test_split_to_single_terms`

---

pennylane/templates/subroutines/flip_sign.py

A warning is currently raised when creating an instance of the `qml.FlipSign` operation passing an integer number as the `wires` argument. This was introduced by [this PR](https://github.com/PennyLaneAI/pennylane/pull/7647) to warn users about the new `qml.FlipSign` behaviour fixing the previous wrong interpretation of that argument.
The aim of this PR is to remove the warning.
[sc-93136]

Remove warning in the `qml.FlipSign` operation

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/linear_combination.py
tests/ops/op_math/test_linear_combination.py

**Context:**
Found in https://github.com/PennyLaneAI/catalyst/pull/1889
The `SProd` instances created during initialization were preventing concrete `LinearCombination` instances from being created.
**Benefits:**
[sc-95516]

LinearCombination can be used in a `PlxprInterpeter`

---

.github/workflows/interface-unit-tests.yml
doc/releases/changelog-dev.md
pennylane/compiler/python_compiler/compiler.py
pennylane/compiler/python_compiler/jax_utils.py
pennylane/compiler/python_compiler/transforms/api/apply_transform_sequence.py
pennylane/compiler/python_compiler/transforms/api/transform_interpreter.py
tests/python_compiler/conftest.py
tests/python_compiler/test_python_compiler.py

**Context:** Updates needed for the Python Compiler to be compatible with the new version of xDSL
**Description of the Change:** Renamed PassPipeline with PipelinePass
**Benefits:** Compatible with the newer version.
[sc-95842]

Update xdsl version

---

doc/releases/changelog-dev.md
pennylane/compiler/python_compiler/transforms/api/compiler_transform.py

[sc-95008]
The error message raised when using compiler transforms with program capture disabled was very cryptic. This PR makes the error message clearer.

Improve error message for incorrect use of compiler transforms

---

doc/releases/changelog-dev.md
pennylane/measurements/classical_shadow.py
pennylane/measurements/counts.py
pennylane/measurements/expval.py
pennylane/measurements/mid_measure.py
pennylane/measurements/mutual_info.py
pennylane/measurements/probs.py
pennylane/measurements/purity.py
pennylane/measurements/sample.py
pennylane/measurements/state.py
pennylane/measurements/var.py
pennylane/measurements/vn_entropy.py

**Context:**
Moves the constructor below the class definition so we can properly type-hint the constructor without quotation marks.
**Benefits:**

improve type hints in measurements module

---

doc/development/deprecations.rst
doc/releases/changelog-dev.md
pennylane/tape/qscript.py
tests/tape/test_qscript.py
tests/tape/test_tape.py

We don't use `QuantumScript.shape` method and `QuantumScript.numeric_type` property anymore. Much cleaner to use the corresponding method/property of the `MeasurementProcess` class instead.
[sc-95548]

Deprecate `QuantumScript.shape` and `QuantumScript.numeric_type`

---

doc/releases/changelog-dev.md
pennylane/compiler/python_compiler/dialects/mbqc.py
tests/python_compiler/dialects/test_mbqc_dialect.py

**Context:** The generic format of attributes in xDSL and in MLIR need to agree in order for the output of a Python compiler pass to be used as input to Catalyst. As such, the measurement-plane attribute of the `mbqc` dialect needs to be output in the "opaque" format. For example, the generic format of an `mbqc.measure_in_basis` op should be
```mlir
%res:2 = "mbqc.measure_in_basis"(%qbit, %angle) <{plane = #mbqc<measurement_plane XY>, postselect = 0 : i32}> : (!quantum.bit, f64) -> (i1, !quantum.bit)
```
Previously, without the opaque format, the `plane` attribute was output as
```mlir
<{plane = #mbqc.measurement_planeXY}>
```
which is incompatible with the attribute as defined in Catalyst.
**Description of the Change:** The class `MeasurementPlaneAttr` now also inherits from the …

Use opaque syntax for the measurement-plane attribute of the mbqc dialect

---

doc/releases/changelog-dev.md
pennylane/templates/subroutines/semi_adder.py
tests/templates/test_subroutines/test_semi_adder.py

**Context:**
the SemiAdder was not working in the edge case of x + y defined with a single qubit. This PR covers this situation
In this scenario, the semiAdder is a CNOT.
Note that in this case work_wires are not needed. So I had to change the logic that was assuming we always have work wires
**Benefits:**

fixing 1 qubit-size SemiAdder

---

.pre-commit-config.yaml
pyproject.toml

We want to have a single source of truth for the config of our tooling.
* Update `pyproject.toml` with `isort` and `black` config
* Update `pre-commit-config.yaml` to use `pyproject.toml` as the source of truth for the config for `isort` and `black`
I confirmed locally that the updated pre-commit hook is able to pull the config from `pyproject.toml` correctly.
[sc-96260]

Add `isort` and `black` to use config from `pyproject.toml`

---

doc/releases/changelog-dev.md
pennylane/__init__.py

Going to class/function definitions using language servers such as Pylance on VSCode does not work well in PennyLane because of the style we use for importing submodules. This PR changes the import style from `import pennylane.potato` to `from pennylane import potato`. This makes `potato` discoverable to language servers, drastically improving developer experience with PennyLane.
**Breaking change:**
`qml.pennylane` is no longer accessible. On `master`:
```pycon
>>> import pennylane as qml
>>> qml.pennylane
<module 'pennylane' from '/Users/mudit.pandey/repos/pennylane/pennylane/__init__.py'>
```
On this branch:
```pycon
>>> import pennylane as qml
>>> qml.pennylane
AttributeError: module 'pennylane' has no attribute 'pennylane'
```
There are many PL submodules that are missing from the …

Update how submodules are import top-level

---

doc/releases/changelog-dev.md
pennylane/labs/resource_estimation/ops/op_math/symbolic.py
pennylane/labs/resource_estimation/resource_operator.py
pennylane/labs/resource_estimation/templates/subroutines.py
pennylane/labs/tests/resource_estimation/test_resource_operator.py
pennylane/queuing.py

**Context:**
Resource operators are tracked using the queuing architecture. The default `queue()` method adds an instance of the Resource operator to the active queuing context. 
In some cases operators consume other operators and thus those inputs need to be removed from the queue. This responsibility was being absorbed into the `queue()` leading to diverging implementations for the various Resource operators depending on their inputs. In this PR we move that responsibility to a more general, separate method called `dequeue`. 
- Refactored the diverging `queue()` method implementations 
- Add a new `dequeue()` method to remove from the queue.

Small refactor of `queue` method for `ResourceOperators`

---

doc/releases/changelog-dev.md
pennylane/ops/functions/matrix.py
tests/ops/functions/test_matrix.py

**Context:**
`qml.matrix` leaks queued ops from decompositions.
Fix the leak.
**Benefits:**
No leak.
N/A
#7975 
[sc-96525]

Stop queuing due to decompositions from within `qml.matrix`.

---

doc/development/release_notes.md
doc/releases/changelog-0.42.0.md
doc/releases/changelog-0.42.1.md
pennylane/__init__.py
pennylane/capture/base_interpreter.py
pennylane/capture/make_plxpr.py
pennylane/devices/qubit/apply_operation.py
pennylane/gradients/pulse_gradient.py
pennylane/labs/dla/variational_kak.py
pennylane/pulse/convenience_functions.py
pennylane/pulse/parametrized_evolution.py
pennylane/qchem/factorization.py

**Context:**
A `v0.42.1` bug fix was released with changes from https://github.com/PennyLaneAI/pennylane/pull/7949. In order to keep up to date, this PR merges relevant changes here. Since `0.7.0` won't be compatible any time soon (waiting on Catalyst) might as well have this warning on master as well.
[sc-96620]

merge in `v0.42.1` bug fix changes

---

doc/releases/changelog-dev.md
pennylane/devices/qubit/simulate.py
tests/devices/qubit/test_simulate.py

**Context:**
```
@qml.qnode(qml.device('default.qubit'))
def c():
qml.H(0)
qml.CNOT((0,2))
qml.measure(0, reset=True)
qml.CNOT((0,1))
return qml.expval(qml.Z(2))
c.update(mcm_method="tree-traversal")(), c.update(mcm_method="deferred")(), qml.set_shots(c, 1000).update(mcm_method="one-shot")()
```
```
(1.0, 0.0, -0.002)
```
tree-traversal is giving incorrect answers with non-sequential wire orders.
Add a sorted to the wire order used in the `StatePrep`.
**Benefits:**
Correct results.
Fixes #7990 [sc-96701]

fix tree-traversal with non-standard wire ordering

---

doc/introduction/compiling_circuits.rst

- Fix typo where `the` was added twice, reported in [QA channel](https://xanaduhq.slack.com/archives/C05C2NU8QBY/p1754504800529449)

fix-typo-in-compiling-circuits

---

doc/development/deprecations.rst

**Context:**
A lot of our entries had weird rendering.
Cleaned up the sphinx directives to have better rendering. See https://xanaduai-pennylane--8034.com.readthedocs.build/en/8034/development/deprecations.html for renders.
[sc-97212]

chore: fix path rendering in `deprecations` page

---

doc/releases/changelog-dev.md
pennylane/transforms/dynamic_one_shot.py

**Context:**
PR #7962 accidentally broke catalyst because I missed a squeeze statement.
Adds the squeeze statement back in.
**Benefits:**
Catalyst tests pass again.

Fix dynamic one shot with squeezing and qjit

---

doc/news/program_capture_sharp_bits.rst
doc/releases/changelog-dev.md
pennylane/ops/op_math/condition.py
tests/capture/test_capture_cond.py

**Context:**
One thing both core pennylane and current catalyst both support is:
```
qml.cond(True, qml.X)(0)
```
Capture currently forbids this, because the `true_fn` and `false_fn` have different outputs.  
If we make the assumption that the above syntax always means "queue an X operator" instead of "return an X operator", we can still consider it well defined.
So if no `false_fn` is provided and the input is a subclass of operator, we should just assume that the operator should be "queued" not necessarily returned.
Removes the output from `true_fn` if it's a subclass of `Operator` and no `false_fn` is provided.
**Benefits:**
Smoother change to using program capture as the new frontend.
Someone might actually want the operator …

[Capture] `cond` can accept an operator `true_fn` with no `false_fn` provided

---

doc/development/release_notes.md
doc/releases/changelog-0.42.1.md
doc/releases/changelog-0.42.2.md
pennylane/_version.py
pennylane/operation.py
pennylane/ops/op_math/pow.py
tests/ops/op_math/test_pow_op.py

**Context:**
A bug was found during `v0.43` development that causes recursion errors for an edge case.
Bug was fixed in `v0.43` development here: https://github.com/PennyLaneAI/pennylane/pull/8044/files. 
This PR just cherry picks that commit and updates any changelog / release notes files as necessary.
[sc-97369]

[Bug Fix Release] fix recursion error when simplifying operators raised to integer powers

---

doc/releases/changelog-0.42.2.md

**Context:**
Follow up to https://github.com/PennyLaneAI/pennylane/pull/8061 - there was a formatting error in the changelog entry of the release notes page.
Renders properly in the release notes page (code block didn't render correctly),
[sc-97369]

[Bug Fix Release] fix: changelog entry in release notes

---

doc/development/release_notes.md
doc/releases/changelog-0.42.1.md
doc/releases/changelog-0.42.2.md

**Context:**
v0.42.2 was released yesterday (https://github.com/PennyLaneAI/pennylane/pull/8061). The bug fix is already in main so we only need to update the changelog entries.
**Benefits:** Up to date code.
[sc-97524]

chore: merge `v0.42.2` bug fix release into `main`

---

doc/development/release_notes.md
doc/releases/changelog-0.42.2.md
doc/releases/changelog-0.42.3.md
pennylane/_version.py
pyproject.toml

**Context:**
The `autoray` package released a new version and broke our PL environment.
Users installing PennyLane from PyPI currently cannot import `pennylane` due to changes in the `autoray` package.
Adds an upper bound to the version requirement to dodge problematic version.
**Benefits:** Users have a functional environment.
[sc-98038]

[Bug Fix Release] add upper bound to `autoray` version requirement in `pyproject.toml`

---

doc/releases/changelog-dev.md
pennylane/ftqc/parametric_midmeasure.py
pennylane/measurements/counts.py
pennylane/measurements/measurement_value.py
pennylane/measurements/mid_measure.py
pennylane/measurements/probs.py
pennylane/transforms/defer_measurements.py
pennylane/transforms/dynamic_one_shot.py
tests/measurements/test_counts.py
tests/measurements/test_probs.py

**Context:**
Measusing counts like:
```
m0 = qml.measure(0)
m1 = qml.measure(1)
counts([2*m0, m1])
```
is ill-defined, but doesn't raise an type of error or warning.  
Adds a `MeasurmentValue.has_processing` and uses it to forbid the above case from happening.
**Benefits:**
Less confusion about what the result in the above case should actually look like.
[sc-97994]

forbid counts of list of mcm's with classical postprocessing

---

doc/releases/changelog-dev.md
pennylane/capture/__init__.py
pennylane/capture/autograph/__init__.py
pennylane/capture/autograph/transformer.py
tests/capture/autograph/test_autograph.py

We wish to move control of when `autograph` is applied from the `QNode` to an external context manager and let `qjit` take priority as the entry point for this feature. 
ℹ️  Please note that the application of `autograph` is done through `qml.capture.autograph.run_autograph` - hence there is no need for an `enable_autograph`. 
Simply adds a decorator that disables autograph for a given function / context. You can see the render for documentation [here](https://xanaduai-pennylane--8102.com.readthedocs.build/en/8102/code/api/pennylane.capture.disable_autograph.html).
We can see this works by considering a simple example. In this case, we expect to see a `cond` primitive captured in the jaxpr from the function `f`.
```python
import jax
from jax import make_jaxpr
from …
```

feat: autograph: add `disable_autograph` context manager

---

doc/releases/changelog-dev.md
tests/capture/workflow/test_capture_qnode.py
tests/ftqc/test_decomposition.py
tests/test_debugging.py

**Context:**
In PR #7944  I had to xfail a couple of tests since they required lightning to be updated to move it's squeezing too. Lightning has now been updated.
Remove the xfails.
**Benefits:**
[sc-96550]

Remove xfails from lightning tests

---

doc/development/release_notes.md
doc/releases/changelog-0.42.2.md
doc/releases/changelog-0.42.3.md

**Context:**
[v0.42.3 bug fix](https://github.com/PennyLaneAI/pennylane/pull/8111) was released yesterday. This PR updates our release notes to include this fix.
[sc-98171]

chore: merge `v0.42.3` bug fix changelog into `main`

---

tests/ops/op_math/test_exp.py

**Context:**
A change to `Select`'s decomposition broke lightning. We responded by natively supporting `Exp` and `SProd` on lightning. This has broken `test_exp.py`.
To unblock the CI, we are xfailing that test while we get a fix.
**Benefits:**
We aren't actually solving the problem. Just letting other work proceed while we fix things.

Temporarily xfail lightning test

---

doc/releases/changelog-dev.md
pennylane/drawer/drawable_layers.py
tests/drawer/test_drawable_layers.py

**Context:**
Unhelpful error message is raised when drawing very deep circuits.
Adds context to the error message.
**Benefits:**
Fixes #8137 [sc-98283]

more informative draw error for deep circuits

---

doc/development/guide/installation.rst
doc/releases/changelog-dev.md
pyproject.toml
requirements-ci.txt
requirements.txt

**Context:**
The lower bound is not correct. We need to make it `0.8.0` because we are accessing something that is only available in `0.8.0` or higher (ar.autoray.AutoNamespace).
[sc-98081]

chore: update lower bound of autoray due to breaking change

---

doc/releases/changelog-dev.md
pennylane/math/decomposition.py
pennylane/math/is_independent.py
pennylane/math/quantum.py
pennylane/math/single_dispatch.py
pennylane/math/utils.py
pennylane/operation.py
pennylane/workflow/_capture_qnode.py
pennylane/workflow/interfaces/jax.py
pennylane/workflow/interfaces/jax_jit.py
pennylane/workflow/interfaces/tensorflow.py
pennylane/workflow/interfaces/tensorflow_autograph.py
pennylane/workflow/jacobian_products.py
pennylane/workflow/qnode.py
tests/test_queuing.py

**Context:**
By default, if the iterables passed to zip are of different lengths, the resulting iterator will be silently truncated to the length of the shortest iterable. This can lead to subtle bugs.
Use `ruff` to add `kwarg` (see [rule](https://docs.astral.sh/ruff/rules/zip-without-explicit-strict/#zip-without-explicit-strict-b905)).
**Benefits:** Better code.
[sc-98487]

chore: add `strict=True` to `zip` in a few core modules

---

doc/releases/changelog-dev.md
pennylane/templates/subroutines/select.py
tests/templates/test_subroutines/test_select.py

**Context**
There is a problem with the signature of new decomp rules of `Select` if there are parameters in the target `ops`.
See #8185
**Change**
Fix #8185 by updating the signature of the `Select` decomposition rules.
**Drawbacks**
N/A
**Related issues**
Fixes #8185
[sc-98595]

Fix decomposition of `Select` with parametrized `ops` in new decomposition system. 

---

doc/releases/changelog-dev.md
pennylane/labs/tests/resource_estimation/test_resource_operator.py

**Context:**
Fixes a test failure due to queening issues in labs ResourceOperator tests. 
**Benefits:**

Fix queening issue in labs ResourceOperator tests

---

tests/devices/test_default_clifford.py

**Context:**
A default clifford test was setting an environment variable.  
Just use monkeypatch instead.
**Benefits:**
Individual tests don't modify the global configuration.
Monkeypatch can sometimes be confusing. But this is the actual reason monkeypatching exists.

Dont set environment variables in tests

---

doc/releases/changelog-dev.md
pennylane/decomposition/decomposition_rule.py

A `.. details::` section was not even rendering 🤦🏼 .
Render is here: https://xanaduai-pennylane--8228.com.readthedocs.build/en/8228/code/api/pennylane.decomposition.register_resources.html.

fix: update sphinx directive in documentation

---

doc/releases/changelog-dev.md
pennylane/about.py

**Context:**
We are really picky about jax versions, so the jax version should be included in the `qml.about()` to help us debug issues.
**Benefits:**

Include jax version in about

---

doc/releases/changelog-dev.md
pennylane/decomposition/decomposition_rule.py
tests/decomposition/test_decomposition_rule.py

**Context:**
These two helpers used to work with classes. As a result, one might see usage (e.g. this [commit](https://github.com/PennyLaneAI/pennylane/pull/8260/files#diff-9da436a44007b8abb8170447c6b939836bbb5920b1a05f26454fe3c3537aab30R523)) like
```python
has_decomp(type(op))
```
**Benefits:**
Now we can simply
```python
has_decomp(op)
```
[sc-99425]

`has_decomps` and `list_decomps` work with operator instances

---

tests/capture/autograph/test_autograph.py

**Context:**
Missing some important tests in the autograph module.
Add a test to make sure these functions get captured in the plxpr. We don't care about plxpr execution through PL anymore.
**Benefits:** Robust code.
[sc-99324]

chore: add tests for nested `adjoint` and `ctrl` transforms with `autograph`

---

doc/releases/changelog-dev.md
pennylane/devices/device_constructor.py

**Context:** The documentation of `qml.device` was outdated, so this PR updates it.
**Description of the Change:** As above.
**Benefits:** The example are compatible with latest PL.
**Possible Drawbacks:** None that I can think of.
**Related GitHub Issues:** #7992
[sc-99473]

Updating the documentation of `qml.device`

---

doc/releases/changelog-dev.md
pennylane/compiler/python_compiler/transforms/convert_to_mbqc_formalism.py

**Context:**
[sc-99558]
The result …

Fix qubit deallocation failure in convert_to_mbqc_formalism pass

---

doc/releases/changelog-dev.md
pennylane/devices/default_qubit.py
tests/devices/default_qubit/test_default_qubit_preprocessing.py
tests/test_qnode.py

**Context:** We weren't erroring out at unsupported mcm methods.
**Benefits:**

add validation for mcm_method on default.qubit

---

doc/releases/changelog-dev.md
pennylane/compiler/python_compiler/transforms/mbqc/convert_to_mbqc_formalism.py
tests/python_compiler/transforms/mbqc/test_xdsl_convert_to_mbqc_formalism.py

[Unified Compiler] Disable error raise for Paulis/GPhase op in the convert-to-mbqc-formalism

---

.github/workflows/interface-unit-tests.yml
.github/workflows/module-validation.yml
.github/workflows/tests-labs.yml
.github/workflows/unit-test.yml
.github/workflows/upload-nightly-release.yml
.github/workflows/upload.yml
doc/releases/changelog-dev.md

**Context:**
Github will be updating their `ubuntu-latest` version from ubuntu-24 to ubuntu-26 in the near future.  This may cause issues later so it's best to fix the ubuntu version and manually update it.
Changing `ubuntu-latest` to `ubuntu-24.04` on workflows that may be version specific.
**Benefits:**
No unexpected issues when `ubuntu-latest` is updated in the future. 
None. `ubuntu-latest` is currently ubuntu-24

Change ubuntu-latest to ubuntu-2404

---

doc/releases/changelog-dev.md
pennylane/ops/op_math/controlled.py
tests/ops/op_math/test_controlled.py

A small patch to simplify the decomposition of the `Controlled` operator, specifically when the base class is the `Identity`. This patch is proposed since we already have similar simplifications in place for other operators, and it avoids computing the more complex `ctrl_decomp_bisect`.

Decompose `Controlled(Identity)` to `Identity`

---

doc/development/release_notes.md
doc/releases/changelog-0.42.3.md
doc/releases/changelog-0.43.0.md
pennylane/_version.py

Context:
Following instructions laid out in the release guide - the changes were automatically generated via shell script.
Changes are the same as last release: https://github.com/PennyLaneAI/pennylane/pull/7796
[sc-100867]

[v0.43.0 release] preparation for release candidate branches

---

doc/development/release_notes.md
doc/releases/changelog-dev.md
pennylane/_version.py

Same as last release: https://github.com/PennyLaneAI/pennylane/pull/7798. Created via automated script.
[sc-100867]

[v0.43.0 release] bump dev version to `v0.44.0`

---

pennylane/_version.py
pennylane/devices/default_qubit.py
pennylane/devices/qubit/apply_operation.py
pennylane/devices/qubit/simulate.py
tests/capture/test_capture_mid_measure.py
tests/devices/default_qubit/test_default_qubit_preprocessing.py
tests/devices/qubit/test_apply_operation.py
tests/devices/qubit/test_simulate.py
tests/test_qnode.py
tests/transforms/test_dynamic_one_shot.py

**Context:**
When using `mcm_method="one-shot"` or `"tree-traversal"`,  combined with `postselect_mode="fill-shots"`,  the postselection breaks the correlation between correlated measurements completely, producing incorrect results. The only way to fix that is by continuously running the simulation until we have enough valid shots, which fundamentally goes against the philosophy of treating shots as a budget constraint. Therefore, we have opted to disallow `"fill-shots"` for anything but `"deferred"` in `default.qubit`.
**Benefits:**
[sc-100562]
[sc-99992]
Fixes https://github.com/PennyLaneAI/pennylane/issues/8366
https://github.com/PennyLaneAI/pennylane/issues/8332

Disable fill-shots on default.qubit for one-shot and tree-traversal
